// =============================================================================
// exim-drivers/src/router_driver.rs — RouterDriver Trait Definition
// =============================================================================
//
// Defines the `RouterDriver` trait that replaces the C `router_info` struct
// inheritance pattern (structs.h lines 372-387). In C, each router (accept,
// dnslookup, manualroute, redirect, etc.) provides a `router_info` struct with
// a `code()` function pointer that returns an int status. In Rust, this becomes
// a trait with a `route()` method returning a `RouterResult` enum.
//
// Also defines:
//   - `RouterResult`         — Enum replacing C int return codes (OK/DEFER/FAIL/ERROR/DECLINE/PASS)
//   - `RouterInstanceConfig` — Struct replacing C `router_instance` (structs.h lines 299-366)
//   - `RouterFlags`          — Bitflag newtype replacing C `ri_flags` field
//   - `RouterDriverFactory`  — Compile-time registration struct for `inventory::submit!`
//
// This file contains ZERO unsafe code (per AAP §0.7.2).

use crate::DriverError;
use std::any::Any;
use std::collections::HashMap;
use std::fmt;

// =============================================================================
// Router Result Enum
// =============================================================================

/// Result of router evaluation for a single address.
///
/// Maps to C router return codes defined in `exim.h`:
///   - `OK`      (0) — Route accepted, address assigned a transport
///   - `DEFER`   (1) — Temporary failure, retry later
///   - `FAIL`    (2) — Routing failed permanently
///   - `ERROR`   (3) — Internal error
///   - `DECLINE` (4) — Router does not handle this address
///   - `PASS`    (5) — Pass to next router in chain
///
/// Per AAP §0.4.1: "RouterDriver trait: route() → Accept/Pass/Decline/Fail/Defer"
///
/// The `Rerouted` variant has no direct C code equivalent — it represents the
/// case where a redirect router generates new addresses, which in C is encoded
/// via the four `address_item **` output parameters of the router entry point.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RouterResult {
    /// Route accepted — address has been assigned a transport for delivery.
    ///
    /// C equivalent: return `OK` (0) with the transport pointer set on the
    /// address item and optional host list attached for remote delivery.
    Accept {
        /// Transport name to use for delivery (e.g., "remote_smtp", "local_delivery").
        /// `None` if the transport is inherited from context or set elsewhere.
        transport_name: Option<String>,
        /// Generated host list for remote delivery. Empty for local transports.
        /// Each entry is a host name or IP address string.
        host_list: Vec<String>,
    },

    /// Pass to next router in chain.
    ///
    /// C equivalent: return `PASS` (5). The router evaluated the address but
    /// explicitly passes it to the next router in the chain (different from
    /// `Decline` which means the router is not applicable at all).
    Pass,

    /// Router declined this address — not applicable to this router.
    ///
    /// C equivalent: return `DECLINE` (4). The router determined that it
    /// does not handle this address type/domain and the framework should
    /// try the next router.
    Decline,

    /// Routing failed permanently — the address cannot be delivered.
    ///
    /// C equivalent: return `FAIL` (2). Generates a bounce/DSN message.
    Fail {
        /// Optional human-readable failure message for the bounce.
        message: Option<String>,
    },

    /// Temporary failure — retry later.
    ///
    /// C equivalent: return `DEFER` (1). The address is placed back in the
    /// queue for retry according to the retry rules.
    Defer {
        /// Optional human-readable deferral reason for logging.
        message: Option<String>,
    },

    /// Internal error during routing.
    ///
    /// C equivalent: return `ERROR` (3). Indicates a bug or misconfiguration
    /// rather than a legitimate routing outcome.
    Error {
        /// Error description for logging and diagnostics.
        message: String,
    },

    /// Address was rerouted to one or more new addresses (redirect router).
    ///
    /// No direct C return code — in C, this is encoded as `OK` with new
    /// addresses linked into the `addr_new` chain via the output parameters
    /// of the router entry point. The Rust API makes this explicit.
    Rerouted {
        /// The new addresses generated by the redirect (alias expansion,
        /// filter output, Sieve redirect, etc.).
        new_addresses: Vec<String>,
    },
}

impl RouterResult {
    // =========================================================================
    // Convenience Constructors
    // =========================================================================

    /// Create an `Accept` result for a local transport.
    ///
    /// # Arguments
    /// * `transport_name` — Name of the transport to use (e.g., "local_delivery").
    pub fn accept(transport_name: impl Into<String>) -> Self {
        Self::Accept {
            transport_name: Some(transport_name.into()),
            host_list: Vec::new(),
        }
    }

    /// Create an `Accept` result for a remote transport with a host list.
    ///
    /// # Arguments
    /// * `transport_name` — Name of the transport (e.g., "remote_smtp").
    /// * `hosts` — List of target hosts for remote delivery.
    pub fn accept_remote(transport_name: impl Into<String>, hosts: Vec<String>) -> Self {
        Self::Accept {
            transport_name: Some(transport_name.into()),
            host_list: hosts,
        }
    }

    /// Create a `Fail` result with a message.
    pub fn fail(message: impl Into<String>) -> Self {
        Self::Fail {
            message: Some(message.into()),
        }
    }

    /// Create a `Defer` result with a message.
    pub fn defer(message: impl Into<String>) -> Self {
        Self::Defer {
            message: Some(message.into()),
        }
    }

    /// Create an `Error` result with a message.
    pub fn error(message: impl Into<String>) -> Self {
        Self::Error {
            message: message.into(),
        }
    }

    /// Create a `Rerouted` result with new target addresses.
    pub fn rerouted(addresses: Vec<String>) -> Self {
        Self::Rerouted {
            new_addresses: addresses,
        }
    }

    // =========================================================================
    // C Code Conversion
    // =========================================================================

    /// Convert this result to the corresponding C-style integer return code.
    ///
    /// Mapping:
    ///   `Accept`/`Rerouted` → 0 (OK), `Defer` → 1, `Fail` → 2,
    ///   `Error` → 3, `Decline` → 4, `Pass` → 5
    pub fn to_c_code(&self) -> i32 {
        match self {
            Self::Accept { .. } | Self::Rerouted { .. } => 0,
            Self::Defer { .. } => 1,
            Self::Fail { .. } => 2,
            Self::Error { .. } => 3,
            Self::Decline => 4,
            Self::Pass => 5,
        }
    }

    // =========================================================================
    // Predicate Methods
    // =========================================================================

    /// Returns `true` if this result indicates the address was successfully routed.
    ///
    /// True for `Accept` and `Rerouted` variants.
    pub fn is_accepted(&self) -> bool {
        matches!(self, Self::Accept { .. } | Self::Rerouted { .. })
    }

    /// Returns `true` if this result is a temporary failure (deferral).
    pub fn is_temporary(&self) -> bool {
        matches!(self, Self::Defer { .. })
    }

    /// Returns `true` if this result is a permanent failure or error.
    pub fn is_permanent_failure(&self) -> bool {
        matches!(self, Self::Fail { .. } | Self::Error { .. })
    }

    /// Returns `true` if this result means the router chain should continue
    /// to the next router.
    ///
    /// True for `Pass` and `Decline` variants.
    pub fn should_continue(&self) -> bool {
        matches!(self, Self::Pass | Self::Decline)
    }
}

impl fmt::Display for RouterResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Accept {
                transport_name,
                host_list,
            } => {
                write!(f, "ACCEPT")?;
                if let Some(t) = transport_name {
                    write!(f, " transport={t}")?;
                }
                if !host_list.is_empty() {
                    write!(f, " hosts={}", host_list.join(","))?;
                }
                Ok(())
            }
            Self::Pass => write!(f, "PASS"),
            Self::Decline => write!(f, "DECLINE"),
            Self::Fail { message } => {
                write!(f, "FAIL")?;
                if let Some(m) = message {
                    write!(f, ": {m}")?;
                }
                Ok(())
            }
            Self::Defer { message } => {
                write!(f, "DEFER")?;
                if let Some(m) = message {
                    write!(f, ": {m}")?;
                }
                Ok(())
            }
            Self::Error { message } => write!(f, "ERROR: {message}"),
            Self::Rerouted { new_addresses } => {
                write!(f, "REROUTED to {}", new_addresses.join(","))
            }
        }
    }
}

// =============================================================================
// Router Instance Config
// =============================================================================

/// Configuration for a single router instance parsed from the Exim config file.
///
/// Replaces the C `router_instance` struct (structs.h lines 299-366). Every
/// field in the C struct has a corresponding Rust field, with C `uschar *`
/// mapped to `Option<String>`, C `BOOL` to `bool`, C `uid_t`/`gid_t` to
/// `u32`, and the opaque `void *options_block` to `Box<dyn Any + Send + Sync>`.
///
/// # C Equivalent
/// ```c
/// typedef struct router_instance {
///   driver_instance drinst;          // name, driver_name, srcfile, srcline
///   uschar *address_data;            // ... through uschar *transport_name
///   BOOL    address_test;            // ... through BOOL dsn_lasthop
///   int     self_code;               // Encoded "self" handling
///   uid_t   uid; gid_t gid;          // Fixed uid/gid
///   host_item *fallback_hostlist;    // Parsed fallback hosts
///   transport_instance *transport;   // Resolved transport (set at runtime)
///   // ... pointers to pass_router, redirect_router, dnssec
/// } router_instance;
/// ```
///
/// The linked-list `next` pointer is replaced by collection-level ownership
/// (a `Vec<RouterInstanceConfig>` in the config subsystem). The `transport`
/// and `pass_router`/`redirect_router` pointers are resolved at runtime by
/// name rather than stored as struct pointers.
#[derive(Debug)]
pub struct RouterInstanceConfig {
    // =========================================================================
    // Base fields (from driver_instance — structs.h lines 142-151)
    // =========================================================================
    /// Instance name from the configuration file.
    ///
    /// This is the user-assigned name from the config (e.g., "dnslookup_router",
    /// "local_user"). In C, this is `drinst.name`.
    pub name: String,

    /// Driver type name (e.g., "accept", "dnslookup", "manualroute", "redirect").
    ///
    /// Matched against registered `RouterDriverFactory::name` values to resolve
    /// the driver implementation. In C, this is `drinst.driver_name`.
    pub driver_name: String,

    /// Configuration source file path for error reporting.
    ///
    /// Set during config file parsing. `None` for programmatically created instances.
    /// In C, this is `drinst.srcfile`.
    pub srcfile: Option<String>,

    /// Configuration source line number for error reporting.
    ///
    /// Set during config file parsing. `None` for programmatically created instances.
    /// In C, this is `drinst.srcline`.
    pub srcline: Option<i32>,

    // =========================================================================
    // Router-specific string fields (structs.h lines 302-328)
    // All map from C `uschar *` → Rust `Option<String>`.
    // =========================================================================
    /// Arbitrary data accessible in conditions and transports via `$address_data`.
    pub address_data: Option<String>,

    /// Error message used when this router cannot route an address.
    /// Overrides the default "Unrouteable address" message.
    pub cannot_route_message: Option<String>,

    /// General condition (expandable string). If set and expands to false/empty,
    /// the router is skipped for this address.
    pub condition: Option<String>,

    /// Working directory set during delivery for the transport.
    pub current_directory: Option<String>,

    /// Debugging output string evaluated when debug mode is active.
    pub debug_string: Option<String>,

    /// Domain list filter — only addresses in matching domains are processed.
    /// Uses Exim domain_list matching syntax.
    pub domains: Option<String>,

    /// Override errors_to address for messages routed by this router.
    pub errors_to: Option<String>,

    /// Expandable string for setting the group ID dynamically.
    pub expand_gid: Option<String>,

    /// Expandable string for setting the user ID dynamically.
    pub expand_uid: Option<String>,

    /// Expandable string for the `more` option.
    pub expand_more: Option<String>,

    /// Expandable string for the `unseen` option.
    pub expand_unseen: Option<String>,

    /// Additional headers to add to messages routed by this router.
    pub extra_headers: Option<String>,

    /// Fallback hosts for remote transports (colon-separated text list).
    /// Used when the primary MX/A lookup yields no usable hosts.
    pub fallback_hosts: Option<String>,

    /// Parsed fallback host list (from `fallback_hosts` or direct configuration).
    /// In C, this is `host_item *fallback_hostlist` — a linked list of host structs.
    pub fallback_hostlist: Vec<String>,

    /// Home directory for use during delivery by the transport.
    pub home_directory: Option<String>,

    /// Host list of target hosts to ignore during routing.
    pub ignore_target_hosts: Option<String>,

    /// Local part list filter — only addresses with matching local parts are processed.
    /// Uses Exim local_part_list matching syntax.
    pub local_parts: Option<String>,

    /// Name of the router to handle addresses that are passed (PASS result).
    /// Resolved at runtime to a `RouterInstanceConfig` reference.
    pub pass_router_name: Option<String>,

    /// Address prefix to strip before routing and re-add after.
    pub prefix: Option<String>,

    /// Name of the router to handle addresses generated by a redirect.
    /// Resolved at runtime to a `RouterInstanceConfig` reference.
    pub redirect_router_name: Option<String>,

    /// Header names to remove from messages routed by this router.
    pub remove_headers: Option<String>,

    /// File existence checks to perform before running this router.
    /// A colon-separated list of file paths; the router is skipped if any
    /// required file is missing.
    pub require_files: Option<String>,

    /// Home directory set while routing (before delivery).
    pub router_home_directory: Option<String>,

    /// Text option for handling "self" reference (when this host is a
    /// listed MX for the destination domain). Encodes actions like "pass",
    /// "fail", "defer", "send", "reroute", "freeze".
    /// Named `self_config` to avoid collision with Rust's `self` keyword.
    pub self_config: Option<String>,

    /// Sender list filter — only messages from matching senders are processed.
    /// Uses Exim sender_list matching syntax.
    pub senders: Option<String>,

    /// Address suffix to strip before routing and re-add after.
    pub suffix: Option<String>,

    /// Expandable string for IP address translation (fudgery).
    pub translate_ip_address: Option<String>,

    /// Transport name to assign to routed addresses.
    /// Resolved at runtime to a transport instance.
    pub transport_name: Option<String>,

    // =========================================================================
    // Boolean flags (structs.h lines 330-354)
    // All map from C `BOOL` → Rust `bool`.
    // =========================================================================
    /// Use this router when testing addresses (via `-bt` flag).
    pub address_test: bool,

    /// Use this router when processing SMTP EXPN commands.
    pub expn: bool,

    /// If `true`, the local part is treated case-sensitively (not lowercased).
    pub caseful_local_part: bool,

    /// If `true`, check that the local part corresponds to a local system user
    /// before running the router. Sets `$local_user_*` expansion variables.
    pub check_local_user: bool,

    /// Disable logging for this router's actions.
    pub disable_logging: bool,

    /// Fail recipient verification if the recipient matches this router.
    pub fail_verify_recipient: bool,

    /// Fail sender verification if the sender matches this router.
    pub fail_verify_sender: bool,

    /// Flag indicating that `gid` has been explicitly set.
    pub gid_set: bool,

    /// If `true`, call `initgroups()` when setting the uid for delivery.
    pub initgroups: bool,

    /// If `true`, log this delivery as a local delivery even if it uses
    /// a remote transport.
    pub log_as_local: bool,

    /// If `false`, do not try more routers if this one fails (returns FAIL).
    /// Default is `true` — continue to next router on failure.
    pub more: bool,

    /// Treat timeout-caused DEFER results as FAIL.
    pub pass_on_timeout: bool,

    /// The address prefix is optional (may or may not be present).
    pub prefix_optional: bool,

    /// If `false`, skip this router if an ancestor address already used it.
    /// Prevents infinite routing loops.
    pub repeat_use: bool,

    /// Include the local part in the retry key for deferred addresses.
    pub retry_use_local_part: bool,

    /// If `true`, copy routing decisions for addresses in the same domain.
    pub same_domain_copy_routing: bool,

    /// If `true`, rewrite message headers when routing creates a local delivery.
    pub self_rewrite: bool,

    /// The address suffix is optional (may or may not be present).
    pub suffix_optional: bool,

    /// Skip this router if we are not verifying (only run during verification).
    pub verify_only: bool,

    /// Use this router when verifying recipients.
    pub verify_recipient: bool,

    /// Use this router when verifying senders.
    pub verify_sender: bool,

    /// Flag indicating that `uid` has been explicitly set.
    pub uid_set: bool,

    /// If `true`, continue processing subsequent routers even after this one
    /// accepts the address. Used for blind-carbon-copy or logging routers.
    pub unseen: bool,

    /// If `true`, mark this router as a DSN last-hop — DSN notifications
    /// are generated here rather than passed further.
    pub dsn_lasthop: bool,

    // =========================================================================
    // Numeric fields (structs.h lines 356-358)
    // =========================================================================
    /// Encoded version of the `self` handling option.
    ///
    /// Maps the `self_config` text to an integer code used internally:
    ///   - 0 = freeze, 1 = defer, 2 = fail, 3 = send, 4 = reroute, 5 = pass
    pub self_code: i32,

    /// Fixed user ID for delivery. Only used when `uid_set` is `true`.
    pub uid: u32,

    /// Fixed group ID for delivery. Only used when `gid_set` is `true`.
    pub gid: u32,

    // =========================================================================
    // Variable settings (structs.h line 347 — between BOOL flags)
    // =========================================================================
    /// Variable = value setting list. A semicolon-separated list of
    /// `variable = value` assignments that are applied when this router runs.
    pub set: Option<String>,

    // =========================================================================
    // Driver-specific options (replaces C `void *options_block`)
    // =========================================================================
    /// Opaque driver-specific options block.
    ///
    /// Each router driver type defines its own options struct (e.g.,
    /// `dnslookup_router_options_block`, `redirect_router_options_block`).
    /// The framework stores it as a type-erased `Box<dyn Any + Send + Sync>`
    /// and the driver implementation downcasts it to the concrete type.
    ///
    /// In C, this was `void *options_block` on `driver_instance`.
    pub options: Box<dyn Any + Send + Sync>,

    /// Driver-specific options as a simple string key-value map.
    ///
    /// Populated by the config parser from the raw private option lines.
    /// Each entry maps an option name (e.g., `"data"`, `"file"`) to its
    /// string value (everything after the `=` sign, trimmed).
    /// This provides a type-agnostic way for driver implementations to
    /// access their private options without needing to downcast the
    /// `options` field.
    pub private_options_map: HashMap<String, String>,
}

impl RouterInstanceConfig {
    /// Create a new `RouterInstanceConfig` with the given instance name and driver name.
    ///
    /// All optional string fields default to `None`, boolean flags default to
    /// values matching the C `readconf.c` initialization pattern:
    ///   - `address_test`, `expn`, `more`, `repeat_use` → `true`
    ///   - `retry_use_local_part`, `verify_recipient`, `verify_sender` → `true`
    ///   - All other booleans → `false`
    ///   - Numeric fields → `0`
    ///   - `options` → `Box::new(())` (empty unit type)
    pub fn new(name: impl Into<String>, driver_name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            driver_name: driver_name.into(),
            srcfile: None,
            srcline: None,
            address_data: None,
            cannot_route_message: None,
            condition: None,
            current_directory: None,
            debug_string: None,
            domains: None,
            errors_to: None,
            expand_gid: None,
            expand_uid: None,
            expand_more: None,
            expand_unseen: None,
            extra_headers: None,
            fallback_hosts: None,
            fallback_hostlist: Vec::new(),
            home_directory: None,
            ignore_target_hosts: None,
            local_parts: None,
            pass_router_name: None,
            prefix: None,
            redirect_router_name: None,
            remove_headers: None,
            require_files: None,
            router_home_directory: None,
            self_config: None,
            senders: None,
            suffix: None,
            translate_ip_address: None,
            transport_name: None,
            // Boolean defaults matching C readconf.c initialization
            address_test: true,
            expn: true,
            caseful_local_part: false,
            check_local_user: false,
            disable_logging: false,
            fail_verify_recipient: false,
            fail_verify_sender: false,
            gid_set: false,
            initgroups: false,
            log_as_local: false,
            more: true,
            pass_on_timeout: false,
            prefix_optional: false,
            repeat_use: true,
            retry_use_local_part: true,
            same_domain_copy_routing: false,
            self_rewrite: false,
            suffix_optional: false,
            verify_only: false,
            verify_recipient: true,
            verify_sender: true,
            uid_set: false,
            unseen: false,
            dsn_lasthop: false,
            self_code: 0,
            uid: 0,
            gid: 0,
            set: None,
            options: Box::new(()),
            private_options_map: HashMap::new(),
        }
    }

    /// Create a new `RouterInstanceConfig` with configuration source information.
    ///
    /// Used during configuration file parsing when the source file and line
    /// number are known.
    pub fn with_source(
        name: impl Into<String>,
        driver_name: impl Into<String>,
        srcfile: impl Into<String>,
        srcline: i32,
    ) -> Self {
        let mut config = Self::new(name, driver_name);
        config.srcfile = Some(srcfile.into());
        config.srcline = Some(srcline);
        config
    }

    /// Format the configuration source location for error messages.
    ///
    /// Returns a string like `"filename:42"` or `"<unknown>"` if no source
    /// information is available.
    pub fn source_location(&self) -> String {
        match (&self.srcfile, self.srcline) {
            (Some(file), Some(line)) => format!("{file}:{line}"),
            (Some(file), None) => file.clone(),
            _ => "<unknown>".to_string(),
        }
    }
}

impl fmt::Display for RouterInstanceConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "router {}({})", self.name, self.driver_name)
    }
}

// =============================================================================
// Router Flags
// =============================================================================

/// Router descriptor flags — replaces the C `ri_flags` field in `router_info`.
///
/// Used to describe static characteristics of a router driver type (not
/// per-instance configuration). Flags are combined using bitwise OR.
///
/// The C codebase defines `ri_flags` as a plain `int` in `router_info`
/// (structs.h line 386). The Rust equivalent uses a newtype wrapper for
/// type safety with bitwise operation support.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RouterFlags(u32);

impl RouterFlags {
    /// No flags set — the default for most router drivers.
    ///
    /// Used by `manualroute` and `queryprogram` routers, which have no
    /// special transport requirements (C: `.ri_flags = 0`).
    pub const NONE: Self = Self(0);

    /// Router requires a transport to be configured (`ri_yestransport`).
    ///
    /// Maps to C `macros.h` line 943:
    /// ```c
    /// #define ri_yestransport    0x0001    /* Must have a transport */
    /// ```
    ///
    /// When this flag is set, the configuration validator reports an error
    /// if no `transport = <name>` directive is present for the router instance.
    ///
    /// Used by: `accept`, `dnslookup`, `ipliteral` routers.
    pub const YES_TRANSPORT: Self = Self(0x0001);

    /// Router must NOT have a transport configured (`ri_notransport`).
    ///
    /// Maps to C `macros.h` line 944:
    /// ```c
    /// #define ri_notransport     0x0002    /* Must not have a transport */
    /// ```
    ///
    /// When this flag is set, the configuration validator reports an error
    /// if a `transport = <name>` directive IS present for the router instance,
    /// because the router generates child addresses rather than assigning a
    /// transport directly to the original address.
    ///
    /// Used by: `iplookup`, `redirect` routers.
    pub const NO_TRANSPORT: Self = Self(0x0002);

    /// Create a `RouterFlags` value from raw bits.
    ///
    /// Used when mapping from C flag constants or when constructing
    /// composite flag values at compile time.
    pub const fn from_bits(bits: u32) -> Self {
        Self(bits)
    }

    /// Extract the raw bits value.
    ///
    /// Useful for serialization, logging, or interfacing with C code via FFI.
    pub const fn bits(self) -> u32 {
        self.0
    }

    /// Check if this flags value contains all bits from `other`.
    ///
    /// Returns `true` if every bit set in `other` is also set in `self`.
    pub const fn contains(self, other: Self) -> bool {
        (self.0 & other.0) == other.0
    }

    /// Returns `true` if no flags are set.
    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }
}

impl std::ops::BitOr for RouterFlags {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self {
        Self(self.0 | rhs.0)
    }
}

impl std::ops::BitAnd for RouterFlags {
    type Output = Self;

    fn bitand(self, rhs: Self) -> Self {
        Self(self.0 & rhs.0)
    }
}

impl std::ops::BitOrAssign for RouterFlags {
    fn bitor_assign(&mut self, rhs: Self) {
        self.0 |= rhs.0;
    }
}

impl std::ops::BitAndAssign for RouterFlags {
    fn bitand_assign(&mut self, rhs: Self) {
        self.0 &= rhs.0;
    }
}

impl std::ops::Not for RouterFlags {
    type Output = Self;

    fn not(self) -> Self {
        Self(!self.0)
    }
}

impl fmt::Display for RouterFlags {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.is_empty() {
            write!(f, "RouterFlags(NONE)")
        } else {
            let mut parts = Vec::new();
            let mut remaining = self.0;
            if self.contains(Self::YES_TRANSPORT) {
                parts.push("YES_TRANSPORT");
                remaining &= !Self::YES_TRANSPORT.0;
            }
            if self.contains(Self::NO_TRANSPORT) {
                parts.push("NO_TRANSPORT");
                remaining &= !Self::NO_TRANSPORT.0;
            }
            if remaining != 0 {
                // Unknown bits present — fall back to full hex display for
                // forward compatibility with future flag additions.
                write!(f, "RouterFlags(0x{:08x})", self.0)
            } else {
                write!(f, "RouterFlags({})", parts.join("|"))
            }
        }
    }
}

// =============================================================================
// RouterDriver Trait
// =============================================================================

/// Trait for router driver implementations.
///
/// Replaces the C `router_info` struct and its function pointers (structs.h
/// lines 372-387). Each router type (accept, dnslookup, ipliteral, iplookup,
/// manualroute, queryprogram, redirect) implements this trait.
///
/// # C Equivalent
///
/// ```c
/// typedef struct router_info {
///   driver_info drinfo;
///   int (*code)(router_instance *, address_item *, struct passwd *, int,
///               address_item **, address_item **, address_item **, address_item **);
///   void (*tidyup)(router_instance *);
///   int ri_flags;
/// } router_info;
/// ```
///
/// The C `code()` function takes 8 parameters:
///   1. `router_instance *` → `&RouterInstanceConfig` (this router's config)
///   2. `address_item *`    → `&str` (the address being routed)
///   3. `struct passwd *`   → `Option<&str>` (local user, if `check_local_user`)
///   4. `int`               → absorbed into the config/context
///   5. through 8. `address_item **` → encoded in the `RouterResult` variants
///
/// The condensed Rust API captures the same semantics with a cleaner signature.
///
/// # Thread Safety
///
/// Router drivers must be `Send + Sync` because the driver registry is static
/// and accessed from multiple forked processes (though not truly concurrent
/// within a single process due to Exim's fork-per-connection model).
pub trait RouterDriver: Send + Sync + fmt::Debug {
    /// Main routing entry point — evaluates whether this router handles the
    /// given address and determines the delivery destination.
    ///
    /// # Arguments
    ///
    /// * `config` — This router instance's configuration from the Exim config file.
    /// * `address` — The email address being routed (may include prefix/suffix).
    /// * `local_user` — Local system user name if `check_local_user` matched,
    ///   `None` otherwise. In C, this was the `struct passwd *` parameter.
    ///
    /// # Returns
    ///
    /// * `Ok(RouterResult::Accept { .. })` — Route accepted with transport assignment.
    /// * `Ok(RouterResult::Pass)` — Explicitly pass to next router.
    /// * `Ok(RouterResult::Decline)` — Router not applicable for this address.
    /// * `Ok(RouterResult::Fail { .. })` — Permanent routing failure.
    /// * `Ok(RouterResult::Defer { .. })` — Temporary failure, retry later.
    /// * `Ok(RouterResult::Error { .. })` — Internal error.
    /// * `Ok(RouterResult::Rerouted { .. })` — Address redirected to new addresses.
    /// * `Err(DriverError)` — Driver-level error (not found, init failed, etc.).
    fn route(
        &self,
        config: &RouterInstanceConfig,
        address: &str,
        local_user: Option<&str>,
    ) -> Result<RouterResult, DriverError>;

    /// Tidyup function called during process cleanup or between messages.
    ///
    /// Replaces C: `void (*tidyup)(router_instance *)`.
    ///
    /// Most routers do not need cleanup — the default implementation is a no-op.
    /// Routers that cache state or hold resources should override this method.
    fn tidyup(&self, _config: &RouterInstanceConfig) {
        // Default no-op — most routers don't need cleanup.
    }

    /// Returns the descriptor flags for this router driver type.
    ///
    /// Replaces C: `ri_flags` field in `router_info`.
    ///
    /// Default returns `RouterFlags::NONE`. Drivers with special characteristics
    /// should override this method.
    fn flags(&self) -> RouterFlags {
        RouterFlags::NONE
    }

    /// Returns the canonical driver name for identification.
    ///
    /// This must match the `name` field of the corresponding `RouterDriverFactory`
    /// and the `driver = <name>` directive in configuration files.
    ///
    /// Examples: `"accept"`, `"dnslookup"`, `"ipliteral"`, `"iplookup"`,
    /// `"manualroute"`, `"queryprogram"`, `"redirect"`.
    fn driver_name(&self) -> &str;
}

// =============================================================================
// RouterDriverFactory
// =============================================================================

/// Factory for creating `RouterDriver` instances at runtime.
///
/// Registered at compile time via `inventory::submit!` in each router
/// implementation crate. The `DriverRegistry` (in `registry.rs`) collects all
/// submitted factories and provides runtime lookup by name for config-driven
/// router instantiation.
///
/// # Registration Example
///
/// ```ignore
/// use exim_drivers::router_driver::{RouterDriverFactory, RouterDriver};
///
/// inventory::submit! {
///     RouterDriverFactory {
///         name: "accept",
///         create: || Box::new(AcceptRouter::new()),
///         avail_string: None,
///     }
/// }
/// ```
///
/// # Lifecycle
///
/// 1. At compile time, `inventory::submit!` registers factories in all linked crates.
/// 2. At startup, `DriverRegistry::find_router("name")` looks up the factory.
/// 3. The `create` function is called to produce a `Box<dyn RouterDriver>`.
/// 4. The driver is paired with a `RouterInstanceConfig` from the config parser.
/// 5. `route()` is called for each address being routed through this instance.
pub struct RouterDriverFactory {
    /// Canonical name of the router driver type.
    ///
    /// Must match the `driver = <name>` directive in Exim configuration files.
    /// Examples: `"accept"`, `"dnslookup"`, `"ipliteral"`, `"iplookup"`,
    /// `"manualroute"`, `"queryprogram"`, `"redirect"`.
    pub name: &'static str,

    /// Factory function that creates a new, default-configured router driver instance.
    ///
    /// The returned driver is stateless — all per-instance configuration is stored
    /// in `RouterInstanceConfig` and passed to `route()` on each invocation.
    pub create: fn() -> Box<dyn RouterDriver>,

    /// Optional display string shown in `-bV` (version) output.
    ///
    /// If `None`, the `name` field is used for display. If `Some`, this string
    /// is displayed instead (matching C's `avail_string` in `driver_info`).
    pub avail_string: Option<&'static str>,
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // =========================================================================
    // RouterResult Tests
    // =========================================================================

    #[test]
    fn test_router_result_accept_local() {
        let result = RouterResult::accept("local_delivery");
        assert!(result.is_accepted());
        assert!(!result.is_temporary());
        assert!(!result.is_permanent_failure());
        assert!(!result.should_continue());
        assert_eq!(result.to_c_code(), 0);
        match result {
            RouterResult::Accept {
                transport_name,
                host_list,
            } => {
                assert_eq!(transport_name.as_deref(), Some("local_delivery"));
                assert!(host_list.is_empty());
            }
            _ => panic!("expected Accept"),
        }
    }

    #[test]
    fn test_router_result_accept_remote() {
        let result = RouterResult::accept_remote(
            "remote_smtp",
            vec!["mx1.example.com".to_string(), "mx2.example.com".to_string()],
        );
        assert!(result.is_accepted());
        assert_eq!(result.to_c_code(), 0);
        match result {
            RouterResult::Accept {
                transport_name,
                host_list,
            } => {
                assert_eq!(transport_name.as_deref(), Some("remote_smtp"));
                assert_eq!(host_list.len(), 2);
                assert_eq!(host_list[0], "mx1.example.com");
                assert_eq!(host_list[1], "mx2.example.com");
            }
            _ => panic!("expected Accept"),
        }
    }

    #[test]
    fn test_router_result_pass() {
        let result = RouterResult::Pass;
        assert!(!result.is_accepted());
        assert!(!result.is_temporary());
        assert!(!result.is_permanent_failure());
        assert!(result.should_continue());
        assert_eq!(result.to_c_code(), 5);
    }

    #[test]
    fn test_router_result_decline() {
        let result = RouterResult::Decline;
        assert!(!result.is_accepted());
        assert!(result.should_continue());
        assert_eq!(result.to_c_code(), 4);
    }

    #[test]
    fn test_router_result_fail() {
        let result = RouterResult::fail("unrouteable address");
        assert!(!result.is_accepted());
        assert!(result.is_permanent_failure());
        assert!(!result.is_temporary());
        assert!(!result.should_continue());
        assert_eq!(result.to_c_code(), 2);
    }

    #[test]
    fn test_router_result_fail_no_message() {
        let result = RouterResult::Fail { message: None };
        assert!(result.is_permanent_failure());
        assert_eq!(result.to_c_code(), 2);
    }

    #[test]
    fn test_router_result_defer() {
        let result = RouterResult::defer("DNS timeout");
        assert!(!result.is_accepted());
        assert!(result.is_temporary());
        assert!(!result.is_permanent_failure());
        assert!(!result.should_continue());
        assert_eq!(result.to_c_code(), 1);
    }

    #[test]
    fn test_router_result_error() {
        let result = RouterResult::error("internal misconfiguration");
        assert!(!result.is_accepted());
        assert!(result.is_permanent_failure());
        assert_eq!(result.to_c_code(), 3);
    }

    #[test]
    fn test_router_result_rerouted() {
        let result = RouterResult::rerouted(vec![
            "user1@example.com".to_string(),
            "user2@example.com".to_string(),
        ]);
        assert!(result.is_accepted());
        assert_eq!(result.to_c_code(), 0);
        match result {
            RouterResult::Rerouted { new_addresses } => {
                assert_eq!(new_addresses.len(), 2);
            }
            _ => panic!("expected Rerouted"),
        }
    }

    #[test]
    fn test_router_result_display() {
        assert_eq!(
            RouterResult::accept("smtp").to_string(),
            "ACCEPT transport=smtp"
        );
        assert_eq!(RouterResult::Pass.to_string(), "PASS");
        assert_eq!(RouterResult::Decline.to_string(), "DECLINE");
        assert_eq!(
            RouterResult::fail("bad address").to_string(),
            "FAIL: bad address"
        );
        assert_eq!(RouterResult::defer("timeout").to_string(), "DEFER: timeout");
        assert_eq!(RouterResult::error("oops").to_string(), "ERROR: oops");
        assert_eq!(
            RouterResult::rerouted(vec!["a@b.com".to_string()]).to_string(),
            "REROUTED to a@b.com"
        );
    }

    #[test]
    fn test_router_result_display_accept_with_hosts() {
        let result = RouterResult::accept_remote(
            "remote_smtp",
            vec!["mx1.example.com".to_string(), "mx2.example.com".to_string()],
        );
        assert_eq!(
            result.to_string(),
            "ACCEPT transport=remote_smtp hosts=mx1.example.com,mx2.example.com"
        );
    }

    #[test]
    fn test_router_result_equality() {
        assert_eq!(RouterResult::Pass, RouterResult::Pass);
        assert_eq!(RouterResult::Decline, RouterResult::Decline);
        assert_ne!(RouterResult::Pass, RouterResult::Decline);
        assert_eq!(
            RouterResult::fail("x"),
            RouterResult::Fail {
                message: Some("x".to_string())
            }
        );
    }

    // =========================================================================
    // RouterInstanceConfig Tests
    // =========================================================================

    #[test]
    fn test_router_instance_config_new() {
        let cfg = RouterInstanceConfig::new("my_router", "dnslookup");
        assert_eq!(cfg.name, "my_router");
        assert_eq!(cfg.driver_name, "dnslookup");
        assert!(cfg.srcfile.is_none());
        assert!(cfg.srcline.is_none());
        // Verify default boolean values
        assert!(cfg.address_test);
        assert!(cfg.expn);
        assert!(cfg.more);
        assert!(cfg.repeat_use);
        assert!(cfg.retry_use_local_part);
        assert!(cfg.verify_recipient);
        assert!(cfg.verify_sender);
        // Verify false-by-default booleans
        assert!(!cfg.caseful_local_part);
        assert!(!cfg.check_local_user);
        assert!(!cfg.disable_logging);
        assert!(!cfg.unseen);
        assert!(!cfg.dsn_lasthop);
        // Verify numeric defaults
        assert_eq!(cfg.self_code, 0);
        assert_eq!(cfg.uid, 0);
        assert_eq!(cfg.gid, 0);
        // Verify optional fields
        assert!(cfg.address_data.is_none());
        assert!(cfg.domains.is_none());
        assert!(cfg.transport_name.is_none());
        assert!(cfg.fallback_hostlist.is_empty());
    }

    #[test]
    fn test_router_instance_config_with_source() {
        let cfg =
            RouterInstanceConfig::with_source("local_user", "accept", "/etc/exim/configure", 42);
        assert_eq!(cfg.name, "local_user");
        assert_eq!(cfg.driver_name, "accept");
        assert_eq!(cfg.srcfile.as_deref(), Some("/etc/exim/configure"));
        assert_eq!(cfg.srcline, Some(42));
        assert_eq!(cfg.source_location(), "/etc/exim/configure:42");
    }

    #[test]
    fn test_router_instance_config_source_location_unknown() {
        let cfg = RouterInstanceConfig::new("test", "test_driver");
        assert_eq!(cfg.source_location(), "<unknown>");
    }

    #[test]
    fn test_router_instance_config_source_location_file_only() {
        let mut cfg = RouterInstanceConfig::new("test", "test_driver");
        cfg.srcfile = Some("/etc/exim/configure".to_string());
        assert_eq!(cfg.source_location(), "/etc/exim/configure");
    }

    #[test]
    fn test_router_instance_config_display() {
        let cfg = RouterInstanceConfig::new("my_router", "dnslookup");
        assert_eq!(cfg.to_string(), "router my_router(dnslookup)");
    }

    #[test]
    fn test_router_instance_config_options_downcast() {
        #[derive(Debug)]
        struct DnslookupOptions {
            check_secondary_mx: bool,
        }
        let mut cfg = RouterInstanceConfig::new("dns", "dnslookup");
        cfg.options = Box::new(DnslookupOptions {
            check_secondary_mx: true,
        });
        let opts = cfg.options.downcast_ref::<DnslookupOptions>().unwrap();
        assert!(opts.check_secondary_mx);
    }

    // =========================================================================
    // RouterFlags Tests
    // =========================================================================

    #[test]
    fn test_router_flags_none() {
        assert!(RouterFlags::NONE.is_empty());
        assert_eq!(RouterFlags::NONE.bits(), 0);
        assert!(RouterFlags::NONE.contains(RouterFlags::NONE));
    }

    #[test]
    fn test_router_flags_yes_transport() {
        assert!(!RouterFlags::YES_TRANSPORT.is_empty());
        assert_eq!(RouterFlags::YES_TRANSPORT.bits(), 0x0001);
        assert!(RouterFlags::YES_TRANSPORT.contains(RouterFlags::YES_TRANSPORT));
        assert!(!RouterFlags::YES_TRANSPORT.contains(RouterFlags::NO_TRANSPORT));
    }

    #[test]
    fn test_router_flags_no_transport() {
        assert!(!RouterFlags::NO_TRANSPORT.is_empty());
        assert_eq!(RouterFlags::NO_TRANSPORT.bits(), 0x0002);
        assert!(RouterFlags::NO_TRANSPORT.contains(RouterFlags::NO_TRANSPORT));
        assert!(!RouterFlags::NO_TRANSPORT.contains(RouterFlags::YES_TRANSPORT));
    }

    #[test]
    fn test_router_flags_yes_no_transport_distinct() {
        // ri_yestransport (0x0001) and ri_notransport (0x0002) must have
        // distinct bit values — they represent mutually exclusive semantics.
        assert_ne!(RouterFlags::YES_TRANSPORT, RouterFlags::NO_TRANSPORT);
        assert_ne!(
            RouterFlags::YES_TRANSPORT.bits(),
            RouterFlags::NO_TRANSPORT.bits()
        );
    }

    #[test]
    fn test_router_flags_from_bits() {
        let flags = RouterFlags::from_bits(0x0001);
        assert!(!flags.is_empty());
        assert_eq!(flags.bits(), 1);
        assert_eq!(flags, RouterFlags::YES_TRANSPORT);
    }

    #[test]
    fn test_router_flags_bitor() {
        let a = RouterFlags::from_bits(0x01);
        let b = RouterFlags::from_bits(0x02);
        let combined = a | b;
        assert_eq!(combined.bits(), 0x03);
        assert!(combined.contains(a));
        assert!(combined.contains(b));
    }

    #[test]
    fn test_router_flags_bitand() {
        let a = RouterFlags::from_bits(0x03);
        let b = RouterFlags::from_bits(0x02);
        let masked = a & b;
        assert_eq!(masked.bits(), 0x02);
    }

    #[test]
    fn test_router_flags_bitor_assign() {
        let mut flags = RouterFlags::NONE;
        flags |= RouterFlags::from_bits(0x04);
        assert_eq!(flags.bits(), 0x04);
        flags |= RouterFlags::from_bits(0x08);
        assert_eq!(flags.bits(), 0x0C);
    }

    #[test]
    fn test_router_flags_bitand_assign() {
        let mut flags = RouterFlags::from_bits(0x0F);
        flags &= RouterFlags::from_bits(0x03);
        assert_eq!(flags.bits(), 0x03);
    }

    #[test]
    fn test_router_flags_not() {
        let flags = RouterFlags::from_bits(0x00000000);
        let inverted = !flags;
        assert_eq!(inverted.bits(), 0xFFFFFFFF);
    }

    #[test]
    fn test_router_flags_display() {
        assert_eq!(RouterFlags::NONE.to_string(), "RouterFlags(NONE)");
        assert_eq!(
            RouterFlags::YES_TRANSPORT.to_string(),
            "RouterFlags(YES_TRANSPORT)"
        );
        assert_eq!(
            RouterFlags::NO_TRANSPORT.to_string(),
            "RouterFlags(NO_TRANSPORT)"
        );
        assert_eq!(
            RouterFlags::from_bits(0x42).to_string(),
            "RouterFlags(0x00000042)"
        );
    }

    #[test]
    fn test_router_flags_equality() {
        assert_eq!(RouterFlags::NONE, RouterFlags::from_bits(0));
        assert_ne!(RouterFlags::NONE, RouterFlags::from_bits(1));
    }

    // =========================================================================
    // RouterDriver Trait Tests
    // =========================================================================

    /// A minimal test implementation of RouterDriver for testing trait requirements.
    #[derive(Debug)]
    struct TestRouter;

    impl RouterDriver for TestRouter {
        fn route(
            &self,
            config: &RouterInstanceConfig,
            address: &str,
            _local_user: Option<&str>,
        ) -> Result<RouterResult, DriverError> {
            if address.contains("@example.com") {
                Ok(RouterResult::accept(
                    config.transport_name.as_deref().unwrap_or("default_smtp"),
                ))
            } else {
                Ok(RouterResult::Decline)
            }
        }

        fn driver_name(&self) -> &str {
            "test_router"
        }
    }

    #[test]
    fn test_router_driver_trait_route_accept() {
        let router = TestRouter;
        let cfg = RouterInstanceConfig::new("test", "test_router");
        let result = router.route(&cfg, "user@example.com", None).unwrap();
        assert!(result.is_accepted());
    }

    #[test]
    fn test_router_driver_trait_route_decline() {
        let router = TestRouter;
        let cfg = RouterInstanceConfig::new("test", "test_router");
        let result = router.route(&cfg, "user@other.org", None).unwrap();
        assert_eq!(result, RouterResult::Decline);
    }

    #[test]
    fn test_router_driver_trait_default_tidyup() {
        let router = TestRouter;
        let cfg = RouterInstanceConfig::new("test", "test_router");
        router.tidyup(&cfg); // Should not panic — default no-op
    }

    #[test]
    fn test_router_driver_trait_default_flags() {
        let router = TestRouter;
        assert_eq!(router.flags(), RouterFlags::NONE);
    }

    #[test]
    fn test_router_driver_trait_driver_name() {
        let router = TestRouter;
        assert_eq!(router.driver_name(), "test_router");
    }

    #[test]
    fn test_router_driver_trait_object_safety() {
        // Verify the trait can be used as a trait object (dyn RouterDriver)
        let router: Box<dyn RouterDriver> = Box::new(TestRouter);
        assert_eq!(router.driver_name(), "test_router");
    }

    #[test]
    fn test_router_driver_send_sync() {
        // Compile-time verification that RouterDriver trait objects are Send + Sync
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<Box<dyn RouterDriver>>();
    }

    // =========================================================================
    // RouterDriverFactory Tests
    // =========================================================================

    #[test]
    fn test_router_driver_factory_create() {
        let factory = RouterDriverFactory {
            name: "test_router",
            create: || Box::new(TestRouter),
            avail_string: None,
        };
        assert_eq!(factory.name, "test_router");
        let driver = (factory.create)();
        assert_eq!(driver.driver_name(), "test_router");
    }

    #[test]
    fn test_router_driver_factory_with_avail_string() {
        let factory = RouterDriverFactory {
            name: "test_router",
            create: || Box::new(TestRouter),
            avail_string: Some("Test Router (experimental)"),
        };
        assert_eq!(factory.avail_string, Some("Test Router (experimental)"));
    }
}
