// =============================================================================
// exim-drivers/src/router_driver.rs — RouterDriver Trait Definition
// =============================================================================
//
// Defines the `RouterDriver` trait that replaces the C `router_info` struct
// inheritance pattern (structs.h lines 372-387). Each router (accept,
// dnslookup, manualroute, redirect, etc.) implements this trait.
//
// This file contains ZERO unsafe code (per AAP §0.7.2).

use crate::DriverError;

// =============================================================================
// Router Result Enum
// =============================================================================

/// Result of router evaluation for a single address.
///
/// Maps to C router return codes:
///   - OK (0) = route accepted, address assigned a transport
///   - PASS (5) = pass to next router
///   - DECLINE (4) = router does not handle this address
///   - FAIL (2) = routing failed permanently
///   - DEFER (1) = temporary failure, retry later
///   - ERROR (3) = internal error
///
/// Per AAP §0.4.1: "RouterDriver trait: route() → Accept/Pass/Decline/Fail/Defer"
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RouterResult {
    /// Route accepted — address has been assigned a transport.
    /// C: OK (0)
    Accept {
        /// Transport name to use for delivery.
        transport_name: Option<String>,
        /// Generated host list for remote delivery.
        host_list: Vec<String>,
    },
    /// Pass to next router in chain.
    /// C: PASS (5)
    Pass,
    /// Router declined this address (not applicable).
    /// C: DECLINE (4)
    Decline,
    /// Routing failed permanently.
    /// C: FAIL (2)
    Fail {
        /// Optional failure message.
        message: Option<String>,
    },
    /// Temporary failure — retry later.
    /// C: DEFER (1)
    Defer {
        /// Optional deferral message.
        message: Option<String>,
    },
    /// Internal error.
    /// C: ERROR (3)
    Error {
        /// Error description.
        message: String,
    },
    /// Address was rerouted to a different address (redirect router).
    Rerouted {
        /// The new addresses generated by the redirect.
        new_addresses: Vec<String>,
    },
}

// =============================================================================
// Router Instance Config
// =============================================================================

/// Configuration for a router instance, from Exim config file.
///
/// Replaces C `router_instance` struct (structs.h lines 299-366).
#[derive(Debug)]
pub struct RouterInstanceConfig {
    // Base fields (from driver_instance)
    /// Instance name from config.
    pub name: String,
    /// Driver name (e.g., "accept", "dnslookup", "manualroute").
    pub driver_name: String,
    /// Config source file for error reporting.
    pub srcfile: Option<String>,
    /// Config source line for error reporting.
    pub srcline: Option<i32>,

    // Router-specific generic fields
    /// Arbitrary data accessible in conditions.
    pub address_data: Option<String>,
    /// Message when routing fails.
    pub cannot_route_message: Option<String>,
    /// General condition (expandable string).
    pub condition: Option<String>,
    /// Current directory for use during delivery.
    pub current_directory: Option<String>,
    /// Debugging output string.
    pub debug_string: Option<String>,
    /// Specific domains (domain_list).
    pub domains: Option<String>,
    /// Errors address.
    pub errors_to: Option<String>,
    /// Expanded gid string.
    pub expand_gid: Option<String>,
    /// Expanded uid string.
    pub expand_uid: Option<String>,
    /// Expanded "more" string.
    pub expand_more: Option<String>,
    /// Expanded "unseen" string.
    pub expand_unseen: Option<String>,
    /// Additional headers.
    pub extra_headers: Option<String>,
    /// Fallback hosts for remote transports (text list).
    pub fallback_hosts: Option<String>,
    /// Parsed fallback host list.
    pub fallback_hostlist: Vec<String>,
    /// Home directory for use during delivery.
    pub home_directory: Option<String>,
    /// Target hosts to ignore.
    pub ignore_target_hosts: Option<String>,
    /// Specific local parts (local_part_list).
    pub local_parts: Option<String>,
    /// Router name for passed addresses.
    pub pass_router_name: Option<String>,
    /// Address prefix.
    pub prefix: Option<String>,
    /// Router name for generated (redirected) addresses.
    pub redirect_router_name: Option<String>,
    /// Headers to remove.
    pub remove_headers: Option<String>,
    /// File checks before router is run.
    pub require_files: Option<String>,
    /// Home directory for use while routing.
    pub router_home_directory: Option<String>,
    /// Text option for handling self reference.
    pub self_config: Option<String>,
    /// Specific senders (sender_list).
    pub senders: Option<String>,
    /// Address suffix.
    pub suffix: Option<String>,
    /// IP address translation fudgery.
    pub translate_ip_address: Option<String>,
    /// Transport name.
    pub transport_name: Option<String>,

    // Boolean flags
    /// Use this router when testing addresses.
    pub address_test: bool,
    /// Use this router when processing EXPN.
    pub expn: bool,
    /// TRUE => don't lowercase local part.
    pub caseful_local_part: bool,
    /// TRUE => check local user.
    pub check_local_user: bool,
    /// Disable logging for this router.
    pub disable_logging: bool,
    /// Fail verify if recipient matches this router.
    pub fail_verify_recipient: bool,
    /// Fail verify if sender matches this router.
    pub fail_verify_sender: bool,
    /// Flag to indicate gid is set.
    pub gid_set: bool,
    /// TRUE if initgroups is required.
    pub initgroups: bool,
    /// TRUE logs as a local delivery.
    pub log_as_local: bool,
    /// If FALSE, do no more if this one fails.
    pub more: bool,
    /// Treat timeout DEFERs as fails.
    pub pass_on_timeout: bool,
    /// Prefix is optional.
    pub prefix_optional: bool,
    /// If FALSE, skip if ancestor used it.
    pub repeat_use: bool,
    /// Use local part in retry key.
    pub retry_use_local_part: bool,
    /// TRUE => copy routing for same domain.
    pub same_domain_copy_routing: bool,
    /// TRUE to rewrite headers if making local.
    pub self_rewrite: bool,
    /// Suffix is optional.
    pub suffix_optional: bool,
    /// Skip this router if not verifying.
    pub verify_only: bool,
    /// Use this router when verifying a recipient.
    pub verify_recipient: bool,
    /// Use this router when verifying a sender.
    pub verify_sender: bool,
    /// Flag to indicate uid is set.
    pub uid_set: bool,
    /// If TRUE carry on, even after success.
    pub unseen: bool,
    /// If TRUE, this router is a DSN endpoint.
    pub dsn_lasthop: bool,

    // Numeric fields
    /// Encoded version of "self" handling.
    pub self_code: i32,
    /// Fixed uid value.
    pub uid: u32,
    /// Fixed gid value.
    pub gid: u32,

    /// Variable = value setting list.
    pub set: Option<String>,

    /// Driver-specific options (opaque to framework).
    pub options: Box<dyn std::any::Any + Send + Sync>,
}

// =============================================================================
// Router Flags
// =============================================================================

/// Router descriptor flags — replaces C `ri_flags` field in `router_info`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RouterFlags(u32);

impl RouterFlags {
    /// No flags set.
    pub const NONE: Self = Self(0);
}

// =============================================================================
// RouterDriver Trait
// =============================================================================

/// Trait for router driver implementations.
///
/// Replaces C `router_info` struct function pointers (structs.h lines 372-387):
/// ```c
/// typedef struct router_info {
///   driver_info drinfo;
///   int (*code)(router_instance *, address_item *, struct passwd *, int,
///               address_item **, address_item **, address_item **, address_item **);
///   void (*tidyup)(router_instance *);
///   int ri_flags;
/// } router_info;
/// ```
///
/// Each router (accept, dnslookup, manualroute, redirect, etc.) implements this trait.
pub trait RouterDriver: Send + Sync + std::fmt::Debug {
    /// Main routing entry point.
    ///
    /// Replaces C: `int (*code)(router_instance *, address_item *, struct passwd *, int, ...)`
    ///
    /// Evaluates whether this router handles the given address and determines
    /// the delivery destination (transport + host list for remote, or local transport).
    fn route(
        &self,
        config: &RouterInstanceConfig,
        address: &str,
        local_user: Option<&str>,
    ) -> Result<RouterResult, DriverError>;

    /// Tidyup function called during cleanup.
    ///
    /// Replaces C: `void (*tidyup)(router_instance *)`.
    fn tidyup(&self, _config: &RouterInstanceConfig) {
        // Default no-op
    }

    /// Router descriptor flags.
    ///
    /// Replaces C: `ri_flags` in `router_info`.
    fn flags(&self) -> RouterFlags {
        RouterFlags::NONE
    }

    /// Driver name for identification (e.g., "accept", "dnslookup", "redirect").
    fn driver_name(&self) -> &str;
}

// =============================================================================
// RouterDriverFactory
// =============================================================================

/// Factory for creating `RouterDriver` instances. Registered via `inventory::submit!`.
pub struct RouterDriverFactory {
    /// Name of the router driver (e.g., "accept", "dnslookup", "redirect").
    pub name: &'static str,
    /// Factory function that creates a new router driver instance.
    pub create: fn() -> Box<dyn RouterDriver>,
    /// Optional display string.
    pub avail_string: Option<&'static str>,
}
