//! Exim message ID generation using base-62 encoding.
//!
//! The message ID uniquely identifies each message in the spool and is used as
//! the filename stem for `-H` (header/metadata) and `-D` (data) files.
//!
//! ## Format
//!
//! **Current format:** `TTTTTT-PPPPPPPPPPP-SSSS` (23 characters)
//!
//! - `T` = base-62 encoded seconds since Unix epoch (6 characters)
//! - `P` = base-62 encoded process ID (11 characters, zero-padded)
//! - `S` = base-62 encoded sub-second component (4 characters)
//!
//! **Legacy format:** `TTTTTT-PPPPPP-SS` (16 characters)
//!
//! - `T` = base-62 encoded seconds since Unix epoch (6 characters)
//! - `P` = base-62 encoded process ID (6 characters, zero-padded)
//! - `S` = base-62 encoded sub-second component (2 characters)
//!
//! The external form (used in `Received:` headers and `${message_exim_id}`)
//! prepends `'E'` to ensure the ID starts with a letter.
//!
//! **CRITICAL RULE (AAP §0.7.1):** Message IDs generated by Rust MUST be
//! format-identical to those produced by C Exim. The existing test harness
//! validates message ID format.
//!
//! **CRITICAL RULE (AAP §0.7.5):** CLI flags, exit codes, and log output
//! format MUST be preserved — message IDs appear in main log, reject log,
//! and panic log entries.
//!
//! ## Source origins
//!
//! - `src/src/receive.c` lines 2780–2825 — Message ID generation logic
//! - `src/src/string.c` lines 224–253 — `string_base62_32()` and
//!   `string_base62_64()`
//! - `src/src/local_scan.h` lines 114–129 — Message ID length constants
//! - `src/src/globals.c` lines 544–549 — `base62_chars` character set
//! - `src/src/functions.h` lines 1246–1262 — `is_new_message_id()`,
//!   `is_old_message_id()`, `spool_data_start_offset()`

use crate::format::{
    MESSAGE_ID_LENGTH, MESSAGE_ID_LENGTH_OLD, MESSAGE_ID_PID_LEN, MESSAGE_ID_PID_LEN_OLD,
    MESSAGE_ID_SUBTIME_LEN, MESSAGE_ID_SUBTIME_LEN_OLD, MESSAGE_ID_TIME_LEN,
};

// =============================================================================
// Compile-time consistency assertions
// =============================================================================
//
// These assertions verify that the imported format constants are internally
// consistent. They produce no runtime code — the compiler evaluates them at
// build time and rejects the crate if any assertion fails.

/// Current format: 6 (time) + 1 (dash) + 11 (pid) + 1 (dash) + 4 (subtime) = 23
const _ASSERT_CURRENT_FORMAT: () = assert!(
    MESSAGE_ID_LENGTH == MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN + 1 + MESSAGE_ID_SUBTIME_LEN,
    "MESSAGE_ID_LENGTH must equal TIME + 1 + PID + 1 + SUBTIME"
);

/// Legacy format: 6 (time) + 1 (dash) + 6 (pid) + 1 (dash) + 2 (subtime) = 16
const _ASSERT_OLD_FORMAT: () = assert!(
    MESSAGE_ID_LENGTH_OLD
        == MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN_OLD + 1 + MESSAGE_ID_SUBTIME_LEN_OLD,
    "MESSAGE_ID_LENGTH_OLD must equal TIME + 1 + PID_OLD + 1 + SUBTIME_OLD"
);

// =============================================================================
// Base-62 Character Set
// =============================================================================
//
// Exim encodes message ID components using a base-62 character set. The
// standard set (BASE_62 == 62) uses digits, uppercase, and lowercase letters.
// An alternative base-36 set (digits + uppercase only) exists for
// case-insensitive filesystems (defined in exim.h with `#if BASE_62 == 62`),
// but is very rarely used in practice.
//
// Source: `src/src/globals.c` lines 544–549:
//   #if BASE_62 == 62
//   uschar *base62_chars =
//       "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
//   #else
//   uschar *base62_chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
//   #endif
//
// To support base-36 on case-insensitive filesystems, add a `base36` feature
// flag to the exim-spool Cargo.toml and use `#[cfg(feature = "base36")]`
// guards around `BASE` and `BASE_CHARS` definitions.

/// The number of distinct characters in the encoding alphabet.
///
/// Default value is 62 (digits + uppercase + lowercase). For case-insensitive
/// filesystems this would be 36 (digits + uppercase only), matching the C
/// `BASE_62` compile-time constant.
const BASE: usize = 62;

/// The ordered character set for base-62 encoding.
///
/// Index 0 = `'0'`, index 9 = `'9'`, index 10 = `'A'`, index 35 = `'Z'`,
/// index 36 = `'a'`, index 61 = `'z'`.
///
/// Source: `src/src/globals.c` lines 544–546.
const BASE_CHARS: &[u8; 62] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

// =============================================================================
// Base-62 Encoding Functions
// =============================================================================

/// Encode a 32-bit value to exactly 6 base-62 characters.
///
/// This is the Rust equivalent of C `string_base62_32()` from
/// `src/src/string.c` lines 224–236. The output is always exactly
/// [`MESSAGE_ID_TIME_LEN`](crate::format::MESSAGE_ID_TIME_LEN) (6)
/// characters. When the value is smaller than 62^6, leading positions are
/// filled with `'0'` (the first character of the base-62 charset).
///
/// # Algorithm
///
/// Fills a fixed 6-byte array from right to left using modular arithmetic:
/// `result[i] = BASE_CHARS[value % 62]` then `value /= 62`. When `value`
/// reaches zero, subsequent positions receive `BASE_CHARS[0]` (`'0'`) because
/// `0 % 62 == 0`.
///
/// This matches the C implementation which uses a static `yield[7]` buffer
/// (6 chars + null terminator) and fills via `while (p > yield)` — always
/// exactly 6 iterations regardless of the input value.
///
/// # Examples
///
/// ```
/// use exim_spool::message_id::string_base62_32;
///
/// // Zero encodes to six '0' characters
/// assert_eq!(&string_base62_32(0), b"000000");
///
/// // Value 1 encodes with leading zeros
/// assert_eq!(&string_base62_32(1), b"000001");
///
/// // Value 62 wraps to next position
/// assert_eq!(&string_base62_32(62), b"000010");
/// ```
pub fn string_base62_32(mut value: u32) -> [u8; 6] {
    // C reference (src/src/string.c lines 227–234):
    //   static uschar yield[7];
    //   uschar * p = yield + sizeof(yield) - 1;
    //   *p = 0;
    //   while (p > yield)
    //     { *--p = base62_chars[value % BASE_62]; value /= BASE_62; }
    let base = BASE as u32;
    let mut result = [0u8; 6];
    for i in (0..6).rev() {
        result[i] = BASE_CHARS[(value % base) as usize];
        value /= base;
    }
    result
}

/// Encode a 64-bit value to exactly 11 base-62 characters, zero-padded.
///
/// This is the Rust equivalent of C `string_base62_64()` from
/// `src/src/string.c` lines 238–253. The output is always exactly
/// [`MESSAGE_ID_PID_LEN`](crate::format::MESSAGE_ID_PID_LEN) (11)
/// characters. Positions where the value has been fully consumed are filled
/// with `'0'` (the first character of the base-62 charset).
///
/// # Algorithm
///
/// Fills a fixed 11-byte array from right to left. While `value > 0`:
/// `result[i] = BASE_CHARS[value % 62]` then `value /= 62`. Once `value`
/// reaches zero, remaining positions are set to `'0'`.
///
/// This matches the C implementation which explicitly zero-pads:
/// ```text
/// while (p > yield)
///   if (value) { *--p = base62_chars[value % BASE_62]; value /= BASE_62; }
///   else *--p = '0';
/// ```
///
/// # Examples
///
/// ```
/// use exim_spool::message_id::string_base62_64;
///
/// // Zero encodes to eleven '0' characters
/// assert_eq!(&string_base62_64(0), b"00000000000");
///
/// // Small value with leading zero-padding
/// assert_eq!(&string_base62_64(1), b"00000000001");
/// ```
pub fn string_base62_64(mut value: u64) -> [u8; 11] {
    // C reference (src/src/string.c lines 241–252):
    //   static uschar yield[12];
    //   uschar * p = yield + sizeof(yield) - 1;
    //   *p = '\0';
    //   while (p > yield)
    //     if (value)
    //       { *--p = base62_chars[value % BASE_62]; value /= BASE_62; }
    //     else
    //       *--p = '0';
    let base = BASE as u64;
    let mut result = [b'0'; 11]; // Pre-fill with '0' for zero-padding
    for i in (0..11).rev() {
        if value > 0 {
            result[i] = BASE_CHARS[(value % base) as usize];
            value /= base;
        }
        // When value == 0, the pre-filled '0' is already correct,
        // matching the C `else *--p = '0'` branch.
    }
    result
}

// =============================================================================
// Message ID Generation
// =============================================================================

/// Generate a complete Exim message ID in the current format.
///
/// Produces a 23-character message ID in the format `TTTTTT-PPPPPPPPPPP-SSSS`:
///
/// - **Time** (`T`, 6 chars): Base-62 encoded seconds since Unix epoch via
///   [`string_base62_32`].
/// - **PID** (`P`, 11 chars): Base-62 encoded process ID via
///   [`string_base62_64`].
/// - **Sub-second** (`S`, 4 chars): Base-62 encoded sub-second component,
///   derived from either:
///   - **With `host_number`**: `host_number × (1000000 / id_resolution) +
///     tv_usec / id_resolution` — encodes both host identity and sub-second
///     precision into a single field.
///   - **Without `host_number`**: `tv_usec / id_resolution` — encodes only
///     the fractional time at the configured resolution.
///
///   In both cases, the full 6-character base-62 output is computed, and only
///   the last [`MESSAGE_ID_SUBTIME_LEN`] (4) characters are used (offset
///   `6 − 4 = 2`, i.e., bytes `[2..6]`).
///
/// This is the Rust equivalent of the message ID generation in
/// `src/src/receive.c` lines 2799–2825.
///
/// # Arguments
///
/// * `tv_sec` — Seconds since Unix epoch (from `gettimeofday`).
/// * `pid` — Process ID of the receiving process (64-bit to support modern
///   kernels with large PID namespaces).
/// * `tv_usec` — Microseconds component of the timestamp (0–999999).
/// * `host_number` — Optional host number for multi-host setups. When
///   `Some(n)`, the sub-second component encodes both the host number and
///   the fractional time. The value is validated at config read time to
///   ensure the calculation does not overflow.
/// * `id_resolution` — Resolution divisor for the sub-second component.
///   Typically 1 (microsecond resolution) or higher for coarser granularity.
///   Must be non-zero.
///
/// # Panics
///
/// Panics if `id_resolution` is zero (division by zero).
///
/// # Examples
///
/// ```
/// use exim_spool::message_id::generate_message_id;
///
/// let id = generate_message_id(1_700_000_000, 12345, 500_000, None, 1);
/// assert_eq!(id.len(), 23);
/// assert_eq!(id.as_bytes()[6], b'-');
/// assert_eq!(id.as_bytes()[18], b'-');
/// ```
pub fn generate_message_id(
    tv_sec: u32,
    pid: u64,
    tv_usec: u32,
    host_number: Option<u32>,
    id_resolution: u32,
) -> String {
    // Pre-allocate the exact capacity for the 23-character message ID
    let mut result = String::with_capacity(MESSAGE_ID_LENGTH);

    // ── Time component (6 chars) ────────────────────────────────────────────
    // C: Ustrncpy(message_id, string_base62_32((long int)(message_id_tv.tv_sec)),
    //            MESSAGE_ID_TIME_LEN);
    let time_chars = string_base62_32(tv_sec);
    for &b in &time_chars {
        result.push(b as char);
    }

    // ── First separator ─────────────────────────────────────────────────────
    // C: message_id[MESSAGE_ID_TIME_LEN] = '-';
    result.push('-');

    // ── PID component (11 chars) ────────────────────────────────────────────
    // C: Ustrncpy(message_id + MESSAGE_ID_TIME_LEN + 1,
    //            string_base62_64((long int)getpid()), MESSAGE_ID_PID_LEN);
    let pid_chars = string_base62_64(pid);
    for &b in &pid_chars {
        result.push(b as char);
    }

    // ── Second separator ────────────────────────────────────────────────────
    // C: sprintf format begins with "-"
    result.push('-');

    // ── Sub-second component (4 chars) ──────────────────────────────────────
    // Compute the sub-second value. Use u64 intermediate to avoid potential
    // overflow when host_number is large, matching the C behavior where the
    // computation occurs in `long int` (64-bit on 64-bit systems) before
    // being passed to string_base62_32.
    let subtime_value: u32 = match host_number {
        Some(hn) => {
            // C: host_number * (1000000/id_resolution)
            //    + message_id_tv.tv_usec/id_resolution
            let val = u64::from(hn) * (1_000_000u64 / u64::from(id_resolution))
                + u64::from(tv_usec) / u64::from(id_resolution);
            val as u32
        }
        None => {
            // C: message_id_tv.tv_usec/id_resolution
            tv_usec / id_resolution
        }
    };

    // Encode to 6 base-62 characters, then take the last MESSAGE_ID_SUBTIME_LEN (4)
    // C: string_base62_32(...) + (6 - MESSAGE_ID_SUBTIME_LEN)
    let subtime_full = string_base62_32(subtime_value);
    let offset = MESSAGE_ID_TIME_LEN - MESSAGE_ID_SUBTIME_LEN; // 6 - 4 = 2
    for &b in &subtime_full[offset..] {
        result.push(b as char);
    }

    debug_assert_eq!(
        result.len(),
        MESSAGE_ID_LENGTH,
        "generated message ID must be exactly {} characters",
        MESSAGE_ID_LENGTH
    );
    result
}

// =============================================================================
// Message ID Format Detection
// =============================================================================

/// Detect if a message ID is in the current (new) format.
///
/// The new format has a dash (`'-'`) at position
/// `MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN` (= 6 + 1 + 11 = **18**),
/// which is the separator before the 4-character sub-second component.
///
/// This is the Rust equivalent of the C inline function `is_new_message_id()`
/// from `src/src/functions.h` lines 1245–1249:
///
/// ```text
/// static inline BOOL is_new_message_id(const uschar * id) {
///     return id[MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN] == '-';
/// }
/// ```
///
/// Unlike the C version, this function performs bounds checking via
/// [`slice::get`] and safely returns `false` for strings shorter than 19
/// characters.
///
/// # Arguments
///
/// * `id` — A string that may be a message ID. May be shorter than the
///   expected length, in which case the function safely returns `false`.
///
/// # Examples
///
/// ```
/// use exim_spool::message_id::is_new_message_id;
///
/// // New-format ID: dash at position 18
/// assert!(is_new_message_id("AAAAAA-00000000000-BBBB"));
///
/// // Old-format ID: no dash at position 18
/// assert!(!is_new_message_id("AAAAAA-BBBBBB-CC"));
///
/// // Short string: safely returns false
/// assert!(!is_new_message_id("short"));
/// ```
pub fn is_new_message_id(id: &str) -> bool {
    // C: return id[MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN] == '-';
    // Position: 6 + 1 + 11 = 18
    id.as_bytes()
        .get(MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN)
        == Some(&b'-')
}

/// Detect if a message ID is in the old (legacy) format.
///
/// The old format has a dash (`'-'`) at position
/// `MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN_OLD` (= 6 + 1 + 6 = **13**),
/// which is the separator before the 2-character sub-second component.
///
/// This is the Rust equivalent of the C inline function `is_old_message_id()`
/// from `src/src/functions.h` lines 1251–1255:
///
/// ```text
/// static inline BOOL is_old_message_id(const uschar * id) {
///     return id[MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN_OLD] == '-';
/// }
/// ```
///
/// Unlike the C version, this function performs bounds checking via
/// [`slice::get`] and safely returns `false` for strings shorter than 14
/// characters.
///
/// # Arguments
///
/// * `id` — A string that may be a message ID. May be shorter than the
///   expected length, in which case the function safely returns `false`.
///
/// # Examples
///
/// ```
/// use exim_spool::message_id::is_old_message_id;
///
/// // Old-format ID: dash at position 13
/// assert!(is_old_message_id("AAAAAA-BBBBBB-CC"));
///
/// // New-format ID: no dash at position 13
/// assert!(!is_old_message_id("AAAAAA-00000000000-BBBB"));
///
/// // Short string: safely returns false
/// assert!(!is_old_message_id("short"));
/// ```
pub fn is_old_message_id(id: &str) -> bool {
    // C: return id[MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN_OLD] == '-';
    // Position: 6 + 1 + 6 = 13
    id.as_bytes()
        .get(MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN_OLD)
        == Some(&b'-')
}

// =============================================================================
// External Message ID
// =============================================================================

/// Format a message ID for external use (e.g., in `Received:` headers).
///
/// Prepends `'E'` to the internal message ID to ensure it starts with a
/// letter, as required by some implementations (notably Smail). The internal
/// spool file names do **not** include this leading letter.
///
/// From `src/src/receive.c` lines 2786–2790:
///
/// > "There doesn't seem to be anything in the RFC which requires a message
/// > id to start with a letter, but Smail was changed to ensure this. The
/// > external form of the message id (as supplied by string expansion)
/// > therefore starts with an additional leading 'E'. The spool file names
/// > do not include this leading letter and it is not used internally."
///
/// # Arguments
///
/// * `id` — The internal message ID (e.g., `"TTTTTT-PPPPPPPPPPP-SSSS"`).
///
/// # Returns
///
/// A [`String`] with `'E'` prepended (e.g., `"ETTTTTT-PPPPPPPPPPP-SSSS"`).
///
/// # Examples
///
/// ```
/// use exim_spool::message_id::external_message_id;
///
/// let ext = external_message_id("1abCDE-000000001s3-ABCD");
/// assert_eq!(ext, "E1abCDE-000000001s3-ABCD");
/// ```
pub fn external_message_id(id: &str) -> String {
    let mut result = String::with_capacity(1 + id.len());
    result.push('E');
    result.push_str(id);
    result
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ── string_base62_32 tests ──────────────────────────────────────────────

    #[test]
    fn test_base62_32_zero() {
        // Zero value produces all '0' characters
        assert_eq!(&string_base62_32(0), b"000000");
    }

    #[test]
    fn test_base62_32_one() {
        // Value 1 produces leading zeros with '1' at the end
        assert_eq!(&string_base62_32(1), b"000001");
    }

    #[test]
    fn test_base62_32_base_value() {
        // Value 62 (one full cycle) wraps to next position
        assert_eq!(&string_base62_32(62), b"000010");
    }

    #[test]
    fn test_base62_32_charset_order() {
        // Verify the character set order matches C:
        // 0-9 → A-Z → a-z
        assert_eq!(string_base62_32(9)[5], b'9');
        assert_eq!(string_base62_32(10)[5], b'A');
        assert_eq!(string_base62_32(35)[5], b'Z');
        assert_eq!(string_base62_32(36)[5], b'a');
        assert_eq!(string_base62_32(61)[5], b'z');
    }

    #[test]
    fn test_base62_32_always_six_chars() {
        // Every output must be exactly 6 characters
        assert_eq!(string_base62_32(0).len(), 6);
        assert_eq!(string_base62_32(1).len(), 6);
        assert_eq!(string_base62_32(u32::MAX).len(), 6);
    }

    #[test]
    fn test_base62_32_max_u32() {
        // u32::MAX = 4294967295
        // Encoding right-to-left:
        //   4294967295 % 62 = 3  → '3', 4294967295 / 62 = 69273666
        //   69273666   % 62 = 12 → 'C', 69273666   / 62 = 1117317
        //   1117317    % 62 = 15 → 'F', 1117317    / 62 = 18021
        //   18021      % 62 = 41 → 'f', 18021      / 62 = 290
        //   290        % 62 = 42 → 'g', 290        / 62 = 4
        //   4          % 62 = 4  → '4', 4          / 62 = 0
        let result = string_base62_32(u32::MAX);
        assert_eq!(&result, b"4gfFC3");
    }

    #[test]
    fn test_base62_32_typical_timestamp() {
        // A typical Unix timestamp (seconds since epoch)
        // 1700000000 (2023-11-14) in base 62:
        //   1700000000 / 62 = 27419354, remainder 52 → 'q'
        //   27419354 / 62   = 442247, remainder 40 → 'e'
        //   442247 / 62     = 7133, remainder 1 → '1'
        //   7133 / 62       = 115, remainder 3 → '3'
        //   115 / 62        = 1, remainder 53 → 'r'
        //   1 / 62          = 0, remainder 1 → '1'
        let result = string_base62_32(1_700_000_000);
        assert_eq!(&result, b"1r31eq");
    }

    // ── string_base62_64 tests ──────────────────────────────────────────────

    #[test]
    fn test_base62_64_zero() {
        // Zero value produces all '0' characters (zero-padded)
        assert_eq!(&string_base62_64(0), b"00000000000");
    }

    #[test]
    fn test_base62_64_one() {
        // Value 1 with zero-padding
        assert_eq!(&string_base62_64(1), b"00000000001");
    }

    #[test]
    fn test_base62_64_base_value() {
        // Value 62 wraps to next position
        assert_eq!(&string_base62_64(62), b"00000000010");
    }

    #[test]
    fn test_base62_64_always_eleven_chars() {
        // Every output must be exactly 11 characters
        assert_eq!(string_base62_64(0).len(), 11);
        assert_eq!(string_base62_64(1).len(), 11);
        assert_eq!(string_base62_64(u64::MAX).len(), 11);
    }

    #[test]
    fn test_base62_64_typical_pid() {
        // A typical Linux PID like 12345
        //   12345 / 62 = 199, remainder 7 → '7'
        //   199 / 62   = 3, remainder 13 → 'D'
        //   3 / 62     = 0, remainder 3 → '3'
        let result = string_base62_64(12345);
        assert_eq!(&result, b"000000003D7");
    }

    // ── generate_message_id tests ───────────────────────────────────────────

    #[test]
    fn test_generate_message_id_length() {
        let id = generate_message_id(1_700_000_000, 12345, 500_000, None, 1);
        assert_eq!(id.len(), MESSAGE_ID_LENGTH);
    }

    #[test]
    fn test_generate_message_id_separators() {
        let id = generate_message_id(1_700_000_000, 12345, 500_000, None, 1);
        // First separator at position 6
        assert_eq!(id.as_bytes()[MESSAGE_ID_TIME_LEN], b'-');
        // Second separator at position 18
        assert_eq!(
            id.as_bytes()[MESSAGE_ID_TIME_LEN + 1 + MESSAGE_ID_PID_LEN],
            b'-'
        );
    }

    #[test]
    fn test_generate_message_id_format() {
        let id = generate_message_id(1_700_000_000, 12345, 500_000, None, 1);
        // Time component: string_base62_32(1700000000) = "1r31eq"
        assert_eq!(&id[0..6], "1r31eq");
        // PID component: string_base62_64(12345) = "000000003D7"
        assert_eq!(&id[7..18], "000000003D7");
        // Sub-second without host_number: string_base62_32(500000/1) = string_base62_32(500000)
        // 500000 / 62 = 8064, remainder 32 → 'W'
        // 8064 / 62   = 130, remainder 4 → '4'
        // 130 / 62    = 2, remainder 6 → '6'
        // 2 / 62      = 0, remainder 2 → '2'
        // Full: "0026" + "4W" → "0026" part starting at offset 2
        // Actually: string_base62_32(500000) then take last 4 chars
        // 500000 in base 62:
        //   500000 / 62 = 8064 r 32 → 'W'
        //   8064 / 62   = 130  r 4  → '4'
        //   130 / 62    = 2    r 6  → '6'
        //   2 / 62      = 0    r 2  → '2'
        //   0 / 62      = 0    r 0  → '0'
        //   0 / 62      = 0    r 0  → '0'
        // Full 6 chars: "0026" + "4W" → "0026" is [0..4], "4W" is [4..6]
        // Wait let me recalculate from right to left:
        // Position 5: 500000 % 62 = 32 → 'W', 500000 / 62 = 8064
        // Position 4: 8064 % 62 = 4 → '4', 8064 / 62 = 130
        // Position 3: 130 % 62 = 6 → '6', 130 / 62 = 2
        // Position 2: 2 % 62 = 2 → '2', 2 / 62 = 0
        // Position 1: 0 % 62 = 0 → '0', 0 / 62 = 0
        // Position 0: 0 % 62 = 0 → '0', 0 / 62 = 0
        // Full: ['0','0','2','6','4','W']
        // Last 4 chars (offset 2): ['2','6','4','W'] → "264W"
        assert_eq!(&id[19..23], "264W");
    }

    #[test]
    fn test_generate_message_id_with_host_number() {
        // With host_number = 5, id_resolution = 1:
        // subtime = 5 * (1000000/1) + 500000/1 = 5000000 + 500000 = 5500000
        let id = generate_message_id(1_700_000_000, 12345, 500_000, Some(5), 1);
        assert_eq!(id.len(), MESSAGE_ID_LENGTH);

        // Verify sub-second component
        // string_base62_32(5500000):
        //   5500000 / 62 = 88709 r 42 → 'g'
        //   88709 / 62   = 1430  r 49 → 'n'
        //   1430 / 62    = 23    r 4  → '4'
        //   23 / 62      = 0     r 23 → 'N'
        //   0 / 62       = 0     r 0  → '0'
        //   0 / 62       = 0     r 0  → '0'
        // Full: "00N4ng"
        // Last 4 chars (offset 2): "N4ng"
        assert_eq!(&id[19..23], "N4ng");
    }

    #[test]
    fn test_generate_message_id_with_resolution() {
        // With id_resolution = 1000:
        // subtime = 500000 / 1000 = 500
        let id = generate_message_id(1_700_000_000, 12345, 500_000, None, 1000);
        assert_eq!(id.len(), MESSAGE_ID_LENGTH);

        // string_base62_32(500):
        //   500 / 62 = 8 r 4 → '4'
        //   8 / 62   = 0 r 8 → '8'
        //   (remaining fill with '0')
        // Full: "000084"
        // Last 4 chars: "0084"
        assert_eq!(&id[19..23], "0084");
    }

    #[test]
    fn test_generate_message_id_zero_values() {
        let id = generate_message_id(0, 0, 0, None, 1);
        assert_eq!(id.len(), MESSAGE_ID_LENGTH);
        // All zeros: "000000-00000000000-0000"
        assert_eq!(id, "000000-00000000000-0000");
    }

    #[test]
    fn test_generate_message_id_is_new_format() {
        let id = generate_message_id(1_700_000_000, 12345, 500_000, None, 1);
        assert!(is_new_message_id(&id));
        assert!(!is_old_message_id(&id));
    }

    // ── is_new_message_id tests ─────────────────────────────────────────────

    #[test]
    fn test_is_new_message_id_valid() {
        // Valid new-format: dash at position 18
        assert!(is_new_message_id("AAAAAA-00000000000-BBBB"));
    }

    #[test]
    fn test_is_new_message_id_old_format() {
        // Old format: no dash at position 18
        assert!(!is_new_message_id("AAAAAA-BBBBBB-CC"));
    }

    #[test]
    fn test_is_new_message_id_empty() {
        assert!(!is_new_message_id(""));
    }

    #[test]
    fn test_is_new_message_id_short() {
        assert!(!is_new_message_id("too_short"));
    }

    // ── is_old_message_id tests ─────────────────────────────────────────────

    #[test]
    fn test_is_old_message_id_valid() {
        // Valid old-format: dash at position 13
        assert!(is_old_message_id("AAAAAA-BBBBBB-CC"));
    }

    #[test]
    fn test_is_old_message_id_new_format() {
        // New format: no dash at position 13
        assert!(!is_old_message_id("AAAAAA-00000000000-BBBB"));
    }

    #[test]
    fn test_is_old_message_id_empty() {
        assert!(!is_old_message_id(""));
    }

    #[test]
    fn test_is_old_message_id_short() {
        assert!(!is_old_message_id("short"));
    }

    // ── external_message_id tests ───────────────────────────────────────────

    #[test]
    fn test_external_message_id_prefix() {
        let ext = external_message_id("TTTTTT-PPPPPPPPPPP-SSSS");
        assert_eq!(ext, "ETTTTTT-PPPPPPPPPPP-SSSS");
    }

    #[test]
    fn test_external_message_id_length() {
        let id = generate_message_id(1_700_000_000, 12345, 500_000, None, 1);
        let ext = external_message_id(&id);
        // External form is 1 character longer than internal form
        assert_eq!(ext.len(), id.len() + 1);
        assert_eq!(ext.as_bytes()[0], b'E');
    }

    #[test]
    fn test_external_message_id_empty() {
        assert_eq!(external_message_id(""), "E");
    }

    // ── Compile-time assertion usage ────────────────────────────────────────

    #[test]
    fn test_format_constants_consistency() {
        // Verify that the compile-time assertions are consistent with
        // the expected values. These also exercise the imported constants
        // that are used by the const assertions above.
        assert_eq!(MESSAGE_ID_LENGTH, 23);
        assert_eq!(MESSAGE_ID_LENGTH_OLD, 16);
        assert_eq!(MESSAGE_ID_TIME_LEN, 6);
        assert_eq!(MESSAGE_ID_PID_LEN, 11);
        assert_eq!(MESSAGE_ID_PID_LEN_OLD, 6);
        assert_eq!(MESSAGE_ID_SUBTIME_LEN, 4);
        assert_eq!(MESSAGE_ID_SUBTIME_LEN_OLD, 2);
    }

    // ── Base-62 character set verification ──────────────────────────────────

    #[test]
    fn test_base62_charset_matches_c() {
        // Verify the Rust base-62 character set is identical to the C version
        let expected = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        assert_eq!(BASE_CHARS, expected);
        assert_eq!(BASE_CHARS.len(), BASE);
    }

    // ── Round-trip consistency ───────────────────────────────────────────────

    #[test]
    fn test_base62_32_encoding_consistency() {
        // Verify that different values produce different encodings
        let a = string_base62_32(0);
        let b = string_base62_32(1);
        let c = string_base62_32(u32::MAX);
        assert_ne!(a, b);
        assert_ne!(b, c);
        assert_ne!(a, c);
    }

    #[test]
    fn test_base62_64_encoding_consistency() {
        // Verify that different values produce different encodings
        let a = string_base62_64(0);
        let b = string_base62_64(1);
        let c = string_base62_64(u64::MAX);
        assert_ne!(a, b);
        assert_ne!(b, c);
        assert_ne!(a, c);
    }

    #[test]
    fn test_generate_message_id_uniqueness() {
        // Different inputs produce different message IDs
        let id1 = generate_message_id(100, 1, 0, None, 1);
        let id2 = generate_message_id(100, 2, 0, None, 1);
        let id3 = generate_message_id(101, 1, 0, None, 1);
        let id4 = generate_message_id(100, 1, 1, None, 1);
        assert_ne!(id1, id2); // Different PIDs
        assert_ne!(id1, id3); // Different times
        assert_ne!(id1, id4); // Different sub-seconds
    }

    // ── All characters are valid base-62 ────────────────────────────────────

    #[test]
    fn test_generated_id_all_valid_chars() {
        let id = generate_message_id(1_700_000_000, 99999, 999_999, None, 1);
        for (i, &b) in id.as_bytes().iter().enumerate() {
            if i == 6 || i == 18 {
                assert_eq!(b, b'-', "separator at position {i}");
            } else {
                assert!(
                    BASE_CHARS.contains(&b),
                    "character '{}' at position {} not in base-62 charset",
                    b as char,
                    i
                );
            }
        }
    }
}
