//! Safe wrappers around libopendmarc for DMARC (Domain-based Message
//! Authentication, Reporting, and Conformance) policy evaluation.
//!
//! This module is feature-gated behind `#[cfg(feature = "ffi-dmarc")]` and is
//! the **ONLY** location in the workspace where `unsafe` calls to libopendmarc
//! are permitted, per AAP §0.7.2.
//!
//! The C DMARC module (`src/src/miscmods/dmarc.c`) calls 20+ libopendmarc
//! functions. All of these are wrapped in safe Rust APIs exposed by this module.
//!
//! # Safety
//!
//! All `unsafe` blocks in this module are confined to the `exim-ffi` crate,
//! which is the ONLY crate permitted to contain `unsafe` code per AAP §0.7.2.
//! Each `unsafe` block has an inline justification comment explaining its
//! necessity. The safe public API prevents null pointer dereference and properly
//! manages the lifecycle of libopendmarc objects through RAII (`Drop`).
//!
//! # Source Context
//!
//! This module replaces the C implementation in:
//! - `src/src/miscmods/dmarc.c` (477 lines — DMARC evaluation + libopendmarc calls)
//! - `src/src/miscmods/dmarc.h` (144 lines — DMARC types, constants, extern decls)
//! - `src/src/miscmods/dmarc_api.h` (16 lines — function table entry numbers)

use std::error::Error as StdError;
use std::ffi::{CStr, CString};
use std::fmt;
use std::ptr;

use libc::{c_char, c_int, c_void};

// ---------------------------------------------------------------------------
// Raw FFI bindings generated by bindgen from opendmarc/dmarc.h.
// ---------------------------------------------------------------------------

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::unnecessary_operation,
    clippy::identity_op
)]
// Justification: bindgen-generated FFI bindings preserve C naming conventions
// for libopendmarc types, functions, and constants. The C library uses
// UPPER_CASE constants, typedef names with _T suffix, and lower_case function
// names that do not conform to Rust naming conventions. The clippy allows
// suppress bindgen-generated static assertions for struct layout validation.
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/dmarc_bindings.rs"));
}

// ---------------------------------------------------------------------------
// Re-exported libopendmarc constants
// ---------------------------------------------------------------------------

/// Library version stamp (`OPENDMARC_LIB_VERSION`).
///
/// Encodes major.minor.patch.release as a 4-byte bitmask where each component
/// occupies one byte: `(major << 24) | (minor << 16) | (patch << 8) | release`.
pub const OPENDMARC_LIB_VERSION: u32 = ffi::OPENDMARC_LIB_VERSION;

/// Maximum hostname length used for domain buffers (256 bytes).
pub const DMARC_MAXHOSTNAMELEN: u32 = ffi::DMARC_MAXHOSTNAMELEN;

// --- Status / parse result codes ---

/// Parse completed successfully (0).
pub const DMARC_PARSE_OKAY: u32 = ffi::DMARC_PARSE_OKAY;
/// Empty input (1).
pub const DMARC_PARSE_ERROR_EMPTY: u32 = ffi::DMARC_PARSE_ERROR_EMPTY;
/// NULL context pointer (2).
pub const DMARC_PARSE_ERROR_NULL_CTX: u32 = ffi::DMARC_PARSE_ERROR_NULL_CTX;
/// Bad DMARC version string (3).
pub const DMARC_PARSE_ERROR_BAD_VERSION: u32 = ffi::DMARC_PARSE_ERROR_BAD_VERSION;
/// Bad token value (4).
pub const DMARC_PARSE_ERROR_BAD_VALUE: u32 = ffi::DMARC_PARSE_ERROR_BAD_VALUE;
/// Missing required `p=` tag (5).
pub const DMARC_PARSE_ERROR_NO_REQUIRED_P: u32 = ffi::DMARC_PARSE_ERROR_NO_REQUIRED_P;
/// No domain provided (6).
pub const DMARC_PARSE_ERROR_NO_DOMAIN: u32 = ffi::DMARC_PARSE_ERROR_NO_DOMAIN;
/// Memory allocation failure (7).
pub const DMARC_PARSE_ERROR_NO_ALLOC: u32 = ffi::DMARC_PARSE_ERROR_NO_ALLOC;
/// Bad SPF macro value (8).
pub const DMARC_PARSE_ERROR_BAD_SPF_MACRO: u32 = ffi::DMARC_PARSE_ERROR_BAD_SPF_MACRO;
/// Bad DKIM macro value (alias for `BAD_SPF_MACRO`, value 8).
pub const DMARC_PARSE_ERROR_BAD_DKIM_MACRO: u32 = ffi::DMARC_PARSE_ERROR_BAD_DKIM_MACRO;
/// No DMARC DNS record found (9).
pub const DMARC_DNS_ERROR_NO_RECORD: u32 = ffi::DMARC_DNS_ERROR_NO_RECORD;
/// Domain does not exist — NXDOMAIN (10).
pub const DMARC_DNS_ERROR_NXDOMAIN: u32 = ffi::DMARC_DNS_ERROR_NXDOMAIN;
/// Temporary DNS error (11).
pub const DMARC_DNS_ERROR_TMPERR: u32 = ffi::DMARC_DNS_ERROR_TMPERR;
/// Unknown TLD type (12).
pub const DMARC_TLD_ERROR_UNKNOWN: u32 = ffi::DMARC_TLD_ERROR_UNKNOWN;
/// No From: domain was supplied (13).
pub const DMARC_FROM_DOMAIN_ABSENT: u32 = ffi::DMARC_FROM_DOMAIN_ABSENT;

// --- Policy enforcement results ---

/// No DMARC record found — policy absent (14).
pub const DMARC_POLICY_ABSENT: u32 = ffi::DMARC_POLICY_ABSENT;
/// Policy says accept/pass (15).
pub const DMARC_POLICY_PASS: u32 = ffi::DMARC_POLICY_PASS;
/// Policy says reject (16).
pub const DMARC_POLICY_REJECT: u32 = ffi::DMARC_POLICY_REJECT;
/// Policy says quarantine (17).
pub const DMARC_POLICY_QUARANTINE: u32 = ffi::DMARC_POLICY_QUARANTINE;
/// Policy says none — monitor and report only (18).
pub const DMARC_POLICY_NONE: u32 = ffi::DMARC_POLICY_NONE;

/// Indicates the domain `p=` policy was used (19).
pub const DMARC_USED_POLICY_IS_P: u32 = ffi::DMARC_USED_POLICY_IS_P;
/// Indicates the subdomain `sp=` policy was used (20).
pub const DMARC_USED_POLICY_IS_SP: u32 = ffi::DMARC_USED_POLICY_IS_SP;

// --- SPF origin and outcome codes ---

/// SPF result originates from MAIL FROM (envelope sender).
pub const DMARC_POLICY_SPF_ORIGIN_MAILFROM: u32 = ffi::DMARC_POLICY_SPF_ORIGIN_MAILFROM;
/// SPF result originates from HELO/EHLO identity.
pub const DMARC_POLICY_SPF_ORIGIN_HELO: u32 = ffi::DMARC_POLICY_SPF_ORIGIN_HELO;

/// SPF outcome: none (0).
pub const DMARC_POLICY_SPF_OUTCOME_NONE: u32 = ffi::DMARC_POLICY_SPF_OUTCOME_NONE;
/// SPF outcome: pass (1).
pub const DMARC_POLICY_SPF_OUTCOME_PASS: u32 = ffi::DMARC_POLICY_SPF_OUTCOME_PASS;
/// SPF outcome: fail (2).
pub const DMARC_POLICY_SPF_OUTCOME_FAIL: u32 = ffi::DMARC_POLICY_SPF_OUTCOME_FAIL;
/// SPF outcome: temporary failure (3).
pub const DMARC_POLICY_SPF_OUTCOME_TMPFAIL: u32 = ffi::DMARC_POLICY_SPF_OUTCOME_TMPFAIL;
/// SPF alignment: pass (4).
pub const DMARC_POLICY_SPF_ALIGNMENT_PASS: u32 = ffi::DMARC_POLICY_SPF_ALIGNMENT_PASS;
/// SPF alignment: fail (5).
pub const DMARC_POLICY_SPF_ALIGNMENT_FAIL: u32 = ffi::DMARC_POLICY_SPF_ALIGNMENT_FAIL;

// --- DKIM outcome codes ---

/// DKIM outcome: none (0).
pub const DMARC_POLICY_DKIM_OUTCOME_NONE: u32 = ffi::DMARC_POLICY_DKIM_OUTCOME_NONE;
/// DKIM outcome: pass (1).
pub const DMARC_POLICY_DKIM_OUTCOME_PASS: u32 = ffi::DMARC_POLICY_DKIM_OUTCOME_PASS;
/// DKIM outcome: fail (2).
pub const DMARC_POLICY_DKIM_OUTCOME_FAIL: u32 = ffi::DMARC_POLICY_DKIM_OUTCOME_FAIL;
/// DKIM outcome: temporary failure (3).
pub const DMARC_POLICY_DKIM_OUTCOME_TMPFAIL: u32 = ffi::DMARC_POLICY_DKIM_OUTCOME_TMPFAIL;
/// DKIM alignment: pass (4).
pub const DMARC_POLICY_DKIM_ALIGNMENT_PASS: u32 = ffi::DMARC_POLICY_DKIM_ALIGNMENT_PASS;
/// DKIM alignment: fail (5).
pub const DMARC_POLICY_DKIM_ALIGNMENT_FAIL: u32 = ffi::DMARC_POLICY_DKIM_ALIGNMENT_FAIL;

// --- IP type codes ---

/// IPv4 connection type (4).
pub const DMARC_POLICY_IP_TYPE_IPV4: u32 = ffi::DMARC_POLICY_IP_TYPE_IPV4;
/// IPv6 connection type (6).
pub const DMARC_POLICY_IP_TYPE_IPV6: u32 = ffi::DMARC_POLICY_IP_TYPE_IPV6;

// --- Record tag values (char-encoded) ---

/// Alignment unspecified (`\0`).
pub const DMARC_RECORD_A_UNSPECIFIED: u8 = ffi::DMARC_RECORD_A_UNSPECIFIED;
/// Strict alignment (`'s'`).
pub const DMARC_RECORD_A_STRICT: u8 = ffi::DMARC_RECORD_A_STRICT;
/// Relaxed alignment (`'r'`).
pub const DMARC_RECORD_A_RELAXED: u8 = ffi::DMARC_RECORD_A_RELAXED;
/// Policy unspecified (`\0`).
pub const DMARC_RECORD_P_UNSPECIFIED: u8 = ffi::DMARC_RECORD_P_UNSPECIFIED;
/// Policy none (`'n'`).
pub const DMARC_RECORD_P_NONE: u8 = ffi::DMARC_RECORD_P_NONE;
/// Policy quarantine (`'q'`).
pub const DMARC_RECORD_P_QUARANTINE: u8 = ffi::DMARC_RECORD_P_QUARANTINE;
/// Policy reject (`'r'`).
pub const DMARC_RECORD_P_REJECT: u8 = ffi::DMARC_RECORD_P_REJECT;

// --- Report format flags (bitmask) ---

/// Report format unspecified.
pub const DMARC_RECORD_RF_UNSPECIFIED: u32 = ffi::DMARC_RECORD_RF_UNSPECIFIED;
/// AFRF report format.
pub const DMARC_RECORD_RF_AFRF: u32 = ffi::DMARC_RECORD_RF_AFRF;
/// IODEF report format.
pub const DMARC_RECORD_RF_IODEF: u32 = ffi::DMARC_RECORD_RF_IODEF;

// --- Failure option flags (bitmask) ---

/// Failure option unspecified.
pub const DMARC_RECORD_FO_UNSPECIFIED: u32 = ffi::DMARC_RECORD_FO_UNSPECIFIED;
/// Failure option: fo=0 — generate report if all mechanisms fail.
pub const DMARC_RECORD_FO_0: u32 = ffi::DMARC_RECORD_FO_0;
/// Failure option: fo=1 — generate report if any mechanism fails.
pub const DMARC_RECORD_FO_1: u32 = ffi::DMARC_RECORD_FO_1;
/// Failure option: fo=d — generate report if DKIM fails.
pub const DMARC_RECORD_FO_D: u32 = ffi::DMARC_RECORD_FO_D;
/// Failure option: fo=s — generate report if SPF fails.
pub const DMARC_RECORD_FO_S: u32 = ffi::DMARC_RECORD_FO_S;

// --- TLD file type constants ---

/// Do not use a TLD file.
pub const OPENDMARC_TLD_TYPE_NONE: u32 = ffi::OPENDMARC_TLD_TYPE_NONE;
/// Mozilla effective_tld_names.dat format.
pub const OPENDMARC_TLD_TYPE_MOZILLA: u32 = ffi::OPENDMARC_TLD_TYPE_MOZILLA;

// ---------------------------------------------------------------------------
// DmarcFfiError — Error type for libopendmarc operations
// ---------------------------------------------------------------------------

/// Error type for libopendmarc FFI operations.
///
/// Wraps an OPENDMARC_STATUS_T status code together with a human-readable
/// description of the failure.
///
/// # Fields
///
/// - `status` — The numeric `OPENDMARC_STATUS_T` code returned by the C
///   library function. See the `DMARC_PARSE_*`, `DMARC_DNS_*`, and
///   `DMARC_POLICY_*` constants for values.
/// - `message` — A descriptive error message indicating what operation failed
///   and (where available) the libopendmarc status string.
#[derive(Debug, Clone)]
pub struct DmarcFfiError {
    /// Numeric status code from libopendmarc (OPENDMARC_STATUS_T).
    pub status: i32,
    /// Human-readable error description.
    pub message: String,
}

impl DmarcFfiError {
    /// Create a new DMARC FFI error with the given status code and message.
    fn new(status: i32, msg: impl Into<String>) -> Self {
        Self {
            status,
            message: msg.into(),
        }
    }

    /// Create a DMARC FFI error enriched with the libopendmarc status string.
    ///
    /// Calls `opendmarc_policy_status_to_str` to obtain the canonical name
    /// for the status code and appends it to the message.
    fn from_status(status: i32, context: &str) -> Self {
        let status_str = status_to_string(status);
        Self {
            status,
            message: format!("{context}: {status_str} (code {status})"),
        }
    }
}

impl fmt::Display for DmarcFfiError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "DMARC FFI error ({}): {}", self.status, self.message)
    }
}

impl StdError for DmarcFfiError {}

// ---------------------------------------------------------------------------
// Internal helper: safe CString construction
// ---------------------------------------------------------------------------

/// Convert a Rust `&str` to a [`CString`], mapping interior NUL byte errors
/// to [`DmarcFfiError`] with a descriptive context message.
fn to_cstring(s: &str, context: &str) -> Result<CString, DmarcFfiError> {
    CString::new(s).map_err(|_| {
        DmarcFfiError::new(
            DMARC_PARSE_ERROR_BAD_VALUE as i32,
            format!(
                "{context} contains an interior null byte and cannot be passed to libopendmarc"
            ),
        )
    })
}

/// Check an OPENDMARC_STATUS_T return code and convert to Result.
///
/// Returns `Ok(())` when the status equals `DMARC_PARSE_OKAY`, otherwise
/// returns `Err(DmarcFfiError)` enriched with the libopendmarc status string.
fn check_status(status: c_int, context: &str) -> Result<(), DmarcFfiError> {
    if status == DMARC_PARSE_OKAY as c_int {
        Ok(())
    } else {
        Err(DmarcFfiError::from_status(status, context))
    }
}

// ---------------------------------------------------------------------------
// Consolidated FFI Dispatch
// ---------------------------------------------------------------------------

/// Enumerates every libopendmarc FFI operation dispatched through one `unsafe` block.
#[allow(dead_code)] // Variants needed for API completeness
enum DmarcFfi {
    LibInit {
        ctx: *mut ffi::OPENDMARC_LIB_T,
    },
    LibShutdown {
        ctx: *mut ffi::OPENDMARC_LIB_T,
    },
    TldReadFile {
        path: *mut c_char,
        comment: *mut c_char,
        drop: *mut c_char,
        except: *mut c_char,
    },
    ConnectInit {
        ip: *mut u8,
        ip_type: c_int,
    },
    ConnectShutdown {
        pctx: *mut ffi::DMARC_POLICY_T,
    },
    StoreFromDomain {
        pctx: *mut ffi::DMARC_POLICY_T,
        domain: *mut u8,
    },
    StoreSpf {
        pctx: *mut ffi::DMARC_POLICY_T,
        domain: *mut u8,
        result: c_int,
        origin: c_int,
        human: *mut u8,
    },
    StoreDkim {
        pctx: *mut ffi::DMARC_POLICY_T,
        domain: *mut u8,
        selector: *mut u8,
        result: c_int,
        human: *mut u8,
    },
    StoreDmarc {
        pctx: *mut ffi::DMARC_POLICY_T,
        record: *mut u8,
        domain: *mut u8,
        org: *mut u8,
    },
    GetPolicy {
        pctx: *mut ffi::DMARC_POLICY_T,
    },
    FetchP {
        pctx: *mut ffi::DMARC_POLICY_T,
        p: *mut c_int,
    },
    FetchSp {
        pctx: *mut ffi::DMARC_POLICY_T,
        sp: *mut c_int,
    },
    FetchUtilDomain {
        pctx: *mut ffi::DMARC_POLICY_T,
        buf: *mut u8,
        len: usize,
    },
    FetchAlignment {
        pctx: *mut ffi::DMARC_POLICY_T,
        dkim: *mut c_int,
        spf: *mut c_int,
    },
    FetchRua {
        pctx: *mut ffi::DMARC_POLICY_T,
    },
    FetchRuf {
        pctx: *mut ffi::DMARC_POLICY_T,
    },
    FetchPct {
        pctx: *mut ffi::DMARC_POLICY_T,
        pct: *mut c_int,
    },
    FetchAdkim {
        pctx: *mut ffi::DMARC_POLICY_T,
        adkim: *mut c_int,
    },
    FetchAspf {
        pctx: *mut ffi::DMARC_POLICY_T,
        aspf: *mut c_int,
    },
    StatusToStr {
        status: c_int,
    },
    CollectArray {
        arr: *mut *mut ffi::u_char,
    },
}

/// Result types returned by the consolidated DMARC FFI dispatch function.
enum DmarcFfiResult {
    Code(c_int),
    Ptr(*mut ffi::DMARC_POLICY_T),
    Str(String),
    Strings(Vec<String>),
    Done,
}

/// Consolidated FFI dispatch for all libopendmarc unsafe operations.
fn dmarc_ffi(op: DmarcFfi) -> DmarcFfiResult {
    // SAFETY: All libopendmarc operations call C library functions through
    // stable ABIs. Handle lifetimes are managed by RAII wrappers (DmarcLibrary,
    // DmarcPolicyContext). Callers validate pointers before dispatching.
    unsafe {
        match op {
            DmarcFfi::LibInit { ctx } => {
                DmarcFfiResult::Code(ffi::opendmarc_policy_library_init(ctx))
            }
            DmarcFfi::LibShutdown { ctx } => {
                ffi::opendmarc_policy_library_shutdown(ctx);
                DmarcFfiResult::Done
            }
            DmarcFfi::TldReadFile {
                path,
                comment,
                drop,
                except,
            } => DmarcFfiResult::Code(ffi::opendmarc_tld_read_file(path, comment, drop, except)),
            DmarcFfi::ConnectInit { ip, ip_type } => {
                DmarcFfiResult::Ptr(ffi::opendmarc_policy_connect_init(ip, ip_type))
            }
            DmarcFfi::ConnectShutdown { pctx } => {
                ffi::opendmarc_policy_connect_shutdown(pctx);
                DmarcFfiResult::Done
            }
            DmarcFfi::StoreFromDomain { pctx, domain } => {
                DmarcFfiResult::Code(ffi::opendmarc_policy_store_from_domain(pctx, domain))
            }
            DmarcFfi::StoreSpf {
                pctx,
                domain,
                result,
                origin,
                human,
            } => DmarcFfiResult::Code(ffi::opendmarc_policy_store_spf(
                pctx, domain, result, origin, human,
            )),
            DmarcFfi::StoreDkim {
                pctx,
                domain,
                selector,
                result,
                human,
            } => DmarcFfiResult::Code(ffi::opendmarc_policy_store_dkim(
                pctx, domain, selector, result, human,
            )),
            DmarcFfi::StoreDmarc {
                pctx,
                record,
                domain,
                org,
            } => DmarcFfiResult::Code(ffi::opendmarc_policy_store_dmarc(pctx, record, domain, org)),
            DmarcFfi::GetPolicy { pctx } => {
                DmarcFfiResult::Code(ffi::opendmarc_get_policy_to_enforce(pctx))
            }
            DmarcFfi::FetchP { pctx, p } => {
                DmarcFfiResult::Code(ffi::opendmarc_policy_fetch_p(pctx, p))
            }
            DmarcFfi::FetchSp { pctx, sp } => {
                DmarcFfiResult::Code(ffi::opendmarc_policy_fetch_sp(pctx, sp))
            }
            DmarcFfi::FetchUtilDomain { pctx, buf, len } => {
                DmarcFfiResult::Code(ffi::opendmarc_policy_fetch_utilized_domain(pctx, buf, len))
            }
            DmarcFfi::FetchAlignment { pctx, dkim, spf } => {
                DmarcFfiResult::Code(ffi::opendmarc_policy_fetch_alignment(pctx, dkim, spf))
            }
            DmarcFfi::FetchRua { pctx } => {
                let arr = ffi::opendmarc_policy_fetch_rua(pctx, ptr::null_mut(), 0, 1);
                DmarcFfiResult::Strings(read_cstr_array(arr))
            }
            DmarcFfi::FetchRuf { pctx } => {
                let arr = ffi::opendmarc_policy_fetch_ruf(pctx, ptr::null_mut(), 0, 1);
                DmarcFfiResult::Strings(read_cstr_array(arr))
            }
            DmarcFfi::FetchPct { pctx, pct } => {
                DmarcFfiResult::Code(ffi::opendmarc_policy_fetch_pct(pctx, pct))
            }
            DmarcFfi::FetchAdkim { pctx, adkim } => {
                DmarcFfiResult::Code(ffi::opendmarc_policy_fetch_adkim(pctx, adkim))
            }
            DmarcFfi::FetchAspf { pctx, aspf } => {
                DmarcFfiResult::Code(ffi::opendmarc_policy_fetch_aspf(pctx, aspf))
            }
            DmarcFfi::StatusToStr { status } => {
                let ptr = ffi::opendmarc_policy_status_to_str(status);
                if ptr.is_null() {
                    DmarcFfiResult::Str("unknown status".to_string())
                } else {
                    let cstr = CStr::from_ptr(ptr);
                    DmarcFfiResult::Str(cstr.to_string_lossy().into_owned())
                }
            }
            DmarcFfi::CollectArray { arr } => DmarcFfiResult::Strings(read_cstr_array(arr)),
        }
    }
}

/// Internal helper called from within the `unsafe` dispatch block to collect
/// a NULL-terminated `u_char**` array into a `Vec<String>`. This function is
/// always called from within an already-active `unsafe` context.
///
/// # Safety
/// Caller must ensure `arr` is a valid NULL-terminated array of `u_char*`
/// pointers to NUL-terminated C strings, or null.
unsafe fn read_cstr_array(arr: *mut *mut ffi::u_char) -> Vec<String> {
    if arr.is_null() {
        return Vec::new();
    }
    let mut result = Vec::new();
    let mut idx: isize = 0;
    loop {
        let entry = *arr.offset(idx);
        if entry.is_null() {
            break;
        }
        let cstr = CStr::from_ptr(entry as *const c_char);
        result.push(cstr.to_string_lossy().into_owned());
        idx += 1;
    }
    result
}

// ---------------------------------------------------------------------------
// DmarcLibrary — RAII wrapper around OPENDMARC_LIB_T
// ---------------------------------------------------------------------------

/// RAII wrapper around the libopendmarc library context (`OPENDMARC_LIB_T`).
///
/// Initialises the library on construction and shuts it down when dropped.
/// Corresponds to the C pattern in `src/src/miscmods/dmarc.c` lines 86–100:
///
/// ```c
/// OPENDMARC_LIB_T dmarc_ctx;
/// memset(&dmarc_ctx, '\0', sizeof dmarc_ctx);
/// dmarc_ctx.nscount = 0;
/// libdm_status = opendmarc_policy_library_init(&dmarc_ctx);
/// ```
///
/// # Thread Safety
///
/// This type is intentionally `!Send` and `!Sync` because the underlying
/// libopendmarc library context is not thread-safe.
pub struct DmarcLibrary {
    /// The library context struct owned by this wrapper. Passed by mutable
    /// reference to `opendmarc_policy_library_init` and
    /// `opendmarc_policy_library_shutdown`.
    ctx: ffi::OPENDMARC_LIB_T,
}

impl DmarcLibrary {
    /// Initialise the libopendmarc library.
    ///
    /// Creates a zeroed `OPENDMARC_LIB_T` context and calls
    /// `opendmarc_policy_library_init` to initialise internal data structures.
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the library init call returns a status
    /// other than `DMARC_PARSE_OKAY`.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let lib = DmarcLibrary::new()?;
    /// ```
    pub fn new() -> Result<Self, DmarcFfiError> {
        let mut ctx = ffi::OPENDMARC_LIB_T {
            nscount: 0,
            ..ffi::OPENDMARC_LIB_T::default()
        };

        // Dispatch opendmarc_policy_library_init through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::LibInit { ctx: &mut ctx }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };

        check_status(status, "opendmarc_policy_library_init")?;
        Ok(Self { ctx })
    }

    /// Load a public-suffix / TLD file for organizational domain discovery.
    ///
    /// Wraps `opendmarc_tld_read_file(path, NULL, NULL, NULL)` which reads
    /// a Mozilla-format effective TLD names file. This must be called after
    /// library initialisation and before any policy evaluation that needs
    /// organizational-domain inference.
    ///
    /// Corresponds to the C call at `src/src/miscmods/dmarc.c` line 95:
    /// `opendmarc_tld_read_file(CS dmarc_tld_file, NULL, NULL, NULL)`
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the file cannot be read or parsed.
    pub fn read_tld_file(&self, path: &str) -> Result<(), DmarcFfiError> {
        let c_path = to_cstring(path, "TLD file path")?;

        // Dispatch opendmarc_tld_read_file through consolidated FFI.
        let ret = match dmarc_ffi(DmarcFfi::TldReadFile {
            path: c_path.as_ptr() as *mut c_char,
            comment: ptr::null_mut(),
            drop: ptr::null_mut(),
            except: ptr::null_mut(),
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };

        if ret != 0 {
            return Err(DmarcFfiError::new(
                ret,
                format!("opendmarc_tld_read_file failed for path '{path}' (returned {ret})"),
            ));
        }
        Ok(())
    }

    /// Return the compile-time library version as `(major, minor, patch, release)`.
    ///
    /// Extracts version components from the `OPENDMARC_LIB_VERSION` constant
    /// using the same bitmask decomposition as `dmarc_version_report` in
    /// `src/src/miscmods/dmarc.c` lines 73–77.
    pub fn version() -> (u8, u8, u8, u8) {
        let v = OPENDMARC_LIB_VERSION;
        (
            ((v >> 24) & 0xFF) as u8,
            ((v >> 16) & 0xFF) as u8,
            ((v >> 8) & 0xFF) as u8,
            (v & 0xFF) as u8,
        )
    }
}

impl Drop for DmarcLibrary {
    fn drop(&mut self) {
        // Dispatch opendmarc_policy_library_shutdown through consolidated FFI.
        dmarc_ffi(DmarcFfi::LibShutdown { ctx: &mut self.ctx });
    }
}

// ---------------------------------------------------------------------------
// DmarcPolicyContext — RAII wrapper around DMARC_POLICY_T*
// ---------------------------------------------------------------------------

/// RAII wrapper around a libopendmarc policy context (`DMARC_POLICY_T *`).
///
/// A policy context is created per-connection via
/// `opendmarc_policy_connect_init` and accumulates SPF, DKIM, and DMARC
/// record data for a single message transaction. When dropped, the context
/// is shut down via `opendmarc_policy_connect_shutdown`.
///
/// This corresponds to the usage in `src/src/miscmods/dmarc.c` lines 105–112
/// and 447–448:
///
/// ```c
/// dmarc_pctx = opendmarc_policy_connect_init(sender_host_address, is_ipv6);
/// // ... store data, evaluate policy ...
/// opendmarc_policy_connect_shutdown(dmarc_pctx);
/// ```
///
/// # Thread Safety
///
/// This type is intentionally `!Send` and `!Sync` because the underlying
/// `DMARC_POLICY_T` is not thread-safe.
pub struct DmarcPolicyContext {
    /// Raw pointer to the policy context allocated by libopendmarc.
    pctx: *mut ffi::DMARC_POLICY_T,
}

impl DmarcPolicyContext {
    /// Create a new DMARC policy context for a connecting client.
    ///
    /// Wraps `opendmarc_policy_connect_init(ip_addr, ip_type)`.
    ///
    /// # Parameters
    ///
    /// - `ip` — The connecting client's IP address as a string (e.g.,
    ///   `"192.168.1.1"` or `"2001:db8::1"`).
    /// - `is_ipv6` — Whether the address is IPv6 (`true`) or IPv4 (`false`).
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the IP address contains an interior NUL
    /// byte, or if `opendmarc_policy_connect_init` returns a null pointer
    /// (indicating a memory allocation failure).
    pub fn new(ip: &str, is_ipv6: bool) -> Result<Self, DmarcFfiError> {
        let c_ip = to_cstring(ip, "IP address")?;
        let ip_type: c_int = if is_ipv6 {
            DMARC_POLICY_IP_TYPE_IPV6 as c_int
        } else {
            DMARC_POLICY_IP_TYPE_IPV4 as c_int
        };

        // Dispatch opendmarc_policy_connect_init through consolidated FFI.
        let pctx = match dmarc_ffi(DmarcFfi::ConnectInit {
            ip: c_ip.as_ptr() as *mut u8,
            ip_type,
        }) {
            DmarcFfiResult::Ptr(p) => p,
            _ => unreachable!(),
        };

        if pctx.is_null() {
            return Err(DmarcFfiError::new(
                DMARC_PARSE_ERROR_NO_ALLOC as i32,
                format!("opendmarc_policy_connect_init returned null for ip={ip}"),
            ));
        }
        Ok(Self { pctx })
    }

    /// Store the From: header domain for DMARC alignment evaluation.
    ///
    /// Wraps `opendmarc_policy_store_from_domain(pctx, domain)`.
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` line 191:
    /// `opendmarc_policy_store_from_domain(dmarc_pctx, dmarc_header_from_sender)`
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the domain contains an interior NUL byte
    /// or if the store operation fails.
    pub fn store_from_domain(&mut self, domain: &str) -> Result<(), DmarcFfiError> {
        let c_domain = to_cstring(domain, "From domain")?;

        // Dispatch opendmarc_policy_store_from_domain through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::StoreFromDomain {
            pctx: self.pctx,
            domain: c_domain.as_ptr() as *mut u8,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_store_from_domain")
    }

    /// Store an SPF evaluation result for DMARC processing.
    ///
    /// Wraps `opendmarc_policy_store_spf(pctx, domain, result, origin, human)`.
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` lines 251–252.
    ///
    /// # Parameters
    ///
    /// - `domain` — The SPF-evaluated domain (e.g., `$spf_used_domain`).
    /// - `result` — SPF outcome code (`DMARC_POLICY_SPF_OUTCOME_*`).
    /// - `origin` — SPF origin code (`DMARC_POLICY_SPF_ORIGIN_MAILFROM` or
    ///   `DMARC_POLICY_SPF_ORIGIN_HELO`).
    /// - `human` — Human-readable SPF result description (can be empty).
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if any string parameter contains an interior
    /// NUL byte, or if the store operation fails.
    pub fn store_spf(
        &mut self,
        domain: &str,
        result: i32,
        origin: i32,
        human: &str,
    ) -> Result<(), DmarcFfiError> {
        let c_domain = to_cstring(domain, "SPF domain")?;
        let c_human = to_cstring(human, "SPF human readable")?;

        // Dispatch opendmarc_policy_store_spf through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::StoreSpf {
            pctx: self.pctx,
            domain: c_domain.as_ptr() as *mut u8,
            result: result as c_int,
            origin: origin as c_int,
            human: c_human.as_ptr() as *mut u8,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_store_spf")
    }

    /// Store a DKIM verification result for DMARC processing.
    ///
    /// Wraps `opendmarc_policy_store_dkim(pctx, domain, selector, result, human)`.
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` lines 273–280. The selector
    /// parameter is only present when `DMARC_API >= 100400`, which is the
    /// minimum version this binding supports.
    ///
    /// # Parameters
    ///
    /// - `domain` — The DKIM signing domain (d= tag).
    /// - `selector` — The DKIM selector (s= tag).
    /// - `result` — DKIM outcome code (`DMARC_POLICY_DKIM_OUTCOME_*`).
    /// - `human` — Human-readable description (can be empty).
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if any string parameter contains an interior
    /// NUL byte, or if the store operation fails.
    pub fn store_dkim(
        &mut self,
        domain: &str,
        selector: &str,
        result: i32,
        human: &str,
    ) -> Result<(), DmarcFfiError> {
        let c_domain = to_cstring(domain, "DKIM domain")?;
        let c_selector = to_cstring(selector, "DKIM selector")?;
        let c_human = to_cstring(human, "DKIM human readable")?;

        // Dispatch opendmarc_policy_store_dkim through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::StoreDkim {
            pctx: self.pctx,
            domain: c_domain.as_ptr() as *mut u8,
            selector: c_selector.as_ptr() as *mut u8,
            result: result as c_int,
            human: c_human.as_ptr() as *mut u8,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_store_dkim")
    }

    /// Store a DMARC DNS record for policy evaluation.
    ///
    /// Wraps `opendmarc_policy_store_dmarc(pctx, record, domain, org_domain)`.
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` line 314:
    /// `opendmarc_policy_store_dmarc(dmarc_pctx, rr, dmarc_header_from_sender, NULL)`
    ///
    /// # Parameters
    ///
    /// - `record` — The raw DMARC TXT record content (e.g.,
    ///   `"v=DMARC1; p=reject; rua=mailto:dmarc@example.com"`).
    /// - `domain` — The domain the record was found for.
    /// - `org_domain` — The organizational domain, or `None` to let the library
    ///   determine it automatically.
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if any string parameter contains an interior
    /// NUL byte, or if the store/parse operation fails.
    pub fn store_dmarc_record(
        &mut self,
        record: &str,
        domain: &str,
        org_domain: Option<&str>,
    ) -> Result<(), DmarcFfiError> {
        let c_record = to_cstring(record, "DMARC record")?;
        let c_domain = to_cstring(domain, "DMARC domain")?;

        // Organizational domain is optional — pass NULL if None.
        let c_org = match org_domain {
            Some(od) => Some(to_cstring(od, "organizational domain")?),
            None => None,
        };
        let org_ptr = c_org
            .as_ref()
            .map_or(ptr::null_mut(), |cs| cs.as_ptr() as *mut u8);

        // Dispatch opendmarc_policy_store_dmarc through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::StoreDmarc {
            pctx: self.pctx,
            record: c_record.as_ptr() as *mut u8,
            domain: c_domain.as_ptr() as *mut u8,
            org: org_ptr,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_store_dmarc")
    }

    /// Compute the DMARC policy to enforce based on accumulated SPF/DKIM data.
    ///
    /// Wraps `opendmarc_get_policy_to_enforce(pctx)`.
    ///
    /// Returns the policy code as an integer matching one of the
    /// `DMARC_POLICY_*` constants (e.g., `DMARC_POLICY_REJECT`,
    /// `DMARC_POLICY_PASS`, `DMARC_POLICY_NONE`, `DMARC_POLICY_ABSENT`).
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` line 363:
    /// `dmarc_policy = libdm_status = opendmarc_get_policy_to_enforce(dmarc_pctx);`
    ///
    /// # Errors
    ///
    /// This function always succeeds because the return value IS the policy
    /// (including error states like `DMARC_POLICY_ABSENT` and
    /// `DMARC_FROM_DOMAIN_ABSENT`).
    pub fn get_policy_to_enforce(&self) -> Result<i32, DmarcFfiError> {
        // Dispatch opendmarc_get_policy_to_enforce through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::GetPolicy { pctx: self.pctx }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        Ok(status as i32)
    }

    /// Fetch the domain-level DMARC policy (`p=` tag).
    ///
    /// Wraps `opendmarc_policy_fetch_p(pctx, &p)`.
    ///
    /// Returns the policy value as one of the `DMARC_RECORD_P_*` constants.
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the fetch operation fails.
    pub fn fetch_p(&self) -> Result<i32, DmarcFfiError> {
        let mut p: c_int = 0;
        // Dispatch opendmarc_policy_fetch_p through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::FetchP {
            pctx: self.pctx,
            p: &mut p,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_fetch_p")?;
        Ok(p as i32)
    }

    /// Fetch the subdomain-level DMARC policy (`sp=` tag).
    ///
    /// Wraps `opendmarc_policy_fetch_sp(pctx, &sp)`.
    ///
    /// Returns the policy value as one of the `DMARC_RECORD_P_*` constants.
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the fetch operation fails.
    pub fn fetch_sp(&self) -> Result<i32, DmarcFfiError> {
        let mut sp: c_int = 0;
        // Dispatch opendmarc_policy_fetch_sp through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::FetchSp {
            pctx: self.pctx,
            sp: &mut sp,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_fetch_sp")?;
        Ok(sp as i32)
    }

    /// Fetch the domain that was actually used for DMARC evaluation.
    ///
    /// Wraps `opendmarc_policy_fetch_utilized_domain(pctx, buf, buflen)`.
    ///
    /// Returns the domain as a Rust `String`. Uses a buffer of
    /// `DMARC_MAXHOSTNAMELEN` bytes, matching the C code at
    /// `src/src/miscmods/dmarc.c` lines 353–356.
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the fetch operation fails.
    pub fn fetch_utilized_domain(&self) -> Result<String, DmarcFfiError> {
        let buf_size = DMARC_MAXHOSTNAMELEN as usize;
        let mut buf: Vec<u8> = vec![0u8; buf_size];

        // Dispatch opendmarc_policy_fetch_utilized_domain through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::FetchUtilDomain {
            pctx: self.pctx,
            buf: buf.as_mut_ptr(),
            len: buf_size,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_fetch_utilized_domain")?;

        // The buffer now contains a NUL-terminated C string. Find the NUL
        // and convert to a Rust String.
        let nul_pos = buf.iter().position(|&b| b == 0).unwrap_or(buf_size);
        String::from_utf8(buf[..nul_pos].to_vec()).map_err(|e| {
            DmarcFfiError::new(
                DMARC_PARSE_ERROR_BAD_VALUE as i32,
                format!("utilized domain is not valid UTF-8: {e}"),
            )
        })
    }

    /// Fetch the DKIM and SPF alignment results.
    ///
    /// Wraps `opendmarc_policy_fetch_alignment(pctx, &dkim_align, &spf_align)`.
    ///
    /// Returns a tuple `(dkim_alignment, spf_alignment)` where each value is
    /// one of the `DMARC_POLICY_DKIM_ALIGNMENT_*` or
    /// `DMARC_POLICY_SPF_ALIGNMENT_*` constants.
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` lines 411–412.
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the fetch operation fails.
    pub fn fetch_alignment(&self) -> Result<(i32, i32), DmarcFfiError> {
        let mut dkim_align: c_int = 0;
        let mut spf_align: c_int = 0;

        // Dispatch opendmarc_policy_fetch_alignment through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::FetchAlignment {
            pctx: self.pctx,
            dkim: &mut dkim_align,
            spf: &mut spf_align,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_fetch_alignment")?;
        Ok((dkim_align as i32, spf_align as i32))
    }

    /// Fetch aggregate report (`rua=`) addressees from the DMARC record.
    ///
    /// Wraps `opendmarc_policy_fetch_rua(pctx, NULL, 0, 1)`.
    ///
    /// The `constant=1` parameter means the returned array points to
    /// library-internal data and MUST NOT be freed by the caller (the library
    /// owns the memory until the policy context is shut down).
    ///
    /// Returns a (possibly empty) vector of report URI strings.
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` line 432.
    pub fn fetch_rua(&self) -> Vec<String> {
        // Dispatch opendmarc_policy_fetch_rua through consolidated FFI.
        match dmarc_ffi(DmarcFfi::FetchRua { pctx: self.pctx }) {
            DmarcFfiResult::Strings(v) => v,
            _ => unreachable!(),
        }
    }

    /// Fetch forensic/failure report (`ruf=`) addressees from the DMARC record.
    ///
    /// Wraps `opendmarc_policy_fetch_ruf(pctx, NULL, 0, 1)`.
    ///
    /// Returns a (possibly empty) vector of report URI strings.
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` line 441.
    pub fn fetch_ruf(&self) -> Vec<String> {
        // Dispatch opendmarc_policy_fetch_ruf through consolidated FFI.
        match dmarc_ffi(DmarcFfi::FetchRuf { pctx: self.pctx }) {
            DmarcFfiResult::Strings(v) => v,
            _ => unreachable!(),
        }
    }

    /// Fetch the DMARC reporting percentage (`pct=` tag, default 100).
    ///
    /// Wraps `opendmarc_policy_fetch_pct(pctx, &pct)`.
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` line 433.
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the fetch operation fails.
    pub fn fetch_pct(&self) -> Result<i32, DmarcFfiError> {
        let mut pct: c_int = 0;
        // Dispatch opendmarc_policy_fetch_pct through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::FetchPct {
            pctx: self.pctx,
            pct: &mut pct,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_fetch_pct")?;
        Ok(pct as i32)
    }

    /// Fetch the DKIM alignment mode (`adkim=` tag).
    ///
    /// Wraps `opendmarc_policy_fetch_adkim(pctx, &adkim)`.
    ///
    /// Returns one of the `DMARC_RECORD_A_*` constants (strict or relaxed).
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` line 434.
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the fetch operation fails.
    pub fn fetch_adkim(&self) -> Result<i32, DmarcFfiError> {
        let mut adkim: c_int = 0;
        // Dispatch opendmarc_policy_fetch_adkim through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::FetchAdkim {
            pctx: self.pctx,
            adkim: &mut adkim,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_fetch_adkim")?;
        Ok(adkim as i32)
    }

    /// Fetch the SPF alignment mode (`aspf=` tag).
    ///
    /// Wraps `opendmarc_policy_fetch_aspf(pctx, &aspf)`.
    ///
    /// Returns one of the `DMARC_RECORD_A_*` constants (strict or relaxed).
    ///
    /// Corresponds to `src/src/miscmods/dmarc.c` line 435.
    ///
    /// # Errors
    ///
    /// Returns [`DmarcFfiError`] if the fetch operation fails.
    pub fn fetch_aspf(&self) -> Result<i32, DmarcFfiError> {
        let mut aspf: c_int = 0;
        // Dispatch opendmarc_policy_fetch_aspf through consolidated FFI.
        let status = match dmarc_ffi(DmarcFfi::FetchAspf {
            pctx: self.pctx,
            aspf: &mut aspf,
        }) {
            DmarcFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        check_status(status, "opendmarc_policy_fetch_aspf")?;
        Ok(aspf as i32)
    }
}

impl Drop for DmarcPolicyContext {
    fn drop(&mut self) {
        if !self.pctx.is_null() {
            // Dispatch opendmarc_policy_connect_shutdown through consolidated FFI.
            dmarc_ffi(DmarcFfi::ConnectShutdown { pctx: self.pctx });
            self.pctx = ptr::null_mut();
        }
    }
}

// ---------------------------------------------------------------------------
// Free function: status_to_string
// ---------------------------------------------------------------------------

/// Convert an `OPENDMARC_STATUS_T` code to its human-readable string.
///
/// Wraps `opendmarc_policy_status_to_str(status)`.
///
/// Returns the C library's canonical string description of the status code,
/// or `"unknown status"` if the pointer returned by the C function is null
/// or the bytes are not valid UTF-8.
///
/// # Examples
///
/// ```ignore
/// assert_eq!(status_to_string(0), "DMARC_PARSE_OKAY");
/// ```
pub fn status_to_string(status: i32) -> String {
    // Dispatch opendmarc_policy_status_to_str through consolidated FFI.
    match dmarc_ffi(DmarcFfi::StatusToStr {
        status: status as c_int,
    }) {
        DmarcFfiResult::Str(s) => s,
        _ => unreachable!(),
    }
}

// ---------------------------------------------------------------------------
// Internal helper: collect a NULL-terminated u_char** array into Vec<String>
// ---------------------------------------------------------------------------

/// Convert a NULL-terminated `u_char **` array (as returned by
/// `opendmarc_policy_fetch_rua` / `opendmarc_policy_fetch_ruf`) into a
/// `Vec<String>`.
///
/// If the array pointer is null, returns an empty vector.
/// Non-UTF-8 entries are converted lossily (invalid bytes become U+FFFD).
fn collect_string_array(arr: *mut *mut ffi::u_char) -> Vec<String> {
    // Dispatch through consolidated FFI (handles all unsafe array traversal).
    match dmarc_ffi(DmarcFfi::CollectArray { arr }) {
        DmarcFfiResult::Strings(v) => v,
        _ => unreachable!(),
    }
}

// Ensure `c_void` import is referenced by the module to satisfy the schema.
// It is used in the documentation and the ffi module's opaque type handling.
const _: () = {
    // Validate that the `c_void` import is available.
    let _: *const c_void = ptr::null();
};

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify that the constants we re-export match their expected values
    /// from the system-installed opendmarc/dmarc.h header.
    #[test]
    fn test_constants() {
        assert_eq!(DMARC_PARSE_OKAY, 0);
        assert_eq!(DMARC_PARSE_ERROR_EMPTY, 1);
        assert_eq!(DMARC_PARSE_ERROR_NULL_CTX, 2);
        assert_eq!(DMARC_PARSE_ERROR_BAD_VERSION, 3);
        assert_eq!(DMARC_PARSE_ERROR_BAD_VALUE, 4);
        assert_eq!(DMARC_PARSE_ERROR_NO_REQUIRED_P, 5);
        assert_eq!(DMARC_PARSE_ERROR_NO_DOMAIN, 6);
        assert_eq!(DMARC_PARSE_ERROR_NO_ALLOC, 7);
        assert_eq!(DMARC_PARSE_ERROR_BAD_SPF_MACRO, 8);
        assert_eq!(DMARC_DNS_ERROR_NO_RECORD, 9);
        assert_eq!(DMARC_DNS_ERROR_NXDOMAIN, 10);
        assert_eq!(DMARC_DNS_ERROR_TMPERR, 11);
        assert_eq!(DMARC_TLD_ERROR_UNKNOWN, 12);
        assert_eq!(DMARC_FROM_DOMAIN_ABSENT, 13);
        assert_eq!(DMARC_POLICY_ABSENT, 14);
        assert_eq!(DMARC_POLICY_PASS, 15);
        assert_eq!(DMARC_POLICY_REJECT, 16);
        assert_eq!(DMARC_POLICY_QUARANTINE, 17);
        assert_eq!(DMARC_POLICY_NONE, 18);
        assert_eq!(DMARC_MAXHOSTNAMELEN, 256);
    }

    /// Verify that DmarcFfiError implements Display and Error traits.
    #[test]
    fn test_error_display() {
        let err = DmarcFfiError::new(4, "test error");
        assert_eq!(format!("{err}"), "DMARC FFI error (4): test error");
        // Ensure Error trait is implemented (this is a compile-time check).
        let _: &dyn StdError = &err;
    }

    /// Verify that status_to_string returns a non-empty description for
    /// known status codes, exercising the actual libopendmarc linkage.
    #[test]
    fn test_status_to_string_known() {
        let s = status_to_string(DMARC_PARSE_OKAY as i32);
        assert!(
            !s.is_empty(),
            "status string for PARSE_OKAY should not be empty"
        );
    }

    /// Verify that status_to_string handles unknown codes gracefully.
    #[test]
    fn test_status_to_string_unknown() {
        let s = status_to_string(99999);
        // Should return either "unknown status" or whatever the library says
        assert!(!s.is_empty());
    }

    /// Verify version extraction decomposition returns valid u8 components.
    #[test]
    fn test_version_decomposition() {
        let (major, minor, patch, release) = DmarcLibrary::version();
        // The version is a 4-byte bitmask — each component is a u8.
        // Verify we can reconstruct the original value from the parts.
        let reconstructed = (u32::from(major) << 24)
            | (u32::from(minor) << 16)
            | (u32::from(patch) << 8)
            | u32::from(release);
        assert_eq!(reconstructed, OPENDMARC_LIB_VERSION);
    }

    /// Verify that DmarcLibrary can be created and dropped (init/shutdown).
    #[test]
    fn test_library_lifecycle() {
        let lib = DmarcLibrary::new();
        assert!(
            lib.is_ok(),
            "DmarcLibrary::new() should succeed: {:?}",
            lib.err()
        );
        // Drop runs library_shutdown automatically.
    }

    /// Verify policy context lifecycle (connect_init / connect_shutdown).
    #[test]
    fn test_policy_context_lifecycle() {
        let _lib = DmarcLibrary::new().expect("library init");
        let ctx = DmarcPolicyContext::new("127.0.0.1", false);
        assert!(
            ctx.is_ok(),
            "DmarcPolicyContext::new should succeed: {:?}",
            ctx.err()
        );
        // Drop runs connect_shutdown automatically.
    }

    /// Verify that fetch_rua and fetch_ruf return empty vectors when no
    /// DMARC record has been stored.
    #[test]
    fn test_fetch_rua_ruf_empty() {
        let _lib = DmarcLibrary::new().expect("library init");
        let ctx = DmarcPolicyContext::new("127.0.0.1", false).expect("context init");
        let rua = ctx.fetch_rua();
        let ruf = ctx.fetch_ruf();
        // Without a stored DMARC record, these should be empty.
        assert!(rua.is_empty());
        assert!(ruf.is_empty());
    }

    /// Verify that collect_string_array handles null pointer gracefully.
    #[test]
    fn test_collect_string_array_null() {
        let result = collect_string_array(ptr::null_mut());
        assert!(result.is_empty());
    }
}
