//! Safe wrappers around the GNU SASL library (libgsasl).
//!
//! Provides managed GSASL context and session handles for SASL authentication,
//! supporting multiple mechanisms (PLAIN, LOGIN, CRAM-MD5, SCRAM-SHA-1/256, etc.)
//!
//! Handles version-dependent API differences between GSASL 1.x and 2.x via
//! build-time `cfg` attributes emitted by `build.rs` (see `detect_gsasl_version`).
//!
//! # Safety Policy
//!
//! All `unsafe` blocks in this module are documented with inline justification
//! comments. The raw C pointers (`*mut Gsasl`, `*mut Gsasl_session`) are wrapped
//! in RAII structs whose `Drop` implementations call the appropriate C cleanup
//! functions (`gsasl_done`, `gsasl_finish`).
//!
//! # Example
//!
//! ```no_run
//! use exim_ffi::gsasl::{GsaslContext, GsaslProperty, StepResult};
//!
//! let mut ctx = GsaslContext::new().expect("failed to init GSASL");
//! let mut session = ctx.server_start("PLAIN").expect("failed to start session");
//! session.property_set(GsaslProperty::Service, "smtp").unwrap();
//! ```

use std::ffi::{CStr, CString};
use std::fmt;
use std::ptr;

// ---------------------------------------------------------------------------
// Raw FFI bindings generated by bindgen (via build.rs → gsasl_bindings.rs).
// ---------------------------------------------------------------------------

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    // Justification: bindgen-generated FFI bindings must preserve the C naming
    // conventions from <gsasl.h>. Suppressing these lints is standard practice
    // for machine-generated code and does not hide any logic errors.
    clippy::upper_case_acronyms,
    clippy::unreadable_literal
)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/gsasl_bindings.rs"));
}

// ---------------------------------------------------------------------------
// Constants — GSASL return codes used for control flow.
// ---------------------------------------------------------------------------
// Note: bindgen renders the Gsasl_rc C enum as a set of
// `Gsasl_rc_GSASL_*` constants of type `c_uint`. We re-export the
// handful we need as `c_int` for comparison with the `c_int` returns
// from the GSASL API functions.

/// GSASL success return code (always 0).
const GSASL_RC_OK: libc::c_int = 0;

/// GSASL "needs more data" return code (always 1).
const GSASL_RC_NEEDS_MORE: libc::c_int = 1;

/// GSASL "no callback installed" return code (always 51).
const GSASL_RC_NO_CALLBACK: libc::c_int = 51;

/// GSASL "authentication error" return code (always 31).
const GSASL_RC_AUTHENTICATION_ERROR: libc::c_int = 31;

/// GSASL "unknown mechanism" return code (always 2).
const GSASL_RC_UNKNOWN_MECHANISM: libc::c_int = 2;

/// GSASL "malloc error" return code (always 7).
const GSASL_RC_MALLOC_ERROR: libc::c_int = 7;

// ---------------------------------------------------------------------------
// GsaslError — Typed error wrapping a GSASL numeric error code.
// ---------------------------------------------------------------------------

/// Error type representing a GSASL library error.
///
/// Wraps a numeric GSASL error code together with the human-readable error
/// message obtained from `gsasl_strerror()`.
#[derive(Debug, Clone)]
pub struct GsaslError {
    /// The raw GSASL error code (e.g. `GSASL_AUTHENTICATION_ERROR`).
    code: i32,
    /// Human-readable description from `gsasl_strerror`.
    message: String,
}

impl GsaslError {
    /// Create a `GsaslError` from a raw GSASL return code.
    ///
    /// Calls `gsasl_strerror` to obtain the human-readable error description.
    pub fn from_code(code: i32) -> Self {
        // SAFETY: `gsasl_strerror` is a pure lookup function that returns a
        // pointer to a statically-allocated NUL-terminated C string for any
        // integer argument. The returned pointer is valid for the lifetime of
        // the library and is never NULL for known codes. We immediately copy
        // the string into an owned Rust `String` via `CStr::from_ptr`.
        let message = unsafe {
            let c_msg = ffi::gsasl_strerror(code as libc::c_int);
            if c_msg.is_null() {
                format!("GSASL error {code}")
            } else {
                CStr::from_ptr(c_msg).to_string_lossy().into_owned()
            }
        };
        Self { code, message }
    }

    /// Return the raw GSASL numeric error code.
    pub fn code(&self) -> i32 {
        self.code
    }
}

impl fmt::Display for GsaslError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "GSASL error {}: {}", self.code, self.message)
    }
}

impl std::error::Error for GsaslError {}

// ---------------------------------------------------------------------------
// StepResult — Outcome of a single SASL exchange step.
// ---------------------------------------------------------------------------

/// Result of a single SASL authentication step.
///
/// A SASL exchange consists of one or more round-trips. Each call to
/// [`GsaslSession::step`] returns either `Continue` (more steps required) or
/// `Done` (authentication decision reached).
#[derive(Debug)]
pub enum StepResult {
    /// More steps are needed. The contained bytes should be sent to the peer.
    Continue(Vec<u8>),
    /// Authentication exchange is complete. The contained bytes are the final
    /// token to send to the peer (may be empty).
    Done(Vec<u8>),
}

// ---------------------------------------------------------------------------
// GsaslProperty — Authentication property identifiers.
// ---------------------------------------------------------------------------

/// GSASL property identifiers used to get/set authentication data on a
/// [`GsaslSession`].
///
/// Each variant maps directly to a `GSASL_*` constant from `<gsasl.h>`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum GsaslProperty {
    /// Authentication identity (username).
    AuthId = 1,
    /// Authorization identity.
    AuthzId = 2,
    /// Password.
    Password = 3,
    /// Anonymous identifier token.
    AnonymousToken = 4,
    /// Service name (e.g. "smtp").
    Service = 5,
    /// Host name.
    Hostname = 6,
    /// GSS-API credential principal name.
    GssapiDisplayName = 7,
    /// SecurID passcode.
    Passcode = 8,
    /// SecurID suggested PIN.
    SuggestedPin = 9,
    /// SecurID PIN.
    Pin = 10,
    /// User realm.
    Realm = 11,
    /// Pre-computed hashed DIGEST-MD5 password.
    DigestMd5HashedPassword = 12,
    /// Set of quality-of-protection values.
    Qops = 13,
    /// Quality-of-protection value.
    Qop = 14,
    /// Number of iterations in SCRAM password-to-key hashing.
    ScramIter = 15,
    /// Salt for SCRAM password-to-key hashing.
    ScramSalt = 16,
    /// Hex-encoded hashed/salted password for SCRAM.
    ScramSaltedPassword = 17,
    /// Base64-encoded tls-unique channel binding data.
    CbTlsUnique = 18,
    /// SAML 2.0 IdP identifier.
    Saml20IdpIdentifier = 19,
    /// SAML 2.0 redirect URL.
    Saml20RedirectUrl = 20,
    /// OpenID 2.0 redirect URL.
    Openid20RedirectUrl = 21,
    /// OpenID 2.0 outcome data.
    Openid20OutcomeData = 22,
    /// Hex-encoded SCRAM ServerKey.
    ScramServerKey = 23,
    /// Hex-encoded SCRAM StoredKey.
    ScramStoredKey = 24,
    /// Base64-encoded tls-exporter channel binding data (GSASL ≥ 2.1).
    CbTlsExporter = 25,
    /// SAML 2.0 authenticate in browser request.
    Saml20AuthenticateInBrowser = 250,
    /// OpenID 2.0 authenticate in browser request.
    Openid20AuthenticateInBrowser = 251,
    /// Request for simple validation (PLAIN, LOGIN, CRAM-MD5).
    ValidateSimple = 500,
    /// Request for validation of EXTERNAL mechanism.
    ValidateExternal = 501,
    /// Request for validation of ANONYMOUS mechanism.
    ValidateAnonymous = 502,
    /// Request for validation of GSSAPI/GS2 mechanism.
    ValidateGssapi = 503,
    /// Request for validation of SecurID mechanism.
    ValidateSecurid = 504,
    /// Request for validation of SAML 2.0.
    ValidateSaml20 = 505,
    /// Request for validation of OpenID 2.0.
    ValidateOpenid20 = 506,
}

impl GsaslProperty {
    /// Convert from a raw C `Gsasl_property` integer to the Rust enum.
    ///
    /// Returns `None` if the value does not correspond to a known property.
    pub fn from_raw(value: i32) -> Option<Self> {
        match value {
            1 => Some(Self::AuthId),
            2 => Some(Self::AuthzId),
            3 => Some(Self::Password),
            4 => Some(Self::AnonymousToken),
            5 => Some(Self::Service),
            6 => Some(Self::Hostname),
            7 => Some(Self::GssapiDisplayName),
            8 => Some(Self::Passcode),
            9 => Some(Self::SuggestedPin),
            10 => Some(Self::Pin),
            11 => Some(Self::Realm),
            12 => Some(Self::DigestMd5HashedPassword),
            13 => Some(Self::Qops),
            14 => Some(Self::Qop),
            15 => Some(Self::ScramIter),
            16 => Some(Self::ScramSalt),
            17 => Some(Self::ScramSaltedPassword),
            18 => Some(Self::CbTlsUnique),
            19 => Some(Self::Saml20IdpIdentifier),
            20 => Some(Self::Saml20RedirectUrl),
            21 => Some(Self::Openid20RedirectUrl),
            22 => Some(Self::Openid20OutcomeData),
            23 => Some(Self::ScramServerKey),
            24 => Some(Self::ScramStoredKey),
            25 => Some(Self::CbTlsExporter),
            250 => Some(Self::Saml20AuthenticateInBrowser),
            251 => Some(Self::Openid20AuthenticateInBrowser),
            500 => Some(Self::ValidateSimple),
            501 => Some(Self::ValidateExternal),
            502 => Some(Self::ValidateAnonymous),
            503 => Some(Self::ValidateGssapi),
            504 => Some(Self::ValidateSecurid),
            505 => Some(Self::ValidateSaml20),
            506 => Some(Self::ValidateOpenid20),
            _ => None,
        }
    }

    /// Convert the property to its raw C integer representation.
    fn to_raw(self) -> ffi::Gsasl_property {
        self as i32 as ffi::Gsasl_property
    }
}

// ---------------------------------------------------------------------------
// Callback infrastructure — extern "C" trampoline + boxed closure storage.
// ---------------------------------------------------------------------------

/// Type-erased callback stored inside [`GsaslContext`].
///
/// The closure receives a mutable reference to a temporary [`GsaslSession`]
/// wrapper (valid only for the duration of the callback) and the property
/// being requested.
type BoxedCallback =
    Box<dyn Fn(&mut GsaslSession, GsaslProperty) -> Result<(), GsaslError> + 'static>;

/// extern "C" trampoline that bridges the C callback interface to the Rust
/// closure stored in the GSASL context's callback hook.
///
/// # Safety
///
/// This function is called by libgsasl whenever a property is requested. The
/// `ctx` pointer is the same one passed to `gsasl_callback_set`, and the hook
/// value was set by `GsaslContext::set_callback` as a `*mut BoxedCallback`.
/// The `sctx` pointer is a valid session pointer managed by libgsasl.
extern "C" fn callback_trampoline(
    ctx: *mut ffi::Gsasl,
    sctx: *mut ffi::Gsasl_session,
    prop: ffi::Gsasl_property,
) -> libc::c_int {
    if ctx.is_null() || sctx.is_null() {
        return GSASL_RC_NO_CALLBACK;
    }

    // SAFETY: We perform two related FFI operations in a single unsafe block:
    // 1. `gsasl_callback_hook_get` retrieves the opaque `void *` pointer that
    //    was stored by `GsaslContext::set_callback` via `gsasl_callback_hook_set`.
    //    This is a `*mut BoxedCallback` that remains valid for the lifetime of
    //    the `GsaslContext` (which owns the `Box`).
    // 2. We dereference the pointer to obtain a shared reference to the callback
    //    closure. This is sound because the `GsaslContext` ensures the Box stays
    //    alive and the closure is only invoked from this trampoline (no aliasing
    //    writes occur).
    let callback_ref: &BoxedCallback = unsafe {
        let hook_ptr = ffi::gsasl_callback_hook_get(ctx);
        if hook_ptr.is_null() {
            return GSASL_RC_NO_CALLBACK;
        }
        &*(hook_ptr as *const BoxedCallback)
    };

    let rust_prop = match GsaslProperty::from_raw(prop as i32) {
        Some(p) => p,
        None => return GSASL_RC_NO_CALLBACK,
    };

    let mut session_wrapper = GsaslSession {
        session: sctx,
        owned: false,
    };

    match callback_ref(&mut session_wrapper, rust_prop) {
        Ok(()) => GSASL_RC_OK,
        Err(e) => e.code() as libc::c_int,
    }
}

// ---------------------------------------------------------------------------
// GsaslSession — Safe wrapper around a GSASL session handle.
// ---------------------------------------------------------------------------

/// Safe wrapper around a `Gsasl_session` pointer.
///
/// Represents a single SASL authentication exchange (one mechanism, one
/// direction: server or client). The session is either *owned* (created by
/// [`GsaslContext::server_start`] / [`GsaslContext::client_start`], and freed
/// on drop) or *borrowed* (used transiently inside a callback, not freed).
pub struct GsaslSession {
    /// Raw pointer to the libgsasl session.
    session: *mut ffi::Gsasl_session,
    /// Whether this wrapper owns the session (and should call `gsasl_finish`
    /// on drop).
    owned: bool,
}

// GsaslSession is not thread-safe (libgsasl sessions are per-thread).
// Explicitly mark as !Send + !Sync is the default because of the raw pointer.

impl GsaslSession {
    /// Perform one step of the SASL exchange.
    ///
    /// `input` is the data received from the peer (may be empty for the initial
    /// client step). Returns a [`StepResult`] indicating whether more steps are
    /// needed or the exchange is complete.
    pub fn step(&mut self, input: &[u8]) -> Result<StepResult, GsaslError> {
        let input_ptr = if input.is_empty() {
            ptr::null()
        } else {
            input.as_ptr().cast::<libc::c_char>()
        };
        let input_len = input.len() as libc::size_t;

        let mut output: *mut libc::c_char = ptr::null_mut();
        let mut output_len: libc::size_t = 0;

        // SAFETY: `gsasl_step` is the core SASL exchange function. We pass:
        //   - a valid session pointer (non-null, managed by this struct)
        //   - an input buffer with its length (or null + 0 for empty input)
        //   - out-pointers for the response buffer and its length
        // On success (GSASL_OK or GSASL_NEEDS_MORE), `output` is allocated by
        // libgsasl and must be freed with `gsasl_free`. We copy the output
        // into an owned `Vec<u8>` and then free the C buffer, all within this
        // single unsafe block to ensure the buffer lifetime is handled
        // correctly.
        let (rc, out_bytes) = unsafe {
            let rc = ffi::gsasl_step(
                self.session,
                input_ptr,
                input_len,
                &mut output,
                &mut output_len,
            );

            let bytes = if !output.is_null() && output_len > 0 {
                std::slice::from_raw_parts(output.cast::<u8>(), output_len).to_vec()
            } else {
                Vec::new()
            };

            if !output.is_null() {
                ffi::gsasl_free(output.cast::<libc::c_void>());
            }

            (rc, bytes)
        };

        if rc != GSASL_RC_OK && rc != GSASL_RC_NEEDS_MORE {
            return Err(GsaslError::from_code(rc));
        }

        if rc == GSASL_RC_NEEDS_MORE {
            Ok(StepResult::Continue(out_bytes))
        } else {
            Ok(StepResult::Done(out_bytes))
        }
    }

    /// Set a SASL property value on this session.
    ///
    /// The value string is copied by libgsasl; the caller retains ownership of
    /// `value`.
    pub fn property_set(&mut self, prop: GsaslProperty, value: &str) -> Result<(), GsaslError> {
        let c_value = CString::new(value).map_err(|_| GsaslError {
            code: GSASL_RC_AUTHENTICATION_ERROR,
            message: "property value contains interior NUL byte".to_string(),
        })?;

        // SAFETY: `gsasl_property_set` copies the value string into internal
        // storage associated with the session. The `self.session` pointer is
        // valid (non-null, managed by this struct). The `c_value` pointer is a
        // valid NUL-terminated C string that outlives this call.
        let rc = unsafe { ffi::gsasl_property_set(self.session, prop.to_raw(), c_value.as_ptr()) };

        if rc != GSASL_RC_OK {
            Err(GsaslError::from_code(rc))
        } else {
            Ok(())
        }
    }

    /// Get a SASL property value from this session.
    ///
    /// Returns `None` if the property has not been set or is unavailable.
    /// The returned string is a copy of the internal value — modifications do
    /// not affect the session state.
    pub fn property_get(&self, prop: GsaslProperty) -> Option<String> {
        // SAFETY: `gsasl_property_get` returns a pointer to an internal string
        // owned by the session, or NULL if the property is not set. This
        // variant may trigger a callback to populate the property. The returned
        // pointer is valid until the next call that modifies this property or
        // until the session is finished. We immediately copy the data into an
        // owned `String` via `CStr::from_ptr` before any further GSASL calls
        // can invalidate the pointer.
        unsafe {
            let ptr = ffi::gsasl_property_get(self.session, prop.to_raw());
            if ptr.is_null() {
                None
            } else {
                Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
            }
        }
    }
}

impl Drop for GsaslSession {
    fn drop(&mut self) {
        if self.owned && !self.session.is_null() {
            // SAFETY: `gsasl_finish` releases all resources associated with the
            // session. This is called exactly once per owned session because
            // `Drop` is called exactly once, and we set `owned = true` only for
            // sessions created by `server_start` / `client_start`.
            unsafe { ffi::gsasl_finish(self.session) };
        }
    }
}

// ---------------------------------------------------------------------------
// GsaslContext — Safe wrapper around the global GSASL library context.
// ---------------------------------------------------------------------------

/// Safe wrapper around the global GSASL library context.
///
/// Manages the lifecycle of a `Gsasl *` context. Only one context should
/// typically exist per process (matching the C Exim usage pattern).
///
/// When dropped, calls `gsasl_done` to release all library resources. If a
/// callback was registered via [`set_callback`](Self::set_callback), the
/// associated closure is also freed at drop time.
pub struct GsaslContext {
    /// Raw pointer to the libgsasl context.
    ctx: *mut ffi::Gsasl,
    /// Heap-allocated callback closure (if set). Stored here so it is freed
    /// when the context is dropped and remains valid for the entire context
    /// lifetime.
    _callback: Option<*mut BoxedCallback>,
}

impl GsaslContext {
    /// Initialize a new GSASL library context.
    ///
    /// Calls `gsasl_init` to allocate and configure the context. Returns an
    /// error if the library cannot be initialized (e.g. out of memory or
    /// library not found).
    pub fn new() -> Result<Self, GsaslError> {
        let mut ctx: *mut ffi::Gsasl = ptr::null_mut();

        // SAFETY: `gsasl_init` allocates a new library context and writes the
        // pointer to `ctx`. It returns GSASL_OK (0) on success or a non-zero
        // error code on failure. The out-pointer `ctx` is only valid when the
        // return code is 0.
        let rc = unsafe { ffi::gsasl_init(&mut ctx) };

        if rc != GSASL_RC_OK {
            return Err(GsaslError::from_code(rc));
        }

        if ctx.is_null() {
            return Err(GsaslError {
                code: GSASL_RC_MALLOC_ERROR,
                message: "gsasl_init returned OK but context is null".to_string(),
            });
        }

        Ok(Self {
            ctx,
            _callback: None,
        })
    }

    /// Check whether the installed GSASL library version satisfies `required`.
    ///
    /// `required` is a version string such as `"2.0.0"`. Returns `Some(version)`
    /// with the actual library version if the requirement is met, or `None` if
    /// the installed version is too old.
    pub fn check_version(required: &str) -> Option<String> {
        let c_req = CString::new(required).ok()?;

        // SAFETY: `gsasl_check_version` compares the required version against
        // the installed library version. It returns a pointer to a static
        // NUL-terminated string with the library version if the requirement is
        // satisfied, or NULL if not. We immediately copy the result into an
        // owned `String` via `CStr::from_ptr`.
        unsafe {
            let result = ffi::gsasl_check_version(c_req.as_ptr());
            if result.is_null() {
                None
            } else {
                Some(CStr::from_ptr(result).to_string_lossy().into_owned())
            }
        }
    }

    /// Register a property callback on this context.
    ///
    /// The callback is invoked by libgsasl whenever a property is needed during
    /// a SASL exchange (e.g. password, realm). The closure receives a mutable
    /// reference to the active [`GsaslSession`] and the requested
    /// [`GsaslProperty`].
    ///
    /// Only one callback can be active at a time; calling this again replaces
    /// the previous callback.
    pub fn set_callback<F>(&mut self, callback: F) -> Result<(), GsaslError>
    where
        F: Fn(&mut GsaslSession, GsaslProperty) -> Result<(), GsaslError> + 'static,
    {
        let boxed: BoxedCallback = Box::new(callback);
        let raw_ptr = Box::into_raw(Box::new(boxed));

        // SAFETY: Three related operations that manage the callback lifecycle:
        // 1. If a previous callback exists, `self._callback` holds a `*mut
        //    BoxedCallback` created by `Box::into_raw` in an earlier call. We
        //    reclaim ownership via `Box::from_raw` and drop it.
        // 2. `gsasl_callback_hook_set` stores the new `*mut BoxedCallback` as
        //    an opaque `void *` in the GSASL context, to be retrieved later by
        //    `callback_trampoline` via `gsasl_callback_hook_get`.
        // 3. `gsasl_callback_set` registers the extern "C" trampoline function
        //    as the library-level callback.
        // All pointers remain valid until this `GsaslContext` is dropped (at
        // which point `_callback` is freed in `Drop`).
        unsafe {
            if let Some(old_ptr) = self._callback.take() {
                let _ = Box::from_raw(old_ptr);
            }
            ffi::gsasl_callback_hook_set(self.ctx, raw_ptr.cast::<std::ffi::c_void>());
            ffi::gsasl_callback_set(self.ctx, Some(callback_trampoline));
        }

        self._callback = Some(raw_ptr);
        Ok(())
    }

    /// Start a new SASL server session for the given mechanism name.
    ///
    /// The `mechanism` string is a standard SASL mechanism identifier such as
    /// `"PLAIN"`, `"SCRAM-SHA-256"`, etc.
    pub fn server_start(&self, mechanism: &str) -> Result<GsaslSession, GsaslError> {
        self.start_session_inner(mechanism, true)
    }

    /// Start a new SASL client session for the given mechanism name.
    ///
    /// The `mechanism` string is a standard SASL mechanism identifier such as
    /// `"PLAIN"`, `"SCRAM-SHA-256"`, etc.
    pub fn client_start(&self, mechanism: &str) -> Result<GsaslSession, GsaslError> {
        self.start_session_inner(mechanism, false)
    }

    /// Shared implementation for [`server_start`](Self::server_start) and
    /// [`client_start`](Self::client_start).
    fn start_session_inner(
        &self,
        mechanism: &str,
        is_server: bool,
    ) -> Result<GsaslSession, GsaslError> {
        let c_mech = CString::new(mechanism).map_err(|_| GsaslError {
            code: GSASL_RC_UNKNOWN_MECHANISM,
            message: "mechanism name contains interior NUL byte".to_string(),
        })?;

        let mut sctx: *mut ffi::Gsasl_session = ptr::null_mut();

        // SAFETY: Both `gsasl_server_start` and `gsasl_client_start` create a
        // new SASL session for the specified mechanism. The `self.ctx` pointer
        // is valid (created in `new`, not yet freed). The mechanism name is a
        // valid NUL-terminated C string. On success (rc == 0), `sctx` receives
        // a pointer to the newly allocated session.
        let rc = unsafe {
            if is_server {
                ffi::gsasl_server_start(self.ctx, c_mech.as_ptr(), &mut sctx)
            } else {
                ffi::gsasl_client_start(self.ctx, c_mech.as_ptr(), &mut sctx)
            }
        };

        if rc != GSASL_RC_OK {
            return Err(GsaslError::from_code(rc));
        }

        if sctx.is_null() {
            return Err(GsaslError {
                code: GSASL_RC_MALLOC_ERROR,
                message: "session start returned OK but session is null".to_string(),
            });
        }

        Ok(GsaslSession {
            session: sctx,
            owned: true,
        })
    }
}

impl Drop for GsaslContext {
    fn drop(&mut self) {
        // SAFETY: Two cleanup operations performed in a single unsafe block:
        // 1. If a callback was registered, `_callback` holds a `*mut
        //    BoxedCallback` created by `Box::into_raw`. We reclaim ownership
        //    via `Box::from_raw` and let it drop, freeing the closure.
        // 2. `gsasl_done` releases all resources held by the library context,
        //    including any remaining sessions. Called exactly once because
        //    `Drop` runs exactly once.
        // The callback must be freed before `gsasl_done` in case the library
        // invokes cleanup callbacks during teardown.
        unsafe {
            if let Some(cb_ptr) = self._callback.take() {
                let _ = Box::from_raw(cb_ptr);
            }
            if !self.ctx.is_null() {
                ffi::gsasl_done(self.ctx);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// GsaslCapabilities — Build-time version capability detection.
// ---------------------------------------------------------------------------

/// GSASL version capability flags detected at build time.
///
/// The `build.rs` script reads `gsasl-version.h` and emits `cargo:rustc-cfg`
/// attributes that mirror the C preprocessor feature gating in
/// `src/src/auths/gsasl.c` lines 43–71.
///
/// These methods return `true` only if the corresponding version-dependent
/// feature was detected during compilation.
pub struct GsaslCapabilities;

impl GsaslCapabilities {
    /// Whether SCRAM-SHA-256 is supported (GSASL ≥ 1.9 or 2.x).
    ///
    /// Corresponds to `EXIM_GSASL_HAVE_SCRAM_SHA_256` in the C source.
    pub fn has_scram_sha256() -> bool {
        cfg!(gsasl_have_scram_sha_256)
    }

    /// Whether SCRAM server-key (S-Key) support is available.
    ///
    /// Corresponds to `EXIM_GSASL_SCRAM_S_KEY` in the C source.
    pub fn has_scram_s_key() -> bool {
        cfg!(gsasl_scram_s_key)
    }

    /// Whether TLS-exporter channel binding is supported (GSASL ≥ 2.1 or
    /// patched 2.0).
    ///
    /// Corresponds to `EXIM_GSASL_HAVE_EXPORTER` in the C source.
    pub fn has_exporter() -> bool {
        cfg!(gsasl_have_exporter)
    }
}

// ---------------------------------------------------------------------------
// Unit tests (gated behind cfg(test), never compiled in production builds).
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify that `GsaslError::from_code` produces a non-empty message for
    /// a known error code.
    #[test]
    fn test_error_from_code() {
        let err = GsaslError::from_code(0);
        assert_eq!(err.code(), 0);
        assert!(!err.message.is_empty(), "error message should not be empty");
    }

    /// Verify Display impl produces sensible output.
    #[test]
    fn test_error_display() {
        let err = GsaslError::from_code(31); // GSASL_AUTHENTICATION_ERROR
        let msg = format!("{err}");
        assert!(msg.contains("31"), "display should include error code");
    }

    /// Verify that `GsaslProperty::from_raw` round-trips correctly for all
    /// known variants.
    #[test]
    fn test_property_round_trip() {
        let props = [
            GsaslProperty::AuthId,
            GsaslProperty::AuthzId,
            GsaslProperty::Password,
            GsaslProperty::AnonymousToken,
            GsaslProperty::Service,
            GsaslProperty::Hostname,
            GsaslProperty::GssapiDisplayName,
            GsaslProperty::Passcode,
            GsaslProperty::SuggestedPin,
            GsaslProperty::Pin,
            GsaslProperty::Realm,
            GsaslProperty::DigestMd5HashedPassword,
            GsaslProperty::Qops,
            GsaslProperty::Qop,
            GsaslProperty::ScramIter,
            GsaslProperty::ScramSalt,
            GsaslProperty::ScramSaltedPassword,
            GsaslProperty::CbTlsUnique,
            GsaslProperty::ScramServerKey,
            GsaslProperty::ScramStoredKey,
            GsaslProperty::CbTlsExporter,
            GsaslProperty::ValidateSimple,
            GsaslProperty::ValidateExternal,
            GsaslProperty::ValidateAnonymous,
            GsaslProperty::ValidateGssapi,
        ];

        for prop in props {
            let raw = prop as i32;
            let recovered = GsaslProperty::from_raw(raw)
                .unwrap_or_else(|| panic!("from_raw failed for {prop:?} (raw={raw})"));
            assert_eq!(prop, recovered);
        }
    }

    /// Verify that unknown property values return None.
    #[test]
    fn test_property_unknown() {
        assert!(GsaslProperty::from_raw(9999).is_none());
        assert!(GsaslProperty::from_raw(-1).is_none());
    }

    /// Verify that GsaslCapabilities functions compile and return bool.
    #[test]
    fn test_capabilities_compile() {
        // These are compile-time cfg checks; we just verify they don't panic.
        let _ = GsaslCapabilities::has_scram_sha256();
        let _ = GsaslCapabilities::has_scram_s_key();
        let _ = GsaslCapabilities::has_exporter();
    }

    /// Test context creation and version check.
    #[test]
    fn test_context_lifecycle() {
        let ctx = GsaslContext::new();
        assert!(ctx.is_ok(), "GsaslContext::new() should succeed");
        // Context drops cleanly at end of scope.
    }

    /// Test version checking.
    #[test]
    fn test_check_version() {
        // The library is at least 1.0.0
        let version = GsaslContext::check_version("1.0.0");
        assert!(version.is_some(), "version check for 1.0.0 should succeed");

        // An impossibly high version should fail.
        let version = GsaslContext::check_version("99.99.99");
        assert!(version.is_none(), "version check for 99.99.99 should fail");
    }

    /// Test server session start with a supported mechanism.
    #[test]
    fn test_server_start_plain() {
        let ctx = GsaslContext::new().expect("init");
        let session = ctx.server_start("PLAIN");
        assert!(session.is_ok(), "server_start(PLAIN) should succeed");
    }

    /// Test client session start with a supported mechanism.
    #[test]
    fn test_client_start_plain() {
        let ctx = GsaslContext::new().expect("init");
        let session = ctx.client_start("PLAIN");
        assert!(session.is_ok(), "client_start(PLAIN) should succeed");
    }

    /// Test server_start with an unsupported mechanism.
    #[test]
    fn test_server_start_unknown() {
        let ctx = GsaslContext::new().expect("init");
        let session = ctx.server_start("NONEXISTENT-MECHANISM-XYZ");
        assert!(session.is_err(), "unknown mechanism should fail");
    }

    /// Test property set and get on a session.
    #[test]
    fn test_property_set_get() {
        let ctx = GsaslContext::new().expect("init");
        let mut session = ctx.server_start("PLAIN").expect("session");

        session
            .property_set(GsaslProperty::Service, "smtp")
            .expect("set service");

        let value = session.property_get(GsaslProperty::Service);
        assert_eq!(value.as_deref(), Some("smtp"));
    }

    /// Test setting a callback and verify it doesn't crash.
    #[test]
    fn test_set_callback() {
        let mut ctx = GsaslContext::new().expect("init");
        let result = ctx.set_callback(|_session, _prop| Ok(()));
        assert!(result.is_ok(), "set_callback should succeed");
    }

    /// Test that replacing a callback works without leaking.
    #[test]
    fn test_replace_callback() {
        let mut ctx = GsaslContext::new().expect("init");
        ctx.set_callback(|_session, _prop| Ok(()))
            .expect("first callback");
        ctx.set_callback(|_session, _prop| Err(GsaslError::from_code(GSASL_RC_NO_CALLBACK)))
            .expect("second callback");
    }
}
