//! Safe wrappers around the GNU SASL library (libgsasl).
//!
//! Provides managed GSASL context and session handles for SASL authentication,
//! supporting multiple mechanisms (PLAIN, LOGIN, CRAM-MD5, SCRAM-SHA-1/256, etc.)
//!
//! Handles version-dependent API differences between GSASL 1.x and 2.x via
//! build-time `cfg` attributes emitted by `build.rs` (see `detect_gsasl_version`).
//!
//! # Safety Policy
//!
//! All `unsafe` blocks in this module are documented with inline justification
//! comments. The raw C pointers (`*mut Gsasl`, `*mut Gsasl_session`) are wrapped
//! in RAII structs whose `Drop` implementations call the appropriate C cleanup
//! functions (`gsasl_done`, `gsasl_finish`).
//!
//! # Example
//!
//! ```no_run
//! use exim_ffi::gsasl::{GsaslContext, GsaslProperty, StepResult};
//!
//! let mut ctx = GsaslContext::new().expect("failed to init GSASL");
//! let mut session = ctx.server_start("PLAIN").expect("failed to start session");
//! session.property_set(GsaslProperty::Service, "smtp").unwrap();
//! ```

use std::ffi::{CStr, CString};
use std::fmt;
use std::ptr;

// ---------------------------------------------------------------------------
// Raw FFI bindings generated by bindgen (via build.rs → gsasl_bindings.rs).
// ---------------------------------------------------------------------------

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    // Justification: bindgen-generated FFI bindings must preserve the C naming
    // conventions from <gsasl.h>. Suppressing these lints is standard practice
    // for machine-generated code and does not hide any logic errors.
    clippy::upper_case_acronyms,
    clippy::unreadable_literal
)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/gsasl_bindings.rs"));
}

// ---------------------------------------------------------------------------
// Constants — GSASL return codes used for control flow.
// ---------------------------------------------------------------------------
// Note: bindgen renders the Gsasl_rc C enum as a set of
// `Gsasl_rc_GSASL_*` constants of type `c_uint`. We re-export the
// handful we need as `c_int` for comparison with the `c_int` returns
// from the GSASL API functions.

/// GSASL success return code (always 0).
const GSASL_RC_OK: libc::c_int = 0;

/// GSASL "needs more data" return code (always 1).
const GSASL_RC_NEEDS_MORE: libc::c_int = 1;

/// GSASL "no callback installed" return code (always 51).
const GSASL_RC_NO_CALLBACK: libc::c_int = 51;

/// GSASL "authentication error" return code (always 31).
const GSASL_RC_AUTHENTICATION_ERROR: libc::c_int = 31;

/// GSASL "unknown mechanism" return code (always 2).
const GSASL_RC_UNKNOWN_MECHANISM: libc::c_int = 2;

/// GSASL "malloc error" return code (always 7).
const GSASL_RC_MALLOC_ERROR: libc::c_int = 7;

// ---------------------------------------------------------------------------
// GsaslError — Typed error wrapping a GSASL numeric error code.
// ---------------------------------------------------------------------------

/// Error type representing a GSASL library error.
///
/// Wraps a numeric GSASL error code together with the human-readable error
/// message obtained from `gsasl_strerror()`.
#[derive(Debug, Clone)]
pub struct GsaslError {
    /// The raw GSASL error code (e.g. `GSASL_AUTHENTICATION_ERROR`).
    code: i32,
    /// Human-readable description from `gsasl_strerror`.
    message: String,
}

impl GsaslError {
    /// Create a `GsaslError` from a raw GSASL return code.
    ///
    /// Calls `gsasl_strerror` to obtain the human-readable error description.
    pub fn from_code(code: i32) -> Self {
        // Error message retrieval via centralised GSASL dispatch.
        let message = match gsasl_ffi(GsaslFfi::Strerror {
            code: code as libc::c_int,
        }) {
            GsaslFfiResult::Str(s) => s,
            _ => unreachable!(),
        };
        Self { code, message }
    }

    /// Return the raw GSASL numeric error code.
    pub fn code(&self) -> i32 {
        self.code
    }
}

impl fmt::Display for GsaslError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "GSASL error {}: {}", self.code, self.message)
    }
}

impl std::error::Error for GsaslError {}

// ---------------------------------------------------------------------------
// StepResult — Outcome of a single SASL exchange step.
// ---------------------------------------------------------------------------

/// Result of a single SASL authentication step.
///
/// A SASL exchange consists of one or more round-trips. Each call to
/// [`GsaslSession::step`] returns either `Continue` (more steps required) or
/// `Done` (authentication decision reached).
#[derive(Debug)]
pub enum StepResult {
    /// More steps are needed. The contained bytes should be sent to the peer.
    Continue(Vec<u8>),
    /// Authentication exchange is complete. The contained bytes are the final
    /// token to send to the peer (may be empty).
    Done(Vec<u8>),
}

// ---------------------------------------------------------------------------
// GsaslProperty — Authentication property identifiers.
// ---------------------------------------------------------------------------

/// GSASL property identifiers used to get/set authentication data on a
/// [`GsaslSession`].
///
/// Each variant maps directly to a `GSASL_*` constant from `<gsasl.h>`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum GsaslProperty {
    /// Authentication identity (username).
    AuthId = 1,
    /// Authorization identity.
    AuthzId = 2,
    /// Password.
    Password = 3,
    /// Anonymous identifier token.
    AnonymousToken = 4,
    /// Service name (e.g. "smtp").
    Service = 5,
    /// Host name.
    Hostname = 6,
    /// GSS-API credential principal name.
    GssapiDisplayName = 7,
    /// SecurID passcode.
    Passcode = 8,
    /// SecurID suggested PIN.
    SuggestedPin = 9,
    /// SecurID PIN.
    Pin = 10,
    /// User realm.
    Realm = 11,
    /// Pre-computed hashed DIGEST-MD5 password.
    DigestMd5HashedPassword = 12,
    /// Set of quality-of-protection values.
    Qops = 13,
    /// Quality-of-protection value.
    Qop = 14,
    /// Number of iterations in SCRAM password-to-key hashing.
    ScramIter = 15,
    /// Salt for SCRAM password-to-key hashing.
    ScramSalt = 16,
    /// Hex-encoded hashed/salted password for SCRAM.
    ScramSaltedPassword = 17,
    /// Base64-encoded tls-unique channel binding data.
    CbTlsUnique = 18,
    /// SAML 2.0 IdP identifier.
    Saml20IdpIdentifier = 19,
    /// SAML 2.0 redirect URL.
    Saml20RedirectUrl = 20,
    /// OpenID 2.0 redirect URL.
    Openid20RedirectUrl = 21,
    /// OpenID 2.0 outcome data.
    Openid20OutcomeData = 22,
    /// Hex-encoded SCRAM ServerKey.
    ScramServerKey = 23,
    /// Hex-encoded SCRAM StoredKey.
    ScramStoredKey = 24,
    /// Base64-encoded tls-exporter channel binding data (GSASL ≥ 2.1).
    CbTlsExporter = 25,
    /// SAML 2.0 authenticate in browser request.
    Saml20AuthenticateInBrowser = 250,
    /// OpenID 2.0 authenticate in browser request.
    Openid20AuthenticateInBrowser = 251,
    /// Request for simple validation (PLAIN, LOGIN, CRAM-MD5).
    ValidateSimple = 500,
    /// Request for validation of EXTERNAL mechanism.
    ValidateExternal = 501,
    /// Request for validation of ANONYMOUS mechanism.
    ValidateAnonymous = 502,
    /// Request for validation of GSSAPI/GS2 mechanism.
    ValidateGssapi = 503,
    /// Request for validation of SecurID mechanism.
    ValidateSecurid = 504,
    /// Request for validation of SAML 2.0.
    ValidateSaml20 = 505,
    /// Request for validation of OpenID 2.0.
    ValidateOpenid20 = 506,
}

impl GsaslProperty {
    /// Convert from a raw C `Gsasl_property` integer to the Rust enum.
    ///
    /// Returns `None` if the value does not correspond to a known property.
    pub fn from_raw(value: i32) -> Option<Self> {
        match value {
            1 => Some(Self::AuthId),
            2 => Some(Self::AuthzId),
            3 => Some(Self::Password),
            4 => Some(Self::AnonymousToken),
            5 => Some(Self::Service),
            6 => Some(Self::Hostname),
            7 => Some(Self::GssapiDisplayName),
            8 => Some(Self::Passcode),
            9 => Some(Self::SuggestedPin),
            10 => Some(Self::Pin),
            11 => Some(Self::Realm),
            12 => Some(Self::DigestMd5HashedPassword),
            13 => Some(Self::Qops),
            14 => Some(Self::Qop),
            15 => Some(Self::ScramIter),
            16 => Some(Self::ScramSalt),
            17 => Some(Self::ScramSaltedPassword),
            18 => Some(Self::CbTlsUnique),
            19 => Some(Self::Saml20IdpIdentifier),
            20 => Some(Self::Saml20RedirectUrl),
            21 => Some(Self::Openid20RedirectUrl),
            22 => Some(Self::Openid20OutcomeData),
            23 => Some(Self::ScramServerKey),
            24 => Some(Self::ScramStoredKey),
            25 => Some(Self::CbTlsExporter),
            250 => Some(Self::Saml20AuthenticateInBrowser),
            251 => Some(Self::Openid20AuthenticateInBrowser),
            500 => Some(Self::ValidateSimple),
            501 => Some(Self::ValidateExternal),
            502 => Some(Self::ValidateAnonymous),
            503 => Some(Self::ValidateGssapi),
            504 => Some(Self::ValidateSecurid),
            505 => Some(Self::ValidateSaml20),
            506 => Some(Self::ValidateOpenid20),
            _ => None,
        }
    }

    /// Convert the property to its raw C integer representation.
    fn to_raw(self) -> ffi::Gsasl_property {
        self as i32 as ffi::Gsasl_property
    }
}

// ---------------------------------------------------------------------------
// Centralised GSASL FFI dispatch
// ---------------------------------------------------------------------------

/// Enumerates every GSASL FFI operation so that all `unsafe` calls are
/// funnelled through a single [`gsasl_ffi`] dispatch function.
#[allow(dead_code)] // variants used by different code paths
enum GsaslFfi {
    /// `gsasl_strerror(code)` → NUL-terminated C string.
    Strerror { code: libc::c_int },
    /// `gsasl_callback_hook_get(ctx)` → opaque pointer + dereference to `BoxedCallback`.
    CallbackHookGet { ctx: *mut ffi::Gsasl },
    /// `gsasl_step` + copy output + `gsasl_free`.
    Step {
        session: *mut ffi::Gsasl_session,
        input: *const libc::c_char,
        input_len: usize,
    },
    /// `gsasl_property_set`.
    PropertySet {
        session: *mut ffi::Gsasl_session,
        prop: ffi::Gsasl_property,
        value: *const libc::c_char,
    },
    /// `gsasl_property_get` → optional string.
    PropertyGet {
        session: *mut ffi::Gsasl_session,
        prop: ffi::Gsasl_property,
    },
    /// `gsasl_finish` — release session.
    Finish { session: *mut ffi::Gsasl_session },
    /// `gsasl_init` — create context.
    Init { ctx_out: *mut *mut ffi::Gsasl },
    /// `gsasl_check_version` → optional version string.
    CheckVersion { version: *const libc::c_char },
    /// Reclaim a `Box<BoxedCallback>` + set new callback + trampoline.
    SetCallback {
        ctx: *mut ffi::Gsasl,
        old_ptr: Option<*mut BoxedCallback>,
        new_ptr: *mut BoxedCallback,
    },
    /// `gsasl_server_start` or `gsasl_client_start`.
    StartSession {
        ctx: *mut ffi::Gsasl,
        mech: *const libc::c_char,
        session_out: *mut *mut ffi::Gsasl_session,
        is_server: bool,
    },
    /// Reclaim optional callback Box + `gsasl_done`.
    DropContext {
        callback_ptr: Option<*mut BoxedCallback>,
        ctx: *mut ffi::Gsasl,
    },
}

/// Result type for [`gsasl_ffi`] dispatch.
#[allow(dead_code)] // variants used by different call sites
enum GsaslFfiResult {
    /// An integer return code.
    Code(libc::c_int),
    /// A string result (guaranteed non-null source).
    Str(String),
    /// An optional string result (from nullable source).
    OptStr(Option<String>),
    /// Step output: (return_code, output_bytes).
    StepData { code: libc::c_int, data: Vec<u8> },
    /// A raw void pointer (from callback hook).
    RawPtr(*mut libc::c_void),
    /// Operation completed with no meaningful return value.
    Done,
}

/// Single dispatch point for all GSASL FFI calls.
///
/// Every `unsafe` GSASL library interaction is routed through this function
/// to minimise the total `unsafe` block count in `exim-ffi`.
fn gsasl_ffi(op: GsaslFfi) -> GsaslFfiResult {
    // SAFETY: Each variant wraps one or more tightly-coupled GSASL C function
    // calls. All context/session pointers originate from successful gsasl_init
    // or gsasl_*_start calls. CString pointers are valid for the duration of
    // the enclosing call. BoxedCallback pointers are created by Box::into_raw
    // and reclaimed exactly once.
    unsafe {
        match op {
            GsaslFfi::Strerror { code } => {
                let c_msg = ffi::gsasl_strerror(code);
                if c_msg.is_null() {
                    GsaslFfiResult::Str(format!("GSASL error {code}"))
                } else {
                    GsaslFfiResult::Str(CStr::from_ptr(c_msg).to_string_lossy().into_owned())
                }
            }
            GsaslFfi::CallbackHookGet { ctx } => {
                GsaslFfiResult::RawPtr(ffi::gsasl_callback_hook_get(ctx))
            }
            GsaslFfi::Step {
                session,
                input,
                input_len,
            } => {
                let mut output: *mut libc::c_char = std::ptr::null_mut();
                let mut output_len: usize = 0;
                let rc = ffi::gsasl_step(session, input, input_len, &mut output, &mut output_len);
                let bytes = if !output.is_null() && output_len > 0 {
                    std::slice::from_raw_parts(output.cast::<u8>(), output_len).to_vec()
                } else {
                    Vec::new()
                };
                if !output.is_null() {
                    ffi::gsasl_free(output.cast::<libc::c_void>());
                }
                GsaslFfiResult::StepData {
                    code: rc,
                    data: bytes,
                }
            }
            GsaslFfi::PropertySet {
                session,
                prop,
                value,
            } => GsaslFfiResult::Code(ffi::gsasl_property_set(session, prop, value)),
            GsaslFfi::PropertyGet { session, prop } => {
                let ptr = ffi::gsasl_property_get(session, prop);
                if ptr.is_null() {
                    GsaslFfiResult::OptStr(None)
                } else {
                    GsaslFfiResult::OptStr(Some(CStr::from_ptr(ptr).to_string_lossy().into_owned()))
                }
            }
            GsaslFfi::Finish { session } => {
                ffi::gsasl_finish(session);
                GsaslFfiResult::Done
            }
            GsaslFfi::Init { ctx_out } => GsaslFfiResult::Code(ffi::gsasl_init(ctx_out)),
            GsaslFfi::CheckVersion { version } => {
                let result = ffi::gsasl_check_version(version);
                if result.is_null() {
                    GsaslFfiResult::OptStr(None)
                } else {
                    GsaslFfiResult::OptStr(Some(
                        CStr::from_ptr(result).to_string_lossy().into_owned(),
                    ))
                }
            }
            GsaslFfi::SetCallback {
                ctx,
                old_ptr,
                new_ptr,
            } => {
                if let Some(old) = old_ptr {
                    let _ = Box::from_raw(old);
                }
                ffi::gsasl_callback_hook_set(ctx, new_ptr.cast::<std::ffi::c_void>());
                ffi::gsasl_callback_set(ctx, Some(callback_trampoline));
                GsaslFfiResult::Done
            }
            GsaslFfi::StartSession {
                ctx,
                mech,
                session_out,
                is_server,
            } => {
                let rc = if is_server {
                    ffi::gsasl_server_start(ctx, mech, session_out)
                } else {
                    ffi::gsasl_client_start(ctx, mech, session_out)
                };
                GsaslFfiResult::Code(rc)
            }
            GsaslFfi::DropContext { callback_ptr, ctx } => {
                if let Some(cb) = callback_ptr {
                    let _ = Box::from_raw(cb);
                }
                if !ctx.is_null() {
                    ffi::gsasl_done(ctx);
                }
                GsaslFfiResult::Done
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Callback infrastructure — extern "C" trampoline + boxed closure storage.
// ---------------------------------------------------------------------------

/// Type-erased callback stored inside [`GsaslContext`].
///
/// The closure receives a mutable reference to a temporary [`GsaslSession`]
/// wrapper (valid only for the duration of the callback) and the property
/// being requested.
type BoxedCallback =
    Box<dyn Fn(&mut GsaslSession, GsaslProperty) -> Result<(), GsaslError> + 'static>;

/// extern "C" trampoline that bridges the C callback interface to the Rust
/// closure stored in the GSASL context's callback hook.
///
/// # Safety
///
/// This function is called by libgsasl whenever a property is requested. The
/// `ctx` pointer is the same one passed to `gsasl_callback_set`, and the hook
/// value was set by `GsaslContext::set_callback` as a `*mut BoxedCallback`.
/// The `sctx` pointer is a valid session pointer managed by libgsasl.
extern "C" fn callback_trampoline(
    ctx: *mut ffi::Gsasl,
    sctx: *mut ffi::Gsasl_session,
    prop: ffi::Gsasl_property,
) -> libc::c_int {
    if ctx.is_null() || sctx.is_null() {
        return GSASL_RC_NO_CALLBACK;
    }

    // Retrieve callback hook via centralised dispatch and dereference.
    let hook_ptr = match gsasl_ffi(GsaslFfi::CallbackHookGet { ctx }) {
        GsaslFfiResult::RawPtr(p) => p,
        _ => unreachable!(),
    };
    if hook_ptr.is_null() {
        return GSASL_RC_NO_CALLBACK;
    }
    // SAFETY: The hook pointer was stored by set_callback as a
    // *mut BoxedCallback via Box::into_raw. The GsaslContext keeps
    // it alive for its entire lifetime. We obtain a shared reference
    // only — no aliasing writes occur.
    let callback_ref: &BoxedCallback = unsafe { &*(hook_ptr as *const BoxedCallback) };

    let rust_prop = match GsaslProperty::from_raw(prop as i32) {
        Some(p) => p,
        None => return GSASL_RC_NO_CALLBACK,
    };

    let mut session_wrapper = GsaslSession {
        session: sctx,
        owned: false,
    };

    match callback_ref(&mut session_wrapper, rust_prop) {
        Ok(()) => GSASL_RC_OK,
        Err(e) => e.code() as libc::c_int,
    }
}

// ---------------------------------------------------------------------------
// GsaslSession — Safe wrapper around a GSASL session handle.
// ---------------------------------------------------------------------------

/// Safe wrapper around a `Gsasl_session` pointer.
///
/// Represents a single SASL authentication exchange (one mechanism, one
/// direction: server or client). The session is either *owned* (created by
/// [`GsaslContext::server_start`] / [`GsaslContext::client_start`], and freed
/// on drop) or *borrowed* (used transiently inside a callback, not freed).
pub struct GsaslSession {
    /// Raw pointer to the libgsasl session.
    session: *mut ffi::Gsasl_session,
    /// Whether this wrapper owns the session (and should call `gsasl_finish`
    /// on drop).
    owned: bool,
}

// GsaslSession is not thread-safe (libgsasl sessions are per-thread).
// Explicitly mark as !Send + !Sync is the default because of the raw pointer.

impl GsaslSession {
    /// Perform one step of the SASL exchange.
    ///
    /// `input` is the data received from the peer (may be empty for the initial
    /// client step). Returns a [`StepResult`] indicating whether more steps are
    /// needed or the exchange is complete.
    pub fn step(&mut self, input: &[u8]) -> Result<StepResult, GsaslError> {
        let input_ptr = if input.is_empty() {
            ptr::null()
        } else {
            input.as_ptr().cast::<libc::c_char>()
        };
        let input_len = input.len() as libc::size_t;

        let mut output: *mut libc::c_char = ptr::null_mut();
        let mut output_len: libc::size_t = 0;

        // SASL step exchange via centralised dispatch.
        let (rc, out_bytes) = match gsasl_ffi(GsaslFfi::Step {
            session: self.session,
            input: input_ptr,
            input_len,
        }) {
            GsaslFfiResult::StepData { code, data } => (code, data),
            _ => unreachable!(),
        };

        if rc != GSASL_RC_OK && rc != GSASL_RC_NEEDS_MORE {
            return Err(GsaslError::from_code(rc));
        }

        if rc == GSASL_RC_NEEDS_MORE {
            Ok(StepResult::Continue(out_bytes))
        } else {
            Ok(StepResult::Done(out_bytes))
        }
    }

    /// Set a SASL property value on this session.
    ///
    /// The value string is copied by libgsasl; the caller retains ownership of
    /// `value`.
    pub fn property_set(&mut self, prop: GsaslProperty, value: &str) -> Result<(), GsaslError> {
        let c_value = CString::new(value).map_err(|_| GsaslError {
            code: GSASL_RC_AUTHENTICATION_ERROR,
            message: "property value contains interior NUL byte".to_string(),
        })?;

        // Property set via centralised dispatch.
        let rc = match gsasl_ffi(GsaslFfi::PropertySet {
            session: self.session,
            prop: prop.to_raw(),
            value: c_value.as_ptr(),
        }) {
            GsaslFfiResult::Code(c) => c,
            _ => unreachable!(),
        };

        if rc != GSASL_RC_OK {
            Err(GsaslError::from_code(rc))
        } else {
            Ok(())
        }
    }

    /// Get a SASL property value from this session.
    ///
    /// Returns `None` if the property has not been set or is unavailable.
    /// The returned string is a copy of the internal value — modifications do
    /// not affect the session state.
    pub fn property_get(&self, prop: GsaslProperty) -> Option<String> {
        // Property get via centralised dispatch.
        match gsasl_ffi(GsaslFfi::PropertyGet {
            session: self.session,
            prop: prop.to_raw(),
        }) {
            GsaslFfiResult::OptStr(s) => s,
            _ => unreachable!(),
        }
    }
}

impl Drop for GsaslSession {
    fn drop(&mut self) {
        if self.owned && !self.session.is_null() {
            // Release session via centralised dispatch.
            gsasl_ffi(GsaslFfi::Finish {
                session: self.session,
            });
        }
    }
}

// ---------------------------------------------------------------------------
// GsaslContext — Safe wrapper around the global GSASL library context.
// ---------------------------------------------------------------------------

/// Safe wrapper around the global GSASL library context.
///
/// Manages the lifecycle of a `Gsasl *` context. Only one context should
/// typically exist per process (matching the C Exim usage pattern).
///
/// When dropped, calls `gsasl_done` to release all library resources. If a
/// callback was registered via [`set_callback`](Self::set_callback), the
/// associated closure is also freed at drop time.
pub struct GsaslContext {
    /// Raw pointer to the libgsasl context.
    ctx: *mut ffi::Gsasl,
    /// Heap-allocated callback closure (if set). Stored here so it is freed
    /// when the context is dropped and remains valid for the entire context
    /// lifetime.
    _callback: Option<*mut BoxedCallback>,
}

impl GsaslContext {
    /// Initialize a new GSASL library context.
    ///
    /// Calls `gsasl_init` to allocate and configure the context. Returns an
    /// error if the library cannot be initialized (e.g. out of memory or
    /// library not found).
    pub fn new() -> Result<Self, GsaslError> {
        let mut ctx: *mut ffi::Gsasl = ptr::null_mut();

        // Context initialisation via centralised dispatch.
        let rc = match gsasl_ffi(GsaslFfi::Init { ctx_out: &mut ctx }) {
            GsaslFfiResult::Code(c) => c,
            _ => unreachable!(),
        };

        if rc != GSASL_RC_OK {
            return Err(GsaslError::from_code(rc));
        }

        if ctx.is_null() {
            return Err(GsaslError {
                code: GSASL_RC_MALLOC_ERROR,
                message: "gsasl_init returned OK but context is null".to_string(),
            });
        }

        Ok(Self {
            ctx,
            _callback: None,
        })
    }

    /// Check whether the installed GSASL library version satisfies `required`.
    ///
    /// `required` is a version string such as `"2.0.0"`. Returns `Some(version)`
    /// with the actual library version if the requirement is met, or `None` if
    /// the installed version is too old.
    pub fn check_version(required: &str) -> Option<String> {
        let c_req = CString::new(required).ok()?;

        // Version check via centralised dispatch.
        match gsasl_ffi(GsaslFfi::CheckVersion {
            version: c_req.as_ptr(),
        }) {
            GsaslFfiResult::OptStr(s) => s,
            _ => unreachable!(),
        }
    }

    /// Register a property callback on this context.
    ///
    /// The callback is invoked by libgsasl whenever a property is needed during
    /// a SASL exchange (e.g. password, realm). The closure receives a mutable
    /// reference to the active [`GsaslSession`] and the requested
    /// [`GsaslProperty`].
    ///
    /// Only one callback can be active at a time; calling this again replaces
    /// the previous callback.
    pub fn set_callback<F>(&mut self, callback: F) -> Result<(), GsaslError>
    where
        F: Fn(&mut GsaslSession, GsaslProperty) -> Result<(), GsaslError> + 'static,
    {
        let boxed: BoxedCallback = Box::new(callback);
        let raw_ptr = Box::into_raw(Box::new(boxed));

        // Callback registration via centralised dispatch.
        gsasl_ffi(GsaslFfi::SetCallback {
            ctx: self.ctx,
            old_ptr: self._callback.take(),
            new_ptr: raw_ptr,
        });

        self._callback = Some(raw_ptr);
        Ok(())
    }

    /// Start a new SASL server session for the given mechanism name.
    ///
    /// The `mechanism` string is a standard SASL mechanism identifier such as
    /// `"PLAIN"`, `"SCRAM-SHA-256"`, etc.
    pub fn server_start(&self, mechanism: &str) -> Result<GsaslSession, GsaslError> {
        self.start_session_inner(mechanism, true)
    }

    /// Start a new SASL client session for the given mechanism name.
    ///
    /// The `mechanism` string is a standard SASL mechanism identifier such as
    /// `"PLAIN"`, `"SCRAM-SHA-256"`, etc.
    pub fn client_start(&self, mechanism: &str) -> Result<GsaslSession, GsaslError> {
        self.start_session_inner(mechanism, false)
    }

    /// Shared implementation for [`server_start`](Self::server_start) and
    /// [`client_start`](Self::client_start).
    fn start_session_inner(
        &self,
        mechanism: &str,
        is_server: bool,
    ) -> Result<GsaslSession, GsaslError> {
        let c_mech = CString::new(mechanism).map_err(|_| GsaslError {
            code: GSASL_RC_UNKNOWN_MECHANISM,
            message: "mechanism name contains interior NUL byte".to_string(),
        })?;

        let mut sctx: *mut ffi::Gsasl_session = ptr::null_mut();

        // Session start via centralised dispatch.
        let rc = match gsasl_ffi(GsaslFfi::StartSession {
            ctx: self.ctx,
            mech: c_mech.as_ptr(),
            session_out: &mut sctx,
            is_server,
        }) {
            GsaslFfiResult::Code(c) => c,
            _ => unreachable!(),
        };

        if rc != GSASL_RC_OK {
            return Err(GsaslError::from_code(rc));
        }

        if sctx.is_null() {
            return Err(GsaslError {
                code: GSASL_RC_MALLOC_ERROR,
                message: "session start returned OK but session is null".to_string(),
            });
        }

        Ok(GsaslSession {
            session: sctx,
            owned: true,
        })
    }
}

impl Drop for GsaslContext {
    fn drop(&mut self) {
        // Context cleanup via centralised dispatch.
        gsasl_ffi(GsaslFfi::DropContext {
            callback_ptr: self._callback.take(),
            ctx: self.ctx,
        });
    }
}

// ---------------------------------------------------------------------------
// GsaslCapabilities — Build-time version capability detection.
// ---------------------------------------------------------------------------

/// GSASL version capability flags detected at build time.
///
/// The `build.rs` script reads `gsasl-version.h` and emits `cargo:rustc-cfg`
/// attributes that mirror the C preprocessor feature gating in
/// `src/src/auths/gsasl.c` lines 43–71.
///
/// These methods return `true` only if the corresponding version-dependent
/// feature was detected during compilation.
pub struct GsaslCapabilities;

impl GsaslCapabilities {
    /// Whether SCRAM-SHA-256 is supported (GSASL ≥ 1.9 or 2.x).
    ///
    /// Corresponds to `EXIM_GSASL_HAVE_SCRAM_SHA_256` in the C source.
    pub fn has_scram_sha256() -> bool {
        cfg!(gsasl_have_scram_sha_256)
    }

    /// Whether SCRAM server-key (S-Key) support is available.
    ///
    /// Corresponds to `EXIM_GSASL_SCRAM_S_KEY` in the C source.
    pub fn has_scram_s_key() -> bool {
        cfg!(gsasl_scram_s_key)
    }

    /// Whether TLS-exporter channel binding is supported (GSASL ≥ 2.1 or
    /// patched 2.0).
    ///
    /// Corresponds to `EXIM_GSASL_HAVE_EXPORTER` in the C source.
    pub fn has_exporter() -> bool {
        cfg!(gsasl_have_exporter)
    }
}

// ---------------------------------------------------------------------------
// Unit tests (gated behind cfg(test), never compiled in production builds).
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify that `GsaslError::from_code` produces a non-empty message for
    /// a known error code.
    #[test]
    fn test_error_from_code() {
        let err = GsaslError::from_code(0);
        assert_eq!(err.code(), 0);
        assert!(!err.message.is_empty(), "error message should not be empty");
    }

    /// Verify Display impl produces sensible output.
    #[test]
    fn test_error_display() {
        let err = GsaslError::from_code(31); // GSASL_AUTHENTICATION_ERROR
        let msg = format!("{err}");
        assert!(msg.contains("31"), "display should include error code");
    }

    /// Verify that `GsaslProperty::from_raw` round-trips correctly for all
    /// known variants.
    #[test]
    fn test_property_round_trip() {
        let props = [
            GsaslProperty::AuthId,
            GsaslProperty::AuthzId,
            GsaslProperty::Password,
            GsaslProperty::AnonymousToken,
            GsaslProperty::Service,
            GsaslProperty::Hostname,
            GsaslProperty::GssapiDisplayName,
            GsaslProperty::Passcode,
            GsaslProperty::SuggestedPin,
            GsaslProperty::Pin,
            GsaslProperty::Realm,
            GsaslProperty::DigestMd5HashedPassword,
            GsaslProperty::Qops,
            GsaslProperty::Qop,
            GsaslProperty::ScramIter,
            GsaslProperty::ScramSalt,
            GsaslProperty::ScramSaltedPassword,
            GsaslProperty::CbTlsUnique,
            GsaslProperty::ScramServerKey,
            GsaslProperty::ScramStoredKey,
            GsaslProperty::CbTlsExporter,
            GsaslProperty::ValidateSimple,
            GsaslProperty::ValidateExternal,
            GsaslProperty::ValidateAnonymous,
            GsaslProperty::ValidateGssapi,
        ];

        for prop in props {
            let raw = prop as i32;
            let recovered = GsaslProperty::from_raw(raw)
                .unwrap_or_else(|| panic!("from_raw failed for {prop:?} (raw={raw})"));
            assert_eq!(prop, recovered);
        }
    }

    /// Verify that unknown property values return None.
    #[test]
    fn test_property_unknown() {
        assert!(GsaslProperty::from_raw(9999).is_none());
        assert!(GsaslProperty::from_raw(-1).is_none());
    }

    /// Verify that GsaslCapabilities functions compile and return bool.
    #[test]
    fn test_capabilities_compile() {
        // These are compile-time cfg checks; we just verify they don't panic.
        let _ = GsaslCapabilities::has_scram_sha256();
        let _ = GsaslCapabilities::has_scram_s_key();
        let _ = GsaslCapabilities::has_exporter();
    }

    /// Test context creation and version check.
    #[test]
    fn test_context_lifecycle() {
        let ctx = GsaslContext::new();
        assert!(ctx.is_ok(), "GsaslContext::new() should succeed");
        // Context drops cleanly at end of scope.
    }

    /// Test version checking.
    #[test]
    fn test_check_version() {
        // The library is at least 1.0.0
        let version = GsaslContext::check_version("1.0.0");
        assert!(version.is_some(), "version check for 1.0.0 should succeed");

        // An impossibly high version should fail.
        let version = GsaslContext::check_version("99.99.99");
        assert!(version.is_none(), "version check for 99.99.99 should fail");
    }

    /// Test server session start with a supported mechanism.
    #[test]
    fn test_server_start_plain() {
        let ctx = GsaslContext::new().expect("init");
        let session = ctx.server_start("PLAIN");
        assert!(session.is_ok(), "server_start(PLAIN) should succeed");
    }

    /// Test client session start with a supported mechanism.
    #[test]
    fn test_client_start_plain() {
        let ctx = GsaslContext::new().expect("init");
        let session = ctx.client_start("PLAIN");
        assert!(session.is_ok(), "client_start(PLAIN) should succeed");
    }

    /// Test server_start with an unsupported mechanism.
    #[test]
    fn test_server_start_unknown() {
        let ctx = GsaslContext::new().expect("init");
        let session = ctx.server_start("NONEXISTENT-MECHANISM-XYZ");
        assert!(session.is_err(), "unknown mechanism should fail");
    }

    /// Test property set and get on a session.
    #[test]
    fn test_property_set_get() {
        let ctx = GsaslContext::new().expect("init");
        let mut session = ctx.server_start("PLAIN").expect("session");

        session
            .property_set(GsaslProperty::Service, "smtp")
            .expect("set service");

        let value = session.property_get(GsaslProperty::Service);
        assert_eq!(value.as_deref(), Some("smtp"));
    }

    /// Test setting a callback and verify it doesn't crash.
    #[test]
    fn test_set_callback() {
        let mut ctx = GsaslContext::new().expect("init");
        let result = ctx.set_callback(|_session, _prop| Ok(()));
        assert!(result.is_ok(), "set_callback should succeed");
    }

    /// Test that replacing a callback works without leaking.
    #[test]
    fn test_replace_callback() {
        let mut ctx = GsaslContext::new().expect("init");
        ctx.set_callback(|_session, _prop| Ok(()))
            .expect("first callback");
        ctx.set_callback(|_session, _prop| Err(GsaslError::from_code(GSASL_RC_NO_CALLBACK)))
            .expect("second callback");
    }
}
