//! Safe wrappers around Heimdal's GSSAPI/Kerberos libraries.
//!
//! Provides managed GSSAPI security contexts for Kerberos authentication,
//! wrapping the GSSAPI C API (`gss_accept_sec_context`, `gss_init_sec_context`,
//! `gss_import_name`, `gss_display_name`, etc.) and Kerberos keytab management
//! via `gsskrb5_register_acceptor_identity`.
//!
//! This module is feature-gated behind `ffi-krb5` and corresponds to the C
//! source file `src/src/auths/heimdal_gssapi.c`. No mature pure-Rust Kerberos
//! client exists (see AAP §0.6.2), so we wrap the system GSSAPI/krb5 C
//! libraries via FFI.
//!
//! # Safety Model
//!
//! All raw GSSAPI handles (`gss_name_t`, `gss_ctx_id_t`, `gss_cred_id_t`,
//! `krb5_context`) are wrapped in RAII structs with `Drop` implementations
//! that call the corresponding release/free function. Every `unsafe` block
//! is documented with an inline justification comment per AAP §0.7.2.

use std::ffi::CString;
use std::fmt;
use std::ptr;

/// Raw FFI bindings generated by bindgen from `<gssapi/gssapi.h>`,
/// `<gssapi/gssapi_krb5.h>`, and `<krb5.h>`.
///
/// Additional function and type declarations that bindgen could not generate
/// (due to macro expansion or missing allowlist entries) are appended manually
/// with the same signatures as the C library headers.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
// Justification: bindgen-generated FFI bindings preserve C naming conventions
// for GSSAPI/Kerberos types and constants. Suppressing these lints is standard
// practice for raw FFI modules.
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/krb5_bindings.rs"));

    // =========================================================================
    // Additional type definitions not generated by bindgen because they were
    // not in the build.rs allowlist. These match the C definitions in
    // <gssapi/gssapi.h> exactly.
    // =========================================================================

    /// GSSAPI OID set descriptor — `gss_OID_set_desc` from `<gssapi/gssapi.h>`.
    ///
    /// Needed by `gss_acquire_cred` for the `desired_mechs` and `actual_mechs`
    /// parameters.
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct gss_OID_set_desc_struct {
        pub count: usize,
        pub elements: gss_OID,
    }

    /// Pointer to a GSSAPI OID set — `gss_OID_set` from `<gssapi/gssapi.h>`.
    pub type gss_OID_set = *mut gss_OID_set_desc_struct;

    // =========================================================================
    // Additional function declarations not generated by bindgen because they
    // were not in the build.rs function allowlist or were preprocessor macros.
    // All signatures match the system headers exactly.
    // =========================================================================

    unsafe extern "C" {
        /// Acquire GSSAPI credentials for a named principal.
        ///
        /// From `<gssapi/gssapi.h>`:
        /// ```c
        /// OM_uint32 gss_acquire_cred(
        ///     OM_uint32 *minor_status,
        ///     gss_name_t desired_name,
        ///     OM_uint32 time_req,
        ///     gss_OID_set desired_mechs,
        ///     gss_cred_usage_t cred_usage,   // typedef int
        ///     gss_cred_id_t *output_cred_handle,
        ///     gss_OID_set *actual_mechs,
        ///     OM_uint32 *time_rec);
        /// ```
        pub fn gss_acquire_cred(
            minor_status: *mut OM_uint32,
            desired_name: gss_name_t,
            time_req: OM_uint32,
            desired_mechs: gss_OID_set,
            cred_usage: ::std::os::raw::c_int,
            output_cred_handle: *mut gss_cred_id_t,
            actual_mechs: *mut gss_OID_set,
            time_rec: *mut OM_uint32,
        ) -> OM_uint32;

        /// Convert a GSSAPI status code to a human-readable message.
        ///
        /// From `<gssapi/gssapi.h>`:
        /// ```c
        /// OM_uint32 gss_display_status(
        ///     OM_uint32 *minor_status,
        ///     OM_uint32 status_value,
        ///     int status_type,
        ///     gss_OID mech_type,
        ///     OM_uint32 *message_context,
        ///     gss_buffer_t status_string);
        /// ```
        pub fn gss_display_status(
            minor_status: *mut OM_uint32,
            status_value: OM_uint32,
            status_type: ::std::os::raw::c_int,
            mech_type: gss_OID,
            message_context: *mut OM_uint32,
            status_string: gss_buffer_t,
        ) -> OM_uint32;

        /// Set the keytab file for GSSAPI acceptor (server) identity.
        ///
        /// This is the real function behind the `gsskrb5_register_acceptor_identity`
        /// preprocessor macro defined in `<gssapi/gssapi_krb5.h>`:
        /// ```c
        /// #define gsskrb5_register_acceptor_identity \
        ///     krb5_gss_register_acceptor_identity
        /// OM_uint32 krb5_gss_register_acceptor_identity(const char *);
        /// ```
        pub fn krb5_gss_register_acceptor_identity(
            keytab: *const ::std::os::raw::c_char,
        ) -> OM_uint32;

        /// Wrap a message with integrity and optional confidentiality.
        ///
        /// From `<gssapi/gssapi.h>`:
        /// ```c
        /// OM_uint32 gss_wrap(
        ///     OM_uint32 *minor_status,
        ///     gss_ctx_id_t context_handle,
        ///     int conf_req_flag,
        ///     gss_qop_t qop_req,
        ///     gss_buffer_t input_message_buffer,
        ///     int *conf_state,
        ///     gss_buffer_t output_message_buffer);
        /// ```
        pub fn gss_wrap(
            minor_status: *mut OM_uint32,
            context_handle: gss_ctx_id_t,
            conf_req_flag: ::std::os::raw::c_int,
            qop_req: OM_uint32,
            input_message_buffer: gss_buffer_t,
            conf_state: *mut ::std::os::raw::c_int,
            output_message_buffer: gss_buffer_t,
        ) -> OM_uint32;

        /// Unwrap a message protected by gss_wrap.
        ///
        /// From `<gssapi/gssapi.h>`:
        /// ```c
        /// OM_uint32 gss_unwrap(
        ///     OM_uint32 *minor_status,
        ///     gss_ctx_id_t context_handle,
        ///     gss_buffer_t input_message_buffer,
        ///     gss_buffer_t output_message_buffer,
        ///     int *conf_state,
        ///     gss_qop_t *qop_state);
        /// ```
        pub fn gss_unwrap(
            minor_status: *mut OM_uint32,
            context_handle: gss_ctx_id_t,
            input_message_buffer: gss_buffer_t,
            output_message_buffer: gss_buffer_t,
            conf_state: *mut ::std::os::raw::c_int,
            qop_state: *mut OM_uint32,
        ) -> OM_uint32;
    }
}

// =============================================================================
// GSSAPI status code helpers
// =============================================================================

/// Check whether a GSSAPI major status code indicates an error.
///
/// Equivalent to the C macro `GSS_ERROR(x)` from `<gssapi/gssapi.h>`:
/// ```c
/// #define GSS_ERROR(x) \
///   ((x) & ((0177ul << GSS_C_ROUTINE_ERROR_OFFSET) | \
///            (0177ul << GSS_C_CALLING_ERROR_OFFSET)))
/// ```
///
/// Errors occupy the upper 16 bits of the major status; supplementary info
/// (e.g. `GSS_S_CONTINUE_NEEDED`) occupies the lower 16 bits and is not
/// considered an error.
#[inline]
fn is_gss_error(major: u32) -> bool {
    // Routine errors are in bits 16–23, calling errors in bits 24–31.
    // The mask combines both 7-bit error fields (0o177 = 0x7F per field).
    const ROUTINE_MASK: u32 = 0x7F << 16;
    const CALLING_MASK: u32 = 0x7F << 24;
    major & (ROUTINE_MASK | CALLING_MASK) != 0
}

// =============================================================================
// GssapiError — Error type for GSSAPI operations
// =============================================================================

/// GSSAPI error with major and minor status codes and a human-readable message.
///
/// Major status codes encode calling errors (bits 24–31), routine errors
/// (bits 16–23), and supplementary info (bits 0–15). Minor status codes
/// are mechanism-specific and provide additional detail.
#[derive(Debug, Clone)]
pub struct GssapiError {
    /// GSSAPI major status code (calling errors bits 24–31, routine errors
    /// bits 16–23, supplementary info bits 0–15).
    pub major: u32,
    /// GSSAPI minor (mechanism-specific) status code providing additional
    /// detail about the failure cause.
    pub minor: u32,
    /// Human-readable error description obtained from `gss_display_status`.
    pub message: String,
}

impl GssapiError {
    /// Create an error from GSSAPI major/minor status codes.
    ///
    /// Calls `gss_display_status` in a loop to convert both the major
    /// (GSS-level) and minor (mechanism-level) status codes into
    /// human-readable messages, then concatenates them.
    pub fn from_status(major: u32, minor: u32) -> Self {
        let mut parts: Vec<String> = Vec::new();

        // Collect major (GSS-level) status messages.
        collect_status_messages(major, ffi::GSS_C_GSS_CODE as i32, &mut parts);

        // Collect minor (mechanism-specific) status messages.
        if minor != 0 {
            collect_status_messages(minor, ffi::GSS_C_MECH_CODE as i32, &mut parts);
        }

        let message = if parts.is_empty() {
            format!("GSSAPI error: major={major:#010x}, minor={minor:#010x}")
        } else {
            parts.join("; ")
        };

        GssapiError {
            major,
            minor,
            message,
        }
    }
}

/// Collect human-readable status messages for a single GSSAPI status value.
///
/// The `gss_display_status` function may produce multiple message fragments
/// for a single status value (indicated by a non-zero `message_context`
/// output). This function loops until all fragments are collected.
fn collect_status_messages(status_value: u32, status_type: i32, out: &mut Vec<String>) {
    let mut msg_ctx: u32 = 0;

    loop {
        let mut min_stat: u32 = 0;
        let mut buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };

        // SAFETY: calling gss_display_status to convert a GSSAPI
        // status code into a human-readable string. All pointer arguments point
        // to valid stack-allocated variables. The output buffer is managed by
        // GSSAPI and released via gss_release_buffer below.
        let maj = unsafe {
            ffi::gss_display_status(
                &mut min_stat,
                status_value,
                status_type,
                ptr::null_mut(), // GSS_C_NO_OID — use default mechanism
                &mut msg_ctx,
                &mut buf,
            )
        };

        if !is_gss_error(maj) && buf.length > 0 && !buf.value.is_null() {
            // SAFETY: gss_display_status succeeded and returned
            // a non-empty buffer. The value pointer is valid for `length` bytes
            // as guaranteed by the GSSAPI specification. We create a byte slice
            // from the raw pointer and length, then convert to a Rust String.
            let bytes = unsafe { std::slice::from_raw_parts(buf.value as *const u8, buf.length) };
            let msg = String::from_utf8_lossy(bytes).into_owned();
            out.push(msg);
        }

        if buf.length > 0 && !buf.value.is_null() {
            let mut release_min: u32 = 0;
            // SAFETY: releasing the buffer allocated by
            // gss_display_status. The buffer descriptor is valid because
            // gss_display_status succeeded and populated it.
            unsafe {
                ffi::gss_release_buffer(&mut release_min, &mut buf);
            }
        }

        // msg_ctx == 0 means all message fragments have been returned.
        if msg_ctx == 0 {
            break;
        }
    }
}

impl fmt::Display for GssapiError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for GssapiError {}

// =============================================================================
// GssName — Safe wrapper around gss_name_t
// =============================================================================

/// Safe wrapper around a GSSAPI name (`gss_name_t`).
///
/// Encapsulates the lifecycle of a GSSAPI internal name, ensuring that
/// `gss_release_name` is called when the name is dropped.
pub struct GssName {
    /// The raw GSSAPI name handle. Null (`GSS_C_NO_NAME`) only after `Drop`.
    name: ffi::gss_name_t,
}

impl GssName {
    /// Import a host-based service name (e.g., `"smtp@mail.example.com"`).
    ///
    /// Calls `gss_import_name` with `GSS_C_NT_HOSTBASED_SERVICE` as the
    /// name type OID, matching the pattern used in
    /// `src/src/auths/heimdal_gssapi.c` lines 256–262.
    ///
    /// # Arguments
    ///
    /// * `service` — Service name (e.g., `"smtp"`)
    /// * `hostname` — Host name (e.g., `"mail.example.com"`)
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_import_name` fails.
    pub fn import_service(service: &str, hostname: &str) -> Result<Self, GssapiError> {
        let name_str = format!("{service}@{hostname}");
        let c_name = CString::new(name_str.as_bytes()).map_err(|_| GssapiError {
            major: 0xFFFF_0000, // Synthetic error — interior NUL byte
            minor: 0,
            message: "Service name contains interior NUL byte".to_string(),
        })?;

        let mut min_stat: u32 = 0;
        let mut output_name: ffi::gss_name_t = ptr::null_mut();
        let mut buf = ffi::gss_buffer_desc_struct {
            length: c_name.as_bytes().len(),
            value: c_name.as_ptr() as *mut libc::c_void,
        };

        // SAFETY: calling gss_import_name with
        // GSS_C_NT_HOSTBASED_SERVICE OID to create a GSSAPI name from a
        // "service@host" string. The input buffer points to valid,
        // null-terminated memory owned by `c_name` which outlives this call.
        // The OID pointer is a global constant provided by the GSSAPI library.
        // The output_name pointer is a valid stack-allocated variable.
        let maj = unsafe {
            ffi::gss_import_name(
                &mut min_stat,
                &mut buf,
                ffi::GSS_C_NT_HOSTBASED_SERVICE,
                &mut output_name,
            )
        };

        if is_gss_error(maj) {
            return Err(GssapiError::from_status(maj, min_stat));
        }

        Ok(GssName { name: output_name })
    }

    /// Display the GSSAPI name as a human-readable string.
    ///
    /// Calls `gss_display_name` to convert the internal GSSAPI name
    /// representation into a string, matching the usage in
    /// `src/src/auths/heimdal_gssapi.c` lines 478–488.
    pub fn display(&self) -> Result<String, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };
        let mut oid: ffi::gss_OID = ptr::null_mut();

        // SAFETY: calling gss_display_name to convert the
        // internal GSSAPI name to a human-readable string representation.
        // `self.name` is a valid gss_name_t obtained from gss_import_name
        // or gss_accept_sec_context. The output buffer and OID are valid
        // stack-allocated variables.
        let maj = unsafe { ffi::gss_display_name(&mut min_stat, self.name, &mut buf, &mut oid) };

        if is_gss_error(maj) {
            return Err(GssapiError::from_status(maj, min_stat));
        }

        // Extract the string from the GSSAPI buffer (length-delimited, not
        // necessarily null-terminated).
        let result = if buf.length > 0 && !buf.value.is_null() {
            // SAFETY: gss_display_name succeeded and returned
            // a non-empty buffer. The value pointer is valid for `length`
            // bytes as guaranteed by the GSSAPI specification.
            let bytes = unsafe { std::slice::from_raw_parts(buf.value as *const u8, buf.length) };
            String::from_utf8_lossy(bytes).into_owned()
        } else {
            String::new()
        };

        // Release the buffer allocated by gss_display_name.
        if buf.length > 0 && !buf.value.is_null() {
            let mut release_min: u32 = 0;
            // SAFETY: releasing the buffer allocated by
            // gss_display_name. The buffer descriptor is valid because
            // gss_display_name succeeded and populated it.
            unsafe {
                ffi::gss_release_buffer(&mut release_min, &mut buf);
            }
        }

        Ok(result)
    }
}

impl Drop for GssName {
    fn drop(&mut self) {
        if !self.name.is_null() {
            let mut min_stat: u32 = 0;
            // SAFETY: calling gss_release_name to free the
            // GSSAPI name resources. `self.name` is a valid gss_name_t that
            // was obtained from gss_import_name, gss_accept_sec_context, or
            // gss_inquire_context and has not been released yet.
            unsafe {
                ffi::gss_release_name(&mut min_stat, &mut self.name);
            }
        }
    }
}

// =============================================================================
// GssContextStepResult — Token exchange outcome
// =============================================================================

/// Result of a single GSSAPI security context establishment step.
///
/// The GSSAPI token exchange is multi-step: the server and client exchange
/// tokens until both sides agree that authentication is complete.
pub enum GssContextStepResult {
    /// More tokens are needed from the client. The contained `Vec<u8>` is the
    /// output token that must be sent back to the client.
    Continue(Vec<u8>),
    /// Authentication is complete. The contained `Vec<u8>` is the final output
    /// token (possibly empty) to send to the client.
    Done(Vec<u8>),
}

// =============================================================================
// GssContext — Safe wrapper around gss_ctx_id_t
// =============================================================================

/// Safe wrapper around a GSSAPI security context (`gss_ctx_id_t`).
///
/// Manages the lifecycle of a GSSAPI security context, ensuring that
/// `gss_delete_sec_context` is called when the context is dropped.
///
/// Usage mirrors the server-side authentication flow in
/// `src/src/auths/heimdal_gssapi.c` lines 227–538.
pub struct GssContext {
    /// The raw GSSAPI context handle. Starts as null (`GSS_C_NO_CONTEXT`)
    /// and is populated by `gss_accept_sec_context`.
    ctx: ffi::gss_ctx_id_t,
}

impl Default for GssContext {
    fn default() -> Self {
        Self::new()
    }
}

impl GssContext {
    /// Create a new empty security context for server-side authentication.
    ///
    /// The context starts in the `GSS_C_NO_CONTEXT` state and is populated
    /// by calling [`accept`](Self::accept) with client tokens.
    pub fn new() -> Self {
        // GSS_C_NO_CONTEXT is defined as ((gss_ctx_id_t) 0) in gssapi.h,
        // which is a null pointer in Rust.
        Self {
            ctx: ptr::null_mut(),
        }
    }

    /// Accept a security context token from the client (server-side).
    ///
    /// Processes one step of the GSSAPI server-side authentication by calling
    /// `gss_accept_sec_context`. This matches the token exchange loop in
    /// `src/src/auths/heimdal_gssapi.c` lines 343–378.
    ///
    /// # Arguments
    ///
    /// * `cred` — Server credentials obtained via [`GssCredential::acquire_accept`].
    /// * `input_token` — Raw token bytes received from the client.
    ///
    /// # Returns
    ///
    /// A tuple of:
    /// - `GssContextStepResult::Continue(token)` if more tokens are needed, or
    ///   `GssContextStepResult::Done(token)` when authentication is complete.
    /// - `Option<GssName>` — The authenticated client identity, present when
    ///   authentication completes (`Done` variant).
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_accept_sec_context` fails.
    pub fn accept(
        &mut self,
        cred: &GssCredential,
        input_token: &[u8],
    ) -> Result<(GssContextStepResult, Option<GssName>), GssapiError> {
        let mut min_stat: u32 = 0;
        let mut src_name: ffi::gss_name_t = ptr::null_mut();
        let mut mech_type: ffi::gss_OID = ptr::null_mut();
        let mut output_buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };
        let mut ret_flags: u32 = 0;
        let mut time_rec: u32 = 0;
        let mut delegated_cred: ffi::gss_cred_id_t = ptr::null_mut();

        // Create a GSSAPI buffer descriptor pointing to the input token bytes.
        // The buffer is read-only from GSSAPI's perspective; the const cast is
        // required by the C API which takes `gss_buffer_t` (pointer to mutable
        // buffer descriptor) even for input buffers.
        let mut input_buf = ffi::gss_buffer_desc_struct {
            length: input_token.len(),
            value: input_token.as_ptr() as *mut libc::c_void,
        };

        // SAFETY: calling gss_accept_sec_context to process one
        // step of the GSSAPI server-side authentication. All pointer arguments
        // point to valid stack-allocated variables or valid handles:
        // - `self.ctx`: either GSS_C_NO_CONTEXT (first call) or a valid context
        //   from a prior call.
        // - `cred.cred`: valid credential from gss_acquire_cred.
        // - `input_buf`: points to valid input_token bytes that outlive this call.
        // - Output pointers (src_name, mech_type, output_buf, ret_flags,
        //   time_rec, delegated_cred) are all valid stack-allocated variables.
        let maj = unsafe {
            ffi::gss_accept_sec_context(
                &mut min_stat,
                &mut self.ctx,
                cred.cred,
                &mut input_buf,
                ptr::null_mut(), // GSS_C_NO_CHANNEL_BINDINGS
                &mut src_name,
                &mut mech_type,
                &mut output_buf,
                &mut ret_flags,
                &mut time_rec,
                &mut delegated_cred,
            )
        };

        // Release any delegated credentials we don't use.
        if !delegated_cred.is_null() {
            let mut rel_min: u32 = 0;
            // SAFETY: releasing delegated credentials that we do
            // not need. The handle is valid because gss_accept_sec_context
            // returned it.
            unsafe {
                ffi::gss_release_cred(&mut rel_min, &mut delegated_cred);
            }
        }

        if is_gss_error(maj) {
            // If gss_accept_sec_context allocated an output buffer before
            // failing, release it.
            if output_buf.length > 0 && !output_buf.value.is_null() {
                let mut rel_min: u32 = 0;
                // SAFETY: releasing the output buffer on error.
                unsafe {
                    ffi::gss_release_buffer(&mut rel_min, &mut output_buf);
                }
            }
            // Release any source name allocated before the error.
            if !src_name.is_null() {
                let mut rel_min: u32 = 0;
                // SAFETY: releasing the source name on error.
                unsafe {
                    ffi::gss_release_name(&mut rel_min, &mut src_name);
                }
            }
            return Err(GssapiError::from_status(maj, min_stat));
        }

        // Copy the output token bytes to an owned Vec before releasing the
        // GSSAPI-managed buffer.
        let output_token = if output_buf.length > 0 && !output_buf.value.is_null() {
            // SAFETY: the output buffer was populated by
            // gss_accept_sec_context on success. The value pointer is valid
            // for `length` bytes.
            let bytes = unsafe {
                std::slice::from_raw_parts(output_buf.value as *const u8, output_buf.length)
            };
            let token = bytes.to_vec();

            let mut rel_min: u32 = 0;
            // SAFETY: releasing the output buffer after copying
            // its contents. The buffer descriptor is valid.
            unsafe {
                ffi::gss_release_buffer(&mut rel_min, &mut output_buf);
            }

            token
        } else {
            Vec::new()
        };

        // Wrap the source name if it was returned.
        let client_name = if !src_name.is_null() {
            Some(GssName { name: src_name })
        } else {
            None
        };

        // Determine whether authentication is complete or continuing.
        let step_result = if maj == ffi::GSS_S_COMPLETE {
            GssContextStepResult::Done(output_token)
        } else {
            // GSS_S_CONTINUE_NEEDED (or other supplementary info)
            GssContextStepResult::Continue(output_token)
        };

        Ok((step_result, client_name))
    }

    /// Query the authenticated client name from a completed security context.
    ///
    /// Calls `gss_inquire_context` to retrieve the source (client) name from
    /// a fully established security context. This is an alternative to
    /// capturing the source name from the final [`accept`](Self::accept) call.
    pub fn inquire_source_name(&self) -> Result<GssName, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut src_name: ffi::gss_name_t = ptr::null_mut();
        let mut targ_name: ffi::gss_name_t = ptr::null_mut();
        let mut lifetime: u32 = 0;
        let mut mech_type: ffi::gss_OID = ptr::null_mut();
        let mut ctx_flags: u32 = 0;
        let mut locally_initiated: i32 = 0;
        let mut open: i32 = 0;

        // SAFETY: calling gss_inquire_context to retrieve the
        // source (client) name from a fully established security context.
        // `self.ctx` is a valid context handle populated by prior calls to
        // gss_accept_sec_context. All output pointers are valid stack-allocated
        // variables. The target name is released below since we only need the
        // source name.
        let maj = unsafe {
            ffi::gss_inquire_context(
                &mut min_stat,
                self.ctx,
                &mut src_name,
                &mut targ_name,
                &mut lifetime,
                &mut mech_type,
                &mut ctx_flags,
                &mut locally_initiated,
                &mut open,
            )
        };

        // Release the target name — we only need the source name.
        if !targ_name.is_null() {
            let mut rel_min: u32 = 0;
            // SAFETY: releasing the target name returned by
            // gss_inquire_context that we do not need.
            unsafe {
                ffi::gss_release_name(&mut rel_min, &mut targ_name);
            }
        }

        if is_gss_error(maj) {
            // Release source name on error if it was partially allocated.
            if !src_name.is_null() {
                let mut rel_min: u32 = 0;
                // SAFETY: releasing partially allocated source name.
                unsafe {
                    ffi::gss_release_name(&mut rel_min, &mut src_name);
                }
            }
            return Err(GssapiError::from_status(maj, min_stat));
        }

        if src_name.is_null() {
            return Err(GssapiError {
                major: 0,
                minor: 0,
                message: "gss_inquire_context returned null source name".to_string(),
            });
        }

        Ok(GssName { name: src_name })
    }

    /// Wrap a message with integrity and optional confidentiality protection.
    ///
    /// Wraps the input message using `gss_wrap()` on a fully established
    /// security context. Used for the SASL GSSAPI security-layer negotiation
    /// where the server sends wrapped capability bytes to the client.
    ///
    /// Replaces the `gss_wrap()` call at `heimdal_gssapi.c` line 393.
    ///
    /// # Arguments
    ///
    /// * `message` — The plaintext message bytes to wrap.
    /// * `confidential` — If `true`, request confidentiality (encryption).
    ///   If `false`, request integrity protection only.
    ///
    /// # Returns
    ///
    /// The wrapped message as a `Vec<u8>`.
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_wrap()` fails.
    pub fn wrap(&self, message: &[u8], confidential: bool) -> Result<Vec<u8>, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut conf_state: i32 = 0;
        let mut output_buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };
        let mut input_buf = ffi::gss_buffer_desc_struct {
            length: message.len(),
            value: message.as_ptr() as *mut libc::c_void,
        };

        let conf_req = if confidential { 1 } else { 0 };

        // SAFETY: calling gss_wrap to protect a message with
        // the established GSSAPI security context. `self.ctx` is a valid
        // context handle from a completed gss_accept_sec_context exchange.
        // `input_buf` points to valid `message` bytes that outlive this call.
        // `output_buf` and `conf_state` are valid stack-allocated variables.
        // `qop_req` of 0 means use default QOP.
        let maj = unsafe {
            ffi::gss_wrap(
                &mut min_stat,
                self.ctx,
                conf_req,
                0, // GSS_C_QOP_DEFAULT
                &mut input_buf,
                &mut conf_state,
                &mut output_buf,
            )
        };

        if is_gss_error(maj) {
            if output_buf.length > 0 && !output_buf.value.is_null() {
                let mut rel_min: u32 = 0;
                // SAFETY: releasing the output buffer on error.
                unsafe {
                    ffi::gss_release_buffer(&mut rel_min, &mut output_buf);
                }
            }
            return Err(GssapiError::from_status(maj, min_stat));
        }

        // Copy the wrapped bytes and release the GSSAPI-managed buffer.
        let result = if output_buf.length > 0 && !output_buf.value.is_null() {
            // SAFETY: the output buffer was populated by gss_wrap
            // on success. The value pointer is valid for `length` bytes.
            let bytes = unsafe {
                std::slice::from_raw_parts(output_buf.value as *const u8, output_buf.length)
            };
            let token = bytes.to_vec();

            let mut rel_min: u32 = 0;
            // SAFETY: releasing the output buffer after copying.
            unsafe {
                ffi::gss_release_buffer(&mut rel_min, &mut output_buf);
            }
            token
        } else {
            Vec::new()
        };

        Ok(result)
    }

    /// Unwrap a message protected by gss_wrap.
    ///
    /// Unwraps the input token using `gss_unwrap()` on a fully established
    /// security context. Used for the SASL GSSAPI security-layer negotiation
    /// where the server unwraps the client's security-layer choice response.
    ///
    /// Replaces the `gss_unwrap()` call at `heimdal_gssapi.c` line 423.
    ///
    /// # Arguments
    ///
    /// * `token` — The wrapped message bytes to unwrap.
    ///
    /// # Returns
    ///
    /// The unwrapped plaintext message as a `Vec<u8>`.
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_unwrap()` fails.
    pub fn unwrap(&self, token: &[u8]) -> Result<Vec<u8>, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut conf_state: i32 = 0;
        let mut qop_state: u32 = 0;
        let mut output_buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };
        let mut input_buf = ffi::gss_buffer_desc_struct {
            length: token.len(),
            value: token.as_ptr() as *mut libc::c_void,
        };

        // SAFETY: calling gss_unwrap to decode a wrapped message
        // with the established GSSAPI security context. `self.ctx` is a valid
        // context handle from a completed gss_accept_sec_context exchange.
        // `input_buf` points to valid `token` bytes that outlive this call.
        // `output_buf`, `conf_state`, and `qop_state` are valid stack vars.
        let maj = unsafe {
            ffi::gss_unwrap(
                &mut min_stat,
                self.ctx,
                &mut input_buf,
                &mut output_buf,
                &mut conf_state,
                &mut qop_state,
            )
        };

        if is_gss_error(maj) {
            if output_buf.length > 0 && !output_buf.value.is_null() {
                let mut rel_min: u32 = 0;
                // SAFETY: releasing the output buffer on error.
                unsafe {
                    ffi::gss_release_buffer(&mut rel_min, &mut output_buf);
                }
            }
            return Err(GssapiError::from_status(maj, min_stat));
        }

        // Copy the unwrapped bytes and release the GSSAPI-managed buffer.
        let result = if output_buf.length > 0 && !output_buf.value.is_null() {
            // SAFETY: the output buffer was populated by gss_unwrap
            // on success. The value pointer is valid for `length` bytes.
            let bytes = unsafe {
                std::slice::from_raw_parts(output_buf.value as *const u8, output_buf.length)
            };
            let token = bytes.to_vec();

            let mut rel_min: u32 = 0;
            // SAFETY: releasing the output buffer after copying.
            unsafe {
                ffi::gss_release_buffer(&mut rel_min, &mut output_buf);
            }
            token
        } else {
            Vec::new()
        };

        Ok(result)
    }
}

impl Drop for GssContext {
    fn drop(&mut self) {
        if !self.ctx.is_null() {
            let mut min_stat: u32 = 0;
            // SAFETY: calling gss_delete_sec_context to release
            // the GSSAPI security context resources. `self.ctx` is a valid
            // context handle that was populated by gss_accept_sec_context and
            // has not been deleted yet. Passing null for the output token
            // (GSS_C_NO_BUFFER) discards any final token.
            unsafe {
                ffi::gss_delete_sec_context(
                    &mut min_stat,
                    &mut self.ctx,
                    ptr::null_mut(), // GSS_C_NO_BUFFER
                );
            }
        }
    }
}

// =============================================================================
// GssCredential — Safe wrapper around gss_cred_id_t
// =============================================================================

/// Safe wrapper around a GSSAPI credential (`gss_cred_id_t`).
///
/// Manages the lifecycle of server-side GSSAPI credentials, ensuring that
/// `gss_release_cred` is called when the credential is dropped.
pub struct GssCredential {
    /// The raw GSSAPI credential handle.
    cred: ffi::gss_cred_id_t,
}

impl GssCredential {
    /// Acquire server (acceptor) credentials for the given service name.
    ///
    /// Calls `gss_acquire_cred` with `GSS_C_ACCEPT` usage to obtain
    /// server credentials for the specified service principal. This matches
    /// the credential acquisition in `src/src/auths/heimdal_gssapi.c`
    /// lines 278–289.
    ///
    /// # Arguments
    ///
    /// * `name` — The service name to acquire credentials for, typically
    ///   created via [`GssName::import_service`].
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_acquire_cred` fails (e.g., keytab not
    /// found, principal not in keytab).
    pub fn acquire_accept(name: &GssName) -> Result<Self, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut cred: ffi::gss_cred_id_t = ptr::null_mut();

        // SAFETY: calling gss_acquire_cred with GSS_C_ACCEPT
        // usage to obtain server credentials for the specified service
        // principal. Arguments:
        // - `name.name`: valid gss_name_t from gss_import_name.
        // - time_req=0: default credential lifetime.
        // - desired_mechs=null (GSS_C_NULL_OID_SET): use default mechanism.
        // - cred_usage=GSS_C_ACCEPT (2): server/acceptor credentials.
        // - output_cred_handle: valid stack pointer receiving the credential.
        // - actual_mechs=null: we don't need the actual mechanism list.
        // - time_rec=null: we don't need the actual lifetime.
        let maj = unsafe {
            ffi::gss_acquire_cred(
                &mut min_stat,
                name.name,
                0,                                        // time_req: default
                ptr::null_mut(),                          // GSS_C_NULL_OID_SET
                ffi::GSS_C_ACCEPT as std::os::raw::c_int, // GSS_C_ACCEPT
                &mut cred,
                ptr::null_mut(), // actual_mechs: not needed
                ptr::null_mut(), // time_rec: not needed
            )
        };

        if is_gss_error(maj) {
            return Err(GssapiError::from_status(maj, min_stat));
        }

        Ok(GssCredential { cred })
    }
}

impl Drop for GssCredential {
    fn drop(&mut self) {
        if !self.cred.is_null() {
            let mut min_stat: u32 = 0;
            // SAFETY: calling gss_release_cred to free the
            // GSSAPI credential resources. `self.cred` is a valid credential
            // handle obtained from gss_acquire_cred and not yet released.
            unsafe {
                ffi::gss_release_cred(&mut min_stat, &mut self.cred);
            }
        }
    }
}

// =============================================================================
// register_acceptor_identity — Keytab registration
// =============================================================================

/// Register a keytab file for GSSAPI acceptor (server) identity.
///
/// Sets the keytab that will be used for server-side GSSAPI authentication.
/// This wraps the Heimdal/MIT function `gsskrb5_register_acceptor_identity`
/// (which is a macro aliasing `krb5_gss_register_acceptor_identity`).
///
/// Matches the keytab registration in `src/src/auths/heimdal_gssapi.c`
/// lines 268–276.
///
/// # Arguments
///
/// * `keytab_path` — Filesystem path to the Kerberos keytab file.
///
/// # Errors
///
/// Returns `GssapiError` if the keytab registration fails.
pub fn register_acceptor_identity(keytab_path: &str) -> Result<(), GssapiError> {
    let c_path = CString::new(keytab_path).map_err(|_| GssapiError {
        major: 0xFFFF_0000,
        minor: 0,
        message: "Keytab path contains interior NUL byte".to_string(),
    })?;

    // SAFETY: calling krb5_gss_register_acceptor_identity (the
    // real function behind the gsskrb5_register_acceptor_identity macro) to
    // set the Kerberos keytab file path for server-side authentication. The
    // argument is a valid null-terminated C string that outlives this call.
    let maj = unsafe { ffi::krb5_gss_register_acceptor_identity(c_path.as_ptr()) };

    if is_gss_error(maj) {
        // This function has no minor status output, so use 0.
        return Err(GssapiError::from_status(maj, 0));
    }

    Ok(())
}

// =============================================================================
// Krb5Context — Minimal Kerberos 5 context for diagnostics
// =============================================================================

/// Minimal Kerberos 5 context for diagnostics and error reporting.
///
/// Wraps `krb5_context` to provide a safe initialization/teardown lifecycle.
/// Used by the `heimdal_gssapi` authenticator's init function for keytab
/// enumeration and debug output (see `src/src/auths/heimdal_gssapi.c`
/// lines 119–201).
pub struct Krb5Context {
    /// The raw Kerberos 5 context handle.
    ctx: ffi::krb5_context,
}

impl Krb5Context {
    /// Initialize a new Kerberos 5 library context.
    ///
    /// Calls `krb5_init_context` to create a Kerberos library context
    /// suitable for error message formatting and keytab diagnostics.
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `krb5_init_context` fails (e.g., Kerberos
    /// configuration is missing or malformed).
    pub fn new() -> Result<Self, GssapiError> {
        let mut ctx: ffi::krb5_context = ptr::null_mut();

        // SAFETY: calling krb5_init_context to initialize a
        // Kerberos library context for error message formatting and
        // diagnostics. The output pointer is a valid stack-allocated variable.
        let rc = unsafe { ffi::krb5_init_context(&mut ctx) };

        if rc != 0 {
            return Err(GssapiError {
                major: 0,
                minor: rc as u32,
                message: format!("krb5_init_context failed with error code {rc}"),
            });
        }

        if ctx.is_null() {
            return Err(GssapiError {
                major: 0,
                minor: 0,
                message: "krb5_init_context returned null context".to_string(),
            });
        }

        Ok(Krb5Context { ctx })
    }
}

impl Drop for Krb5Context {
    fn drop(&mut self) {
        if !self.ctx.is_null() {
            // SAFETY: calling krb5_free_context to release the
            // Kerberos library context. `self.ctx` is a valid krb5_context
            // obtained from krb5_init_context and not yet freed.
            unsafe {
                ffi::krb5_free_context(self.ctx);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gss_error_detection() {
        // GSS_S_COMPLETE (0) is not an error.
        assert!(!is_gss_error(ffi::GSS_S_COMPLETE));

        // GSS_S_CONTINUE_NEEDED (1) is supplementary info, not an error.
        assert!(!is_gss_error(ffi::GSS_S_CONTINUE_NEEDED));

        // A routine error in bits 16–23 should be detected.
        assert!(is_gss_error(1 << 16));

        // A calling error in bits 24–31 should be detected.
        assert!(is_gss_error(1 << 24));

        // Combined routine + supplementary is still an error.
        assert!(is_gss_error((1 << 16) | ffi::GSS_S_CONTINUE_NEEDED));
    }

    #[test]
    fn test_gssapi_error_display() {
        let err = GssapiError {
            major: 0x000D_0000,
            minor: 0,
            message: "test error message".to_string(),
        };
        assert_eq!(format!("{err}"), "test error message");
    }

    #[test]
    fn test_gssapi_error_debug() {
        let err = GssapiError::from_status(0, 0);
        // With both codes zero, from_status should produce a fallback message.
        let debug = format!("{err:?}");
        assert!(debug.contains("GssapiError"));
    }

    #[test]
    fn test_context_step_result_variants() {
        let cont = GssContextStepResult::Continue(vec![1, 2, 3]);
        match cont {
            GssContextStepResult::Continue(data) => assert_eq!(data, vec![1, 2, 3]),
            GssContextStepResult::Done(_) => panic!("Expected Continue variant"),
        }

        let done = GssContextStepResult::Done(vec![4, 5]);
        match done {
            GssContextStepResult::Done(data) => assert_eq!(data, vec![4, 5]),
            GssContextStepResult::Continue(_) => panic!("Expected Done variant"),
        }
    }

    #[test]
    fn test_gss_context_new() {
        let ctx = GssContext::new();
        // The context should start as GSS_C_NO_CONTEXT (null pointer).
        assert!(ctx.ctx.is_null());
        // Drop should be safe on a null context.
        drop(ctx);
    }
}
