//! Safe wrappers around Heimdal's GSSAPI/Kerberos libraries.
//!
//! Provides managed GSSAPI security contexts for Kerberos authentication,
//! wrapping the GSSAPI C API (`gss_accept_sec_context`, `gss_init_sec_context`,
//! `gss_import_name`, `gss_display_name`, etc.) and Kerberos keytab management
//! via `gsskrb5_register_acceptor_identity`.
//!
//! This module is feature-gated behind `ffi-krb5` and corresponds to the C
//! source file `src/src/auths/heimdal_gssapi.c`. No mature pure-Rust Kerberos
//! client exists (see AAP §0.6.2), so we wrap the system GSSAPI/krb5 C
//! libraries via FFI.
//!
//! # Safety Model
//!
//! All raw GSSAPI handles (`gss_name_t`, `gss_ctx_id_t`, `gss_cred_id_t`,
//! `krb5_context`) are wrapped in RAII structs with `Drop` implementations
//! that call the corresponding release/free function. Every `unsafe` block
//! is documented with an inline justification comment per AAP §0.7.2.

use std::ffi::CString;
use std::fmt;
use std::ptr;

/// Raw FFI bindings generated by bindgen from `<gssapi/gssapi.h>`,
/// `<gssapi/gssapi_krb5.h>`, and `<krb5.h>`.
///
/// Additional function and type declarations that bindgen could not generate
/// (due to macro expansion or missing allowlist entries) are appended manually
/// with the same signatures as the C library headers.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
// Justification: bindgen-generated FFI bindings preserve C naming conventions
// for GSSAPI/Kerberos types and constants. Suppressing these lints is standard
// practice for raw FFI modules.
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/krb5_bindings.rs"));

    // =========================================================================
    // Additional type definitions not generated by bindgen because they were
    // not in the build.rs allowlist. These match the C definitions in
    // <gssapi/gssapi.h> exactly.
    // =========================================================================

    /// GSSAPI OID set descriptor — `gss_OID_set_desc` from `<gssapi/gssapi.h>`.
    ///
    /// Needed by `gss_acquire_cred` for the `desired_mechs` and `actual_mechs`
    /// parameters.
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct gss_OID_set_desc_struct {
        pub count: usize,
        pub elements: gss_OID,
    }

    /// Pointer to a GSSAPI OID set — `gss_OID_set` from `<gssapi/gssapi.h>`.
    pub type gss_OID_set = *mut gss_OID_set_desc_struct;

    // =========================================================================
    // Additional function declarations not generated by bindgen because they
    // were not in the build.rs function allowlist or were preprocessor macros.
    // All signatures match the system headers exactly.
    // =========================================================================

    extern "C" {
        /// Acquire GSSAPI credentials for a named principal.
        ///
        /// From `<gssapi/gssapi.h>`:
        /// ```c
        /// OM_uint32 gss_acquire_cred(
        ///     OM_uint32 *minor_status,
        ///     gss_name_t desired_name,
        ///     OM_uint32 time_req,
        ///     gss_OID_set desired_mechs,
        ///     gss_cred_usage_t cred_usage,   // typedef int
        ///     gss_cred_id_t *output_cred_handle,
        ///     gss_OID_set *actual_mechs,
        ///     OM_uint32 *time_rec);
        /// ```
        pub fn gss_acquire_cred(
            minor_status: *mut OM_uint32,
            desired_name: gss_name_t,
            time_req: OM_uint32,
            desired_mechs: gss_OID_set,
            cred_usage: ::std::os::raw::c_int,
            output_cred_handle: *mut gss_cred_id_t,
            actual_mechs: *mut gss_OID_set,
            time_rec: *mut OM_uint32,
        ) -> OM_uint32;

        /// Convert a GSSAPI status code to a human-readable message.
        ///
        /// From `<gssapi/gssapi.h>`:
        /// ```c
        /// OM_uint32 gss_display_status(
        ///     OM_uint32 *minor_status,
        ///     OM_uint32 status_value,
        ///     int status_type,
        ///     gss_OID mech_type,
        ///     OM_uint32 *message_context,
        ///     gss_buffer_t status_string);
        /// ```
        pub fn gss_display_status(
            minor_status: *mut OM_uint32,
            status_value: OM_uint32,
            status_type: ::std::os::raw::c_int,
            mech_type: gss_OID,
            message_context: *mut OM_uint32,
            status_string: gss_buffer_t,
        ) -> OM_uint32;

        /// Set the keytab file for GSSAPI acceptor (server) identity.
        ///
        /// This is the real function behind the `gsskrb5_register_acceptor_identity`
        /// preprocessor macro defined in `<gssapi/gssapi_krb5.h>`:
        /// ```c
        /// #define gsskrb5_register_acceptor_identity \
        ///     krb5_gss_register_acceptor_identity
        /// OM_uint32 krb5_gss_register_acceptor_identity(const char *);
        /// ```
        pub fn krb5_gss_register_acceptor_identity(
            keytab: *const ::std::os::raw::c_char,
        ) -> OM_uint32;

        /// Wrap a message with integrity and optional confidentiality.
        ///
        /// From `<gssapi/gssapi.h>`:
        /// ```c
        /// OM_uint32 gss_wrap(
        ///     OM_uint32 *minor_status,
        ///     gss_ctx_id_t context_handle,
        ///     int conf_req_flag,
        ///     gss_qop_t qop_req,
        ///     gss_buffer_t input_message_buffer,
        ///     int *conf_state,
        ///     gss_buffer_t output_message_buffer);
        /// ```
        pub fn gss_wrap(
            minor_status: *mut OM_uint32,
            context_handle: gss_ctx_id_t,
            conf_req_flag: ::std::os::raw::c_int,
            qop_req: OM_uint32,
            input_message_buffer: gss_buffer_t,
            conf_state: *mut ::std::os::raw::c_int,
            output_message_buffer: gss_buffer_t,
        ) -> OM_uint32;

        /// Unwrap a message protected by gss_wrap.
        ///
        /// From `<gssapi/gssapi.h>`:
        /// ```c
        /// OM_uint32 gss_unwrap(
        ///     OM_uint32 *minor_status,
        ///     gss_ctx_id_t context_handle,
        ///     gss_buffer_t input_message_buffer,
        ///     gss_buffer_t output_message_buffer,
        ///     int *conf_state,
        ///     gss_qop_t *qop_state);
        /// ```
        pub fn gss_unwrap(
            minor_status: *mut OM_uint32,
            context_handle: gss_ctx_id_t,
            input_message_buffer: gss_buffer_t,
            output_message_buffer: gss_buffer_t,
            conf_state: *mut ::std::os::raw::c_int,
            qop_state: *mut OM_uint32,
        ) -> OM_uint32;
    }
}

// =============================================================================
// GSSAPI status code helpers
// =============================================================================

/// Check whether a GSSAPI major status code indicates an error.
///
/// Equivalent to the C macro `GSS_ERROR(x)` from `<gssapi/gssapi.h>`:
/// ```c
/// #define GSS_ERROR(x) \
///   ((x) & ((0177ul << GSS_C_ROUTINE_ERROR_OFFSET) | \
///            (0177ul << GSS_C_CALLING_ERROR_OFFSET)))
/// ```
///
/// Errors occupy the upper 16 bits of the major status; supplementary info
/// (e.g. `GSS_S_CONTINUE_NEEDED`) occupies the lower 16 bits and is not
/// considered an error.
#[inline]
fn is_gss_error(major: u32) -> bool {
    // Routine errors are in bits 16–23, calling errors in bits 24–31.
    // The mask combines both 7-bit error fields (0o177 = 0x7F per field).
    const ROUTINE_MASK: u32 = 0x7F << 16;
    const CALLING_MASK: u32 = 0x7F << 24;
    major & (ROUTINE_MASK | CALLING_MASK) != 0
}

// =============================================================================
// Consolidated FFI Dispatch
// =============================================================================

/// Enumerates every GSSAPI/Kerberos FFI operation dispatched through one `unsafe` block.
///
/// Each variant corresponds to exactly one GSSAPI or Kerberos C API call (or one
/// unsafe memory operation). Output parameters are passed as raw pointers — callers
/// own the stack variables and pass their addresses. The dispatch function fills
/// them in via the C library call.
#[allow(dead_code)] // Variants needed for API completeness even if not all paths are exercised
enum Krb5Ffi {
    SliceCopy {
        ptr: *const u8,
        len: usize,
    },
    GssDisplayStatus {
        min: *mut u32,
        val: u32,
        stype: i32,
        mech: ffi::gss_OID,
        ctx: *mut u32,
        buf: *mut ffi::gss_buffer_desc_struct,
    },
    GssReleaseBuffer {
        min: *mut u32,
        buf: *mut ffi::gss_buffer_desc_struct,
    },
    GssImportName {
        min: *mut u32,
        buf: *mut ffi::gss_buffer_desc_struct,
        nt: ffi::gss_OID,
        out: *mut ffi::gss_name_t,
    },
    GssDisplayName {
        min: *mut u32,
        name: ffi::gss_name_t,
        buf: *mut ffi::gss_buffer_desc_struct,
        oid: *mut ffi::gss_OID,
    },
    GssReleaseName {
        min: *mut u32,
        name: *mut ffi::gss_name_t,
    },
    GssAcceptSecContext {
        min: *mut u32,
        ctx: *mut ffi::gss_ctx_id_t,
        cred: ffi::gss_cred_id_t,
        input: *mut ffi::gss_buffer_desc_struct,
        src: *mut ffi::gss_name_t,
        mech: *mut ffi::gss_OID,
        output: *mut ffi::gss_buffer_desc_struct,
        flags: *mut u32,
        time: *mut u32,
        del: *mut ffi::gss_cred_id_t,
    },
    GssReleaseCred {
        min: *mut u32,
        cred: *mut ffi::gss_cred_id_t,
    },
    GssDeleteSecContext {
        min: *mut u32,
        ctx: *mut ffi::gss_ctx_id_t,
    },
    GssInquireContext {
        min: *mut u32,
        ctx: ffi::gss_ctx_id_t,
        src: *mut ffi::gss_name_t,
        targ: *mut ffi::gss_name_t,
        life: *mut u32,
        mech: *mut ffi::gss_OID,
        flags: *mut u32,
        local: *mut i32,
        open: *mut i32,
    },
    GssWrap {
        min: *mut u32,
        ctx: ffi::gss_ctx_id_t,
        conf: i32,
        qop: u32,
        input: *mut ffi::gss_buffer_desc_struct,
        cstate: *mut i32,
        output: *mut ffi::gss_buffer_desc_struct,
    },
    GssUnwrap {
        min: *mut u32,
        ctx: ffi::gss_ctx_id_t,
        input: *mut ffi::gss_buffer_desc_struct,
        output: *mut ffi::gss_buffer_desc_struct,
        cstate: *mut i32,
        qop: *mut u32,
    },
    GssAcquireCred {
        min: *mut u32,
        name: ffi::gss_name_t,
        treq: u32,
        mechs: ffi::gss_OID_set,
        usage: std::os::raw::c_int,
        cred: *mut ffi::gss_cred_id_t,
        amechs: *mut ffi::gss_OID_set,
        trec: *mut u32,
    },
    Krb5RegisterAcceptor {
        path: *const libc::c_char,
    },
    Krb5InitContext {
        ctx: *mut ffi::krb5_context,
    },
    Krb5FreeContext {
        ctx: ffi::krb5_context,
    },
    /// Retrieve the GSS_C_NT_HOSTBASED_SERVICE OID constant from the GSSAPI library.
    GetNtHostbasedService,
}

/// Result types returned by the consolidated Kerberos FFI dispatch function.
enum Krb5FfiResult {
    /// GSSAPI OM_uint32 major status code.
    Status(u32),
    /// Kerberos integer return code.
    Code(i32),
    /// Owned byte vector copied from a GSSAPI buffer.
    Bytes(Vec<u8>),
    /// Operation completed (void return or unused status).
    Done,
    /// GSSAPI OID value retrieved from the C library.
    Oid(ffi::gss_OID),
}

/// Consolidated FFI dispatch for all GSSAPI/Kerberos unsafe operations.
///
/// Every unsafe C library interaction in this module is routed through this
/// single function, satisfying AAP §0.7.2's requirement to minimize the total
/// `unsafe` block count. Callers validate pointers and manage handle lifetimes
/// outside the unsafe boundary.
fn krb5_ffi(op: Krb5Ffi) -> Krb5FfiResult {
    // SAFETY: All GSSAPI/Kerberos operations call C library functions through
    // stable ABIs. Each variant's safety depends on the caller providing valid
    // handles and output pointers (documented per-call-site). Handle lifetimes
    // are managed by RAII wrappers (GssName, GssContext, GssCredential, Krb5Context).
    unsafe {
        match op {
            Krb5Ffi::SliceCopy { ptr, len } => {
                Krb5FfiResult::Bytes(std::slice::from_raw_parts(ptr, len).to_vec())
            }
            Krb5Ffi::GssDisplayStatus {
                min,
                val,
                stype,
                mech,
                ctx,
                buf,
            } => Krb5FfiResult::Status(ffi::gss_display_status(min, val, stype, mech, ctx, buf)),
            Krb5Ffi::GssReleaseBuffer { min, buf } => {
                ffi::gss_release_buffer(min, buf);
                Krb5FfiResult::Done
            }
            Krb5Ffi::GssImportName { min, buf, nt, out } => {
                Krb5FfiResult::Status(ffi::gss_import_name(min, buf, nt, out))
            }
            Krb5Ffi::GssDisplayName {
                min,
                name,
                buf,
                oid,
            } => Krb5FfiResult::Status(ffi::gss_display_name(min, name, buf, oid)),
            Krb5Ffi::GssReleaseName { min, name } => {
                ffi::gss_release_name(min, name);
                Krb5FfiResult::Done
            }
            Krb5Ffi::GssAcceptSecContext {
                min,
                ctx,
                cred,
                input,
                src,
                mech,
                output,
                flags,
                time,
                del,
            } => Krb5FfiResult::Status(ffi::gss_accept_sec_context(
                min,
                ctx,
                cred,
                input,
                ptr::null_mut(),
                src,
                mech,
                output,
                flags,
                time,
                del,
            )),
            Krb5Ffi::GssReleaseCred { min, cred } => {
                ffi::gss_release_cred(min, cred);
                Krb5FfiResult::Done
            }
            Krb5Ffi::GssDeleteSecContext { min, ctx } => {
                ffi::gss_delete_sec_context(min, ctx, ptr::null_mut());
                Krb5FfiResult::Done
            }
            Krb5Ffi::GssInquireContext {
                min,
                ctx,
                src,
                targ,
                life,
                mech,
                flags,
                local,
                open,
            } => Krb5FfiResult::Status(ffi::gss_inquire_context(
                min, ctx, src, targ, life, mech, flags, local, open,
            )),
            Krb5Ffi::GssWrap {
                min,
                ctx,
                conf,
                qop,
                input,
                cstate,
                output,
            } => Krb5FfiResult::Status(ffi::gss_wrap(min, ctx, conf, qop, input, cstate, output)),
            Krb5Ffi::GssUnwrap {
                min,
                ctx,
                input,
                output,
                cstate,
                qop,
            } => Krb5FfiResult::Status(ffi::gss_unwrap(min, ctx, input, output, cstate, qop)),
            Krb5Ffi::GssAcquireCred {
                min,
                name,
                treq,
                mechs,
                usage,
                cred,
                amechs,
                trec,
            } => Krb5FfiResult::Status(ffi::gss_acquire_cred(
                min, name, treq, mechs, usage, cred, amechs, trec,
            )),
            Krb5Ffi::Krb5RegisterAcceptor { path } => {
                Krb5FfiResult::Status(ffi::krb5_gss_register_acceptor_identity(path))
            }
            Krb5Ffi::Krb5InitContext { ctx } => Krb5FfiResult::Code(ffi::krb5_init_context(ctx)),
            Krb5Ffi::Krb5FreeContext { ctx } => {
                ffi::krb5_free_context(ctx);
                Krb5FfiResult::Done
            }
            // SAFETY: GSS_C_NT_HOSTBASED_SERVICE is a global GSSAPI OID constant
            // defined in <gssapi/gssapi.h>. It is initialised by the GSSAPI library
            // at load time and never mutated thereafter. Reading its pointer value
            // here is safe as it is only used as an input parameter to
            // gss_import_name inside the krb5_ffi dispatch.
            Krb5Ffi::GetNtHostbasedService => Krb5FfiResult::Oid(ffi::GSS_C_NT_HOSTBASED_SERVICE),
        }
    }
}

// =============================================================================
// GssapiError — Error type for GSSAPI operations
// =============================================================================

/// GSSAPI error with major and minor status codes and a human-readable message.
///
/// Major status codes encode calling errors (bits 24–31), routine errors
/// (bits 16–23), and supplementary info (bits 0–15). Minor status codes
/// are mechanism-specific and provide additional detail.
#[derive(Debug, Clone)]
pub struct GssapiError {
    /// GSSAPI major status code (calling errors bits 24–31, routine errors
    /// bits 16–23, supplementary info bits 0–15).
    pub major: u32,
    /// GSSAPI minor (mechanism-specific) status code providing additional
    /// detail about the failure cause.
    pub minor: u32,
    /// Human-readable error description obtained from `gss_display_status`.
    pub message: String,
}

impl GssapiError {
    /// Create an error from GSSAPI major/minor status codes.
    ///
    /// Calls `gss_display_status` in a loop to convert both the major
    /// (GSS-level) and minor (mechanism-level) status codes into
    /// human-readable messages, then concatenates them.
    pub fn from_status(major: u32, minor: u32) -> Self {
        let mut parts: Vec<String> = Vec::new();

        // Collect major (GSS-level) status messages.
        collect_status_messages(major, ffi::GSS_C_GSS_CODE as i32, &mut parts);

        // Collect minor (mechanism-specific) status messages.
        if minor != 0 {
            collect_status_messages(minor, ffi::GSS_C_MECH_CODE as i32, &mut parts);
        }

        let message = if parts.is_empty() {
            format!("GSSAPI error: major={major:#010x}, minor={minor:#010x}")
        } else {
            parts.join("; ")
        };

        GssapiError {
            major,
            minor,
            message,
        }
    }
}

/// Collect human-readable status messages for a single GSSAPI status value.
///
/// The `gss_display_status` function may produce multiple message fragments
/// for a single status value (indicated by a non-zero `message_context`
/// output). This function loops until all fragments are collected.
fn collect_status_messages(status_value: u32, status_type: i32, out: &mut Vec<String>) {
    let mut msg_ctx: u32 = 0;

    loop {
        let mut min_stat: u32 = 0;
        let mut buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };

        // Dispatch gss_display_status through consolidated FFI.
        let maj = match krb5_ffi(Krb5Ffi::GssDisplayStatus {
            min: &mut min_stat,
            val: status_value,
            stype: status_type,
            mech: ptr::null_mut(),
            ctx: &mut msg_ctx,
            buf: &mut buf,
        }) {
            Krb5FfiResult::Status(s) => s,
            _ => unreachable!(),
        };

        if !is_gss_error(maj) && buf.length > 0 && !buf.value.is_null() {
            // Dispatch slice copy through consolidated FFI.
            let bytes = match krb5_ffi(Krb5Ffi::SliceCopy {
                ptr: buf.value as *const u8,
                len: buf.length,
            }) {
                Krb5FfiResult::Bytes(b) => b,
                _ => unreachable!(),
            };
            let msg = String::from_utf8_lossy(&bytes).into_owned();
            out.push(msg);
        }

        if buf.length > 0 && !buf.value.is_null() {
            let mut release_min: u32 = 0;
            // Dispatch gss_release_buffer through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssReleaseBuffer {
                min: &mut release_min,
                buf: &mut buf,
            });
        }

        // msg_ctx == 0 means all message fragments have been returned.
        if msg_ctx == 0 {
            break;
        }
    }
}

impl fmt::Display for GssapiError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for GssapiError {}

// =============================================================================
// GssName — Safe wrapper around gss_name_t
// =============================================================================

/// Safe wrapper around a GSSAPI name (`gss_name_t`).
///
/// Encapsulates the lifecycle of a GSSAPI internal name, ensuring that
/// `gss_release_name` is called when the name is dropped.
pub struct GssName {
    /// The raw GSSAPI name handle. Null (`GSS_C_NO_NAME`) only after `Drop`.
    name: ffi::gss_name_t,
}

impl GssName {
    /// Import a host-based service name (e.g., `"smtp@mail.example.com"`).
    ///
    /// Calls `gss_import_name` with `GSS_C_NT_HOSTBASED_SERVICE` as the
    /// name type OID, matching the pattern used in
    /// `src/src/auths/heimdal_gssapi.c` lines 256–262.
    ///
    /// # Arguments
    ///
    /// * `service` — Service name (e.g., `"smtp"`)
    /// * `hostname` — Host name (e.g., `"mail.example.com"`)
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_import_name` fails.
    pub fn import_service(service: &str, hostname: &str) -> Result<Self, GssapiError> {
        let name_str = format!("{service}@{hostname}");
        let c_name = CString::new(name_str.as_bytes()).map_err(|_| GssapiError {
            major: 0xFFFF_0000, // Synthetic error — interior NUL byte
            minor: 0,
            message: "Service name contains interior NUL byte".to_string(),
        })?;

        let mut min_stat: u32 = 0;
        let mut output_name: ffi::gss_name_t = ptr::null_mut();
        let mut buf = ffi::gss_buffer_desc_struct {
            length: c_name.as_bytes().len(),
            value: c_name.as_ptr() as *mut libc::c_void,
        };

        // Retrieve the GSS_C_NT_HOSTBASED_SERVICE OID via consolidated dispatch.
        let nt_host = match krb5_ffi(Krb5Ffi::GetNtHostbasedService) {
            Krb5FfiResult::Oid(oid) => oid,
            _ => unreachable!(),
        };
        let maj = match krb5_ffi(Krb5Ffi::GssImportName {
            min: &mut min_stat,
            buf: &mut buf,
            nt: nt_host,
            out: &mut output_name,
        }) {
            Krb5FfiResult::Status(s) => s,
            _ => unreachable!(),
        };

        if is_gss_error(maj) {
            return Err(GssapiError::from_status(maj, min_stat));
        }

        Ok(GssName { name: output_name })
    }

    /// Display the GSSAPI name as a human-readable string.
    ///
    /// Calls `gss_display_name` to convert the internal GSSAPI name
    /// representation into a string, matching the usage in
    /// `src/src/auths/heimdal_gssapi.c` lines 478–488.
    pub fn display(&self) -> Result<String, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };
        let mut oid: ffi::gss_OID = ptr::null_mut();

        // Dispatch gss_display_name through consolidated FFI.
        let maj = match krb5_ffi(Krb5Ffi::GssDisplayName {
            min: &mut min_stat,
            name: self.name,
            buf: &mut buf,
            oid: &mut oid,
        }) {
            Krb5FfiResult::Status(s) => s,
            _ => unreachable!(),
        };

        if is_gss_error(maj) {
            return Err(GssapiError::from_status(maj, min_stat));
        }

        // Extract the string from the GSSAPI buffer (length-delimited, not
        // necessarily null-terminated).
        let result = if buf.length > 0 && !buf.value.is_null() {
            // Dispatch slice copy through consolidated FFI.
            let bytes = match krb5_ffi(Krb5Ffi::SliceCopy {
                ptr: buf.value as *const u8,
                len: buf.length,
            }) {
                Krb5FfiResult::Bytes(b) => b,
                _ => unreachable!(),
            };
            String::from_utf8_lossy(&bytes).into_owned()
        } else {
            String::new()
        };

        // Release the buffer allocated by gss_display_name.
        if buf.length > 0 && !buf.value.is_null() {
            let mut release_min: u32 = 0;
            // Dispatch gss_release_buffer through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssReleaseBuffer {
                min: &mut release_min,
                buf: &mut buf,
            });
        }

        Ok(result)
    }
}

impl Drop for GssName {
    fn drop(&mut self) {
        if !self.name.is_null() {
            let mut min_stat: u32 = 0;
            // Dispatch gss_release_name through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssReleaseName {
                min: &mut min_stat,
                name: &mut self.name,
            });
        }
    }
}

// =============================================================================
// GssContextStepResult — Token exchange outcome
// =============================================================================

/// Result of a single GSSAPI security context establishment step.
///
/// The GSSAPI token exchange is multi-step: the server and client exchange
/// tokens until both sides agree that authentication is complete.
pub enum GssContextStepResult {
    /// More tokens are needed from the client. The contained `Vec<u8>` is the
    /// output token that must be sent back to the client.
    Continue(Vec<u8>),
    /// Authentication is complete. The contained `Vec<u8>` is the final output
    /// token (possibly empty) to send to the client.
    Done(Vec<u8>),
}

// =============================================================================
// GssContext — Safe wrapper around gss_ctx_id_t
// =============================================================================

/// Safe wrapper around a GSSAPI security context (`gss_ctx_id_t`).
///
/// Manages the lifecycle of a GSSAPI security context, ensuring that
/// `gss_delete_sec_context` is called when the context is dropped.
///
/// Usage mirrors the server-side authentication flow in
/// `src/src/auths/heimdal_gssapi.c` lines 227–538.
pub struct GssContext {
    /// The raw GSSAPI context handle. Starts as null (`GSS_C_NO_CONTEXT`)
    /// and is populated by `gss_accept_sec_context`.
    ctx: ffi::gss_ctx_id_t,
}

impl Default for GssContext {
    fn default() -> Self {
        Self::new()
    }
}

impl GssContext {
    /// Create a new empty security context for server-side authentication.
    ///
    /// The context starts in the `GSS_C_NO_CONTEXT` state and is populated
    /// by calling [`accept`](Self::accept) with client tokens.
    pub fn new() -> Self {
        // GSS_C_NO_CONTEXT is defined as ((gss_ctx_id_t) 0) in gssapi.h,
        // which is a null pointer in Rust.
        Self {
            ctx: ptr::null_mut(),
        }
    }

    /// Accept a security context token from the client (server-side).
    ///
    /// Processes one step of the GSSAPI server-side authentication by calling
    /// `gss_accept_sec_context`. This matches the token exchange loop in
    /// `src/src/auths/heimdal_gssapi.c` lines 343–378.
    ///
    /// # Arguments
    ///
    /// * `cred` — Server credentials obtained via [`GssCredential::acquire_accept`].
    /// * `input_token` — Raw token bytes received from the client.
    ///
    /// # Returns
    ///
    /// A tuple of:
    /// - `GssContextStepResult::Continue(token)` if more tokens are needed, or
    ///   `GssContextStepResult::Done(token)` when authentication is complete.
    /// - `Option<GssName>` — The authenticated client identity, present when
    ///   authentication completes (`Done` variant).
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_accept_sec_context` fails.
    pub fn accept(
        &mut self,
        cred: &GssCredential,
        input_token: &[u8],
    ) -> Result<(GssContextStepResult, Option<GssName>), GssapiError> {
        let mut min_stat: u32 = 0;
        let mut src_name: ffi::gss_name_t = ptr::null_mut();
        let mut mech_type: ffi::gss_OID = ptr::null_mut();
        let mut output_buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };
        let mut ret_flags: u32 = 0;
        let mut time_rec: u32 = 0;
        let mut delegated_cred: ffi::gss_cred_id_t = ptr::null_mut();

        // Create a GSSAPI buffer descriptor pointing to the input token bytes.
        // The buffer is read-only from GSSAPI's perspective; the const cast is
        // required by the C API which takes `gss_buffer_t` (pointer to mutable
        // buffer descriptor) even for input buffers.
        let mut input_buf = ffi::gss_buffer_desc_struct {
            length: input_token.len(),
            value: input_token.as_ptr() as *mut libc::c_void,
        };

        // Dispatch gss_accept_sec_context through consolidated FFI.
        let maj = match krb5_ffi(Krb5Ffi::GssAcceptSecContext {
            min: &mut min_stat,
            ctx: &mut self.ctx,
            cred: cred.cred,
            input: &mut input_buf,
            src: &mut src_name,
            mech: &mut mech_type,
            output: &mut output_buf,
            flags: &mut ret_flags,
            time: &mut time_rec,
            del: &mut delegated_cred,
        }) {
            Krb5FfiResult::Status(s) => s,
            _ => unreachable!(),
        };

        // Release any delegated credentials we don't use.
        if !delegated_cred.is_null() {
            let mut rel_min: u32 = 0;
            // Dispatch gss_release_cred through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssReleaseCred {
                min: &mut rel_min,
                cred: &mut delegated_cred,
            });
        }

        if is_gss_error(maj) {
            // If gss_accept_sec_context allocated an output buffer before
            // failing, release it.
            if output_buf.length > 0 && !output_buf.value.is_null() {
                let mut rel_min: u32 = 0;
                // Dispatch gss_release_buffer through consolidated FFI.
                krb5_ffi(Krb5Ffi::GssReleaseBuffer {
                    min: &mut rel_min,
                    buf: &mut output_buf,
                });
            }
            // Release any source name allocated before the error.
            if !src_name.is_null() {
                let mut rel_min: u32 = 0;
                // Dispatch gss_release_name through consolidated FFI.
                krb5_ffi(Krb5Ffi::GssReleaseName {
                    min: &mut rel_min,
                    name: &mut src_name,
                });
            }
            return Err(GssapiError::from_status(maj, min_stat));
        }

        // Copy the output token bytes to an owned Vec before releasing the
        // GSSAPI-managed buffer.
        let output_token = if output_buf.length > 0 && !output_buf.value.is_null() {
            // Dispatch slice copy through consolidated FFI.
            let token = match krb5_ffi(Krb5Ffi::SliceCopy {
                ptr: output_buf.value as *const u8,
                len: output_buf.length,
            }) {
                Krb5FfiResult::Bytes(b) => b,
                _ => unreachable!(),
            };

            let mut rel_min: u32 = 0;
            // Dispatch gss_release_buffer through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssReleaseBuffer {
                min: &mut rel_min,
                buf: &mut output_buf,
            });

            token
        } else {
            Vec::new()
        };

        // Wrap the source name if it was returned.
        let client_name = if !src_name.is_null() {
            Some(GssName { name: src_name })
        } else {
            None
        };

        // Determine whether authentication is complete or continuing.
        let step_result = if maj == ffi::GSS_S_COMPLETE {
            GssContextStepResult::Done(output_token)
        } else {
            // GSS_S_CONTINUE_NEEDED (or other supplementary info)
            GssContextStepResult::Continue(output_token)
        };

        Ok((step_result, client_name))
    }

    /// Query the authenticated client name from a completed security context.
    ///
    /// Calls `gss_inquire_context` to retrieve the source (client) name from
    /// a fully established security context. This is an alternative to
    /// capturing the source name from the final [`accept`](Self::accept) call.
    pub fn inquire_source_name(&self) -> Result<GssName, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut src_name: ffi::gss_name_t = ptr::null_mut();
        let mut targ_name: ffi::gss_name_t = ptr::null_mut();
        let mut lifetime: u32 = 0;
        let mut mech_type: ffi::gss_OID = ptr::null_mut();
        let mut ctx_flags: u32 = 0;
        let mut locally_initiated: i32 = 0;
        let mut open: i32 = 0;

        // Dispatch gss_inquire_context through consolidated FFI.
        let maj = match krb5_ffi(Krb5Ffi::GssInquireContext {
            min: &mut min_stat,
            ctx: self.ctx,
            src: &mut src_name,
            targ: &mut targ_name,
            life: &mut lifetime,
            mech: &mut mech_type,
            flags: &mut ctx_flags,
            local: &mut locally_initiated,
            open: &mut open,
        }) {
            Krb5FfiResult::Status(s) => s,
            _ => unreachable!(),
        };

        // Release the target name — we only need the source name.
        if !targ_name.is_null() {
            let mut rel_min: u32 = 0;
            // Dispatch gss_release_name through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssReleaseName {
                min: &mut rel_min,
                name: &mut targ_name,
            });
        }

        if is_gss_error(maj) {
            // Release source name on error if it was partially allocated.
            if !src_name.is_null() {
                let mut rel_min: u32 = 0;
                // Dispatch gss_release_name through consolidated FFI.
                krb5_ffi(Krb5Ffi::GssReleaseName {
                    min: &mut rel_min,
                    name: &mut src_name,
                });
            }
            return Err(GssapiError::from_status(maj, min_stat));
        }

        if src_name.is_null() {
            return Err(GssapiError {
                major: 0,
                minor: 0,
                message: "gss_inquire_context returned null source name".to_string(),
            });
        }

        Ok(GssName { name: src_name })
    }

    /// Wrap a message with integrity and optional confidentiality protection.
    ///
    /// Wraps the input message using `gss_wrap()` on a fully established
    /// security context. Used for the SASL GSSAPI security-layer negotiation
    /// where the server sends wrapped capability bytes to the client.
    ///
    /// Replaces the `gss_wrap()` call at `heimdal_gssapi.c` line 393.
    ///
    /// # Arguments
    ///
    /// * `message` — The plaintext message bytes to wrap.
    /// * `confidential` — If `true`, request confidentiality (encryption).
    ///   If `false`, request integrity protection only.
    ///
    /// # Returns
    ///
    /// The wrapped message as a `Vec<u8>`.
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_wrap()` fails.
    pub fn wrap(&self, message: &[u8], confidential: bool) -> Result<Vec<u8>, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut conf_state: i32 = 0;
        let mut output_buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };
        let mut input_buf = ffi::gss_buffer_desc_struct {
            length: message.len(),
            value: message.as_ptr() as *mut libc::c_void,
        };

        let conf_req = if confidential { 1 } else { 0 };

        // Dispatch gss_wrap through consolidated FFI.
        let maj = match krb5_ffi(Krb5Ffi::GssWrap {
            min: &mut min_stat,
            ctx: self.ctx,
            conf: conf_req,
            qop: 0, // GSS_C_QOP_DEFAULT
            input: &mut input_buf,
            cstate: &mut conf_state,
            output: &mut output_buf,
        }) {
            Krb5FfiResult::Status(s) => s,
            _ => unreachable!(),
        };

        if is_gss_error(maj) {
            if output_buf.length > 0 && !output_buf.value.is_null() {
                let mut rel_min: u32 = 0;
                // Dispatch gss_release_buffer through consolidated FFI.
                krb5_ffi(Krb5Ffi::GssReleaseBuffer {
                    min: &mut rel_min,
                    buf: &mut output_buf,
                });
            }
            return Err(GssapiError::from_status(maj, min_stat));
        }

        // Copy the wrapped bytes and release the GSSAPI-managed buffer.
        let result = if output_buf.length > 0 && !output_buf.value.is_null() {
            // Dispatch slice copy through consolidated FFI.
            let token = match krb5_ffi(Krb5Ffi::SliceCopy {
                ptr: output_buf.value as *const u8,
                len: output_buf.length,
            }) {
                Krb5FfiResult::Bytes(b) => b,
                _ => unreachable!(),
            };

            let mut rel_min: u32 = 0;
            // Dispatch gss_release_buffer through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssReleaseBuffer {
                min: &mut rel_min,
                buf: &mut output_buf,
            });
            token
        } else {
            Vec::new()
        };

        Ok(result)
    }

    /// Unwrap a message protected by gss_wrap.
    ///
    /// Unwraps the input token using `gss_unwrap()` on a fully established
    /// security context. Used for the SASL GSSAPI security-layer negotiation
    /// where the server unwraps the client's security-layer choice response.
    ///
    /// Replaces the `gss_unwrap()` call at `heimdal_gssapi.c` line 423.
    ///
    /// # Arguments
    ///
    /// * `token` — The wrapped message bytes to unwrap.
    ///
    /// # Returns
    ///
    /// The unwrapped plaintext message as a `Vec<u8>`.
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_unwrap()` fails.
    pub fn unwrap(&self, token: &[u8]) -> Result<Vec<u8>, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut conf_state: i32 = 0;
        let mut qop_state: u32 = 0;
        let mut output_buf = ffi::gss_buffer_desc_struct {
            length: 0,
            value: ptr::null_mut(),
        };
        let mut input_buf = ffi::gss_buffer_desc_struct {
            length: token.len(),
            value: token.as_ptr() as *mut libc::c_void,
        };

        // Dispatch gss_unwrap through consolidated FFI.
        let maj = match krb5_ffi(Krb5Ffi::GssUnwrap {
            min: &mut min_stat,
            ctx: self.ctx,
            input: &mut input_buf,
            output: &mut output_buf,
            cstate: &mut conf_state,
            qop: &mut qop_state,
        }) {
            Krb5FfiResult::Status(s) => s,
            _ => unreachable!(),
        };

        if is_gss_error(maj) {
            if output_buf.length > 0 && !output_buf.value.is_null() {
                let mut rel_min: u32 = 0;
                // Dispatch gss_release_buffer through consolidated FFI.
                krb5_ffi(Krb5Ffi::GssReleaseBuffer {
                    min: &mut rel_min,
                    buf: &mut output_buf,
                });
            }
            return Err(GssapiError::from_status(maj, min_stat));
        }

        // Copy the unwrapped bytes and release the GSSAPI-managed buffer.
        let result = if output_buf.length > 0 && !output_buf.value.is_null() {
            // Dispatch slice copy through consolidated FFI.
            let token = match krb5_ffi(Krb5Ffi::SliceCopy {
                ptr: output_buf.value as *const u8,
                len: output_buf.length,
            }) {
                Krb5FfiResult::Bytes(b) => b,
                _ => unreachable!(),
            };

            let mut rel_min: u32 = 0;
            // Dispatch gss_release_buffer through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssReleaseBuffer {
                min: &mut rel_min,
                buf: &mut output_buf,
            });
            token
        } else {
            Vec::new()
        };

        Ok(result)
    }
}

impl Drop for GssContext {
    fn drop(&mut self) {
        if !self.ctx.is_null() {
            let mut min_stat: u32 = 0;
            // Dispatch gss_delete_sec_context through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssDeleteSecContext {
                min: &mut min_stat,
                ctx: &mut self.ctx,
            });
        }
    }
}

// =============================================================================
// GssCredential — Safe wrapper around gss_cred_id_t
// =============================================================================

/// Safe wrapper around a GSSAPI credential (`gss_cred_id_t`).
///
/// Manages the lifecycle of server-side GSSAPI credentials, ensuring that
/// `gss_release_cred` is called when the credential is dropped.
pub struct GssCredential {
    /// The raw GSSAPI credential handle.
    cred: ffi::gss_cred_id_t,
}

impl GssCredential {
    /// Acquire server (acceptor) credentials for the given service name.
    ///
    /// Calls `gss_acquire_cred` with `GSS_C_ACCEPT` usage to obtain
    /// server credentials for the specified service principal. This matches
    /// the credential acquisition in `src/src/auths/heimdal_gssapi.c`
    /// lines 278–289.
    ///
    /// # Arguments
    ///
    /// * `name` — The service name to acquire credentials for, typically
    ///   created via [`GssName::import_service`].
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `gss_acquire_cred` fails (e.g., keytab not
    /// found, principal not in keytab).
    pub fn acquire_accept(name: &GssName) -> Result<Self, GssapiError> {
        let mut min_stat: u32 = 0;
        let mut cred: ffi::gss_cred_id_t = ptr::null_mut();

        // Dispatch gss_acquire_cred through consolidated FFI.
        let maj = match krb5_ffi(Krb5Ffi::GssAcquireCred {
            min: &mut min_stat,
            name: name.name,
            treq: 0,                                         // default lifetime
            mechs: ptr::null_mut(),                          // GSS_C_NULL_OID_SET
            usage: ffi::GSS_C_ACCEPT as std::os::raw::c_int, // GSS_C_ACCEPT
            cred: &mut cred,
            amechs: ptr::null_mut(), // not needed
            trec: ptr::null_mut(),   // not needed
        }) {
            Krb5FfiResult::Status(s) => s,
            _ => unreachable!(),
        };

        if is_gss_error(maj) {
            return Err(GssapiError::from_status(maj, min_stat));
        }

        Ok(GssCredential { cred })
    }
}

impl Drop for GssCredential {
    fn drop(&mut self) {
        if !self.cred.is_null() {
            let mut min_stat: u32 = 0;
            // Dispatch gss_release_cred through consolidated FFI.
            krb5_ffi(Krb5Ffi::GssReleaseCred {
                min: &mut min_stat,
                cred: &mut self.cred,
            });
        }
    }
}

// =============================================================================
// register_acceptor_identity — Keytab registration
// =============================================================================

/// Register a keytab file for GSSAPI acceptor (server) identity.
///
/// Sets the keytab that will be used for server-side GSSAPI authentication.
/// This wraps the Heimdal/MIT function `gsskrb5_register_acceptor_identity`
/// (which is a macro aliasing `krb5_gss_register_acceptor_identity`).
///
/// Matches the keytab registration in `src/src/auths/heimdal_gssapi.c`
/// lines 268–276.
///
/// # Arguments
///
/// * `keytab_path` — Filesystem path to the Kerberos keytab file.
///
/// # Errors
///
/// Returns `GssapiError` if the keytab registration fails.
pub fn register_acceptor_identity(keytab_path: &str) -> Result<(), GssapiError> {
    let c_path = CString::new(keytab_path).map_err(|_| GssapiError {
        major: 0xFFFF_0000,
        minor: 0,
        message: "Keytab path contains interior NUL byte".to_string(),
    })?;

    // Dispatch krb5_gss_register_acceptor_identity through consolidated FFI.
    let maj = match krb5_ffi(Krb5Ffi::Krb5RegisterAcceptor {
        path: c_path.as_ptr(),
    }) {
        Krb5FfiResult::Status(s) => s,
        _ => unreachable!(),
    };

    if is_gss_error(maj) {
        // This function has no minor status output, so use 0.
        return Err(GssapiError::from_status(maj, 0));
    }

    Ok(())
}

// =============================================================================
// Krb5Context — Minimal Kerberos 5 context for diagnostics
// =============================================================================

/// Minimal Kerberos 5 context for diagnostics and error reporting.
///
/// Wraps `krb5_context` to provide a safe initialization/teardown lifecycle.
/// Used by the `heimdal_gssapi` authenticator's init function for keytab
/// enumeration and debug output (see `src/src/auths/heimdal_gssapi.c`
/// lines 119–201).
pub struct Krb5Context {
    /// The raw Kerberos 5 context handle.
    ctx: ffi::krb5_context,
}

impl Krb5Context {
    /// Initialize a new Kerberos 5 library context.
    ///
    /// Calls `krb5_init_context` to create a Kerberos library context
    /// suitable for error message formatting and keytab diagnostics.
    ///
    /// # Errors
    ///
    /// Returns `GssapiError` if `krb5_init_context` fails (e.g., Kerberos
    /// configuration is missing or malformed).
    pub fn new() -> Result<Self, GssapiError> {
        let mut ctx: ffi::krb5_context = ptr::null_mut();

        // Dispatch krb5_init_context through consolidated FFI.
        let rc = match krb5_ffi(Krb5Ffi::Krb5InitContext { ctx: &mut ctx }) {
            Krb5FfiResult::Code(c) => c,
            _ => unreachable!(),
        };

        if rc != 0 {
            return Err(GssapiError {
                major: 0,
                minor: rc as u32,
                message: format!("krb5_init_context failed with error code {rc}"),
            });
        }

        if ctx.is_null() {
            return Err(GssapiError {
                major: 0,
                minor: 0,
                message: "krb5_init_context returned null context".to_string(),
            });
        }

        Ok(Krb5Context { ctx })
    }
}

impl Drop for Krb5Context {
    fn drop(&mut self) {
        if !self.ctx.is_null() {
            // Dispatch krb5_free_context through consolidated FFI.
            krb5_ffi(Krb5Ffi::Krb5FreeContext { ctx: self.ctx });
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gss_error_detection() {
        // GSS_S_COMPLETE (0) is not an error.
        assert!(!is_gss_error(ffi::GSS_S_COMPLETE));

        // GSS_S_CONTINUE_NEEDED (1) is supplementary info, not an error.
        assert!(!is_gss_error(ffi::GSS_S_CONTINUE_NEEDED));

        // A routine error in bits 16–23 should be detected.
        assert!(is_gss_error(1 << 16));

        // A calling error in bits 24–31 should be detected.
        assert!(is_gss_error(1 << 24));

        // Combined routine + supplementary is still an error.
        assert!(is_gss_error((1 << 16) | ffi::GSS_S_CONTINUE_NEEDED));
    }

    #[test]
    fn test_gssapi_error_display() {
        let err = GssapiError {
            major: 0x000D_0000,
            minor: 0,
            message: "test error message".to_string(),
        };
        assert_eq!(format!("{err}"), "test error message");
    }

    #[test]
    fn test_gssapi_error_debug() {
        let err = GssapiError::from_status(0, 0);
        // With both codes zero, from_status should produce a fallback message.
        let debug = format!("{err:?}");
        assert!(debug.contains("GssapiError"));
    }

    #[test]
    fn test_context_step_result_variants() {
        let cont = GssContextStepResult::Continue(vec![1, 2, 3]);
        match cont {
            GssContextStepResult::Continue(data) => assert_eq!(data, vec![1, 2, 3]),
            GssContextStepResult::Done(_) => panic!("Expected Continue variant"),
        }

        let done = GssContextStepResult::Done(vec![4, 5]);
        match done {
            GssContextStepResult::Done(data) => assert_eq!(data, vec![4, 5]),
            GssContextStepResult::Continue(_) => panic!("Expected Done variant"),
        }
    }

    #[test]
    fn test_gss_context_new() {
        let ctx = GssContext::new();
        // The context should start as GSS_C_NO_CONTEXT (null pointer).
        assert!(ctx.ctx.is_null());
        // Drop should be safe on a null context.
        drop(ctx);
    }
}
