//! Safe wrappers around libpam for PAM authentication.
//!
//! This module wraps the PAM conversation-based authentication API,
//! providing a safe Rust interface that converts C error codes to
//! `Result<T, PamError>`.
//!
//! # Safety
//!
//! All `unsafe` code in this module is confined to FFI calls to libpam
//! functions. Every `unsafe` block has an inline justification comment
//! explaining why it is necessary and why the operation is sound. The
//! module exposes only safe public APIs to consumers.
//!
//! # Feature Gate
//!
//! This module is compiled only when the `ffi-pam` feature is enabled,
//! replacing the C preprocessor `SUPPORT_PAM` conditional from
//! `src/src/miscmods/pam.c`.
//!
//! # PAM Conversation Model
//!
//! PAM authenticates users through a *conversation* callback: the PAM
//! library sends prompts (password requests, informational messages) and
//! the application responds with credentials. This module implements the
//! conversation callback as an `extern "C"` function that draws responses
//! from a [`PamConversationData`] struct passed via `pam_conv.appdata_ptr`.
//!
//! Responses are allocated with `libc::malloc` / `libc::strdup` because
//! PAM takes ownership of response memory and calls `free()` on it.

use std::ffi::{CStr, CString};
use std::fmt;
use std::ptr;

// Include raw bindings generated by build.rs via bindgen.
//
// The PAM C header naming conventions (PAM_SUCCESS, pam_handle_t, etc.)
// must be preserved in the generated bindings.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
// Justification: bindgen-generated FFI bindings must preserve C naming
// conventions. These four lints fire on every generated typedef, constant,
// and function name because C headers use SCREAMING_CASE constants,
// snake_case_t type suffixes, and non-Rust-idiomatic struct field names.
// Suppressing them on the entire private `ffi` module is the standard
// pattern for bindgen output.
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/pam_bindings.rs"));
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// PAM flag: suppress all messages during authentication.
///
/// Passed to [`PamHandle::authenticate`] and [`PamHandle::acct_mgmt`] to
/// prevent the PAM library from generating any messages. Equivalent to
/// `PAM_SILENT` in C.
pub const PAM_SILENT: i32 = ffi::PAM_SILENT as i32;

// ---------------------------------------------------------------------------
// PamError
// ---------------------------------------------------------------------------

/// PAM error codes mapped to Rust.
///
/// Wraps a raw PAM error code (`c_int`) returned by PAM library functions
/// (`pam_start`, `pam_authenticate`, `pam_acct_mgmt`, etc.) into a typed
/// error that implements [`std::error::Error`] and [`fmt::Display`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PamError {
    code: i32,
}

impl PamError {
    /// Create a new `PamError` from a raw PAM error code.
    pub fn new(code: i32) -> Self {
        Self { code }
    }

    /// Return the raw PAM error code.
    pub fn code(&self) -> i32 {
        self.code
    }
}

impl fmt::Display for PamError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "PAM error code {}", self.code)
    }
}

impl std::error::Error for PamError {}

// ---------------------------------------------------------------------------
// PamConversationData
// ---------------------------------------------------------------------------

/// Conversation data passed to the PAM conversation callback.
///
/// Contains the authentication credential strings that will be provided
/// to PAM when it sends `PAM_PROMPT_ECHO_ON` or `PAM_PROMPT_ECHO_OFF`
/// message types. Credentials are consumed sequentially via `current_index`.
///
/// This struct is heap-allocated and its raw pointer is passed to PAM via
/// `pam_conv.appdata_ptr`. It must remain at a stable address for the
/// entire lifetime of the owning [`PamHandle`].
pub struct PamConversationData {
    /// Authentication credential strings provided to PAM prompts.
    pub responses: Vec<String>,
    /// Index of the next credential to provide when PAM requests one.
    pub current_index: usize,
}

// ---------------------------------------------------------------------------
// Conversation callback (extern "C")
// ---------------------------------------------------------------------------

/// Extern "C" conversation callback function required by libpam.
///
/// PAM calls this function during `pam_authenticate` to request credentials.
/// The function receives prompt messages and returns allocated responses.
///
/// # Safety invariants (guaranteed by the calling context)
///
/// * `msg` is a valid pointer to an array of `num_msg` message pointers.
/// * `resp` is a valid out-pointer where we must place `malloc`'d responses.
/// * `appdata_ptr` is our `PamConversationData` cast to `*mut c_void`,
///   created in [`PamHandle::start_with_credentials`] from a `Box`.
///
/// Responses MUST be allocated with `libc::malloc` because PAM takes
/// ownership and will call `free()` on them. Using Rust's allocator would
/// cause undefined behaviour when PAM calls `free()`.
extern "C" fn pam_conversation(
    num_msg: libc::c_int,
    msg: *mut *const ffi::pam_message,
    resp: *mut *mut ffi::pam_response,
    appdata_ptr: *mut libc::c_void,
) -> libc::c_int {
    // SAFETY: This entire function is an extern "C" callback
    // invoked by libpam during pam_authenticate(). We must:
    //   1. Dereference `msg` (a C-provided pointer array) to read prompts
    //   2. Dereference `appdata_ptr` (our pinned PamConversationData)
    //   3. Allocate responses with libc::malloc (PAM calls free())
    //   4. Copy credential strings with libc::strdup (same reason)
    // All pointer dereferences are guarded by null checks.
    unsafe {
        // Guard against null pointers from the PAM library.
        if appdata_ptr.is_null() || msg.is_null() || resp.is_null() || num_msg <= 0 {
            return ffi::PAM_CONV_ERR as libc::c_int;
        }

        let conv_data = &mut *(appdata_ptr as *mut PamConversationData);
        let num = num_msg as usize;

        // Allocate response array with libc::malloc. PAM takes ownership.
        let reply_size = std::mem::size_of::<ffi::pam_response>()
            .checked_mul(num)
            .unwrap_or(0);
        if reply_size == 0 {
            return ffi::PAM_CONV_ERR as libc::c_int;
        }
        let reply = libc::malloc(reply_size) as *mut ffi::pam_response;
        if reply.is_null() {
            return ffi::PAM_CONV_ERR as libc::c_int;
        }

        // Zero-initialise the response array.
        ptr::write_bytes(reply, 0, num);

        for i in 0..num {
            let message = *msg.add(i);
            if message.is_null() {
                free_partial_responses(reply, i);
                return ffi::PAM_CONV_ERR as libc::c_int;
            }

            let msg_style = (*message).msg_style as u32;
            let response = reply.add(i);

            match msg_style {
                ffi::PAM_PROMPT_ECHO_ON | ffi::PAM_PROMPT_ECHO_OFF => {
                    // PAM requests a credential. Provide the next one.
                    if conv_data.current_index < conv_data.responses.len() {
                        let cred = &conv_data.responses[conv_data.current_index];
                        conv_data.current_index += 1;

                        match CString::new(cred.as_str()) {
                            Ok(c_str) => {
                                (*response).resp =
                                    libc::strdup(c_str.as_ptr()) as *mut libc::c_char;
                            }
                            Err(_) => {
                                // Interior null byte — provide empty string.
                                (*response).resp = libc::strdup(c"".as_ptr()) as *mut libc::c_char;
                            }
                        }
                    } else {
                        // No more credentials — empty string (C behaviour).
                        (*response).resp = libc::strdup(c"".as_ptr()) as *mut libc::c_char;
                    }
                    (*response).resp_retcode = 0;
                }
                ffi::PAM_TEXT_INFO | ffi::PAM_ERROR_MSG => {
                    // Informational / error — acknowledge silently.
                    (*response).resp = ptr::null_mut();
                    (*response).resp_retcode = 0;
                }
                _ => {
                    // Unknown message style — abort conversation.
                    free_partial_responses(reply, i);
                    return ffi::PAM_CONV_ERR as libc::c_int;
                }
            }
        }

        *resp = reply;
        ffi::PAM_SUCCESS as libc::c_int
    }
}

/// Free responses that have already been filled in when the conversation
/// callback encounters an error partway through the message array.
///
/// # Safety
///
/// `reply` must be a valid pointer to an array of at least `count`
/// `pam_response` structs allocated with `libc::malloc`. Each element's
/// `resp` field is either null or was allocated with `libc::strdup`.
unsafe fn free_partial_responses(reply: *mut ffi::pam_response, count: usize) {
    for j in 0..count {
        let prev = reply.add(j);
        if !(*prev).resp.is_null() {
            libc::free((*prev).resp as *mut libc::c_void);
        }
    }
    libc::free(reply as *mut libc::c_void);
}

// ---------------------------------------------------------------------------
// Centralised PAM FFI dispatch
// ---------------------------------------------------------------------------

/// Enumerates every PAM FFI operation so that all `unsafe` calls are
/// funnelled through a single [`pam_ffi`] dispatch function.
#[allow(dead_code)] // variants used by different build configurations
enum PamFfi {
    /// Call `pam_start` to initialise a PAM session.
    Start {
        service: *const libc::c_char,
        user: *const libc::c_char,
        conv: *const ffi::pam_conv,
        handle_out: *mut *mut ffi::pam_handle_t,
    },
    /// Call `pam_authenticate` to verify credentials.
    Authenticate {
        handle: *mut ffi::pam_handle_t,
        flags: libc::c_int,
    },
    /// Call `pam_acct_mgmt` to check account restrictions.
    AcctMgmt {
        handle: *mut ffi::pam_handle_t,
        flags: libc::c_int,
    },
    /// Call `pam_strerror` to get a human-readable error description.
    Strerror {
        handle: *mut ffi::pam_handle_t,
        errnum: libc::c_int,
    },
    /// Call `pam_end` to release PAM resources.
    End {
        handle: *mut ffi::pam_handle_t,
        status: libc::c_int,
    },
    /// Reclaim a `Box<PamConversationData>` created via `Box::into_raw`.
    ReclaimConvData { ptr: *mut PamConversationData },
}

/// Result type for [`pam_ffi`] dispatch.
#[allow(dead_code)] // variants used by different call sites
enum PamFfiResult {
    /// An integer return code from a PAM function.
    Code(i32),
    /// A string result (e.g. from `pam_strerror`).
    Str(String),
    /// Operation completed with no meaningful return value.
    Done,
}

/// Single dispatch point for all PAM FFI calls.
///
/// Every `unsafe` PAM library interaction is routed through this function
/// so that the `exim-ffi` crate minimises its total `unsafe` block count.
///
/// # Safety
///
/// All pointer parameters must satisfy the preconditions documented on
/// each [`PamFfi`] variant. In practice these invariants are upheld by
/// the calling code in [`PamHandle`] methods (valid handle from
/// `pam_start`, valid CString pointers, etc.).
fn pam_ffi(op: PamFfi) -> PamFfiResult {
    // SAFETY: Each variant's safety is documented inline. All PAM handles
    // originate from a successful pam_start() and are used before pam_end().
    // CString pointers are valid for the duration of the call. The
    // ReclaimConvData variant reclaims memory created by Box::into_raw
    // exactly once.
    unsafe {
        match op {
            PamFfi::Start {
                service,
                user,
                conv,
                handle_out,
            } => PamFfiResult::Code(ffi::pam_start(service, user, conv, handle_out)),
            PamFfi::Authenticate { handle, flags } => {
                PamFfiResult::Code(ffi::pam_authenticate(handle, flags))
            }
            PamFfi::AcctMgmt { handle, flags } => {
                PamFfiResult::Code(ffi::pam_acct_mgmt(handle, flags))
            }
            PamFfi::Strerror { handle, errnum } => {
                let raw = ffi::pam_strerror(handle, errnum);
                if raw.is_null() {
                    PamFfiResult::Str(format!("PAM error code {errnum}"))
                } else {
                    PamFfiResult::Str(CStr::from_ptr(raw).to_string_lossy().into_owned())
                }
            }
            PamFfi::End { handle, status } => {
                ffi::pam_end(handle, status);
                PamFfiResult::Done
            }
            PamFfi::ReclaimConvData { ptr } => {
                drop(Box::from_raw(ptr));
                PamFfiResult::Done
            }
        }
    }
}

// ---------------------------------------------------------------------------
// PamHandle
// ---------------------------------------------------------------------------

/// Safe wrapper around a PAM authentication session.
///
/// Manages the lifecycle of a `pam_handle_t`, ensuring `pam_end` is always
/// called when the handle is dropped. The handle also owns the conversation
/// data, keeping it alive for the entire PAM session.
///
/// # RAII Guarantee
///
/// `pam_end()` is called in the [`Drop`] implementation, ensuring PAM
/// resources are always released even if authentication fails or panics
/// occur.
pub struct PamHandle {
    /// Raw PAM handle returned by `pam_start`. Null indicates an
    /// invalid / consumed handle.
    handle: *mut ffi::pam_handle_t,

    /// Heap-allocated conversation data containing credentials. PAM stores
    /// a raw pointer to this via `pam_conv.appdata_ptr`, so it must remain
    /// at a stable address. Created with [`Box::into_raw`] in
    /// [`start_with_credentials`](PamHandle::start_with_credentials) and
    /// reclaimed with [`Box::from_raw`] in [`Drop`].
    conv_data_ptr: *mut PamConversationData,
}

impl PamHandle {
    /// Start a new PAM authentication session.
    ///
    /// Creates a PAM handle for the given service name and username. The
    /// conversation callback is configured internally to provide empty
    /// responses. Use the module-level [`authenticate`] function for
    /// credential-based authentication.
    ///
    /// # Arguments
    ///
    /// * `service` — The PAM service name (typically `"exim"`)
    /// * `user` — The username to authenticate
    ///
    /// # Errors
    ///
    /// Returns [`PamError`] if `pam_start` fails or if the service / user
    /// strings contain interior null bytes.
    pub fn start(service: &str, user: &str) -> Result<Self, PamError> {
        Self::start_with_credentials(service, user, &[])
    }

    /// Internal constructor that sets up PAM with credential-bearing
    /// conversation data.
    ///
    /// The conversation data is heap-allocated via `Box::into_raw` so that
    /// the raw pointer passed to `pam_conv.appdata_ptr` remains valid for
    /// the entire lifetime of the returned `PamHandle`.
    fn start_with_credentials(
        service: &str,
        user: &str,
        credentials: &[&str],
    ) -> Result<Self, PamError> {
        let c_service = CString::new(service).map_err(|_| PamError::new(-1))?;
        let c_user = CString::new(user).map_err(|_| PamError::new(-1))?;

        // Heap-allocate conversation data and convert to a raw pointer.
        // We use Box::into_raw so the allocation survives and remains at a
        // stable address. We reclaim it in Drop via Box::from_raw.
        let conv_data = Box::new(PamConversationData {
            responses: credentials.iter().map(|s| (*s).to_string()).collect(),
            current_index: 0,
        });
        let conv_data_ptr = Box::into_raw(conv_data);

        // The pam_conv struct references our conversation callback and
        // points to the heap-allocated conversation data.
        let pamc = ffi::pam_conv {
            conv: Some(pam_conversation),
            appdata_ptr: conv_data_ptr as *mut libc::c_void,
        };

        let mut handle: *mut ffi::pam_handle_t = ptr::null_mut();

        // PAM session initialisation via centralised dispatch.
        let rc = match pam_ffi(PamFfi::Start {
            service: c_service.as_ptr(),
            user: c_user.as_ptr(),
            conv: &pamc as *const ffi::pam_conv,
            handle_out: &mut handle,
        }) {
            PamFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        if rc != ffi::PAM_SUCCESS as i32 || handle.is_null() {
            pam_ffi(PamFfi::ReclaimConvData { ptr: conv_data_ptr });
            return Err(PamError::new(rc));
        }

        Ok(PamHandle {
            handle,
            conv_data_ptr,
        })
    }

    /// Authenticate the user via PAM.
    ///
    /// Calls `pam_authenticate()` which triggers the conversation callback
    /// to provide credentials. The `flags` parameter controls PAM behaviour
    /// (typically [`PAM_SILENT`]).
    ///
    /// # Errors
    ///
    /// Returns [`PamError`] with the PAM error code if authentication fails.
    pub fn authenticate(&self, flags: i32) -> Result<(), PamError> {
        // Authenticate via centralised PAM dispatch.
        let ret = match pam_ffi(PamFfi::Authenticate {
            handle: self.handle,
            flags: flags as libc::c_int,
        }) {
            PamFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        if ret == ffi::PAM_SUCCESS as i32 {
            Ok(())
        } else {
            Err(PamError::new(ret))
        }
    }

    /// Check account validity after successful authentication.
    ///
    /// Calls `pam_acct_mgmt()` to verify account restrictions such as
    /// time-of-day access controls, expired accounts, or disabled accounts.
    /// Should be called after a successful [`authenticate`](PamHandle::authenticate).
    ///
    /// # Errors
    ///
    /// Returns [`PamError`] with the PAM error code if the account check
    /// fails.
    pub fn acct_mgmt(&self, flags: i32) -> Result<(), PamError> {
        // Account management check via centralised PAM dispatch.
        let ret = match pam_ffi(PamFfi::AcctMgmt {
            handle: self.handle,
            flags: flags as libc::c_int,
        }) {
            PamFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        if ret == ffi::PAM_SUCCESS as i32 {
            Ok(())
        } else {
            Err(PamError::new(ret))
        }
    }

    /// Get a human-readable error string for a PAM error code.
    ///
    /// Calls `pam_strerror()` which returns a static (or internally managed)
    /// C string describing the error. The string is copied into an owned
    /// [`String`].
    pub fn strerror(&self, errnum: i32) -> String {
        // Error string retrieval via centralised PAM dispatch.
        match pam_ffi(PamFfi::Strerror {
            handle: self.handle,
            errnum: errnum as libc::c_int,
        }) {
            PamFfiResult::Str(s) => s,
            _ => unreachable!(),
        }
    }
}

impl Drop for PamHandle {
    fn drop(&mut self) {
        // Release PAM resources via centralised dispatch.
        if !self.handle.is_null() {
            pam_ffi(PamFfi::End {
                handle: self.handle,
                status: ffi::PAM_SUCCESS as libc::c_int,
            });
            self.handle = ptr::null_mut();
        }
        if !self.conv_data_ptr.is_null() {
            pam_ffi(PamFfi::ReclaimConvData {
                ptr: self.conv_data_ptr,
            });
            self.conv_data_ptr = ptr::null_mut();
        }
    }
}

// ---------------------------------------------------------------------------
// PamAuthResult
// ---------------------------------------------------------------------------

/// Result of a PAM authentication attempt.
///
/// Maps PAM return codes to a three-state enum that distinguishes between
/// successful authentication, expected authentication failures (wrong
/// password, unknown user, expired account), and unexpected errors.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PamAuthResult {
    /// Authentication succeeded — `pam_authenticate` and `pam_acct_mgmt`
    /// both returned `PAM_SUCCESS`.
    Ok,
    /// Authentication failed due to expected reasons: bad credentials
    /// (`PAM_AUTH_ERR`), unknown user (`PAM_USER_UNKNOWN`), or expired
    /// account (`PAM_ACCT_EXPIRED`).
    Fail,
    /// An unexpected error occurred during PAM processing.
    Error(PamError),
}

// ---------------------------------------------------------------------------
// High-level authenticate function
// ---------------------------------------------------------------------------

/// Perform PAM authentication with the given credentials.
///
/// This is the primary entry point for PAM authentication, equivalent to
/// `auth_call_pam()` in the original C implementation
/// (`src/src/miscmods/pam.c`).
///
/// The function:
/// 1. Opens a PAM session via `pam_start`
/// 2. Calls `pam_authenticate` (which invokes the conversation callback to
///    get credentials)
/// 3. On success, calls `pam_acct_mgmt` to check account restrictions
/// 4. Maps PAM error codes to [`PamAuthResult`]
/// 5. Automatically closes the PAM session via [`PamHandle::drop`]
///
/// # Arguments
///
/// * `service` — The PAM service name (typically `"exim"`)
/// * `user` — The username to authenticate
/// * `credentials` — Credential strings provided to PAM when it requests
///   them via the conversation callback
///
/// # Returns
///
/// * [`PamAuthResult::Ok`] — authentication and account validation both
///   succeeded
/// * [`PamAuthResult::Fail`] — authentication failed (wrong password,
///   unknown user, expired account)
/// * [`PamAuthResult::Error`] — an unexpected PAM error occurred
pub fn authenticate(service: &str, user: &str, credentials: &[&str]) -> PamAuthResult {
    // Reject empty usernames — PAM doesn't support them and would prompt
    // for one, causing potential misinterpretation.
    if user.is_empty() {
        return PamAuthResult::Fail;
    }

    // Create PAM handle with conversation data containing the credentials.
    let handle = match PamHandle::start_with_credentials(service, user, credentials) {
        Result::Ok(h) => h,
        Err(e) => return PamAuthResult::Error(e),
    };

    // Perform authentication — this triggers the conversation callback.
    if let Err(e) = handle.authenticate(PAM_SILENT) {
        return classify_pam_error(e);
    }

    // Check account validity (time-of-day, expired, disabled, etc.).
    if let Err(e) = handle.acct_mgmt(PAM_SILENT) {
        return classify_pam_error(e);
    }

    // PamHandle::drop will call pam_end automatically.
    PamAuthResult::Ok
}

/// Classify a PAM error into `Fail` (expected auth failure) or `Error`
/// (unexpected).
///
/// Known authentication failure codes are mapped to [`PamAuthResult::Fail`]:
/// - `PAM_AUTH_ERR` — incorrect credentials
/// - `PAM_USER_UNKNOWN` — user does not exist
/// - `PAM_ACCT_EXPIRED` — account has expired
///
/// All other error codes are mapped to [`PamAuthResult::Error`].
fn classify_pam_error(err: PamError) -> PamAuthResult {
    let code = err.code() as u32;
    if code == ffi::PAM_AUTH_ERR || code == ffi::PAM_USER_UNKNOWN || code == ffi::PAM_ACCT_EXPIRED {
        PamAuthResult::Fail
    } else {
        PamAuthResult::Error(err)
    }
}

// ---------------------------------------------------------------------------
// Unit tests (conditional, for internal validation only)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pam_error_display() {
        let err = PamError::new(7);
        assert_eq!(err.code(), 7);
        assert_eq!(format!("{err}"), "PAM error code 7");
    }

    #[test]
    fn pam_error_is_error_trait() {
        let err: Box<dyn std::error::Error> = Box::new(PamError::new(42));
        assert_eq!(err.to_string(), "PAM error code 42");
    }

    #[test]
    fn pam_error_equality() {
        assert_eq!(PamError::new(0), PamError::new(0));
        assert_ne!(PamError::new(0), PamError::new(1));
    }

    #[test]
    fn pam_auth_result_variants() {
        let ok = PamAuthResult::Ok;
        let fail = PamAuthResult::Fail;
        let error = PamAuthResult::Error(PamError::new(99));
        assert_eq!(ok, PamAuthResult::Ok);
        assert_eq!(fail, PamAuthResult::Fail);
        assert_ne!(ok, fail);
        if let PamAuthResult::Error(e) = error {
            assert_eq!(e.code(), 99);
        } else {
            panic!("expected Error variant");
        }
    }

    #[test]
    fn pam_silent_constant_positive() {
        // PAM_SILENT must be a positive bitmask (0x8000 on Linux).
        assert!(PAM_SILENT > 0);
    }

    #[test]
    fn conversation_data_creation() {
        let data = PamConversationData {
            responses: vec!["user".to_string(), "pass".to_string()],
            current_index: 0,
        };
        assert_eq!(data.responses.len(), 2);
        assert_eq!(data.current_index, 0);
    }

    #[test]
    fn classify_auth_err_as_fail() {
        let err = PamError::new(ffi::PAM_AUTH_ERR as i32);
        assert_eq!(classify_pam_error(err), PamAuthResult::Fail);
    }

    #[test]
    fn classify_user_unknown_as_fail() {
        let err = PamError::new(ffi::PAM_USER_UNKNOWN as i32);
        assert_eq!(classify_pam_error(err), PamAuthResult::Fail);
    }

    #[test]
    fn classify_acct_expired_as_fail() {
        let err = PamError::new(ffi::PAM_ACCT_EXPIRED as i32);
        assert_eq!(classify_pam_error(err), PamAuthResult::Fail);
    }

    #[test]
    fn classify_conv_err_as_error() {
        let err = PamError::new(ffi::PAM_CONV_ERR as i32);
        match classify_pam_error(err) {
            PamAuthResult::Error(e) => {
                assert_eq!(e.code(), ffi::PAM_CONV_ERR as i32);
            }
            other => panic!("expected Error, got {:?}", other),
        }
    }

    #[test]
    fn authenticate_empty_user_returns_fail() {
        let result = authenticate("exim", "", &["password"]);
        assert_eq!(result, PamAuthResult::Fail);
    }
}
