//! Safe wrappers around the embedded Perl interpreter (libperl).
//!
//! Provides a managed [`PerlInterpreter`] that supports:
//! - Interpreter startup with configured options
//! - Adding Perl code blocks for evaluation
//! - Calling Perl functions with arguments and capturing return values
//!
//! This wraps the Perl C API: `perl_alloc`, `perl_construct`, `perl_parse`,
//! `perl_run`, `Perl_eval_pv`, `Perl_call_pv`, `perl_destruct`, `perl_free`.
//!
//! Perl embedding is inherently FFI — there is NO viable Rust-native
//! replacement (AAP §0.6.2).
//!
//! # Safety Model
//!
//! All `unsafe` blocks are confined to this module within the `exim-ffi` crate
//! (the ONLY crate permitted to contain unsafe code per AAP §0.7.2). Each
//! `unsafe` block has an inline justification comment. The raw
//! `*mut ffi::PerlInterpreter` pointer is wrapped in an RAII struct whose
//! [`Drop`] implementation calls `perl_destruct` and `perl_free`.
//!
//! # Source Context
//!
//! This module replaces the C implementation in:
//! - `src/src/miscmods/perl.c` (345 lines — embedded Perl integration)
//! - `src/src/miscmods/perl_api.h` (17 lines — function table entry numbers)

use std::ffi::CString;
use std::fmt;
use std::ptr;

// =============================================================================
// Raw FFI Bindings
// =============================================================================

/// Raw FFI bindings generated by bindgen from Perl headers (`perl.h`,
/// `EXTERN.h`, `XSUB.h`) and C macro wrapper functions compiled via `cc`.
///
/// The C wrapper functions (`exim_ffi_SvPV`, `exim_ffi_ERRSV`, etc.) expand
/// deeply nested Perl macros into callable C functions. See `build.rs`
/// `generate_perl_bindings()` for the complete wrapper source and allowlist.
///
/// Perl headers define types like `PerlInterpreter`, `SV`, `CV`, constants
/// like `G_SCALAR`, `G_EVAL`, and functions like `perl_alloc`, `Perl_eval_pv`
/// that use C naming patterns.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unnecessary_transmutes,
    clippy::upper_case_acronyms,
    clippy::unreadable_literal,
    clippy::useless_transmute,
    clippy::ptr_offset_with_cast,
    clippy::too_many_arguments
)]
// Justification: bindgen-generated FFI bindings must preserve C naming
// conventions from Perl headers. Perl defines types (`PerlInterpreter`, `SV`,
// `CV`), constants (`G_SCALAR`, `G_EVAL`), and functions (`perl_alloc`,
// `Perl_eval_pv`) using C conventions. Suppressing these lints is standard
// practice for machine-generated FFI code and does not hide logic errors.
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/perl_bindings.rs"));

    // =========================================================================
    // boot_DynaLoader — not present in bindgen output because it is declared
    // via `EXTERN_C` in application code (perl.c line 52), not in the standard
    // Perl headers parsed by bindgen. We declare it manually with the exact
    // signature matching the Perl XSUBADDR_t convention with MULTIPLICITY.
    // =========================================================================
    unsafe extern "C" {
        /// Bootstrap function for the DynaLoader XS extension module.
        ///
        /// This symbol is provided by the Perl DynaLoader shared object at
        /// link time. It is registered via `Perl_newXS` during interpreter
        /// startup to enable dynamic loading of Perl XS modules.
        ///
        /// Source: `src/src/miscmods/perl.c` line 52:
        /// `EXTERN_C void boot_DynaLoader(pTHX_ CV *cv);`
        pub fn boot_DynaLoader(my_perl: *mut PerlInterpreter, cv: *mut CV);
    }
}

// =============================================================================
// PerlError — Error type for Perl interpreter operations
// =============================================================================

/// Error from the Perl interpreter.
///
/// Wraps an error message from the Perl interpreter, typically obtained from
/// `$@` (ERRSV) after a failed eval or function call, or from a lifecycle
/// operation failure (allocation, parse, run).
///
/// Implements [`std::fmt::Display`] and [`std::error::Error`] for integration
/// with Rust's error handling ecosystem.
#[derive(Debug, Clone)]
pub struct PerlError {
    /// Human-readable error message from the Perl interpreter.
    message: String,
}

impl PerlError {
    /// Create a new [`PerlError`] with the given message.
    ///
    /// Accepts any type that implements `Into<String>`, including `&str`,
    /// `String`, and formatted strings.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// use exim_ffi::perl::PerlError;
    /// let err = PerlError::new("syntax error at line 1");
    /// assert_eq!(err.to_string(), "Perl error: syntax error at line 1");
    /// ```
    pub fn new(msg: impl Into<String>) -> Self {
        Self {
            message: msg.into(),
        }
    }

    /// Returns the error message as a string slice.
    pub fn message(&self) -> &str {
        &self.message
    }
}

impl fmt::Display for PerlError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Perl error: {}", self.message)
    }
}

impl std::error::Error for PerlError {}

// =============================================================================
// PerlInterpreter — Safe wrapper around embedded Perl
// =============================================================================

/// Safe wrapper around an embedded Perl interpreter instance.
///
/// Manages the full lifecycle: allocation, construction, parsing startup code,
/// running, evaluating code blocks, calling functions, destruction, and freeing.
///
/// # Lifecycle
///
/// 1. [`PerlInterpreter::new()`] — allocates and constructs the interpreter
/// 2. [`PerlInterpreter::startup()`] — parses startup arguments and initializes
/// 3. [`PerlInterpreter::add_code_block()`] — evaluates Perl code blocks
/// 4. [`PerlInterpreter::call_function()`] — calls named Perl subroutines
/// 5. [`Drop`] — automatically destructs and frees on scope exit
///
/// # Thread Safety
///
/// A `PerlInterpreter` is NOT thread-safe. Each OS thread that needs Perl
/// must create its own interpreter. This type intentionally does NOT implement
/// `Send` or `Sync` (enforced by the raw pointer field).
///
/// # Source Context
///
/// Mirrors the lifecycle managed by `interp_perl` and `exim_perl_init` /
/// `call_perl_cat` / `exim_cleanup_perl` in `src/src/miscmods/perl.c`.
pub struct PerlInterpreter {
    /// Raw pointer to the C `PerlInterpreter` struct. Non-null for a valid,
    /// initialized interpreter; set to null after `perl_free` in [`Drop`].
    interp: *mut ffi::PerlInterpreter,
}

impl PerlInterpreter {
    /// Allocate and construct a new Perl interpreter.
    ///
    /// Calls `perl_alloc()` to allocate memory for the interpreter, then
    /// `perl_construct()` to initialize it. After creation, call [`startup()`]
    /// to parse initial code before using [`add_code_block()`] or
    /// [`call_function()`].
    ///
    /// # Errors
    ///
    /// Returns [`PerlError`] if `perl_alloc` returns a null pointer
    /// (allocation failure — extremely rare, typically means the system
    /// is out of memory).
    ///
    /// # Source Context
    ///
    /// Mirrors `perl_alloc()` + `perl_construct()` in `perl.c` lines 199-200.
    pub fn new() -> Result<Self, PerlError> {
        // Safety justification: calling perl_alloc to allocate a new Perl
        // interpreter instance, then perl_construct to initialize its internal
        // structures. perl_alloc is the documented entry point for embedding
        // Perl (perlapi(1)) and returns either a valid pointer or null on
        // failure. perl_construct requires a non-null pointer from perl_alloc
        // which is guaranteed by the null check.
        unsafe {
            let interp = ffi::perl_alloc();
            if interp.is_null() {
                return Err(PerlError::new(
                    "perl_alloc returned null: failed to allocate Perl interpreter",
                ));
            }
            ffi::perl_construct(interp);
            Ok(Self { interp })
        }
    }

    /// Parse and run Perl startup code.
    ///
    /// `args` are the equivalent of command-line arguments to `perl`.
    /// This calls `perl_parse()` with DynaLoader registration via the
    /// [`xs_init_callback`] and `perl_run()`.
    ///
    /// Typical usage mirrors `exim_perl_init` in `perl.c` lines 186-202:
    /// ```ignore
    /// let mut interp = PerlInterpreter::new()?;
    /// interp.startup(&["exim-perl", "/dev/null"])?;
    /// // Or with taint mode:
    /// interp.startup(&["exim-perl", "-T", "/dev/null"])?;
    /// ```
    ///
    /// # Errors
    ///
    /// Returns [`PerlError`] if:
    /// - Any argument string contains a null byte
    /// - `perl_parse` returns a non-zero exit code
    /// - `perl_run` returns a non-zero exit code
    pub fn startup(&mut self, args: &[&str]) -> Result<(), PerlError> {
        // Convert Rust string slices to null-terminated C strings.
        let c_args: Vec<CString> = args
            .iter()
            .map(|a| {
                CString::new(*a).map_err(|e| PerlError::new(format!("null byte in argument: {e}")))
            })
            .collect::<Result<Vec<_>, _>>()?;

        // Build the argv pointer array. perl_parse requires a mutable pointer
        // array terminated by a null pointer, matching C's (argc, argv) pattern.
        let mut c_ptrs: Vec<*mut libc::c_char> = c_args
            .iter()
            .map(|s| s.as_ptr() as *mut libc::c_char)
            .collect();
        c_ptrs.push(ptr::null_mut());

        let argc = c_args.len() as libc::c_int;

        // Safety justification: calling perl_parse on a valid interpreter with
        // the xs_init_callback for DynaLoader registration. The argc/argv
        // array is built from CStrings that remain alive for the duration of
        // this call (owned by c_args Vec). The null-terminated c_ptrs array
        // matches the C (argc, argv) convention. perl_run is called on a
        // successfully parsed interpreter. Both functions are documented in
        // perlapi(1) and perlembed(1).
        unsafe {
            let parse_result = ffi::perl_parse(
                self.interp,
                Some(xs_init_callback),
                argc,
                c_ptrs.as_mut_ptr(),
                ptr::null_mut(),
            );
            if parse_result != 0 {
                return Err(PerlError::new(format!(
                    "perl_parse failed with exit code {parse_result}"
                )));
            }

            let run_result = ffi::perl_run(self.interp);
            if run_result != 0 {
                return Err(PerlError::new(format!(
                    "perl_run failed with exit code {run_result}"
                )));
            }
        }

        Ok(())
    }

    /// Add a block of Perl code to the interpreter for evaluation.
    ///
    /// Evaluates the given Perl code string via `Perl_eval_pv`. Returns
    /// `Ok(())` on success, or `Err(PerlError)` with the error message from
    /// `$@` (ERRSV) on failure.
    ///
    /// After evaluation, the locale is reset to `"C"` to prevent Perl modules
    /// from affecting the process locale (matching the C implementation
    /// behavior in `perl.c` line 83).
    ///
    /// # Source Context
    ///
    /// Mirrors `exim_perl_add_codeblock` in `perl.c` lines 60-86. The C
    /// implementation uses `perl_eval_sv` with `G_SCALAR|G_DISCARD|G_KEEPERR`;
    /// we use `Perl_eval_pv` which provides equivalent functionality with a
    /// simpler string-based API. Error checking via ERRSV is identical.
    ///
    /// # Errors
    ///
    /// Returns [`PerlError`] if:
    /// - The code string contains a null byte
    /// - Perl evaluation fails (syntax error, runtime error, `die`)
    pub fn add_code_block(&mut self, code: &str) -> Result<(), PerlError> {
        let c_code = CString::new(code)
            .map_err(|e| PerlError::new(format!("null byte in code string: {e}")))?;

        // Safety justification: calling Perl_eval_pv to evaluate a Perl code
        // string on a valid interpreter. The code is a null-terminated CString.
        // croak_on_error is 0 so errors are captured in $@ (ERRSV) rather
        // than triggering a C longjmp/croak. After evaluation, we check ERRSV
        // for errors via exim_ffi_ERRSV and exim_ffi_SvPV (C macro wrappers),
        // then reset the locale to "C" with libc::setlocale (matching perl.c
        // line 83: `setlocale(LC_ALL, "C")`).
        unsafe {
            ffi::Perl_eval_pv(self.interp, c_code.as_ptr(), 0);

            // Check $@ for errors.
            let err = self.extract_errsv_error();

            // Reset locale to "C" regardless of success/failure.
            libc::setlocale(libc::LC_ALL, c"C".as_ptr());

            err
        }
    }

    /// Call a named Perl function with string arguments.
    ///
    /// Returns the string result from the Perl function, or an error.
    ///
    /// Arguments are passed as single-quoted Perl string literals with proper
    /// escaping of `'` and `\` characters (the only two characters that
    /// require escaping inside Perl single quotes).
    ///
    /// # Implementation Note
    ///
    /// Uses `Perl_eval_pv` to construct and evaluate a Perl expression rather
    /// than the lower-level `Perl_call_pv` + stack manipulation macros
    /// (`PUSHMARK`, `XPUSHs`, `PUTBACK`, `SPAGAIN`, `POPs`, etc.) because
    /// those macros cannot be called directly from Rust — they expand to
    /// deeply nested C preprocessor expressions that access thread-local Perl
    /// interpreter state. The `eval_pv` approach is functionally equivalent
    /// for the Exim use case where arguments are always strings.
    ///
    /// # Source Context
    ///
    /// Mirrors `call_perl_cat` in `perl.c` lines 276-320. The C version uses
    /// `perl_call_pv(name, G_SCALAR|G_EVAL)` with explicit Perl stack
    /// manipulation.
    ///
    /// # Errors
    ///
    /// Returns [`PerlError`] if:
    /// - The function name or any argument contains a null byte
    /// - The Perl function call raises an error (`die`/`croak`)
    /// - The interpreter has not been started
    pub fn call_function(&mut self, func_name: &str, args: &[&str]) -> Result<String, PerlError> {
        if self.interp.is_null() {
            return Err(PerlError::new("the Perl interpreter has not been started"));
        }

        // Construct a Perl expression: func_name('arg1', 'arg2', ...)
        // Arguments are single-quoted with proper escaping.
        let escaped_args: Vec<String> = args.iter().map(|a| escape_perl_single_quote(a)).collect();
        let expr = if escaped_args.is_empty() {
            format!("scalar({func_name}())")
        } else {
            format!("scalar({func_name}({}))", escaped_args.join(","))
        };

        let c_expr = CString::new(expr)
            .map_err(|e| PerlError::new(format!("null byte in expression: {e}")))?;

        // Safety justification: calling Perl_eval_pv to evaluate the function
        // call expression, then checking ERRSV ($@) for errors, extracting the
        // string result via exim_ffi_SvPV, and resetting the locale to "C".
        // The interpreter pointer is valid (non-null checked above). The
        // expression is a valid null-terminated CString. croak_on_error is 0
        // so errors go to $@. The returned SV* is valid for the duration of
        // the current Perl scope. exim_ffi_SvPV safely expands the SvPV macro
        // and returns a pointer into the SV's string buffer; we immediately
        // copy the bytes into an owned Rust String. std::slice::from_raw_parts
        // is safe because we verify ptr is non-null and len > 0 first.
        unsafe {
            let sv = ffi::Perl_eval_pv(self.interp, c_expr.as_ptr(), 0);

            // Check $@ for errors.
            let err = self.extract_errsv_error();
            if err.is_err() {
                libc::setlocale(libc::LC_ALL, c"C".as_ptr());
                return err.map(|()| String::new());
            }

            // Extract string result from the returned SV.
            let result = if sv.is_null() {
                String::new()
            } else {
                let mut len: usize = 0;
                let raw_ptr = ffi::exim_ffi_SvPV(self.interp, sv, &mut len);
                if raw_ptr.is_null() || len == 0 {
                    String::new()
                } else {
                    let bytes = std::slice::from_raw_parts(raw_ptr as *const u8, len);
                    String::from_utf8_lossy(bytes).into_owned()
                }
            };

            // Reset locale to "C" (matching perl.c line 318).
            libc::setlocale(libc::LC_ALL, c"C".as_ptr());

            Ok(result)
        }
    }

    /// Extract an error from Perl's `$@` (ERRSV) if present.
    ///
    /// Returns `Ok(())` if `$@` is empty (no error), or `Err(PerlError)` with
    /// the error message if `$@` contains a non-empty string.
    ///
    /// # Safety
    ///
    /// Caller must ensure `self.interp` is a valid, initialized Perl
    /// interpreter pointer. This function calls `exim_ffi_ERRSV` and
    /// `exim_ffi_SvPV` which are compiled C wrapper functions that safely
    /// expand Perl macros (ERRSV, SvPV) on the given interpreter.
    unsafe fn extract_errsv_error(&self) -> Result<(), PerlError> {
        let err_sv = ffi::exim_ffi_ERRSV(self.interp);
        if err_sv.is_null() {
            return Ok(());
        }

        let mut err_len: usize = 0;
        let err_ptr = ffi::exim_ffi_SvPV(self.interp, err_sv, &mut err_len);
        if err_len > 0 && !err_ptr.is_null() {
            let bytes = std::slice::from_raw_parts(err_ptr as *const u8, err_len);
            let err_msg = String::from_utf8_lossy(bytes).into_owned();
            return Err(PerlError::new(err_msg));
        }

        Ok(())
    }
}

impl Drop for PerlInterpreter {
    fn drop(&mut self) {
        if !self.interp.is_null() {
            // Safety justification: calling perl_destruct and perl_free to
            // cleanly shut down and deallocate the Perl interpreter. This is
            // the documented cleanup sequence for embedded Perl (perlembed(1))
            // and must happen exactly once per interpreter instance. The
            // pointer is set to null afterwards to prevent double-free.
            // perl_destruct returns a status code that we intentionally ignore
            // during cleanup (matching the C code in perl.c lines 263-268
            // where exim_cleanup_perl discards the return value).
            unsafe {
                ffi::perl_destruct(self.interp);
                ffi::perl_free(self.interp);
            }
            self.interp = ptr::null_mut();
        }
    }
}

// =============================================================================
// XS Initialization Callback
// =============================================================================

/// XS initialization callback passed to `perl_parse`.
///
/// Called by the Perl runtime during interpreter startup to register built-in
/// XS functions. Registers DynaLoader to enable dynamic Perl module loading.
///
/// # Source Context
///
/// Mirrors the `xs_init` function in `perl.c` lines 170-179. The C version
/// registers DynaLoader plus four Exim-specific XS functions (`Exim::expand_string`,
/// `Exim::debug_write`, `Exim::log_write`, `Exim::dns_lookup`). We register
/// only DynaLoader here because the Exim-specific functions require access to
/// Exim internals and are registered at a higher level in the `exim-miscmods`
/// crate, not in the FFI layer.
///
/// # Safety
///
/// This function is called by the Perl runtime during `perl_parse`. The
/// `my_perl` parameter is a valid interpreter being initialized. The function
/// is `unsafe extern "C"` because it is a C callback invoked by the Perl
/// library.
unsafe extern "C" fn xs_init_callback(my_perl: *mut ffi::PerlInterpreter) {
    // Register DynaLoader bootstrap function for XS module support.
    // "DynaLoader::boot_DynaLoader" is the standard name that Perl's
    // DynaLoader module expects to find for its bootstrap entry point.
    let name = c"DynaLoader::boot_DynaLoader";
    let file = c"exim-ffi/src/perl.rs";
    ffi::Perl_newXS(
        my_perl,
        name.as_ptr(),
        Some(ffi::boot_DynaLoader),
        file.as_ptr(),
    );
}

// =============================================================================
// DynaLoader Registration Helper
// =============================================================================

/// Register the DynaLoader boot function needed for XS module loading.
///
/// This is a crate-internal helper that can be used to register DynaLoader
/// on an existing interpreter, for example when setting up a custom
/// `xs_init` callback that needs to register additional XS functions
/// alongside DynaLoader.
///
/// In normal usage, DynaLoader is automatically registered via the
/// [`xs_init_callback`] during [`PerlInterpreter::startup()`].
///
/// # Errors
///
/// Returns [`PerlError`] if the interpreter pointer is null.
#[allow(dead_code)]
// Justification: This is a crate-internal helper for registering DynaLoader on
// an existing interpreter from other FFI modules. It is not currently called
// within exim-ffi but is provided as a reusable building block for future XS
// registration patterns (e.g., when a custom xs_init needs to register both
// DynaLoader and Exim-specific XS functions).
pub(crate) fn register_dynaloader(interp: &mut PerlInterpreter) -> Result<(), PerlError> {
    if interp.interp.is_null() {
        return Err(PerlError::new(
            "cannot register DynaLoader: interpreter is null",
        ));
    }

    // Safety justification: calling Perl_newXS to register the DynaLoader
    // boot function on a valid interpreter. The interpreter pointer is
    // guaranteed non-null by the check above. The name and file byte
    // literals are compile-time constant null-terminated strings.
    // boot_DynaLoader is a symbol provided by the Perl DynaLoader
    // shared object at link time.
    unsafe {
        let name = c"DynaLoader::boot_DynaLoader";
        let file = c"exim-ffi/src/perl.rs";
        ffi::Perl_newXS(
            interp.interp,
            name.as_ptr(),
            Some(ffi::boot_DynaLoader),
            file.as_ptr(),
        );
    }

    Ok(())
}

// =============================================================================
// Helper Functions
// =============================================================================

/// Escape a string for use as a Perl single-quoted string literal.
///
/// In Perl, single-quoted strings only require escaping of two characters:
/// - `\` (backslash) → `\\`
/// - `'` (single quote) → `\'`
///
/// All other characters (including `$`, `@`, `%`, `{`, `}`, newlines, etc.)
/// are treated as literal characters inside single quotes.
///
/// The result is wrapped in single quotes: `'escaped_content'`.
///
/// This is used by [`PerlInterpreter::call_function()`] to safely pass
/// string arguments to Perl functions via `Perl_eval_pv`.
///
/// # Examples
///
/// ```ignore
/// assert_eq!(escape_perl_single_quote("hello"), "'hello'");
/// assert_eq!(escape_perl_single_quote("it's"), "'it\\'s'");
/// assert_eq!(escape_perl_single_quote("a\\b"), "'a\\\\b'");
/// assert_eq!(escape_perl_single_quote("$var"), "'$var'");
/// ```
fn escape_perl_single_quote(s: &str) -> String {
    // Pre-allocate with room for the two surrounding quotes plus a small
    // margin for escape sequences.
    let mut result = String::with_capacity(s.len() + 4);
    result.push('\'');
    for ch in s.chars() {
        match ch {
            '\'' => result.push_str("\\'"),
            '\\' => result.push_str("\\\\"),
            _ => result.push(ch),
        }
    }
    result.push('\'');
    result
}

// =============================================================================
// Unit Tests (cfg(test) — not compiled in production)
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_perl_error_new_and_display() {
        let err = PerlError::new("test error message");
        assert_eq!(err.message(), "test error message");
        assert_eq!(err.to_string(), "Perl error: test error message");
    }

    #[test]
    fn test_perl_error_from_string() {
        let err = PerlError::new(String::from("dynamic error"));
        assert_eq!(err.message(), "dynamic error");
    }

    #[test]
    fn test_perl_error_clone() {
        let err1 = PerlError::new("clone test");
        let err2 = err1.clone();
        assert_eq!(err1.message(), err2.message());
    }

    #[test]
    fn test_perl_error_debug() {
        let err = PerlError::new("debug test");
        let debug_str = format!("{err:?}");
        assert!(debug_str.contains("debug test"));
    }

    #[test]
    fn test_perl_error_is_std_error() {
        let err = PerlError::new("std error test");
        // Verify that PerlError implements std::error::Error
        let _: &dyn std::error::Error = &err;
    }

    #[test]
    fn test_escape_empty() {
        assert_eq!(escape_perl_single_quote(""), "''");
    }

    #[test]
    fn test_escape_no_special() {
        assert_eq!(escape_perl_single_quote("hello world"), "'hello world'");
    }

    #[test]
    fn test_escape_single_quote() {
        assert_eq!(escape_perl_single_quote("it's"), "'it\\'s'");
    }

    #[test]
    fn test_escape_backslash() {
        assert_eq!(escape_perl_single_quote("a\\b"), "'a\\\\b'");
    }

    #[test]
    fn test_escape_both() {
        assert_eq!(
            escape_perl_single_quote("it's a\\path"),
            "'it\\'s a\\\\path'"
        );
    }

    #[test]
    fn test_escape_dollar_not_interpolated() {
        // Single quotes in Perl do NOT interpolate $variables.
        assert_eq!(escape_perl_single_quote("$var"), "'$var'");
    }

    #[test]
    fn test_escape_at_not_interpolated() {
        // Single quotes in Perl do NOT interpolate @arrays.
        assert_eq!(escape_perl_single_quote("@arr"), "'@arr'");
    }

    #[test]
    fn test_escape_unicode() {
        assert_eq!(escape_perl_single_quote("héllo"), "'héllo'");
    }

    #[test]
    fn test_escape_newlines() {
        // Newlines are literal in single-quoted strings.
        assert_eq!(escape_perl_single_quote("a\nb"), "'a\nb'");
    }
}
