//! Safe wrappers around RADIUS authentication libraries.
//!
//! Supports three C library variants behind a unified safe Rust API:
//!
//! - **radlib** (FreeBSD's `libradius`) — selected when `radius_lib_radlib` cfg is set
//!   by the build script upon detecting `<radlib.h>`.
//! - **freeradiusclient** (modern radiusclient API) — selected when `radius_lib_radiusclient`
//!   cfg is set upon detecting `<freeradius-client.h>`.
//! - **radiusclient** (legacy radiusclient API) — also uses `radius_lib_radiusclient` cfg
//!   upon detecting `<radiusclient.h>`.
//!
//! The build script (`exim-ffi/build.rs`) performs header detection at compile time,
//! generates bindgen FFI bindings into `OUT_DIR/radius_bindings.rs`, and sets exactly
//! one of the two `cfg` attributes (`radius_lib_radlib` or `radius_lib_radiusclient`).
//!
//! The safe API exposes:
//! - [`RadiusClient`] — RAII handle wrapping the library lifecycle (open → authenticate → close)
//! - [`authenticate()`] — Convenience function combining client creation and authentication
//! - [`RadiusAuthResult`] — Typed enum mapping C return codes to Rust variants
//! - [`RadiusError`] — Error type for failed operations
//!
//! # Safety Policy (AAP §0.7.2)
//!
//! Every `unsafe` block has an inline justification comment. Raw C pointers are
//! confined to the [`RadiusClient`] struct which implements [`Drop`] for RAII cleanup.
//! All string parameters are converted to [`CString`] before crossing the FFI boundary.
//!
//! [`CString`]: std::ffi::CString

use std::ffi::CString;
use std::fmt;

// CStr is only used in the radlib code path for rad_strerror() result parsing
#[cfg(radius_lib_radlib)]
use std::ffi::CStr;

// ── Raw FFI Bindings (generated by build.rs via bindgen) ────────────────────
//
// The build script detects the installed RADIUS library header, generates
// bindings via bindgen with an appropriate allowlist, and writes the output
// to `$OUT_DIR/radius_bindings.rs`. The allowlist includes:
//
//   radlib: rad_auth_open, rad_close, rad_config, rad_create_request,
//           rad_put_string, rad_put_int, rad_send_request, rad_strerror,
//           rad_handle type
//
//   radiusclient/freeradiusclient: rc_read_config, rc_read_dictionary,
//           rc_avpair_add, rc_auth, rc_openlog, rc_conf_str,
//           rc_handle type, VALUE_PAIR type,
//           PW_USER_NAME, PW_USER_PASSWORD, PW_SERVICE_TYPE,
//           PW_AUTHENTICATE_ONLY constants

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
// Justification: bindgen-generated FFI bindings must preserve C naming conventions
// from the RADIUS library headers (radlib.h / freeradius-client.h / radiusclient.h).
// dead_code is allowed because not all generated symbols may be used in the safe wrapper.
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/radius_bindings.rs"));
}

// ── RADIUS Result Code Constants ────────────────────────────────────────────
//
// These constants map C preprocessor defines that may not be captured by
// bindgen's allowlist. They are defined explicitly for each library variant
// to ensure correctness regardless of header parsing behavior.

/// radiusclient / freeradiusclient authentication result codes returned by `rc_auth()`.
///
/// Values sourced from `<freeradius-client.h>` / `<radiusclient.h>`:
///   `OK_RC = 0`, `TIMEOUT_RC = 1`, `REJECT_RC = 2`, `ERROR_RC = 3`, `BADRESP_RC = 4`
#[cfg(radius_lib_radiusclient)]
mod rc_result_codes {
    /// Authentication succeeded.
    pub const OK_RC: libc::c_int = 0;
    /// RADIUS server did not respond within the configured timeout.
    pub const TIMEOUT_RC: libc::c_int = 1;
    /// Authentication rejected by the RADIUS server.
    pub const REJECT_RC: libc::c_int = 2;
    /// Generic error during authentication exchange.
    pub const ERROR_RC: libc::c_int = 3;
    /// Unexpected or malformed response from RADIUS server.
    pub const BADRESP_RC: libc::c_int = 4;
}

/// radlib (FreeBSD) RADIUS attribute type constants and request/response codes.
///
/// Values sourced from `<radlib.h>`:
///   `RAD_ACCESS_REQUEST = 1`, `RAD_ACCESS_ACCEPT = 2`, `RAD_ACCESS_REJECT = 3`
///   Attribute types follow RFC 2865 numbering.
#[cfg(radius_lib_radlib)]
mod radlib_codes {
    /// RADIUS Access-Request packet type (RFC 2865 §4.1).
    pub const RAD_ACCESS_REQUEST: libc::c_int = 1;
    /// RADIUS Access-Accept response — authentication succeeded (RFC 2865 §4.2).
    pub const RAD_ACCESS_ACCEPT: libc::c_int = 2;
    /// RADIUS Access-Reject response — authentication failed (RFC 2865 §4.3).
    pub const RAD_ACCESS_REJECT: libc::c_int = 3;
    /// User-Name attribute (RFC 2865 §5.1).
    pub const RAD_USER_NAME: libc::c_int = 1;
    /// User-Password attribute (RFC 2865 §5.2).
    pub const RAD_USER_PASSWORD: libc::c_int = 2;
    /// NAS-Identifier attribute (RFC 2865 §5.32).
    pub const RAD_NAS_IDENTIFIER: libc::c_int = 32;
    /// Service-Type attribute (RFC 2865 §5.6).
    pub const RAD_SERVICE_TYPE: libc::c_int = 6;
    /// Authenticate-Only service type value (RFC 2865 §5.6).
    pub const RAD_AUTHENTICATE_ONLY: libc::c_int = 8;
}

// ── Error Type ──────────────────────────────────────────────────────────────

/// RADIUS authentication error.
///
/// Wraps error messages from the underlying C RADIUS library (radlib's
/// `rad_strerror`, or radiusclient error conditions) into a Rust error type
/// implementing [`std::error::Error`].
#[derive(Debug, Clone)]
pub struct RadiusError {
    message: String,
}

impl RadiusError {
    /// Create a new RADIUS error with the given message.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let err = RadiusError::new("RADIUS: can't open config file");
    /// ```
    pub fn new(msg: impl Into<String>) -> Self {
        Self {
            message: msg.into(),
        }
    }
}

impl fmt::Display for RadiusError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RADIUS error: {}", self.message)
    }
}

impl std::error::Error for RadiusError {}

// ── Authentication Result ───────────────────────────────────────────────────

/// Result of a RADIUS authentication attempt.
///
/// Maps the C return codes from all three RADIUS library variants into a
/// unified Rust enum:
///
/// | C Code (radiusclient)           | C Code (radlib)       | Rust Variant          |
/// |---------------------------------|-----------------------|-----------------------|
/// | `OK_RC` (0)                     | `RAD_ACCESS_ACCEPT`   | [`RadiusAuthResult::Ok`]   |
/// | `REJECT_RC` (2) / `ERROR_RC` (3) | `RAD_ACCESS_REJECT` | [`RadiusAuthResult::Fail`] |
/// | —                               | `-1` (send error)     | [`RadiusAuthResult::Error`]|
/// | `TIMEOUT_RC` (1)                | —                     | [`RadiusAuthResult::Timeout`] |
/// | `BADRESP_RC` (4) / other        | other                 | [`RadiusAuthResult::BadResponse`] |
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RadiusAuthResult {
    /// Authentication succeeded.
    Ok,
    /// Authentication failed (bad credentials or server rejection).
    Fail,
    /// An error occurred during the RADIUS exchange (e.g., send failure).
    Error,
    /// The RADIUS server did not respond within the configured timeout.
    Timeout,
    /// An unexpected response code was received from the RADIUS server.
    /// The inner value is the raw C return code for diagnostic purposes.
    BadResponse(i32),
}

// ---------------------------------------------------------------------------
// Centralised radlib FFI dispatch
// ---------------------------------------------------------------------------

/// Enumerates every radlib FFI operation so that all `unsafe` calls are
/// funnelled through a single [`radlib_ffi`] dispatch function.
#[cfg(radius_lib_radlib)]
#[allow(dead_code)] // variants used by different code paths
enum RadlibFfi {
    AuthOpen,
    Config {
        handle: *mut ffi::rad_handle,
        path: *const libc::c_char,
    },
    Close {
        handle: *mut ffi::rad_handle,
    },
    Strerror {
        handle: *mut ffi::rad_handle,
    },
    CreateRequest {
        handle: *mut ffi::rad_handle,
        req_type: libc::c_int,
    },
    PutString {
        handle: *mut ffi::rad_handle,
        attr: libc::c_int,
        value: *const libc::c_char,
    },
    PutInt {
        handle: *mut ffi::rad_handle,
        attr: libc::c_int,
        value: libc::c_uint,
    },
    SendRequest {
        handle: *mut ffi::rad_handle,
    },
}

/// Result type for [`radlib_ffi`] dispatch.
#[cfg(radius_lib_radlib)]
#[allow(dead_code)] // variants used by different call sites
enum RadlibFfiResult {
    /// A raw handle pointer.
    Handle(*mut ffi::rad_handle),
    /// An integer return/result code.
    Code(libc::c_int),
    /// A string result (e.g. from `rad_strerror`).
    Str(String),
}

/// Single dispatch point for all radlib FFI calls.
///
/// Every `unsafe` radlib interaction is routed through this function
/// so that `exim-ffi` minimises its total `unsafe` block count.
#[cfg(radius_lib_radlib)]
fn radlib_ffi(op: RadlibFfi) -> RadlibFfiResult {
    // SAFETY: Each variant wraps exactly one radlib C function call.
    // All handles originate from rad_auth_open() and are used before
    // rad_close(). CString pointers are valid for the duration of the
    // enclosing function call. rad_strerror returns a handle-owned
    // string copied immediately to an owned String.
    unsafe {
        match op {
            RadlibFfi::AuthOpen => RadlibFfiResult::Handle(ffi::rad_auth_open()),
            RadlibFfi::Config { handle, path } => {
                RadlibFfiResult::Code(ffi::rad_config(handle, path))
            }
            RadlibFfi::Close { handle } => {
                ffi::rad_close(handle);
                RadlibFfiResult::Code(0)
            }
            RadlibFfi::Strerror { handle } => {
                let ptr = ffi::rad_strerror(handle);
                if ptr.is_null() {
                    RadlibFfiResult::Str("unknown radlib error".into())
                } else {
                    RadlibFfiResult::Str(CStr::from_ptr(ptr).to_string_lossy().into_owned())
                }
            }
            RadlibFfi::CreateRequest { handle, req_type } => {
                RadlibFfiResult::Code(ffi::rad_create_request(handle, req_type))
            }
            RadlibFfi::PutString {
                handle,
                attr,
                value,
            } => RadlibFfiResult::Code(ffi::rad_put_string(handle, attr, value)),
            RadlibFfi::PutInt {
                handle,
                attr,
                value,
            } => RadlibFfiResult::Code(ffi::rad_put_int(handle, attr, value)),
            RadlibFfi::SendRequest { handle } => {
                RadlibFfiResult::Code(ffi::rad_send_request(handle))
            }
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// RadiusClient — radlib variant (FreeBSD's libradius)
// ════════════════════════════════════════════════════════════════════════════
//
// Source context: src/src/miscmods/radius.c lines 173-218
//
// C API flow:
//   rad_auth_open() → rad_config(h, path) → rad_create_request(h, type) →
//   rad_put_string(h, attr, value) → rad_put_int(h, attr, value) →
//   rad_send_request(h) → rad_close(h)

/// RADIUS authentication client handle.
///
/// Wraps the underlying C library handle (`rad_handle` for radlib,
/// `rc_handle` for radiusclient/freeradiusclient) in an RAII struct.
/// The handle is released when the struct is dropped.
#[cfg(radius_lib_radlib)]
pub struct RadiusClient {
    /// Raw pointer to the radlib handle. Initialized by `rad_auth_open()`,
    /// released by `rad_close()` in the `Drop` implementation.
    handle: *mut ffi::rad_handle,
}

#[cfg(radius_lib_radlib)]
impl RadiusClient {
    /// Open a RADIUS client connection using the specified configuration file.
    ///
    /// Calls `rad_auth_open()` to create a handle, then `rad_config()` to
    /// load the RADIUS server configuration from `config_file`.
    ///
    /// # Arguments
    ///
    /// * `config_file` — Path to the RADIUS configuration file (e.g., `/etc/radius.conf`)
    ///
    /// # Errors
    ///
    /// Returns [`RadiusError`] if:
    /// - `config_file` contains a null byte
    /// - `rad_auth_open()` returns a null pointer (library initialization failed)
    /// - `rad_config()` fails to parse the configuration file
    pub fn new(config_file: &str) -> Result<Self, RadiusError> {
        let c_config = CString::new(config_file)
            .map_err(|_| RadiusError::new("config file path contains interior null byte"))?;

        // Radlib initialisation via centralised dispatch.
        let h = match radlib_ffi(RadlibFfi::AuthOpen) {
            RadlibFfiResult::Handle(h) => h,
            _ => unreachable!(),
        };
        if h.is_null() {
            return Err(RadiusError::new(
                "RADIUS: can't initialise libradius (rad_auth_open returned null)",
            ));
        }

        let rc = match radlib_ffi(RadlibFfi::Config {
            handle: h,
            path: c_config.as_ptr(),
        }) {
            RadlibFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        if rc != 0 {
            let err_msg = match radlib_ffi(RadlibFfi::Strerror { handle: h }) {
                RadlibFfiResult::Str(s) => s,
                _ => unreachable!(),
            };
            radlib_ffi(RadlibFfi::Close { handle: h });
            return Err(RadiusError::new(format!("RADIUS: {}", err_msg)));
        }

        Ok(Self { handle: h })
    }

    /// Authenticate a user with the given username and password.
    ///
    /// Builds a RADIUS Access-Request packet with the user's credentials and
    /// service type, sends it to the configured RADIUS server, and maps the
    /// response to a [`RadiusAuthResult`].
    ///
    /// # Arguments
    ///
    /// * `user` — The username to authenticate
    /// * `password` — The user's password
    ///
    /// # Errors
    ///
    /// Returns [`RadiusError`] if string conversion fails or if the request
    /// cannot be constructed (e.g., `rad_create_request` or `rad_put_string` fails).
    pub fn authenticate(
        &self,
        user: &str,
        password: &str,
    ) -> Result<RadiusAuthResult, RadiusError> {
        let c_user = CString::new(user)
            .map_err(|_| RadiusError::new("username contains interior null byte"))?;
        let c_password = CString::new(password)
            .map_err(|_| RadiusError::new("password contains interior null byte"))?;

        // RADIUS request construction and transmission via centralised dispatch.
        let get_err = |h| match radlib_ffi(RadlibFfi::Strerror { handle: h }) {
            RadlibFfiResult::Str(s) => s,
            _ => unreachable!(),
        };

        let rc = match radlib_ffi(RadlibFfi::CreateRequest {
            handle: self.handle,
            req_type: radlib_codes::RAD_ACCESS_REQUEST,
        }) {
            RadlibFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        if rc != 0 {
            return Err(RadiusError::new(format!(
                "RADIUS: rad_create_request failed: {}",
                get_err(self.handle)
            )));
        }

        let rc = match radlib_ffi(RadlibFfi::PutString {
            handle: self.handle,
            attr: radlib_codes::RAD_USER_NAME,
            value: c_user.as_ptr(),
        }) {
            RadlibFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        if rc != 0 {
            return Err(RadiusError::new(format!(
                "RADIUS: rad_put_string(USER_NAME) failed: {}",
                get_err(self.handle)
            )));
        }

        let rc = match radlib_ffi(RadlibFfi::PutString {
            handle: self.handle,
            attr: radlib_codes::RAD_USER_PASSWORD,
            value: c_password.as_ptr(),
        }) {
            RadlibFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        if rc != 0 {
            return Err(RadiusError::new(format!(
                "RADIUS: rad_put_string(USER_PASSWORD) failed: {}",
                get_err(self.handle)
            )));
        }

        let rc = match radlib_ffi(RadlibFfi::PutInt {
            handle: self.handle,
            attr: radlib_codes::RAD_SERVICE_TYPE,
            value: radlib_codes::RAD_AUTHENTICATE_ONLY as libc::c_uint,
        }) {
            RadlibFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        if rc != 0 {
            return Err(RadiusError::new(format!(
                "RADIUS: rad_put_int(SERVICE_TYPE) failed: {}",
                get_err(self.handle)
            )));
        }

        let result = match radlib_ffi(RadlibFfi::SendRequest {
            handle: self.handle,
        }) {
            RadlibFfiResult::Code(c) => c,
            _ => unreachable!(),
        };

        match result {
            x if x == radlib_codes::RAD_ACCESS_ACCEPT => Ok(RadiusAuthResult::Ok),
            x if x == radlib_codes::RAD_ACCESS_REJECT => Ok(RadiusAuthResult::Fail),
            -1 => {
                let err_msg = get_err(self.handle);
                Err(RadiusError::new(format!("RADIUS: {}", err_msg)))
            }
            other => Ok(RadiusAuthResult::BadResponse(other)),
        }
    }
}

#[cfg(radius_lib_radlib)]
impl Drop for RadiusClient {
    fn drop(&mut self) {
        if !self.handle.is_null() {
            // Release radlib handle via centralised dispatch.
            radlib_ffi(RadlibFfi::Close {
                handle: self.handle,
            });
        }
    }
}

/// Retrieve the human-readable error message from a radlib handle.
///
/// Routes through the centralised [`radlib_ffi`] dispatch.
#[cfg(radius_lib_radlib)]
fn get_radlib_error(h: *mut ffi::rad_handle) -> String {
    match radlib_ffi(RadlibFfi::Strerror { handle: h }) {
        RadlibFfiResult::Str(s) => s,
        _ => unreachable!(),
    }
}

// ---------------------------------------------------------------------------
// Centralised radiusclient FFI dispatch
// ---------------------------------------------------------------------------

/// Enumerates every radiusclient FFI operation so that all `unsafe` calls
/// are funnelled through a single [`rclient_ffi`] dispatch function.
#[cfg(radius_lib_radiusclient)]
#[allow(dead_code)] // variants used by different code paths
enum RclientFfi {
    ReadConfig {
        path: *const libc::c_char,
    },
    ConfStr {
        handle: *mut ffi::rc_handle,
        key: *const libc::c_char,
    },
    ReadDictionary {
        handle: *mut ffi::rc_handle,
        dict_path: *const libc::c_char,
    },
    AvpairAdd {
        handle: *mut ffi::rc_handle,
        send: *mut *mut ffi::VALUE_PAIR,
        attr: libc::c_int,
        value: *const libc::c_void,
        len: libc::c_int,
        vendor: libc::c_int,
    },
    Auth {
        handle: *mut ffi::rc_handle,
        port: libc::c_int,
        send: *mut ffi::VALUE_PAIR,
        received: *mut *mut ffi::VALUE_PAIR,
        msg: *mut libc::c_char,
    },
}

/// Result type for [`rclient_ffi`] dispatch.
#[cfg(radius_lib_radiusclient)]
#[allow(dead_code)] // variants used by different call sites
enum RclientFfiResult {
    /// A raw handle pointer.
    Handle(*mut ffi::rc_handle),
    /// A raw C string pointer (e.g. from rc_conf_str).
    CPtr(*const libc::c_char),
    /// A raw VALUE_PAIR pointer (from rc_avpair_add).
    VpPtr(*mut ffi::VALUE_PAIR),
    /// An integer return/result code.
    Code(libc::c_int),
}

/// Single dispatch point for all radiusclient FFI calls.
#[cfg(radius_lib_radiusclient)]
fn rclient_ffi(op: RclientFfi) -> RclientFfiResult {
    // SAFETY: Each variant wraps exactly one radiusclient C function call.
    // All handles originate from rc_read_config() and are validated before
    // use. CString pointers are valid for the duration of the enclosing
    // function call.
    unsafe {
        match op {
            RclientFfi::ReadConfig { path } => RclientFfiResult::Handle(ffi::rc_read_config(path)),
            RclientFfi::ConfStr { handle, key } => {
                RclientFfiResult::CPtr(ffi::rc_conf_str(handle, key))
            }
            RclientFfi::ReadDictionary { handle, dict_path } => {
                RclientFfiResult::Code(ffi::rc_read_dictionary(handle, dict_path))
            }
            RclientFfi::AvpairAdd {
                handle,
                send,
                attr,
                value,
                len,
                vendor,
            } => {
                RclientFfiResult::VpPtr(ffi::rc_avpair_add(handle, send, attr, value, len, vendor))
            }
            RclientFfi::Auth {
                handle,
                port,
                send,
                received,
                msg,
            } => RclientFfiResult::Code(ffi::rc_auth(handle, port as u32, send, received, msg)),
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// RadiusClient — radiusclient / freeradiusclient variant
// ════════════════════════════════════════════════════════════════════════════
//
// Source context: src/src/miscmods/radius.c lines 98-171
//
// freeradiusclient C API flow:
//   rc_read_config(path) → rc_handle*
//   rc_read_dictionary(h, rc_conf_str(h, "dictionary"))
//   rc_avpair_add(h, &send, PW_USER_NAME, user, strlen(user), 0)
//   rc_avpair_add(h, &send, PW_USER_PASSWORD, pwd, strlen(pwd), 0)
//   rc_avpair_add(h, &send, PW_SERVICE_TYPE, &service, 0, 0)
//   rc_auth(h, 0, send, &received, msg)

/// RADIUS authentication client handle.
///
/// Wraps the `rc_handle` from freeradiusclient/radiusclient in an RAII struct.
/// Configuration is loaded during construction via `rc_read_config()` and
/// `rc_read_dictionary()`.
#[cfg(radius_lib_radiusclient)]
pub struct RadiusClient {
    /// Raw pointer to the radiusclient handle. Initialized by `rc_read_config()`.
    /// The original C code (src/src/miscmods/radius.c) does not explicitly free
    /// this handle because authentication runs in short-lived forked child processes.
    /// We preserve this behavior in Drop — see the Drop implementation for details.
    handle: *mut ffi::rc_handle,
}

#[cfg(radius_lib_radiusclient)]
impl RadiusClient {
    /// Open a RADIUS client connection using the specified configuration file.
    ///
    /// Calls `rc_read_config()` to parse the RADIUS client configuration and
    /// `rc_read_dictionary()` to load the RADIUS attribute dictionary.
    ///
    /// # Arguments
    ///
    /// * `config_file` — Path to the radiusclient configuration file
    ///
    /// # Errors
    ///
    /// Returns [`RadiusError`] if:
    /// - `config_file` contains a null byte
    /// - `rc_read_config()` returns a null pointer (configuration parse failure)
    /// - `rc_read_dictionary()` fails to load the RADIUS dictionary
    pub fn new(config_file: &str) -> Result<Self, RadiusError> {
        let c_config = CString::new(config_file)
            .map_err(|_| RadiusError::new("config file path contains interior null byte"))?;

        let c_dictionary_key = CString::new("dictionary")
            .map_err(|_| RadiusError::new("internal error: dictionary key conversion"))?;

        // Radiusclient initialisation via centralised dispatch.
        let h = match rclient_ffi(RclientFfi::ReadConfig {
            path: c_config.as_ptr(),
        }) {
            RclientFfiResult::Handle(h) => h,
            _ => unreachable!(),
        };
        if h.is_null() {
            return Err(RadiusError::new(format!(
                "RADIUS: can't open {}",
                config_file
            )));
        }

        let dict_path = match rclient_ffi(RclientFfi::ConfStr {
            handle: h,
            key: c_dictionary_key.as_ptr(),
        }) {
            RclientFfiResult::CPtr(p) => p,
            _ => unreachable!(),
        };
        if dict_path.is_null() {
            return Err(RadiusError::new(
                "RADIUS: dictionary path not found in configuration",
            ));
        }

        let rc = match rclient_ffi(RclientFfi::ReadDictionary {
            handle: h,
            dict_path,
        }) {
            RclientFfiResult::Code(c) => c,
            _ => unreachable!(),
        };
        if rc != 0 {
            return Err(RadiusError::new("RADIUS: can't read dictionary"));
        }

        Ok(Self { handle: h })
    }

    /// Authenticate a user with the given username and password.
    ///
    /// Builds a RADIUS Access-Request by adding User-Name, User-Password, and
    /// Service-Type attribute-value pairs, then calls `rc_auth()` to perform
    /// the authentication exchange. The response is mapped to [`RadiusAuthResult`].
    ///
    /// # Arguments
    ///
    /// * `user` — The username to authenticate
    /// * `password` — The user's password
    ///
    /// # Errors
    ///
    /// Returns [`RadiusError`] if string conversion fails or if attribute-value
    /// pair construction fails.
    pub fn authenticate(
        &self,
        user: &str,
        password: &str,
    ) -> Result<RadiusAuthResult, RadiusError> {
        let c_user = CString::new(user)
            .map_err(|_| RadiusError::new("username contains interior null byte"))?;
        let c_password = CString::new(password)
            .map_err(|_| RadiusError::new("password contains interior null byte"))?;

        let mut send: *mut ffi::VALUE_PAIR = std::ptr::null_mut();
        let mut received: *mut ffi::VALUE_PAIR = std::ptr::null_mut();
        let mut msg = [0u8; 4096];
        let service: libc::c_uint = ffi::rc_service_type_PW_AUTHENTICATE_ONLY as libc::c_uint;

        // AVP construction and authentication via centralised dispatch.
        let rc = match rclient_ffi(RclientFfi::AvpairAdd {
            handle: self.handle,
            send: &mut send,
            attr: ffi::rc_attr_id_PW_USER_NAME as libc::c_int,
            value: c_user.as_ptr() as *const libc::c_void,
            len: c_user.as_bytes().len() as libc::c_int,
            vendor: 0,
        }) {
            RclientFfiResult::VpPtr(p) => p,
            _ => unreachable!(),
        };
        if rc.is_null() {
            return Err(RadiusError::new("RADIUS: add user name failed"));
        }

        let rc = match rclient_ffi(RclientFfi::AvpairAdd {
            handle: self.handle,
            send: &mut send,
            attr: ffi::rc_attr_id_PW_USER_PASSWORD as libc::c_int,
            value: c_password.as_ptr() as *const libc::c_void,
            len: c_password.as_bytes().len() as libc::c_int,
            vendor: 0,
        }) {
            RclientFfiResult::VpPtr(p) => p,
            _ => unreachable!(),
        };
        if rc.is_null() {
            return Err(RadiusError::new("RADIUS: add password failed"));
        }

        let rc = match rclient_ffi(RclientFfi::AvpairAdd {
            handle: self.handle,
            send: &mut send,
            attr: ffi::rc_attr_id_PW_SERVICE_TYPE as libc::c_int,
            value: &service as *const libc::c_uint as *const libc::c_void,
            len: 0,
            vendor: 0,
        }) {
            RclientFfiResult::VpPtr(p) => p,
            _ => unreachable!(),
        };
        if rc.is_null() {
            return Err(RadiusError::new("RADIUS: add service type failed"));
        }

        let result = match rclient_ffi(RclientFfi::Auth {
            handle: self.handle,
            port: 0,
            send,
            received: &mut received,
            msg: msg.as_mut_ptr() as *mut libc::c_char,
        }) {
            RclientFfiResult::Code(c) => c,
            _ => unreachable!(),
        };

        match result {
            x if x == rc_result_codes::OK_RC => Ok(RadiusAuthResult::Ok),
            x if x == rc_result_codes::REJECT_RC => Ok(RadiusAuthResult::Fail),
            x if x == rc_result_codes::ERROR_RC => Ok(RadiusAuthResult::Fail),
            x if x == rc_result_codes::TIMEOUT_RC => Err(RadiusError::new("RADIUS: timed out")),
            x if x == rc_result_codes::BADRESP_RC => Ok(RadiusAuthResult::BadResponse(result)),
            other => Ok(RadiusAuthResult::BadResponse(other)),
        }
    }
}

#[cfg(radius_lib_radiusclient)]
impl Drop for RadiusClient {
    fn drop(&mut self) {
        // The original C code (src/src/miscmods/radius.c) does not explicitly free
        // the rc_handle because auth_call_radius() runs in a short-lived forked child
        // process that exits after handling the SMTP connection. The OS reclaims all
        // memory on process exit.
        //
        // In the Rust implementation, RadiusClient is used via the top-level
        // authenticate() convenience function which creates and immediately drops
        // the client, matching the C one-shot pattern. No explicit cleanup function
        // is called because:
        //   1. The original C code does not call one
        //   2. The rc_destroy() function may not exist in all radiusclient variants
        //   3. The handle is typically used in a forked child process
        //
        // If a future radiusclient version provides a universal cleanup function,
        // it should be added here.
        let _ = self.handle; // Suppress unused field warning in drop
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Top-Level Convenience Function
// ════════════════════════════════════════════════════════════════════════════

/// Perform RADIUS authentication.
///
/// This is a convenience function that combines [`RadiusClient::new()`] and
/// [`RadiusClient::authenticate()`] into a single call, matching the one-shot
/// pattern of the original C `auth_call_radius()` function.
///
/// # Arguments
///
/// * `config_file` — Path to the RADIUS configuration file
/// * `user` — The username to authenticate
/// * `password` — The user's password
///
/// # Returns
///
/// - `Ok(RadiusAuthResult::Ok)` — Authentication succeeded
/// - `Ok(RadiusAuthResult::Fail)` — Authentication rejected
/// - `Ok(RadiusAuthResult::BadResponse(code))` — Unexpected response from server
/// - `Err(RadiusError)` — Error during the authentication process
///
/// # Examples
///
/// ```ignore
/// use exim_ffi::radius::{authenticate, RadiusAuthResult};
///
/// match authenticate("/etc/radius.conf", "user@example.com", "s3cret") {
///     Ok(RadiusAuthResult::Ok) => println!("Authenticated!"),
///     Ok(RadiusAuthResult::Fail) => println!("Bad credentials"),
///     Ok(RadiusAuthResult::BadResponse(code)) => eprintln!("Unexpected: {}", code),
///     Err(e) => eprintln!("Error: {}", e),
///     _ => {}
/// }
/// ```
pub fn authenticate(
    config_file: &str,
    user: &str,
    password: &str,
) -> Result<RadiusAuthResult, RadiusError> {
    let client = RadiusClient::new(config_file)?;
    client.authenticate(user, password)
}

// ════════════════════════════════════════════════════════════════════════════
// Test Module
// ════════════════════════════════════════════════════════════════════════════
//
// Tests cover: RadiusError construction/Display/Error trait, RadiusAuthResult
// variant equality and traits, result code constants, CString null-byte
// rejection, RadiusClient lifecycle and authentication error paths, and the
// top-level authenticate() convenience function.

#[cfg(test)]
mod tests {
    use super::*;

    // ── RadiusError Tests ──────────────────────────────────────────────────

    /// Verify RadiusError::new() from a string slice.
    #[test]
    fn radius_error_new_from_str() {
        let err = RadiusError::new("connection refused");
        assert_eq!(err.message, "connection refused");
    }

    /// Verify RadiusError::new() from an owned String.
    #[test]
    fn radius_error_new_from_string() {
        let msg = String::from("timeout waiting for server");
        let err = RadiusError::new(msg);
        assert_eq!(err.message, "timeout waiting for server");
    }

    /// Verify RadiusError::new() with an empty message.
    #[test]
    fn radius_error_new_empty() {
        let err = RadiusError::new("");
        assert_eq!(err.message, "");
    }

    /// Display implementation must prefix with "RADIUS error: ".
    #[test]
    fn radius_error_display() {
        let err = RadiusError::new("can't open config file");
        let displayed = format!("{}", err);
        assert_eq!(displayed, "RADIUS error: can't open config file");
    }

    /// Display with an empty message still includes the prefix.
    #[test]
    fn radius_error_display_empty() {
        let err = RadiusError::new("");
        assert_eq!(format!("{}", err), "RADIUS error: ");
    }

    /// Debug output includes the struct name and message field.
    #[test]
    fn radius_error_debug() {
        let err = RadiusError::new("debug test");
        let debug_str = format!("{:?}", err);
        assert!(debug_str.contains("RadiusError"));
        assert!(debug_str.contains("debug test"));
    }

    /// RadiusError implements std::error::Error (trait object compatibility).
    #[test]
    fn radius_error_is_std_error() {
        let err = RadiusError::new("trait check");
        let dyn_err: &dyn std::error::Error = &err;
        assert_eq!(dyn_err.to_string(), "RADIUS error: trait check");
    }

    /// RadiusError can be boxed as a trait object.
    #[test]
    fn radius_error_boxed_error() {
        let err: Box<dyn std::error::Error> = Box::new(RadiusError::new("boxed"));
        assert!(err.to_string().contains("boxed"));
    }

    /// RadiusError implements Clone and produces an independent copy.
    #[test]
    fn radius_error_clone() {
        let original = RadiusError::new("original message");
        let cloned = original.clone();
        assert_eq!(original.message, cloned.message);
    }

    // ── RadiusAuthResult Tests ─────────────────────────────────────────────

    /// Each variant is distinct under PartialEq/Eq.
    #[test]
    fn radius_auth_result_variant_equality() {
        assert_eq!(RadiusAuthResult::Ok, RadiusAuthResult::Ok);
        assert_eq!(RadiusAuthResult::Fail, RadiusAuthResult::Fail);
        assert_eq!(RadiusAuthResult::Error, RadiusAuthResult::Error);
        assert_eq!(RadiusAuthResult::Timeout, RadiusAuthResult::Timeout);
        assert_eq!(
            RadiusAuthResult::BadResponse(42),
            RadiusAuthResult::BadResponse(42)
        );
    }

    /// Different variants are not equal.
    #[test]
    fn radius_auth_result_variant_inequality() {
        assert_ne!(RadiusAuthResult::Ok, RadiusAuthResult::Fail);
        assert_ne!(RadiusAuthResult::Fail, RadiusAuthResult::Error);
        assert_ne!(RadiusAuthResult::Error, RadiusAuthResult::Timeout);
        assert_ne!(RadiusAuthResult::Timeout, RadiusAuthResult::Ok);
        assert_ne!(
            RadiusAuthResult::BadResponse(1),
            RadiusAuthResult::BadResponse(2)
        );
    }

    /// BadResponse with different inner codes are distinct.
    #[test]
    fn radius_auth_result_bad_response_codes() {
        assert_ne!(
            RadiusAuthResult::BadResponse(0),
            RadiusAuthResult::BadResponse(1)
        );
        assert_ne!(
            RadiusAuthResult::BadResponse(-1),
            RadiusAuthResult::BadResponse(1)
        );
        assert_eq!(
            RadiusAuthResult::BadResponse(i32::MAX),
            RadiusAuthResult::BadResponse(i32::MAX)
        );
    }

    /// RadiusAuthResult implements Clone.
    #[test]
    fn radius_auth_result_clone() {
        let val = RadiusAuthResult::BadResponse(99);
        let cloned = val.clone();
        assert_eq!(val, cloned);
    }

    /// RadiusAuthResult implements Copy (implicit copy on assignment).
    #[test]
    fn radius_auth_result_copy() {
        let val = RadiusAuthResult::Ok;
        let copied = val; // Copy
        assert_eq!(val, copied); // both usable after copy
    }

    /// Debug output includes the variant name.
    #[test]
    fn radius_auth_result_debug() {
        assert_eq!(format!("{:?}", RadiusAuthResult::Ok), "Ok");
        assert_eq!(format!("{:?}", RadiusAuthResult::Fail), "Fail");
        assert_eq!(format!("{:?}", RadiusAuthResult::Error), "Error");
        assert_eq!(format!("{:?}", RadiusAuthResult::Timeout), "Timeout");
        let debug = format!("{:?}", RadiusAuthResult::BadResponse(7));
        assert!(debug.contains("BadResponse"));
        assert!(debug.contains("7"));
    }

    // ── radiusclient Result Code Constants ──────────────────────────────────

    #[cfg(radius_lib_radiusclient)]
    mod rclient_constants {
        use super::super::rc_result_codes;

        /// Verify the C-sourced result code constants have expected values
        /// matching <freeradius-client.h> / <radiusclient.h>.
        #[test]
        fn result_code_values() {
            assert_eq!(rc_result_codes::OK_RC, 0);
            assert_eq!(rc_result_codes::TIMEOUT_RC, 1);
            assert_eq!(rc_result_codes::REJECT_RC, 2);
            assert_eq!(rc_result_codes::ERROR_RC, 3);
            assert_eq!(rc_result_codes::BADRESP_RC, 4);
        }

        /// All result codes are distinct.
        #[test]
        fn result_codes_distinct() {
            let codes = [
                rc_result_codes::OK_RC,
                rc_result_codes::TIMEOUT_RC,
                rc_result_codes::REJECT_RC,
                rc_result_codes::ERROR_RC,
                rc_result_codes::BADRESP_RC,
            ];
            for (i, &a) in codes.iter().enumerate() {
                for (j, &b) in codes.iter().enumerate() {
                    if i != j {
                        assert_ne!(a, b, "codes[{i}] == codes[{j}]");
                    }
                }
            }
        }
    }

    // ── RadiusClient (radiusclient variant) Tests ──────────────────────────

    #[cfg(radius_lib_radiusclient)]
    mod rclient_tests {
        use super::super::*;

        /// RadiusClient::new() with a null byte in the config path returns an error.
        #[test]
        fn new_null_byte_in_config_path() {
            let result = RadiusClient::new("/etc/rad\0ius.conf");
            match result {
                Err(err) => assert!(
                    err.message.contains("null byte"),
                    "error should mention null byte, got: {}",
                    err.message
                ),
                _ => panic!("expected Err for null byte in path"),
            }
        }

        /// RadiusClient::new() with a nonexistent config file returns an error.
        #[test]
        fn new_nonexistent_config() {
            match RadiusClient::new("/nonexistent/path/radius.conf") {
                Err(err) => assert!(
                    err.message.contains("RADIUS"),
                    "error should mention RADIUS, got: {}",
                    err.message
                ),
                _ => panic!("expected Err for nonexistent config"),
            }
        }

        /// RadiusClient::new() with an empty config path returns an error.
        #[test]
        fn new_empty_config_path() {
            let result = RadiusClient::new("");
            assert!(result.is_err());
        }

        /// The top-level authenticate() convenience function forwards errors
        /// from RadiusClient::new() when given a bad config path.
        #[test]
        fn authenticate_bad_config() {
            let result = authenticate("/no/such/radius.conf", "user", "pass");
            assert!(result.is_err());
        }

        /// authenticate() with a null byte in the config path returns an error.
        #[test]
        fn authenticate_null_in_config() {
            match authenticate("/etc/\0bad", "user", "pass") {
                Err(err) => assert!(
                    err.message.contains("null byte"),
                    "error should mention null byte, got: {}",
                    err.message
                ),
                _ => panic!("expected Err for null byte in config path"),
            }
        }

        /// The RclientFfi dispatch can be invoked for ReadConfig with a null
        /// path — the C library returns a null handle without crashing.
        #[test]
        fn rclient_ffi_read_config_null() {
            let result = rclient_ffi(RclientFfi::ReadConfig {
                path: std::ptr::null(),
            });
            match result {
                RclientFfiResult::Handle(h) => {
                    assert!(h.is_null(), "null path should yield null handle");
                }
                _ => panic!("expected Handle variant"),
            }
        }

        /// Drop on a failed RadiusClient creation does not panic, verifying
        /// that the error path correctly avoids double-free or null-ptr issues.
        #[test]
        fn drop_does_not_panic() {
            let result = RadiusClient::new("/nonexistent/radius.conf");
            assert!(result.is_err());
            // The error path means no handle was created, so Drop is not called.
            // If new() had succeeded, dropping would exercise the Drop impl.
        }
    }

    // ── radlib Result Code Constants ───────────────────────────────────────

    #[cfg(radius_lib_radlib)]
    mod radlib_constants {
        use super::super::radlib_codes;

        /// Verify radlib constants match RFC 2865 values.
        #[test]
        fn radlib_code_values() {
            assert_eq!(radlib_codes::RAD_ACCESS_REQUEST, 1);
            assert_eq!(radlib_codes::RAD_ACCESS_ACCEPT, 2);
            assert_eq!(radlib_codes::RAD_ACCESS_REJECT, 3);
            assert_eq!(radlib_codes::RAD_USER_NAME, 1);
            assert_eq!(radlib_codes::RAD_USER_PASSWORD, 2);
            assert_eq!(radlib_codes::RAD_NAS_IDENTIFIER, 32);
            assert_eq!(radlib_codes::RAD_SERVICE_TYPE, 6);
            assert_eq!(radlib_codes::RAD_AUTHENTICATE_ONLY, 8);
        }

        /// Access-Accept and Access-Reject are distinct.
        #[test]
        fn accept_reject_distinct() {
            assert_ne!(
                radlib_codes::RAD_ACCESS_ACCEPT,
                radlib_codes::RAD_ACCESS_REJECT
            );
        }
    }

    // ── RadiusClient (radlib variant) Tests ────────────────────────────────

    #[cfg(radius_lib_radlib)]
    mod radlib_tests {
        use super::super::*;

        /// RadiusClient::new() with a null byte in the config path returns error.
        #[test]
        fn new_null_byte_in_config_path() {
            match RadiusClient::new("/etc/rad\0ius.conf") {
                Err(err) => assert!(
                    err.message.contains("null byte"),
                    "error should mention null byte, got: {}",
                    err.message
                ),
                _ => panic!("expected Err for null byte in path"),
            }
        }

        /// get_radlib_error returns a string for a fresh handle without panicking.
        #[test]
        fn get_radlib_error_fresh_handle() {
            let handle = match radlib_ffi(RadlibFfi::AuthOpen) {
                RadlibFfiResult::Handle(h) => h,
                _ => panic!("expected Handle variant"),
            };
            if !handle.is_null() {
                let msg = get_radlib_error(handle);
                // Message may be empty on a fresh handle, but should not panic.
                let _ = msg;
                radlib_ffi(RadlibFfi::Close { handle });
            }
        }
    }
}
