//! Safe wrappers around RADIUS authentication libraries.
//!
//! Supports three C library variants behind a unified safe Rust API:
//!
//! - **radlib** (FreeBSD's `libradius`) — selected when `radius_lib_radlib` cfg is set
//!   by the build script upon detecting `<radlib.h>`.
//! - **freeradiusclient** (modern radiusclient API) — selected when `radius_lib_radiusclient`
//!   cfg is set upon detecting `<freeradius-client.h>`.
//! - **radiusclient** (legacy radiusclient API) — also uses `radius_lib_radiusclient` cfg
//!   upon detecting `<radiusclient.h>`.
//!
//! The build script (`exim-ffi/build.rs`) performs header detection at compile time,
//! generates bindgen FFI bindings into `OUT_DIR/radius_bindings.rs`, and sets exactly
//! one of the two `cfg` attributes (`radius_lib_radlib` or `radius_lib_radiusclient`).
//!
//! The safe API exposes:
//! - [`RadiusClient`] — RAII handle wrapping the library lifecycle (open → authenticate → close)
//! - [`authenticate()`] — Convenience function combining client creation and authentication
//! - [`RadiusAuthResult`] — Typed enum mapping C return codes to Rust variants
//! - [`RadiusError`] — Error type for failed operations
//!
//! # Safety Policy (AAP §0.7.2)
//!
//! Every `unsafe` block has an inline justification comment. Raw C pointers are
//! confined to the [`RadiusClient`] struct which implements [`Drop`] for RAII cleanup.
//! All string parameters are converted to [`CString`] before crossing the FFI boundary.
//!
//! [`CString`]: std::ffi::CString

use std::ffi::CString;
use std::fmt;

// CStr is only used in the radlib code path for rad_strerror() result parsing
#[cfg(radius_lib_radlib)]
use std::ffi::CStr;

// ── Raw FFI Bindings (generated by build.rs via bindgen) ────────────────────
//
// The build script detects the installed RADIUS library header, generates
// bindings via bindgen with an appropriate allowlist, and writes the output
// to `$OUT_DIR/radius_bindings.rs`. The allowlist includes:
//
//   radlib: rad_auth_open, rad_close, rad_config, rad_create_request,
//           rad_put_string, rad_put_int, rad_send_request, rad_strerror,
//           rad_handle type
//
//   radiusclient/freeradiusclient: rc_read_config, rc_read_dictionary,
//           rc_avpair_add, rc_auth, rc_openlog, rc_conf_str,
//           rc_handle type, VALUE_PAIR type,
//           PW_USER_NAME, PW_USER_PASSWORD, PW_SERVICE_TYPE,
//           PW_AUTHENTICATE_ONLY constants

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
// Justification: bindgen-generated FFI bindings must preserve C naming conventions
// from the RADIUS library headers (radlib.h / freeradius-client.h / radiusclient.h).
// dead_code is allowed because not all generated symbols may be used in the safe wrapper.
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/radius_bindings.rs"));
}

// ── RADIUS Result Code Constants ────────────────────────────────────────────
//
// These constants map C preprocessor defines that may not be captured by
// bindgen's allowlist. They are defined explicitly for each library variant
// to ensure correctness regardless of header parsing behavior.

/// radiusclient / freeradiusclient authentication result codes returned by `rc_auth()`.
///
/// Values sourced from `<freeradius-client.h>` / `<radiusclient.h>`:
///   `OK_RC = 0`, `TIMEOUT_RC = 1`, `REJECT_RC = 2`, `ERROR_RC = 3`, `BADRESP_RC = 4`
#[cfg(radius_lib_radiusclient)]
mod rc_result_codes {
    /// Authentication succeeded.
    pub const OK_RC: libc::c_int = 0;
    /// RADIUS server did not respond within the configured timeout.
    pub const TIMEOUT_RC: libc::c_int = 1;
    /// Authentication rejected by the RADIUS server.
    pub const REJECT_RC: libc::c_int = 2;
    /// Generic error during authentication exchange.
    pub const ERROR_RC: libc::c_int = 3;
    /// Unexpected or malformed response from RADIUS server.
    pub const BADRESP_RC: libc::c_int = 4;
}

/// radlib (FreeBSD) RADIUS attribute type constants and request/response codes.
///
/// Values sourced from `<radlib.h>`:
///   `RAD_ACCESS_REQUEST = 1`, `RAD_ACCESS_ACCEPT = 2`, `RAD_ACCESS_REJECT = 3`
///   Attribute types follow RFC 2865 numbering.
#[cfg(radius_lib_radlib)]
mod radlib_codes {
    /// RADIUS Access-Request packet type (RFC 2865 §4.1).
    pub const RAD_ACCESS_REQUEST: libc::c_int = 1;
    /// RADIUS Access-Accept response — authentication succeeded (RFC 2865 §4.2).
    pub const RAD_ACCESS_ACCEPT: libc::c_int = 2;
    /// RADIUS Access-Reject response — authentication failed (RFC 2865 §4.3).
    pub const RAD_ACCESS_REJECT: libc::c_int = 3;
    /// User-Name attribute (RFC 2865 §5.1).
    pub const RAD_USER_NAME: libc::c_int = 1;
    /// User-Password attribute (RFC 2865 §5.2).
    pub const RAD_USER_PASSWORD: libc::c_int = 2;
    /// NAS-Identifier attribute (RFC 2865 §5.32).
    pub const RAD_NAS_IDENTIFIER: libc::c_int = 32;
    /// Service-Type attribute (RFC 2865 §5.6).
    pub const RAD_SERVICE_TYPE: libc::c_int = 6;
    /// Authenticate-Only service type value (RFC 2865 §5.6).
    pub const RAD_AUTHENTICATE_ONLY: libc::c_int = 8;
}

// ── Error Type ──────────────────────────────────────────────────────────────

/// RADIUS authentication error.
///
/// Wraps error messages from the underlying C RADIUS library (radlib's
/// `rad_strerror`, or radiusclient error conditions) into a Rust error type
/// implementing [`std::error::Error`].
#[derive(Debug, Clone)]
pub struct RadiusError {
    message: String,
}

impl RadiusError {
    /// Create a new RADIUS error with the given message.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let err = RadiusError::new("RADIUS: can't open config file");
    /// ```
    pub fn new(msg: impl Into<String>) -> Self {
        Self {
            message: msg.into(),
        }
    }
}

impl fmt::Display for RadiusError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RADIUS error: {}", self.message)
    }
}

impl std::error::Error for RadiusError {}

// ── Authentication Result ───────────────────────────────────────────────────

/// Result of a RADIUS authentication attempt.
///
/// Maps the C return codes from all three RADIUS library variants into a
/// unified Rust enum:
///
/// | C Code (radiusclient)           | C Code (radlib)       | Rust Variant          |
/// |---------------------------------|-----------------------|-----------------------|
/// | `OK_RC` (0)                     | `RAD_ACCESS_ACCEPT`   | [`RadiusAuthResult::Ok`]   |
/// | `REJECT_RC` (2) / `ERROR_RC` (3) | `RAD_ACCESS_REJECT` | [`RadiusAuthResult::Fail`] |
/// | —                               | `-1` (send error)     | [`RadiusAuthResult::Error`]|
/// | `TIMEOUT_RC` (1)                | —                     | [`RadiusAuthResult::Timeout`] |
/// | `BADRESP_RC` (4) / other        | other                 | [`RadiusAuthResult::BadResponse`] |
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RadiusAuthResult {
    /// Authentication succeeded.
    Ok,
    /// Authentication failed (bad credentials or server rejection).
    Fail,
    /// An error occurred during the RADIUS exchange (e.g., send failure).
    Error,
    /// The RADIUS server did not respond within the configured timeout.
    Timeout,
    /// An unexpected response code was received from the RADIUS server.
    /// The inner value is the raw C return code for diagnostic purposes.
    BadResponse(i32),
}

// ════════════════════════════════════════════════════════════════════════════
// RadiusClient — radlib variant (FreeBSD's libradius)
// ════════════════════════════════════════════════════════════════════════════
//
// Source context: src/src/miscmods/radius.c lines 173-218
//
// C API flow:
//   rad_auth_open() → rad_config(h, path) → rad_create_request(h, type) →
//   rad_put_string(h, attr, value) → rad_put_int(h, attr, value) →
//   rad_send_request(h) → rad_close(h)

/// RADIUS authentication client handle.
///
/// Wraps the underlying C library handle (`rad_handle` for radlib,
/// `rc_handle` for radiusclient/freeradiusclient) in an RAII struct.
/// The handle is released when the struct is dropped.
#[cfg(radius_lib_radlib)]
pub struct RadiusClient {
    /// Raw pointer to the radlib handle. Initialized by `rad_auth_open()`,
    /// released by `rad_close()` in the `Drop` implementation.
    handle: *mut ffi::rad_handle,
}

#[cfg(radius_lib_radlib)]
impl RadiusClient {
    /// Open a RADIUS client connection using the specified configuration file.
    ///
    /// Calls `rad_auth_open()` to create a handle, then `rad_config()` to
    /// load the RADIUS server configuration from `config_file`.
    ///
    /// # Arguments
    ///
    /// * `config_file` — Path to the RADIUS configuration file (e.g., `/etc/radius.conf`)
    ///
    /// # Errors
    ///
    /// Returns [`RadiusError`] if:
    /// - `config_file` contains a null byte
    /// - `rad_auth_open()` returns a null pointer (library initialization failed)
    /// - `rad_config()` fails to parse the configuration file
    pub fn new(config_file: &str) -> Result<Self, RadiusError> {
        let c_config = CString::new(config_file)
            .map_err(|_| RadiusError::new("config file path contains interior null byte"))?;

        // SAFETY: calling rad_auth_open() to create a new radlib
        // authentication handle. This is the documented entry point for the radlib
        // API. Returns null on allocation failure; we check before use.
        let h = unsafe { ffi::rad_auth_open() };
        if h.is_null() {
            return Err(RadiusError::new(
                "RADIUS: can't initialise libradius (rad_auth_open returned null)",
            ));
        }

        // SAFETY: calling rad_config() to load the RADIUS configuration
        // file into a valid, non-null handle returned by rad_auth_open(). The config
        // file path is a valid null-terminated C string created by CString::new().
        // Returns 0 on success, -1 on failure.
        let rc = unsafe { ffi::rad_config(h, c_config.as_ptr()) };
        if rc != 0 {
            let err_msg = get_radlib_error(h);
            // SAFETY: calling rad_close() to release the handle that
            // was successfully allocated by rad_auth_open() but whose configuration
            // failed. This prevents resource leaks on the error path.
            unsafe {
                ffi::rad_close(h);
            }
            return Err(RadiusError::new(format!("RADIUS: {}", err_msg)));
        }

        Ok(Self { handle: h })
    }

    /// Authenticate a user with the given username and password.
    ///
    /// Builds a RADIUS Access-Request packet with the user's credentials and
    /// service type, sends it to the configured RADIUS server, and maps the
    /// response to a [`RadiusAuthResult`].
    ///
    /// # Arguments
    ///
    /// * `user` — The username to authenticate
    /// * `password` — The user's password
    ///
    /// # Errors
    ///
    /// Returns [`RadiusError`] if string conversion fails or if the request
    /// cannot be constructed (e.g., `rad_create_request` or `rad_put_string` fails).
    pub fn authenticate(
        &self,
        user: &str,
        password: &str,
    ) -> Result<RadiusAuthResult, RadiusError> {
        let c_user = CString::new(user)
            .map_err(|_| RadiusError::new("username contains interior null byte"))?;
        let c_password = CString::new(password)
            .map_err(|_| RadiusError::new("password contains interior null byte"))?;

        // SAFETY: calling rad_create_request(), rad_put_string(), and
        // rad_put_int() to build a RADIUS Access-Request packet on the valid handle
        // initialized in new(). All string arguments are valid null-terminated C
        // strings created by CString::new(). Each function returns 0 on success,
        // -1 on failure. We check after each call.
        unsafe {
            if ffi::rad_create_request(self.handle, radlib_codes::RAD_ACCESS_REQUEST) != 0 {
                return Err(RadiusError::new(format!(
                    "RADIUS: rad_create_request failed: {}",
                    get_radlib_error(self.handle)
                )));
            }
            if ffi::rad_put_string(self.handle, radlib_codes::RAD_USER_NAME, c_user.as_ptr()) != 0 {
                return Err(RadiusError::new(format!(
                    "RADIUS: rad_put_string(USER_NAME) failed: {}",
                    get_radlib_error(self.handle)
                )));
            }
            if ffi::rad_put_string(
                self.handle,
                radlib_codes::RAD_USER_PASSWORD,
                c_password.as_ptr(),
            ) != 0
            {
                return Err(RadiusError::new(format!(
                    "RADIUS: rad_put_string(USER_PASSWORD) failed: {}",
                    get_radlib_error(self.handle)
                )));
            }
            if ffi::rad_put_int(
                self.handle,
                radlib_codes::RAD_SERVICE_TYPE,
                radlib_codes::RAD_AUTHENTICATE_ONLY as libc::c_uint,
            ) != 0
            {
                return Err(RadiusError::new(format!(
                    "RADIUS: rad_put_int(SERVICE_TYPE) failed: {}",
                    get_radlib_error(self.handle)
                )));
            }
        }

        // SAFETY: calling rad_send_request() to send the constructed
        // Access-Request packet and receive the response. The handle is valid and
        // the request was fully constructed above. Returns one of the RAD_ACCESS_*
        // constants on success, or -1 on send/receive failure.
        let result = unsafe { ffi::rad_send_request(self.handle) };

        match result {
            x if x == radlib_codes::RAD_ACCESS_ACCEPT => Ok(RadiusAuthResult::Ok),
            x if x == radlib_codes::RAD_ACCESS_REJECT => Ok(RadiusAuthResult::Fail),
            -1 => {
                let err_msg = get_radlib_error(self.handle);
                Err(RadiusError::new(format!("RADIUS: {}", err_msg)))
            }
            other => Ok(RadiusAuthResult::BadResponse(other)),
        }
    }
}

#[cfg(radius_lib_radlib)]
impl Drop for RadiusClient {
    fn drop(&mut self) {
        if !self.handle.is_null() {
            // SAFETY: calling rad_close() to release the radlib handle
            // that was allocated by rad_auth_open() in new(). The handle is guaranteed
            // non-null by the check above and was successfully initialized. This is
            // called exactly once via Drop, matching the C code's cleanup pattern
            // (src/src/miscmods/radius.c line 215).
            unsafe {
                ffi::rad_close(self.handle);
            }
        }
    }
}

/// Retrieve the human-readable error message from a radlib handle.
///
/// Calls `rad_strerror()` on the given handle and converts the result to
/// an owned Rust `String`.
#[cfg(radius_lib_radlib)]
fn get_radlib_error(h: *mut ffi::rad_handle) -> String {
    // SAFETY: calling rad_strerror() on a valid radlib handle to
    // retrieve the error message for the most recent failed operation. The function
    // returns a pointer to a static or handle-owned string that is valid until the
    // next radlib call on this handle. We copy it immediately to an owned String.
    let ptr = unsafe { ffi::rad_strerror(h) };
    if ptr.is_null() {
        return String::from("unknown radlib error");
    }
    // SAFETY: reading the null-terminated C string pointed to by
    // the non-null pointer returned from rad_strerror(). The string is valid for
    // the duration of this call since no other radlib operations intervene.
    let cstr = unsafe { CStr::from_ptr(ptr) };
    cstr.to_string_lossy().into_owned()
}

// ════════════════════════════════════════════════════════════════════════════
// RadiusClient — radiusclient / freeradiusclient variant
// ════════════════════════════════════════════════════════════════════════════
//
// Source context: src/src/miscmods/radius.c lines 98-171
//
// freeradiusclient C API flow:
//   rc_read_config(path) → rc_handle*
//   rc_read_dictionary(h, rc_conf_str(h, "dictionary"))
//   rc_avpair_add(h, &send, PW_USER_NAME, user, strlen(user), 0)
//   rc_avpair_add(h, &send, PW_USER_PASSWORD, pwd, strlen(pwd), 0)
//   rc_avpair_add(h, &send, PW_SERVICE_TYPE, &service, 0, 0)
//   rc_auth(h, 0, send, &received, msg)

/// RADIUS authentication client handle.
///
/// Wraps the `rc_handle` from freeradiusclient/radiusclient in an RAII struct.
/// Configuration is loaded during construction via `rc_read_config()` and
/// `rc_read_dictionary()`.
#[cfg(radius_lib_radiusclient)]
pub struct RadiusClient {
    /// Raw pointer to the radiusclient handle. Initialized by `rc_read_config()`.
    /// The original C code (src/src/miscmods/radius.c) does not explicitly free
    /// this handle because authentication runs in short-lived forked child processes.
    /// We preserve this behavior in Drop — see the Drop implementation for details.
    handle: *mut ffi::rc_handle,
}

#[cfg(radius_lib_radiusclient)]
impl RadiusClient {
    /// Open a RADIUS client connection using the specified configuration file.
    ///
    /// Calls `rc_read_config()` to parse the RADIUS client configuration and
    /// `rc_read_dictionary()` to load the RADIUS attribute dictionary.
    ///
    /// # Arguments
    ///
    /// * `config_file` — Path to the radiusclient configuration file
    ///
    /// # Errors
    ///
    /// Returns [`RadiusError`] if:
    /// - `config_file` contains a null byte
    /// - `rc_read_config()` returns a null pointer (configuration parse failure)
    /// - `rc_read_dictionary()` fails to load the RADIUS dictionary
    pub fn new(config_file: &str) -> Result<Self, RadiusError> {
        let c_config = CString::new(config_file)
            .map_err(|_| RadiusError::new("config file path contains interior null byte"))?;

        let c_dictionary_key = CString::new("dictionary")
            .map_err(|_| RadiusError::new("internal error: dictionary key conversion"))?;

        // SAFETY: calling rc_read_config() to parse the RADIUS client
        // configuration file and create an rc_handle. The config_file path is a valid
        // null-terminated C string from CString::new(). Returns null on failure.
        let h = unsafe { ffi::rc_read_config(c_config.as_ptr()) };
        if h.is_null() {
            return Err(RadiusError::new(format!(
                "RADIUS: can't open {}",
                config_file
            )));
        }

        // SAFETY: calling rc_conf_str() to retrieve the dictionary
        // file path from the configuration that was just loaded into the valid,
        // non-null handle. The key "dictionary" is a standard radiusclient config
        // option. Returns a pointer to an internal config string (not owned by us).
        let dict_path = unsafe { ffi::rc_conf_str(h, c_dictionary_key.as_ptr()) };
        if dict_path.is_null() {
            return Err(RadiusError::new(
                "RADIUS: dictionary path not found in configuration",
            ));
        }

        // SAFETY: calling rc_read_dictionary() to load the RADIUS
        // attribute dictionary from the path obtained above. Both the handle and
        // the dictionary path pointer are valid. Returns 0 on success.
        let rc = unsafe { ffi::rc_read_dictionary(h, dict_path) };
        if rc != 0 {
            return Err(RadiusError::new("RADIUS: can't read dictionary"));
        }

        Ok(Self { handle: h })
    }

    /// Authenticate a user with the given username and password.
    ///
    /// Builds a RADIUS Access-Request by adding User-Name, User-Password, and
    /// Service-Type attribute-value pairs, then calls `rc_auth()` to perform
    /// the authentication exchange. The response is mapped to [`RadiusAuthResult`].
    ///
    /// # Arguments
    ///
    /// * `user` — The username to authenticate
    /// * `password` — The user's password
    ///
    /// # Errors
    ///
    /// Returns [`RadiusError`] if string conversion fails or if attribute-value
    /// pair construction fails.
    pub fn authenticate(
        &self,
        user: &str,
        password: &str,
    ) -> Result<RadiusAuthResult, RadiusError> {
        let c_user = CString::new(user)
            .map_err(|_| RadiusError::new("username contains interior null byte"))?;
        let c_password = CString::new(password)
            .map_err(|_| RadiusError::new("password contains interior null byte"))?;

        let mut send: *mut ffi::VALUE_PAIR = std::ptr::null_mut();
        let mut received: *mut ffi::VALUE_PAIR = std::ptr::null_mut();
        let mut msg = [0u8; 4096];
        let service: libc::c_uint = ffi::rc_service_type_PW_AUTHENTICATE_ONLY as libc::c_uint;

        // SAFETY: calling rc_avpair_add() three times to build the
        // RADIUS attribute-value pair list for authentication. The handle was
        // initialized in new(), &send is a valid mutable pointer to our local
        // VALUE_PAIR pointer, and all string arguments are valid null-terminated
        // C strings from CString::new(). The function returns null on failure.
        //
        // Each attribute is added in sequence: User-Name, User-Password, Service-Type.
        // This mirrors the C code at src/src/miscmods/radius.c lines 128-136.
        unsafe {
            let rc = ffi::rc_avpair_add(
                self.handle,
                &mut send,
                ffi::rc_attr_id_PW_USER_NAME as libc::c_int,
                c_user.as_ptr() as *const libc::c_void,
                c_user.as_bytes().len() as libc::c_int,
                0,
            );
            if rc.is_null() {
                return Err(RadiusError::new("RADIUS: add user name failed"));
            }

            let rc = ffi::rc_avpair_add(
                self.handle,
                &mut send,
                ffi::rc_attr_id_PW_USER_PASSWORD as libc::c_int,
                c_password.as_ptr() as *const libc::c_void,
                c_password.as_bytes().len() as libc::c_int,
                0,
            );
            if rc.is_null() {
                return Err(RadiusError::new("RADIUS: add password failed"));
            }

            let rc = ffi::rc_avpair_add(
                self.handle,
                &mut send,
                ffi::rc_attr_id_PW_SERVICE_TYPE as libc::c_int,
                &service as *const libc::c_uint as *const libc::c_void,
                0,
                0,
            );
            if rc.is_null() {
                return Err(RadiusError::new("RADIUS: add service type failed"));
            }
        }

        // SAFETY: calling rc_auth() to perform the RADIUS authentication
        // exchange. All arguments are valid:
        //   - self.handle: valid rc_handle from new()
        //   - 0: port number (use default)
        //   - send: valid attribute-value pair list built above
        //   - &received: mutable pointer to receive response AVPs
        //   - msg: 4096-byte buffer for server message
        // Returns one of: OK_RC, REJECT_RC, ERROR_RC, TIMEOUT_RC, BADRESP_RC.
        let result = unsafe {
            ffi::rc_auth(
                self.handle,
                0,
                send,
                &mut received,
                msg.as_mut_ptr() as *mut libc::c_char,
            )
        };

        match result {
            x if x == rc_result_codes::OK_RC => Ok(RadiusAuthResult::Ok),
            x if x == rc_result_codes::REJECT_RC => Ok(RadiusAuthResult::Fail),
            x if x == rc_result_codes::ERROR_RC => Ok(RadiusAuthResult::Fail),
            x if x == rc_result_codes::TIMEOUT_RC => Err(RadiusError::new("RADIUS: timed out")),
            x if x == rc_result_codes::BADRESP_RC => Ok(RadiusAuthResult::BadResponse(result)),
            other => Ok(RadiusAuthResult::BadResponse(other)),
        }
    }
}

#[cfg(radius_lib_radiusclient)]
impl Drop for RadiusClient {
    fn drop(&mut self) {
        // The original C code (src/src/miscmods/radius.c) does not explicitly free
        // the rc_handle because auth_call_radius() runs in a short-lived forked child
        // process that exits after handling the SMTP connection. The OS reclaims all
        // memory on process exit.
        //
        // In the Rust implementation, RadiusClient is used via the top-level
        // authenticate() convenience function which creates and immediately drops
        // the client, matching the C one-shot pattern. No explicit cleanup function
        // is called because:
        //   1. The original C code does not call one
        //   2. The rc_destroy() function may not exist in all radiusclient variants
        //   3. The handle is typically used in a forked child process
        //
        // If a future radiusclient version provides a universal cleanup function,
        // it should be added here.
        let _ = self.handle; // Suppress unused field warning in drop
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Top-Level Convenience Function
// ════════════════════════════════════════════════════════════════════════════

/// Perform RADIUS authentication.
///
/// This is a convenience function that combines [`RadiusClient::new()`] and
/// [`RadiusClient::authenticate()`] into a single call, matching the one-shot
/// pattern of the original C `auth_call_radius()` function.
///
/// # Arguments
///
/// * `config_file` — Path to the RADIUS configuration file
/// * `user` — The username to authenticate
/// * `password` — The user's password
///
/// # Returns
///
/// - `Ok(RadiusAuthResult::Ok)` — Authentication succeeded
/// - `Ok(RadiusAuthResult::Fail)` — Authentication rejected
/// - `Ok(RadiusAuthResult::BadResponse(code))` — Unexpected response from server
/// - `Err(RadiusError)` — Error during the authentication process
///
/// # Examples
///
/// ```ignore
/// use exim_ffi::radius::{authenticate, RadiusAuthResult};
///
/// match authenticate("/etc/radius.conf", "user@example.com", "s3cret") {
///     Ok(RadiusAuthResult::Ok) => println!("Authenticated!"),
///     Ok(RadiusAuthResult::Fail) => println!("Bad credentials"),
///     Ok(RadiusAuthResult::BadResponse(code)) => eprintln!("Unexpected: {}", code),
///     Err(e) => eprintln!("Error: {}", e),
///     _ => {}
/// }
/// ```
pub fn authenticate(
    config_file: &str,
    user: &str,
    password: &str,
) -> Result<RadiusAuthResult, RadiusError> {
    let client = RadiusClient::new(config_file)?;
    client.authenticate(user, password)
}
