//! Safe wrappers around libspf2 for SPF (Sender Policy Framework) validation.
//!
//! Provides managed SPF server, request, and response objects that wrap
//! the libspf2 C API for checking SPF records against connecting IP addresses.
//!
//! Supports custom DNS resolver hooks via the Exim DNS subsystem integration.
//!
//! # Safety
//!
//! All `unsafe` blocks in this module are confined to the `exim-ffi` crate,
//! which is the ONLY crate permitted to contain `unsafe` code per AAP §0.7.2.
//! Each `unsafe` block has an inline justification comment explaining its
//! necessity. The safe public API prevents null pointer dereference and
//! properly manages the lifecycle of libspf2 objects through RAII (`Drop`).
//!
//! # Source Context
//!
//! This module replaces the C implementation in:
//! - `src/src/miscmods/spf.c` (627 lines — SPF evaluation + DNS bridge)
//! - `src/src/miscmods/spf.h` (41 lines — SPF type definitions + constants)
//! - `src/src/miscmods/spf_api.h` (36 lines — result codes + function table)

use std::error::Error as StdError;
use std::ffi::{CStr, CString};
use std::fmt;
use std::ptr;

use libc::c_int;

// ---------------------------------------------------------------------------
// Raw FFI bindings generated by bindgen from libspf2 headers.
// ---------------------------------------------------------------------------

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
// Justification: bindgen-generated FFI bindings preserve C naming conventions
// for libspf2 types, functions, and constants. The C library uses UPPER_CASE
// constants, PascalCase_t type suffixes, and mixed_case function names that
// do not conform to Rust naming conventions.
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/spf_bindings.rs"));
}

// ---------------------------------------------------------------------------
// SpfResult — SPF validation result codes
// ---------------------------------------------------------------------------

/// SPF validation result codes.
///
/// Maps directly to the libspf2 `SPF_result_t` enum values and the Exim
/// `spf_result_id_list` table in `src/src/miscmods/spf.c` lines 17–28.
///
/// | Variant    | Code | C Constant           | Exim String  |
/// |------------|------|----------------------|--------------|
/// | Invalid    | 0    | SPF_RESULT_INVALID   | `"invalid"`  |
/// | Neutral    | 1    | SPF_RESULT_NEUTRAL   | `"neutral"`  |
/// | Pass       | 2    | SPF_RESULT_PASS      | `"pass"`     |
/// | Fail       | 3    | SPF_RESULT_FAIL      | `"fail"`     |
/// | SoftFail   | 4    | SPF_RESULT_SOFTFAIL  | `"softfail"` |
/// | None       | 5    | SPF_RESULT_NONE      | `"none"`     |
/// | TempError  | 6    | SPF_RESULT_TEMPERROR | `"temperror"`|
/// | PermError  | 7    | SPF_RESULT_PERMERROR | `"permerror"`|
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum SpfResult {
    /// Invalid SPF result (code 0).
    Invalid = 0,
    /// Neutral — domain does not assert whether the sender is authorized (code 1).
    Neutral = 1,
    /// Pass — the sender is authorized by the domain's SPF record (code 2).
    Pass = 2,
    /// Fail — the sender is NOT authorized; the message should be rejected (code 3).
    Fail = 3,
    /// SoftFail — the sender is probably NOT authorized (code 4).
    SoftFail = 4,
    /// None — no SPF record was found for the domain (code 5).
    None = 5,
    /// TempError — a temporary DNS or processing error occurred (code 6).
    TempError = 6,
    /// PermError — a permanent error in the SPF record was detected (code 7).
    PermError = 7,
}

impl SpfResult {
    /// Convert a numeric result code to an [`SpfResult`] variant.
    ///
    /// Returns [`Option::None`] if the code does not correspond to a known
    /// SPF result (i.e., not in the range 0–7).
    ///
    /// # Examples
    ///
    /// ```ignore
    /// assert_eq!(SpfResult::from_code(2), Some(SpfResult::Pass));
    /// assert_eq!(SpfResult::from_code(99), None);
    /// ```
    pub fn from_code(code: i32) -> Option<Self> {
        match code {
            0 => Some(SpfResult::Invalid),
            1 => Some(SpfResult::Neutral),
            2 => Some(SpfResult::Pass),
            3 => Some(SpfResult::Fail),
            4 => Some(SpfResult::SoftFail),
            5 => Some(SpfResult::None),
            6 => Some(SpfResult::TempError),
            7 => Some(SpfResult::PermError),
            _ => Option::None,
        }
    }

    /// Get the human-readable string representation of this result.
    ///
    /// Returns the same lowercase strings used by Exim's `spf_result_id_list`
    /// table: `"invalid"`, `"neutral"`, `"pass"`, `"fail"`, `"softfail"`,
    /// `"none"`, `"temperror"`, `"permerror"`.
    pub fn as_str(&self) -> &'static str {
        match self {
            SpfResult::Invalid => "invalid",
            SpfResult::Neutral => "neutral",
            SpfResult::Pass => "pass",
            SpfResult::Fail => "fail",
            SpfResult::SoftFail => "softfail",
            SpfResult::None => "none",
            SpfResult::TempError => "temperror",
            SpfResult::PermError => "permerror",
        }
    }
}

impl fmt::Display for SpfResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

// ---------------------------------------------------------------------------
// SpfProcessMode — SPF processing modes
// ---------------------------------------------------------------------------

/// SPF processing modes controlling how SPF evaluation is performed.
///
/// Maps to the C constants in `src/src/miscmods/spf.h` lines 31–40:
/// - `SPF_PROCESS_NORMAL  = 0`
/// - `SPF_PROCESS_GUESS   = 1`
/// - `SPF_PROCESS_FALLBACK = 2`
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum SpfProcessMode {
    /// Normal SPF processing using standard DNS lookups and the domain's
    /// published SPF record.
    Normal = 0,
    /// Guess mode — applies best-guess SPF records for domains that do not
    /// publish their own SPF record.
    Guess = 1,
    /// Fallback mode — applies a configured fallback SPF record when the
    /// domain's record cannot be retrieved.
    Fallback = 2,
}

// ---------------------------------------------------------------------------
// SpfError — SPF error type
// ---------------------------------------------------------------------------

/// Error type for SPF operations.
///
/// Wraps error messages from libspf2 API calls and provides full
/// `std::error::Error` integration for idiomatic Rust error handling.
#[derive(Debug, Clone)]
pub struct SpfError {
    message: String,
}

impl SpfError {
    /// Create a new SPF error with the given descriptive message.
    pub fn new(msg: impl Into<String>) -> Self {
        Self {
            message: msg.into(),
        }
    }
}

impl fmt::Display for SpfError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "SPF error: {}", self.message)
    }
}

impl StdError for SpfError {}

// ---------------------------------------------------------------------------
// DnsLookupFn / DnsRecord — DNS resolver hook types
// ---------------------------------------------------------------------------

/// Callback type for custom DNS resolution.
///
/// This allows the Exim DNS subsystem to be plugged in as the DNS resolver
/// for libspf2, rather than using libspf2's built-in resolver. The function
/// receives a domain name and DNS resource record type, and returns matching
/// records or an error.
///
/// The `rr_type` parameter uses standard DNS RR type values:
/// - `1`  — A record (IPv4 address)
/// - `15` — MX record (mail exchange)
/// - `16` — TXT record (text, containing SPF data)
/// - `28` — AAAA record (IPv6 address)
/// - `33` — SRV record (service locator)
///
/// # Source Context
///
/// This replaces the `SPF_dns_exim_lookup` extern "C" callback function
/// defined in `src/src/miscmods/spf.c` lines 66–160, which bridges
/// libspf2's DNS queries to Exim's internal DNS resolution subsystem.
pub type DnsLookupFn = Box<dyn Fn(&str, u16) -> Result<Vec<DnsRecord>, SpfError> + Send + Sync>;

/// A DNS record returned by the custom resolver.
///
/// Represents a single resource record with its type and raw data payload,
/// suitable for passing back through the libspf2 DNS callback interface.
#[derive(Debug, Clone)]
pub struct DnsRecord {
    /// DNS resource record type (e.g., 1=A, 15=MX, 16=TXT, 28=AAAA).
    pub rr_type: u16,
    /// Raw record data bytes as they would appear in a DNS response.
    pub data: Vec<u8>,
}

// ---------------------------------------------------------------------------
// Internal helper: safe CString construction
// ---------------------------------------------------------------------------

/// Convert a Rust `&str` to a [`CString`], mapping interior NUL byte errors
/// to [`SpfError`] with a descriptive context message.
fn to_cstring(s: &str, context: &str) -> Result<CString, SpfError> {
    CString::new(s).map_err(|_| {
        SpfError::new(format!(
            "{context} contains an interior null byte and cannot be passed to libspf2"
        ))
    })
}

// ---------------------------------------------------------------------------
// SpfServer — safe wrapper around SPF_server_t
// ---------------------------------------------------------------------------

/// Safe wrapper around an SPF server context (`SPF_server_t`).
///
/// The SPF server manages DNS resolution configuration and caching for SPF
/// queries. It is typically created once per Exim process lifetime (or per
/// connection batch) and reused across multiple SPF requests.
///
/// # Lifecycle
///
/// The server is automatically freed via `SPF_server_free` when dropped.
/// Creating a new request via [`new_request`](SpfServer::new_request) does
/// NOT transfer ownership of the server — the server must outlive all
/// requests derived from it.
///
/// # Thread Safety
///
/// This type is intentionally `!Send` and `!Sync` because the underlying
/// libspf2 `SPF_server_t` is not thread-safe.
pub struct SpfServer {
    server: *mut ffi::SPF_server_t,
}

impl SpfServer {
    /// Create a new SPF server with DNS caching enabled.
    ///
    /// This creates a server using `SPF_DNS_CACHE` as the DNS resolver type,
    /// matching the Exim C code pattern: `SPF_server_new(SPF_DNS_CACHE, 0)`.
    /// The debug level is set to 0 (no debug output).
    ///
    /// # Errors
    ///
    /// Returns [`SpfError`] if `SPF_server_new` returns a null pointer,
    /// indicating a memory allocation failure or library initialization error.
    pub fn new() -> Result<Self, SpfError> {
        // unsafe justification: calling SPF_server_new to create an SPF server
        // context with DNS caching enabled. The function allocates a new
        // SPF_server_t and returns null on failure, which we check immediately.
        // SPF_DNS_CACHE is a compile-time constant from libspf2.
        let server = unsafe { ffi::SPF_server_new(ffi::SPF_server_dnstype_enum_SPF_DNS_CACHE, 0) };
        if server.is_null() {
            return Err(SpfError::new(
                "SPF_server_new returned null — failed to initialize SPF server context",
            ));
        }
        Ok(Self { server })
    }

    /// Create a new SPF request associated with this server.
    ///
    /// The returned [`SpfRequest`] uses this server's DNS resolver and cache
    /// configuration. Multiple concurrent requests can share the same server.
    ///
    /// # Errors
    ///
    /// Returns [`SpfError`] if `SPF_request_new` returns a null pointer.
    pub fn new_request(&self) -> Result<SpfRequest, SpfError> {
        // unsafe justification: calling SPF_request_new to allocate and
        // initialize an SPF request associated with this server. The server
        // pointer was validated non-null during SpfServer construction.
        // Returns null on allocation failure.
        let request = unsafe { ffi::SPF_request_new(self.server) };
        if request.is_null() {
            return Err(SpfError::new(
                "SPF_request_new returned null — failed to create SPF request",
            ));
        }
        Ok(SpfRequest { request })
    }

    /// Get the libspf2 library version as `(major, minor, patch)`.
    ///
    /// Calls `SPF_get_lib_version` to retrieve the compile-time version
    /// numbers of the linked libspf2 library (e.g., `(1, 2, 10)`).
    pub fn lib_version() -> (i32, i32, i32) {
        let mut major: c_int = 0;
        let mut minor: c_int = 0;
        let mut patch: c_int = 0;
        // unsafe justification: calling SPF_get_lib_version to retrieve the
        // compile-time library version numbers. The function writes to the
        // three provided pointer locations, which are valid stack variables
        // with deterministic lifetimes.
        unsafe {
            ffi::SPF_get_lib_version(&mut major, &mut minor, &mut patch);
        }
        (major as i32, minor as i32, patch as i32)
    }
}

impl Drop for SpfServer {
    fn drop(&mut self) {
        if !self.server.is_null() {
            // unsafe justification: calling SPF_server_free to release all
            // memory and resources associated with the SPF server context.
            // The pointer was validated non-null during construction and is
            // set to null after freeing to prevent double-free.
            unsafe {
                ffi::SPF_server_free(self.server);
            }
            self.server = ptr::null_mut();
        }
    }
}

// ---------------------------------------------------------------------------
// SpfRequest — safe wrapper around SPF_request_t
// ---------------------------------------------------------------------------

/// Safe wrapper around an SPF request (`SPF_request_t`).
///
/// An SPF request encapsulates the parameters needed for a single SPF
/// evaluation: the connecting client's IP address, HELO/EHLO domain, and
/// envelope sender (MAIL FROM) address.
///
/// # Usage Flow
///
/// ```ignore
/// let server = SpfServer::new()?;
/// let mut req = server.new_request()?;
/// req.set_ipv4("192.168.1.100")?;
/// req.set_helo_domain("mail.example.com")?;
/// req.set_env_from("sender@example.com")?;
/// let response = req.query_mailfrom()?;
/// println!("SPF result: {}", response.result());
/// ```
///
/// # Lifecycle
///
/// The request is automatically freed via `SPF_request_free` when dropped.
///
/// # Thread Safety
///
/// This type is intentionally `!Send` and `!Sync` because the underlying
/// libspf2 `SPF_request_t` is not thread-safe.
pub struct SpfRequest {
    request: *mut ffi::SPF_request_t,
}

impl SpfRequest {
    /// Set the client IP address (IPv4).
    ///
    /// The IP address string should be in standard dotted-decimal notation
    /// (e.g., `"192.168.1.1"` or `"10.0.0.42"`).
    ///
    /// This corresponds to the C call:
    /// `SPF_request_set_ipv4_str(spf_request, CS ip_address)`
    /// from `src/src/miscmods/spf.c` line ~380.
    ///
    /// # Errors
    ///
    /// Returns [`SpfError`] if the IP address string contains an interior
    /// null byte, or if `SPF_request_set_ipv4_str` returns a non-success
    /// error code (e.g., invalid format).
    pub fn set_ipv4(&mut self, ip: &str) -> Result<(), SpfError> {
        let c_ip = to_cstring(ip, "IPv4 address")?;
        // unsafe justification: calling SPF_request_set_ipv4_str to set the
        // connecting client's IPv4 address for SPF evaluation. The request
        // pointer was validated non-null during construction. The CString
        // provides a valid null-terminated C string that outlives this call.
        let rc = unsafe { ffi::SPF_request_set_ipv4_str(self.request, c_ip.as_ptr()) };
        if rc != 0 {
            return Err(SpfError::new(format!(
                "SPF_request_set_ipv4_str failed for '{}' (error code {})",
                ip, rc
            )));
        }
        Ok(())
    }

    /// Set the client IP address (IPv6).
    ///
    /// The IP address string should be in standard colon-hex notation
    /// (e.g., `"2001:db8::1"` or `"::ffff:192.168.1.1"`).
    ///
    /// # Errors
    ///
    /// Returns [`SpfError`] if the IP address string contains an interior
    /// null byte, or if `SPF_request_set_ipv6_str` returns a non-success
    /// error code.
    pub fn set_ipv6(&mut self, ip: &str) -> Result<(), SpfError> {
        let c_ip = to_cstring(ip, "IPv6 address")?;
        // unsafe justification: calling SPF_request_set_ipv6_str to set the
        // connecting client's IPv6 address for SPF evaluation. The request
        // pointer was validated non-null during construction.
        let rc = unsafe { ffi::SPF_request_set_ipv6_str(self.request, c_ip.as_ptr()) };
        if rc != 0 {
            return Err(SpfError::new(format!(
                "SPF_request_set_ipv6_str failed for '{}' (error code {})",
                ip, rc
            )));
        }
        Ok(())
    }

    /// Set the HELO/EHLO domain.
    ///
    /// The domain string is the argument presented by the connecting client
    /// in the SMTP HELO or EHLO command (e.g., `"mail.example.com"`).
    ///
    /// # Errors
    ///
    /// Returns [`SpfError`] if the domain string contains an interior null
    /// byte, or if `SPF_request_set_helo_dom` returns a non-success error
    /// code.
    pub fn set_helo_domain(&mut self, domain: &str) -> Result<(), SpfError> {
        let c_domain = to_cstring(domain, "HELO domain")?;
        // unsafe justification: calling SPF_request_set_helo_dom to set the
        // HELO domain for SPF evaluation. The request pointer was validated
        // non-null during construction.
        let rc = unsafe { ffi::SPF_request_set_helo_dom(self.request, c_domain.as_ptr()) };
        if rc != 0 {
            return Err(SpfError::new(format!(
                "SPF_request_set_helo_dom failed for '{}' (error code {})",
                domain, rc
            )));
        }
        Ok(())
    }

    /// Set the envelope sender (MAIL FROM) address.
    ///
    /// Note: The underlying `SPF_request_set_env_from` returns `int` (not
    /// `SPF_errcode_t`), where non-zero indicates an error. This matches
    /// the Exim C source pattern at line ~434:
    /// `if (SPF_request_set_env_from(spf_request, CS mailaddr))`.
    ///
    /// # Errors
    ///
    /// Returns [`SpfError`] if the sender contains an interior null byte,
    /// or if `SPF_request_set_env_from` returns a non-zero value.
    pub fn set_env_from(&mut self, sender: &str) -> Result<(), SpfError> {
        let c_sender = to_cstring(sender, "envelope sender")?;
        // unsafe justification: calling SPF_request_set_env_from to set the
        // envelope sender for SPF evaluation. This function returns int (not
        // SPF_errcode_t), with non-zero indicating an error. The request
        // pointer was validated non-null during construction.
        let rc = unsafe { ffi::SPF_request_set_env_from(self.request, c_sender.as_ptr()) };
        if rc != 0 {
            return Err(SpfError::new(format!(
                "SPF_request_set_env_from failed for '{}' (error code {})",
                sender, rc
            )));
        }
        Ok(())
    }

    /// Query the SPF record for the MAIL FROM sender.
    ///
    /// Performs the full SPF lookup and validation, including DNS resolution
    /// of TXT records, SPF record parsing, mechanism evaluation, and result
    /// determination. Returns a response object containing the result code
    /// and human-readable explanation.
    ///
    /// This corresponds to the C call:
    /// `SPF_request_query_mailfrom(spf_request, &spf_response)`
    /// from `src/src/miscmods/spf.c` line ~440.
    ///
    /// # Errors
    ///
    /// Returns [`SpfError`] if the query encounters a fatal error or if the
    /// response pointer is null after the query completes.
    pub fn query_mailfrom(&self) -> Result<SpfResponse, SpfError> {
        let mut response: *mut ffi::SPF_response_t = ptr::null_mut();
        // unsafe justification: calling SPF_request_query_mailfrom to perform
        // the SPF lookup and validation. The response is an output parameter
        // that receives a newly allocated SPF_response_t on success. The
        // request pointer was validated non-null during construction. The
        // caller (SpfResponse) takes ownership of the response pointer and
        // frees it via SPF_response_free in its Drop implementation.
        let rc = unsafe { ffi::SPF_request_query_mailfrom(self.request, &mut response) };
        if response.is_null() {
            return Err(SpfError::new(format!(
                "SPF_request_query_mailfrom returned null response (error code {})",
                rc
            )));
        }
        Ok(SpfResponse { response })
    }

    /// Query the SPF record for a RCPT TO recipient (secondary validation).
    ///
    /// The `rcpt_to` parameter specifies the recipient address for the
    /// per-recipient SPF check. This is used for SPF validation scoped to
    /// individual recipients rather than the global MAIL FROM.
    ///
    /// Note: The C function signature for `SPF_request_query_rcptto` includes
    /// an additional `const char *rcpt_to` parameter compared to
    /// `SPF_request_query_mailfrom`.
    ///
    /// # Errors
    ///
    /// Returns [`SpfError`] if the query fails, `rcpt_to` contains an
    /// interior null byte, or the response pointer is null after the query.
    pub fn query_rcptto(&self, rcpt_to: &str) -> Result<SpfResponse, SpfError> {
        let c_rcpt = to_cstring(rcpt_to, "RCPT TO address")?;
        let mut response: *mut ffi::SPF_response_t = ptr::null_mut();
        // unsafe justification: calling SPF_request_query_rcptto to perform
        // per-recipient SPF validation. The C function takes an additional
        // rcpt_to parameter (const char*) compared to query_mailfrom. The
        // request pointer was validated non-null during construction. The
        // response output pointer is checked for null before wrapping.
        let rc =
            unsafe { ffi::SPF_request_query_rcptto(self.request, &mut response, c_rcpt.as_ptr()) };
        if response.is_null() {
            return Err(SpfError::new(format!(
                "SPF_request_query_rcptto returned null response for '{}' (error code {})",
                rcpt_to, rc
            )));
        }
        Ok(SpfResponse { response })
    }
}

impl Drop for SpfRequest {
    fn drop(&mut self) {
        if !self.request.is_null() {
            // unsafe justification: calling SPF_request_free to release all
            // memory and resources associated with this SPF request. The
            // pointer was validated non-null during construction and is set
            // to null after freeing to prevent double-free.
            unsafe {
                ffi::SPF_request_free(self.request);
            }
            self.request = ptr::null_mut();
        }
    }
}

// ---------------------------------------------------------------------------
// SpfResponse — safe wrapper around SPF_response_t
// ---------------------------------------------------------------------------

/// Safe wrapper around an SPF response (`SPF_response_t`).
///
/// Contains the result of an SPF evaluation, including the result code
/// (pass/fail/softfail/etc.), a human-readable result string, and a reason
/// explanation string.
///
/// # Lifecycle
///
/// The response is automatically freed via `SPF_response_free` when dropped.
/// Responses are created by [`SpfRequest::query_mailfrom`] or
/// [`SpfRequest::query_rcptto`] and must NOT outlive the originating request.
///
/// # Thread Safety
///
/// This type is intentionally `!Send` and `!Sync` because the underlying
/// libspf2 `SPF_response_t` is not thread-safe.
pub struct SpfResponse {
    response: *mut ffi::SPF_response_t,
}

impl SpfResponse {
    /// Get the SPF result code.
    ///
    /// Calls `SPF_response_result` to retrieve the numeric result and maps
    /// it to the [`SpfResult`] enum. If the result code is outside the known
    /// range (0–7), returns [`SpfResult::Invalid`] as a safe fallback.
    pub fn result(&self) -> SpfResult {
        // unsafe justification: calling SPF_response_result to retrieve the
        // SPF result code from the response. The response pointer was
        // validated non-null when the SpfResponse was constructed by
        // query_mailfrom or query_rcptto.
        let code = unsafe { ffi::SPF_response_result(self.response) };
        SpfResult::from_code(code as i32).unwrap_or(SpfResult::Invalid)
    }

    /// Get the human-readable result string from libspf2.
    ///
    /// Calls `SPF_response_result` followed by `SPF_strresult` to convert
    /// the numeric result to the library's canonical string representation
    /// (e.g., `"pass"`, `"fail"`, `"softfail"`, `"temperror"`).
    ///
    /// Returns `"unknown"` if the library returns a null string pointer.
    pub fn result_str(&self) -> String {
        // unsafe justification: calling SPF_response_result to get the numeric
        // result code, then SPF_strresult to convert it to a human-readable
        // static C string owned by libspf2. The response pointer was validated
        // non-null during construction. SPF_strresult returns a pointer to a
        // static string constant within libspf2, so it remains valid for the
        // lifetime of this call. We copy the string into an owned Rust String.
        unsafe {
            let code = ffi::SPF_response_result(self.response);
            let c_str = ffi::SPF_strresult(code);
            if c_str.is_null() {
                return String::from("unknown");
            }
            CStr::from_ptr(c_str).to_string_lossy().into_owned()
        }
    }

    /// Get the reason string for the SPF result.
    ///
    /// Calls `SPF_response_reason` followed by `SPF_strreason` to get a
    /// human-readable explanation of why the SPF result was determined
    /// (e.g., `"mechanism"`, `"default"`, `"local-policy"`).
    ///
    /// Returns `"unknown"` if the library returns a null string pointer.
    pub fn reason_str(&self) -> String {
        // unsafe justification: calling SPF_response_reason to get the numeric
        // reason code, then SPF_strreason to convert it to a human-readable
        // static C string owned by libspf2. The response pointer was validated
        // non-null during construction. SPF_strreason returns a pointer to a
        // static string constant within libspf2, so it remains valid for the
        // lifetime of this call. We copy the string into an owned Rust String.
        unsafe {
            let reason = ffi::SPF_response_reason(self.response);
            let c_str = ffi::SPF_strreason(reason);
            if c_str.is_null() {
                return String::from("unknown");
            }
            CStr::from_ptr(c_str).to_string_lossy().into_owned()
        }
    }
}

impl Drop for SpfResponse {
    fn drop(&mut self) {
        if !self.response.is_null() {
            // unsafe justification: calling SPF_response_free to release all
            // memory and resources associated with this SPF response. The
            // pointer was validated non-null when the SpfResponse was
            // constructed by query_mailfrom or query_rcptto, and is set to
            // null after freeing to prevent double-free.
            unsafe {
                ffi::SPF_response_free(self.response);
            }
            self.response = ptr::null_mut();
        }
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spf_result_from_code_valid() {
        assert_eq!(SpfResult::from_code(0), Some(SpfResult::Invalid));
        assert_eq!(SpfResult::from_code(1), Some(SpfResult::Neutral));
        assert_eq!(SpfResult::from_code(2), Some(SpfResult::Pass));
        assert_eq!(SpfResult::from_code(3), Some(SpfResult::Fail));
        assert_eq!(SpfResult::from_code(4), Some(SpfResult::SoftFail));
        assert_eq!(SpfResult::from_code(5), Some(SpfResult::None));
        assert_eq!(SpfResult::from_code(6), Some(SpfResult::TempError));
        assert_eq!(SpfResult::from_code(7), Some(SpfResult::PermError));
    }

    #[test]
    fn spf_result_from_code_invalid() {
        assert_eq!(SpfResult::from_code(-1), Option::None);
        assert_eq!(SpfResult::from_code(8), Option::None);
        assert_eq!(SpfResult::from_code(100), Option::None);
        assert_eq!(SpfResult::from_code(i32::MAX), Option::None);
        assert_eq!(SpfResult::from_code(i32::MIN), Option::None);
    }

    #[test]
    fn spf_result_as_str() {
        assert_eq!(SpfResult::Invalid.as_str(), "invalid");
        assert_eq!(SpfResult::Neutral.as_str(), "neutral");
        assert_eq!(SpfResult::Pass.as_str(), "pass");
        assert_eq!(SpfResult::Fail.as_str(), "fail");
        assert_eq!(SpfResult::SoftFail.as_str(), "softfail");
        assert_eq!(SpfResult::None.as_str(), "none");
        assert_eq!(SpfResult::TempError.as_str(), "temperror");
        assert_eq!(SpfResult::PermError.as_str(), "permerror");
    }

    #[test]
    fn spf_result_display() {
        assert_eq!(format!("{}", SpfResult::Pass), "pass");
        assert_eq!(format!("{}", SpfResult::Fail), "fail");
        assert_eq!(format!("{}", SpfResult::TempError), "temperror");
    }

    #[test]
    fn spf_result_roundtrip() {
        for code in 0..=7 {
            let result = SpfResult::from_code(code).expect("valid code");
            assert_eq!(result as i32, code);
        }
    }

    #[test]
    fn spf_process_mode_values() {
        assert_eq!(SpfProcessMode::Normal as i32, 0);
        assert_eq!(SpfProcessMode::Guess as i32, 1);
        assert_eq!(SpfProcessMode::Fallback as i32, 2);
    }

    #[test]
    fn spf_error_new_and_display() {
        let err = SpfError::new("test failure");
        assert_eq!(format!("{}", err), "SPF error: test failure");
        assert_eq!(err.message, "test failure");
    }

    #[test]
    fn spf_error_from_string() {
        let msg = String::from("dynamic error");
        let err = SpfError::new(msg);
        assert_eq!(err.message, "dynamic error");
    }

    #[test]
    fn spf_error_is_std_error() {
        let err = SpfError::new("check trait");
        let _: &dyn StdError = &err;
    }

    #[test]
    fn dns_record_construction() {
        let record = DnsRecord {
            rr_type: 16,
            data: b"v=spf1 +all".to_vec(),
        };
        assert_eq!(record.rr_type, 16);
        assert_eq!(record.data, b"v=spf1 +all");
    }

    #[test]
    fn dns_record_clone() {
        let record = DnsRecord {
            rr_type: 1,
            data: vec![192, 168, 1, 1],
        };
        let cloned = record.clone();
        assert_eq!(cloned.rr_type, record.rr_type);
        assert_eq!(cloned.data, record.data);
    }

    #[test]
    fn to_cstring_valid() {
        let result = to_cstring("hello", "test");
        assert!(result.is_ok());
    }

    #[test]
    fn to_cstring_with_null() {
        let result = to_cstring("hel\0lo", "test value");
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.message.contains("test value"));
        assert!(err.message.contains("null byte"));
    }

    #[test]
    fn to_cstring_empty_string() {
        let result = to_cstring("", "empty");
        assert!(result.is_ok());
    }

    #[test]
    fn spf_server_lib_version() {
        let (major, minor, patch) = SpfServer::lib_version();
        // libspf2 version should be reasonable (1.x.x range)
        assert!(major >= 0);
        assert!(minor >= 0);
        assert!(patch >= 0);
    }
}
